package com.eugenefe.entity.takion;
//Generated Dec 19, 2016 6:36:07 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

/**
* ScenarioDetailId generated by hbm2java
*/

public class ScenarioDetailIdTest implements java.io.Serializable, Navigatable {

	private String scenario;
	private String marketVariable;

	public ScenarioDetailIdTest() {
	}


	public String getScenario() {
		return scenario;
	}


	public void setScenario(String scenario) {
		this.scenario = scenario;
	}


	public String getMarketVariable() {
		return marketVariable;
	}


	public void setMarketVariable(String marketVariable) {
		this.marketVariable = marketVariable;
	}


	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getScenario());
		buffer.append("#").append(getMarketVariable());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ScenarioDetailIdTest))
			return false;
		ScenarioDetailIdTest castOther = (ScenarioDetailIdTest) other;

		return ((this.getScenario() == castOther.getScenario())
				|| (this.getScenario() != null && castOther.getScenario() != null && this.getScenario().equals(castOther.getScenario())))
				&& ((this.getMarketVariable() == castOther.getMarketVariable())
						|| (this.getMarketVariable() != null && castOther.getMarketVariable() != null && this.getMarketVariable().equals(castOther.getMarketVariable())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getScenario() == null ? 0 : this.getScenario().hashCode());
		result = 37 * result + (getMarketVariable() == null ? 0 : this.getMarketVariable().hashCode());
		return result;
	}

}