package com.eugenefe.entity.takion;
// Generated Dec 19, 2016 6:36:07 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.eugenefe.util.Navigatable;

/**
 * Bond generated by hbm2java
 */

@Entity
//@IdClass(value = WebUserMenuMultiId.class)s
@Table(name = "WEB_USER_MENU_MULTI", schema = "TAKION79")
public class WebUserMenuMulti  implements java.io.Serializable, Navigatable, Cloneable {

	private Long seqNo;
	private String userId;
//	private WebUser user;
	private String menuId;
	private MenuMst menu;
	private String menuName;
	private String menuGroup;
    private Integer menuColumn;
    private String menuStyle;
    private String iconName;
    
    
    @Id
//    @SequenceGenerator()
//	@GeneratedValue(strategy=GenerationType.AUTO)
    @GeneratedValue(generator="some_seq_gen_name")
    @SequenceGenerator(name="some_seq_gen_name", sequenceName="WEB_USER_MENU_SEQ", allocationSize=1)
	@Column(name = "SEQ_NO", nullable = false)
	public Long getSeqNo() {
		return seqNo;
	}

	public void setSeqNo(Long seqNo) {
		try {
			this.seqNo = seqNo;
		} catch (Exception e) {
			System.out.println("Error on set SeqNo " + seqNo);
		}
	} 
	
	@Column(name = "USER_ID",  nullable = false, length = 50)
	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	/*@ManyToOne
	@JoinColumn(name="USER_ID", referencedColumnName="USER_ID", insertable=false, updatable=false, nullable=false)
	public WebUser getUser() {
		return user;
	}

	public void setUser(WebUser user) {
		this.user = user;
	}*/
	
	@Column(name = "MENU_ID",  nullable = false, length = 50)
	public String getMenuId() {
		return menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}
	
//	@ManyToOne(cascade=CascadeType.ALL)
	@ManyToOne
	@JoinColumn(name="MENU_ID", referencedColumnName="MENU_ID", insertable=false, updatable=false, nullable=false)
	public MenuMst getMenu() {
		return menu;
	}

	public void setMenu(MenuMst menu) {
		this.menu = menu;
	}
	
	public WebUserMenuMulti() {
	}
	

	@Column(name="MENU_NAME", nullable = false)
	public String getMenuName() {
		return menuName;
	}

	

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}
	
	@Column(name="MENU_GROUP", nullable = true)
	public String getMenuGroup() {
		return menuGroup;
	}

	public void setMenuGroup(String menuGroup) {
		this.menuGroup = menuGroup;
	}
	
	@Column(name="MENU_COLUMN", nullable = true)
	public Integer getMenuColumn() {
		return menuColumn;
	}

	public void setMenuColumn(Integer menuColumn) {
		this.menuColumn = menuColumn;
	}

	@Column(name="MENU_STYLE", nullable = true)
	public String getMenuStyle() {
		return menuStyle;
	}

	public void setMenuStyle(String menuStyle) {
		this.menuStyle = menuStyle;
	}

	@Column(name="ICON_NAME", nullable = true)
	public String getIconName() {
		return iconName;
	}

	public void setIconName(String iconName) {
		this.iconName = iconName;
	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getSeqNo());

		String rst = buffer.toString();

		return rst;
	}

	

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WebUserMenuMulti))
			return false;
		WebUserMenuMulti castOther = (WebUserMenuMulti) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (idString() == null ? 0 : this.idString().hashCode());
		return result;
	}

}
