package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.eugenefe.util.Navigatable;


/**
 * NcmBatLog generated by hbm2java
 */

@Entity
@IdClass(value = NcmBatLogId.class)
@Table(name = "NCM_BAT_LOG", schema = "NCM")
public class NcmBatLog implements java.io.Serializable, Navigatable {

	private String baseDate;
	private String batCd;
	private String batCdNm;
	private Long cnt;
	private String status;
	private String errMsg;
	private String updateId;
	private Date lastUpdate;

	public NcmBatLog() {
	}

	@Id
	@Column(name = "BASE_DATE", nullable = false, length = 8)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Id
	@Column(name = "BAT_CD", nullable = false, length = 20)
	public String getBatCd() {
		return this.batCd;
	}

	public void setBatCd(String batCd) {
		this.batCd = batCd;
	}

	@Column(name = "BAT_CD_NM", length = 100)
	public String getBatCdNm() {
		return this.batCdNm;
	}

	public void setBatCdNm(String batCdNm) {
		this.batCdNm = batCdNm;

	}

	@Column(name = "CNT", precision = 18, scale = 0)
	public Long getCnt() {
		return this.cnt;
	}

	public void setCnt(Long cnt) {
		this.cnt = cnt;

	}

	@Column(name = "STATUS", length = 100)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;

	}

	@Column(name = "ERR_MSG", length = 1000)
	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getBatCd());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmBatLog))
			return false;
		NcmBatLog castOther = (NcmBatLog) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getBatCd() == null ? 0 : this.getBatCd().hashCode());
		return result;
	}

}
