package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmErpTxIfrStg generated by hbm2java
 */
@Entity
@Table(name = "NCM_ERP_TX_IFR_STG", schema = "NCM")
public class NcmErpTxIfrStg implements java.io.Serializable {

	private NcmErpTxIfrStgId id;

	public NcmErpTxIfrStg() {
	}

	public NcmErpTxIfrStg(NcmErpTxIfrStgId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "eaiSeqNo", column = @Column(name = "EAI_SEQ_NO", nullable = false, precision = 15, scale = 0)),
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 20)),
			@AttributeOverride(name = "finTxNo", column = @Column(name = "FIN_TX_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "bizDiv", column = @Column(name = "BIZ_DIV", length = 20)),
			@AttributeOverride(name = "bizDivNm", column = @Column(name = "BIZ_DIV_NM", length = 100)),
			@AttributeOverride(name = "captDiv", column = @Column(name = "CAPT_DIV", length = 20)),
			@AttributeOverride(name = "captDivNm", column = @Column(name = "CAPT_DIV_NM", length = 100)),
			@AttributeOverride(name = "txType", column = @Column(name = "TX_TYPE", length = 20)),
			@AttributeOverride(name = "txTypeNm", column = @Column(name = "TX_TYPE_NM", length = 100)),
			@AttributeOverride(name = "prodNm", column = @Column(name = "PROD_NM", length = 100)),
			@AttributeOverride(name = "fstFinTxNo", column = @Column(name = "FST_FIN_TX_NO", length = 20)),
			@AttributeOverride(name = "cntPrty", column = @Column(name = "CNT_PRTY", length = 20)),
			@AttributeOverride(name = "cntPrtyNm", column = @Column(name = "CNT_PRTY_NM", length = 100)),
			@AttributeOverride(name = "acctNo", column = @Column(name = "ACCT_NO", length = 25)),
			@AttributeOverride(name = "termStDate", column = @Column(name = "TERM_ST_DATE", length = 20)),
			@AttributeOverride(name = "termEdDate", column = @Column(name = "TERM_ED_DATE", length = 20)),
			@AttributeOverride(name = "origAmt", column = @Column(name = "ORIG_AMT", precision = 20, scale = 0)),
			@AttributeOverride(name = "acctCode", column = @Column(name = "ACCT_CODE", length = 20)),
			@AttributeOverride(name = "acctCodeNm", column = @Column(name = "ACCT_CODE_NM", length = 100)),
			@AttributeOverride(name = "payAmt", column = @Column(name = "PAY_AMT", precision = 20, scale = 0)),
			@AttributeOverride(name = "intAmt", column = @Column(name = "INT_AMT", precision = 20, scale = 0)),
			@AttributeOverride(name = "corpTaxAmt", column = @Column(name = "CORP_TAX_AMT", precision = 20, scale = 0)),
			@AttributeOverride(name = "muniTaxAmt", column = @Column(name = "MUNI_TAX_AMT", precision = 20, scale = 0)),
			@AttributeOverride(name = "residualAmt", column = @Column(name = "RESIDUAL_AMT", precision = 20, scale = 0)),
			@AttributeOverride(name = "bookingDate", column = @Column(name = "BOOKING_DATE", length = 20)),
			@AttributeOverride(name = "bookingNo", column = @Column(name = "BOOKING_NO", length = 20)),
			@AttributeOverride(name = "creDttm", column = @Column(name = "CRE_DTTM", length = 20)),
			@AttributeOverride(name = "chgDttm", column = @Column(name = "CHG_DTTM", length = 20)),
			@AttributeOverride(name = "eaiPttn", column = @Column(name = "EAI_PTTN", length = 1)),
			@AttributeOverride(name = "eaiCreDttm", column = @Column(name = "EAI_CRE_DTTM", length = 7)),
			@AttributeOverride(name = "eaiTrstType", column = @Column(name = "EAI_TRST_TYPE", length = 1)),
			@AttributeOverride(name = "eaiTrstDttm", column = @Column(name = "EAI_TRST_DTTM", length = 7)),
			@AttributeOverride(name = "errMsg", column = @Column(name = "ERR_MSG", length = 200)) })
	public NcmErpTxIfrStgId getId() {
		return this.id;
	}

	public void setId(NcmErpTxIfrStgId id) {
		this.id = id;
	}

}
