package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmErpAccountIfr generated by hbm2java
 */
@Entity
@Table(name = "NCM_ERP_ACCOUNT_IFR", schema = "NCM")
public class NcmErpAccountIfr implements java.io.Serializable {

	private NcmErpAccountIfrId id;
	private String stateCode;
	private String txTypeNm;
	private String termType;
	private String prodType;
	private String prodTypeNm;
	private String cntPrty;
	private String cntPrtyNm;
	private String startDate;
	private String endDate;
	private String creDttm;
	private String chgDttm;
	private String eaiPttn;
	private Date eaiCreDttm;
	private String eaiTrstType;
	private Date eaiTrstDttm;
	private String errMsg;

	public NcmErpAccountIfr() {
	}

	public NcmErpAccountIfr(NcmErpAccountIfrId id) {
		this.id = id;
	}

	public NcmErpAccountIfr(NcmErpAccountIfrId id, String stateCode, String txTypeNm, String termType, String prodType,
			String prodTypeNm, String cntPrty, String cntPrtyNm, String startDate, String endDate, String creDttm,
			String chgDttm, String eaiPttn, Date eaiCreDttm, String eaiTrstType, Date eaiTrstDttm, String errMsg) {
		this.id = id;
		this.stateCode = stateCode;
		this.txTypeNm = txTypeNm;
		this.termType = termType;
		this.prodType = prodType;
		this.prodTypeNm = prodTypeNm;
		this.cntPrty = cntPrty;
		this.cntPrtyNm = cntPrtyNm;
		this.startDate = startDate;
		this.endDate = endDate;
		this.creDttm = creDttm;
		this.chgDttm = chgDttm;
		this.eaiPttn = eaiPttn;
		this.eaiCreDttm = eaiCreDttm;
		this.eaiTrstType = eaiTrstType;
		this.eaiTrstDttm = eaiTrstDttm;
		this.errMsg = errMsg;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "eaiSeqNo", column = @Column(name = "EAI_SEQ_NO", nullable = false, precision = 15, scale = 0)),
			@AttributeOverride(name = "acctNo", column = @Column(name = "ACCT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "txType", column = @Column(name = "TX_TYPE", nullable = false, length = 20)) })
	public NcmErpAccountIfrId getId() {
		return this.id;
	}

	public void setId(NcmErpAccountIfrId id) {
		this.id = id;
	}

	@Column(name = "STATE_CODE", length = 20)
	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	@Column(name = "TX_TYPE_NM", length = 100)
	public String getTxTypeNm() {
		return this.txTypeNm;
	}

	public void setTxTypeNm(String txTypeNm) {
		this.txTypeNm = txTypeNm;
	}

	@Column(name = "TERM_TYPE", length = 20)
	public String getTermType() {
		return this.termType;
	}

	public void setTermType(String termType) {
		this.termType = termType;
	}

	@Column(name = "PROD_TYPE", length = 20)
	public String getProdType() {
		return this.prodType;
	}

	public void setProdType(String prodType) {
		this.prodType = prodType;
	}

	@Column(name = "PROD_TYPE_NM", length = 100)
	public String getProdTypeNm() {
		return this.prodTypeNm;
	}

	public void setProdTypeNm(String prodTypeNm) {
		this.prodTypeNm = prodTypeNm;
	}

	@Column(name = "CNT_PRTY", length = 20)
	public String getCntPrty() {
		return this.cntPrty;
	}

	public void setCntPrty(String cntPrty) {
		this.cntPrty = cntPrty;
	}

	@Column(name = "CNT_PRTY_NM", length = 100)
	public String getCntPrtyNm() {
		return this.cntPrtyNm;
	}

	public void setCntPrtyNm(String cntPrtyNm) {
		this.cntPrtyNm = cntPrtyNm;
	}

	@Column(name = "START_DATE", length = 20)
	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	@Column(name = "END_DATE", length = 20)
	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@Column(name = "CRE_DTTM", length = 20)
	public String getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(String creDttm) {
		this.creDttm = creDttm;
	}

	@Column(name = "CHG_DTTM", length = 20)
	public String getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(String chgDttm) {
		this.chgDttm = chgDttm;
	}

	@Column(name = "EAI_PTTN", length = 1)
	public String getEaiPttn() {
		return this.eaiPttn;
	}

	public void setEaiPttn(String eaiPttn) {
		this.eaiPttn = eaiPttn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EAI_CRE_DTTM", length = 7)
	public Date getEaiCreDttm() {
		return this.eaiCreDttm;
	}

	public void setEaiCreDttm(Date eaiCreDttm) {
		this.eaiCreDttm = eaiCreDttm;
	}

	@Column(name = "EAI_TRST_TYPE", length = 1)
	public String getEaiTrstType() {
		return this.eaiTrstType;
	}

	public void setEaiTrstType(String eaiTrstType) {
		this.eaiTrstType = eaiTrstType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EAI_TRST_DTTM", length = 7)
	public Date getEaiTrstDttm() {
		return this.eaiTrstDttm;
	}

	public void setEaiTrstDttm(Date eaiTrstDttm) {
		this.eaiTrstDttm = eaiTrstDttm;
	}

	@Column(name = "ERR_MSG", length = 200)
	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

}
