package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NcmErpPositionIfrId generated by hbm2java
 */
@Embeddable
public class NcmErpPositionIfrId implements java.io.Serializable {

	private long eaiSeqNo;
	private String baseDate;
	private String finTxNo;

	public NcmErpPositionIfrId() {
	}

	public NcmErpPositionIfrId(long eaiSeqNo, String baseDate, String finTxNo) {
		this.eaiSeqNo = eaiSeqNo;
		this.baseDate = baseDate;
		this.finTxNo = finTxNo;
	}

	@Column(name = "EAI_SEQ_NO", nullable = false, precision = 15, scale = 0)
	public long getEaiSeqNo() {
		return this.eaiSeqNo;
	}

	public void setEaiSeqNo(long eaiSeqNo) {
		this.eaiSeqNo = eaiSeqNo;
	}

	@Column(name = "BASE_DATE", nullable = false, length = 20)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Column(name = "FIN_TX_NO", nullable = false, length = 20)
	public String getFinTxNo() {
		return this.finTxNo;
	}

	public void setFinTxNo(String finTxNo) {
		this.finTxNo = finTxNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmErpPositionIfrId))
			return false;
		NcmErpPositionIfrId castOther = (NcmErpPositionIfrId) other;

		return (this.getEaiSeqNo() == castOther.getEaiSeqNo())
				&& ((this.getBaseDate() == castOther.getBaseDate()) || (this.getBaseDate() != null
						&& castOther.getBaseDate() != null && this.getBaseDate().equals(castOther.getBaseDate())))
				&& ((this.getFinTxNo() == castOther.getFinTxNo()) || (this.getFinTxNo() != null
						&& castOther.getFinTxNo() != null && this.getFinTxNo().equals(castOther.getFinTxNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getEaiSeqNo();
		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getFinTxNo() == null ? 0 : this.getFinTxNo().hashCode());
		return result;
	}

}
