package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * NcmErpTxIfrStg generated by hbm2java
 */

@Entity
@IdClass(value = NcmErpTxIfrStgId.class)
@Table(name = "NCM_ERP_TX_IFR_STG", schema = "NCM")
public class NcmErpTxIfrStg implements java.io.Serializable {

	private long eaiSeqNo;
	private String baseDate;
	private String finTxNo;
	private String bizDiv;
	private String bizDivNm;
	private String captDiv;
	private String captDivNm;
	private String txType;
	private String txTypeNm;
	private String prodNm;
	private String fstFinTxNo;
	private String cntPrty;
	private String cntPrtyNm;
	private String acctNo;
	private String termStDate;
	private String termEdDate;
	private BigDecimal origAmt;
	private String acctCode;
	private String acctCodeNm;
	private BigDecimal payAmt;
	private BigDecimal intAmt;
	private BigDecimal corpTaxAmt;
	private BigDecimal muniTaxAmt;
	private BigDecimal residualAmt;
	private String bookingDate;
	private String bookingNo;
	private String creDttm;
	private String chgDttm;
	private String eaiPttn;
	private Date eaiCreDttm;
	private String eaiTrstType;
	private Date eaiTrstDttm;
	private String errMsg;

	public NcmErpTxIfrStg() {
	}

	@Id
	@Column(name = "EAI_SEQ_NO", nullable = false, precision = 15, scale = 0)
	public long getEaiSeqNo() {
		return this.eaiSeqNo;
	}

	public void setEaiSeqNo(long eaiSeqNo) {
		this.eaiSeqNo = eaiSeqNo;
	}

	@Id
	@Column(name = "BASE_DATE", nullable = false, length = 20)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Id
	@Column(name = "FIN_TX_NO", nullable = false, length = 20)
	public String getFinTxNo() {
		return this.finTxNo;
	}

	public void setFinTxNo(String finTxNo) {
		this.finTxNo = finTxNo;
	}

	@Id
	@Column(name = "BIZ_DIV", length = 20)
	public String getBizDiv() {
		return this.bizDiv;
	}

	public void setBizDiv(String bizDiv) {
		this.bizDiv = bizDiv;
	}

	@Id
	@Column(name = "BIZ_DIV_NM", length = 100)
	public String getBizDivNm() {
		return this.bizDivNm;
	}

	public void setBizDivNm(String bizDivNm) {
		this.bizDivNm = bizDivNm;
	}

	@Id
	@Column(name = "CAPT_DIV", length = 20)
	public String getCaptDiv() {
		return this.captDiv;
	}

	public void setCaptDiv(String captDiv) {
		this.captDiv = captDiv;
	}

	@Id
	@Column(name = "CAPT_DIV_NM", length = 100)
	public String getCaptDivNm() {
		return this.captDivNm;
	}

	public void setCaptDivNm(String captDivNm) {
		this.captDivNm = captDivNm;
	}

	@Id
	@Column(name = "TX_TYPE", length = 20)
	public String getTxType() {
		return this.txType;
	}

	public void setTxType(String txType) {
		this.txType = txType;
	}

	@Id
	@Column(name = "TX_TYPE_NM", length = 100)
	public String getTxTypeNm() {
		return this.txTypeNm;
	}

	public void setTxTypeNm(String txTypeNm) {
		this.txTypeNm = txTypeNm;
	}

	@Id
	@Column(name = "PROD_NM", length = 100)
	public String getProdNm() {
		return this.prodNm;
	}

	public void setProdNm(String prodNm) {
		this.prodNm = prodNm;
	}

	@Id
	@Column(name = "FST_FIN_TX_NO", length = 20)
	public String getFstFinTxNo() {
		return this.fstFinTxNo;
	}

	public void setFstFinTxNo(String fstFinTxNo) {
		this.fstFinTxNo = fstFinTxNo;
	}

	@Id
	@Column(name = "CNT_PRTY", length = 20)
	public String getCntPrty() {
		return this.cntPrty;
	}

	public void setCntPrty(String cntPrty) {
		this.cntPrty = cntPrty;
	}

	@Id
	@Column(name = "CNT_PRTY_NM", length = 100)
	public String getCntPrtyNm() {
		return this.cntPrtyNm;
	}

	public void setCntPrtyNm(String cntPrtyNm) {
		this.cntPrtyNm = cntPrtyNm;
	}

	@Id
	@Column(name = "ACCT_NO", length = 25)
	public String getAcctNo() {
		return this.acctNo;
	}

	public void setAcctNo(String acctNo) {
		this.acctNo = acctNo;
	}

	@Id
	@Column(name = "TERM_ST_DATE", length = 20)
	public String getTermStDate() {
		return this.termStDate;
	}

	public void setTermStDate(String termStDate) {
		this.termStDate = termStDate;
	}

	@Id
	@Column(name = "TERM_ED_DATE", length = 20)
	public String getTermEdDate() {
		return this.termEdDate;
	}

	public void setTermEdDate(String termEdDate) {
		this.termEdDate = termEdDate;
	}

	@Id
	@Column(name = "ORIG_AMT", precision = 20, scale = 0)
	public BigDecimal getOrigAmt() {
		return this.origAmt;
	}

	public void setOrigAmt(BigDecimal origAmt) {
		this.origAmt = origAmt;
	}

	@Id
	@Column(name = "ACCT_CODE", length = 20)
	public String getAcctCode() {
		return this.acctCode;
	}

	public void setAcctCode(String acctCode) {
		this.acctCode = acctCode;
	}

	@Id
	@Column(name = "ACCT_CODE_NM", length = 100)
	public String getAcctCodeNm() {
		return this.acctCodeNm;
	}

	public void setAcctCodeNm(String acctCodeNm) {
		this.acctCodeNm = acctCodeNm;
	}

	@Id
	@Column(name = "PAY_AMT", precision = 20, scale = 0)
	public BigDecimal getPayAmt() {
		return this.payAmt;
	}

	public void setPayAmt(BigDecimal payAmt) {
		this.payAmt = payAmt;
	}

	@Id
	@Column(name = "INT_AMT", precision = 20, scale = 0)
	public BigDecimal getIntAmt() {
		return this.intAmt;
	}

	public void setIntAmt(BigDecimal intAmt) {
		this.intAmt = intAmt;
	}

	@Id
	@Column(name = "CORP_TAX_AMT", precision = 20, scale = 0)
	public BigDecimal getCorpTaxAmt() {
		return this.corpTaxAmt;
	}

	public void setCorpTaxAmt(BigDecimal corpTaxAmt) {
		this.corpTaxAmt = corpTaxAmt;
	}

	@Id
	@Column(name = "MUNI_TAX_AMT", precision = 20, scale = 0)
	public BigDecimal getMuniTaxAmt() {
		return this.muniTaxAmt;
	}

	public void setMuniTaxAmt(BigDecimal muniTaxAmt) {
		this.muniTaxAmt = muniTaxAmt;
	}

	@Id
	@Column(name = "RESIDUAL_AMT", precision = 20, scale = 0)
	public BigDecimal getResidualAmt() {
		return this.residualAmt;
	}

	public void setResidualAmt(BigDecimal residualAmt) {
		this.residualAmt = residualAmt;
	}

	@Id
	@Column(name = "BOOKING_DATE", length = 20)
	public String getBookingDate() {
		return this.bookingDate;
	}

	public void setBookingDate(String bookingDate) {
		this.bookingDate = bookingDate;
	}

	@Id
	@Column(name = "BOOKING_NO", length = 20)
	public String getBookingNo() {
		return this.bookingNo;
	}

	public void setBookingNo(String bookingNo) {
		this.bookingNo = bookingNo;
	}

	@Id
	@Column(name = "CRE_DTTM", length = 20)
	public String getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(String creDttm) {
		this.creDttm = creDttm;
	}

	@Id
	@Column(name = "CHG_DTTM", length = 20)
	public String getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(String chgDttm) {
		this.chgDttm = chgDttm;
	}

	@Id
	@Column(name = "EAI_PTTN", length = 1)
	public String getEaiPttn() {
		return this.eaiPttn;
	}

	public void setEaiPttn(String eaiPttn) {
		this.eaiPttn = eaiPttn;
	}

	@Id
	@Column(name = "EAI_CRE_DTTM", length = 7)
	public Date getEaiCreDttm() {
		return this.eaiCreDttm;
	}

	public void setEaiCreDttm(Date eaiCreDttm) {
		this.eaiCreDttm = eaiCreDttm;
	}

	@Id
	@Column(name = "EAI_TRST_TYPE", length = 1)
	public String getEaiTrstType() {
		return this.eaiTrstType;
	}

	public void setEaiTrstType(String eaiTrstType) {
		this.eaiTrstType = eaiTrstType;
	}

	@Id
	@Column(name = "EAI_TRST_DTTM", length = 7)
	public Date getEaiTrstDttm() {
		return this.eaiTrstDttm;
	}

	public void setEaiTrstDttm(Date eaiTrstDttm) {
		this.eaiTrstDttm = eaiTrstDttm;
	}

	@Id
	@Column(name = "ERR_MSG", length = 200)
	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getEaiSeqNo());
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getFinTxNo());
		buffer.append("#").append(getBizDiv());
		buffer.append("#").append(getBizDivNm());
		buffer.append("#").append(getCaptDiv());
		buffer.append("#").append(getCaptDivNm());
		buffer.append("#").append(getTxType());
		buffer.append("#").append(getTxTypeNm());
		buffer.append("#").append(getProdNm());
		buffer.append("#").append(getFstFinTxNo());
		buffer.append("#").append(getCntPrty());
		buffer.append("#").append(getCntPrtyNm());
		buffer.append("#").append(getAcctNo());
		buffer.append("#").append(getTermStDate());
		buffer.append("#").append(getTermEdDate());
		buffer.append("#").append(getOrigAmt());
		buffer.append("#").append(getAcctCode());
		buffer.append("#").append(getAcctCodeNm());
		buffer.append("#").append(getPayAmt());
		buffer.append("#").append(getIntAmt());
		buffer.append("#").append(getCorpTaxAmt());
		buffer.append("#").append(getMuniTaxAmt());
		buffer.append("#").append(getResidualAmt());
		buffer.append("#").append(getBookingDate());
		buffer.append("#").append(getBookingNo());
		buffer.append("#").append(getCreDttm());
		buffer.append("#").append(getChgDttm());
		buffer.append("#").append(getEaiPttn());
		buffer.append("#").append(getEaiCreDttm());
		buffer.append("#").append(getEaiTrstType());
		buffer.append("#").append(getEaiTrstDttm());
		buffer.append("#").append(getErrMsg());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmErpTxIfrStg))
			return false;
		NcmErpTxIfrStg castOther = (NcmErpTxIfrStg) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getEaiSeqNo();
		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getFinTxNo() == null ? 0 : this.getFinTxNo().hashCode());
		result = 37 * result + (getBizDiv() == null ? 0 : this.getBizDiv().hashCode());
		result = 37 * result + (getBizDivNm() == null ? 0 : this.getBizDivNm().hashCode());
		result = 37 * result + (getCaptDiv() == null ? 0 : this.getCaptDiv().hashCode());
		result = 37 * result + (getCaptDivNm() == null ? 0 : this.getCaptDivNm().hashCode());
		result = 37 * result + (getTxType() == null ? 0 : this.getTxType().hashCode());
		result = 37 * result + (getTxTypeNm() == null ? 0 : this.getTxTypeNm().hashCode());
		result = 37 * result + (getProdNm() == null ? 0 : this.getProdNm().hashCode());
		result = 37 * result + (getFstFinTxNo() == null ? 0 : this.getFstFinTxNo().hashCode());
		result = 37 * result + (getCntPrty() == null ? 0 : this.getCntPrty().hashCode());
		result = 37 * result + (getCntPrtyNm() == null ? 0 : this.getCntPrtyNm().hashCode());
		result = 37 * result + (getAcctNo() == null ? 0 : this.getAcctNo().hashCode());
		result = 37 * result + (getTermStDate() == null ? 0 : this.getTermStDate().hashCode());
		result = 37 * result + (getTermEdDate() == null ? 0 : this.getTermEdDate().hashCode());
		result = 37 * result + (getOrigAmt() == null ? 0 : this.getOrigAmt().hashCode());
		result = 37 * result + (getAcctCode() == null ? 0 : this.getAcctCode().hashCode());
		result = 37 * result + (getAcctCodeNm() == null ? 0 : this.getAcctCodeNm().hashCode());
		result = 37 * result + (getPayAmt() == null ? 0 : this.getPayAmt().hashCode());
		result = 37 * result + (getIntAmt() == null ? 0 : this.getIntAmt().hashCode());
		result = 37 * result + (getCorpTaxAmt() == null ? 0 : this.getCorpTaxAmt().hashCode());
		result = 37 * result + (getMuniTaxAmt() == null ? 0 : this.getMuniTaxAmt().hashCode());
		result = 37 * result + (getResidualAmt() == null ? 0 : this.getResidualAmt().hashCode());
		result = 37 * result + (getBookingDate() == null ? 0 : this.getBookingDate().hashCode());
		result = 37 * result + (getBookingNo() == null ? 0 : this.getBookingNo().hashCode());
		result = 37 * result + (getCreDttm() == null ? 0 : this.getCreDttm().hashCode());
		result = 37 * result + (getChgDttm() == null ? 0 : this.getChgDttm().hashCode());
		result = 37 * result + (getEaiPttn() == null ? 0 : this.getEaiPttn().hashCode());
		result = 37 * result + (getEaiCreDttm() == null ? 0 : this.getEaiCreDttm().hashCode());
		result = 37 * result + (getEaiTrstType() == null ? 0 : this.getEaiTrstType().hashCode());
		result = 37 * result + (getEaiTrstDttm() == null ? 0 : this.getEaiTrstDttm().hashCode());
		result = 37 * result + (getErrMsg() == null ? 0 : this.getErrMsg().hashCode());
		return result;
	}

}
