package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmErpPositionIfr generated by hbm2java
 */
@Entity
@Table(name = "NCM_ERP_POSITION_IFR", schema = "NCM")
public class NcmErpPositionIfr implements java.io.Serializable {

	private NcmErpPositionIfrId id;
	private String acctDiv;
	private String bizDiv;
	private String bizDivNm;
	private String captDiv;
	private String captDivNm;
	private String txType;
	private String txTypeNm;
	private String prodNm;
	private String fstFinTxNo;
	private String termType;
	private String cntPrty;
	private String cntPrtyNm;
	private String acctNo;
	private String buyDate;
	private String maturityDate;
	private Long holdingTerm;
	private BigDecimal holdingAmt;
	private BigDecimal intRate;
	private String creDttm;
	private String chgDttm;
	private String eaiPttn;
	private Date eaiCreDttm;
	private String eaiTrstType;
	private Date eaiTrstDttm;
	private String errMsg;

	public NcmErpPositionIfr() {
	}

	public NcmErpPositionIfr(NcmErpPositionIfrId id) {
		this.id = id;
	}

	public NcmErpPositionIfr(NcmErpPositionIfrId id, String acctDiv, String bizDiv, String bizDivNm, String captDiv,
			String captDivNm, String txType, String txTypeNm, String prodNm, String fstFinTxNo, String termType,
			String cntPrty, String cntPrtyNm, String acctNo, String buyDate, String maturityDate, Long holdingTerm,
			BigDecimal holdingAmt, BigDecimal intRate, String creDttm, String chgDttm, String eaiPttn, Date eaiCreDttm,
			String eaiTrstType, Date eaiTrstDttm, String errMsg) {
		this.id = id;
		this.acctDiv = acctDiv;
		this.bizDiv = bizDiv;
		this.bizDivNm = bizDivNm;
		this.captDiv = captDiv;
		this.captDivNm = captDivNm;
		this.txType = txType;
		this.txTypeNm = txTypeNm;
		this.prodNm = prodNm;
		this.fstFinTxNo = fstFinTxNo;
		this.termType = termType;
		this.cntPrty = cntPrty;
		this.cntPrtyNm = cntPrtyNm;
		this.acctNo = acctNo;
		this.buyDate = buyDate;
		this.maturityDate = maturityDate;
		this.holdingTerm = holdingTerm;
		this.holdingAmt = holdingAmt;
		this.intRate = intRate;
		this.creDttm = creDttm;
		this.chgDttm = chgDttm;
		this.eaiPttn = eaiPttn;
		this.eaiCreDttm = eaiCreDttm;
		this.eaiTrstType = eaiTrstType;
		this.eaiTrstDttm = eaiTrstDttm;
		this.errMsg = errMsg;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "eaiSeqNo", column = @Column(name = "EAI_SEQ_NO", nullable = false, precision = 15, scale = 0)),
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 20)),
			@AttributeOverride(name = "finTxNo", column = @Column(name = "FIN_TX_NO", nullable = false, length = 20)) })
	public NcmErpPositionIfrId getId() {
		return this.id;
	}

	public void setId(NcmErpPositionIfrId id) {
		this.id = id;
	}

	@Column(name = "ACCT_DIV", length = 20)
	public String getAcctDiv() {
		return this.acctDiv;
	}

	public void setAcctDiv(String acctDiv) {
		this.acctDiv = acctDiv;
	}

	@Column(name = "BIZ_DIV", length = 20)
	public String getBizDiv() {
		return this.bizDiv;
	}

	public void setBizDiv(String bizDiv) {
		this.bizDiv = bizDiv;
	}

	@Column(name = "BIZ_DIV_NM", length = 100)
	public String getBizDivNm() {
		return this.bizDivNm;
	}

	public void setBizDivNm(String bizDivNm) {
		this.bizDivNm = bizDivNm;
	}

	@Column(name = "CAPT_DIV", length = 20)
	public String getCaptDiv() {
		return this.captDiv;
	}

	public void setCaptDiv(String captDiv) {
		this.captDiv = captDiv;
	}

	@Column(name = "CAPT_DIV_NM", length = 100)
	public String getCaptDivNm() {
		return this.captDivNm;
	}

	public void setCaptDivNm(String captDivNm) {
		this.captDivNm = captDivNm;
	}

	@Column(name = "TX_TYPE", length = 20)
	public String getTxType() {
		return this.txType;
	}

	public void setTxType(String txType) {
		this.txType = txType;
	}

	@Column(name = "TX_TYPE_NM", length = 100)
	public String getTxTypeNm() {
		return this.txTypeNm;
	}

	public void setTxTypeNm(String txTypeNm) {
		this.txTypeNm = txTypeNm;
	}

	@Column(name = "PROD_NM", length = 100)
	public String getProdNm() {
		return this.prodNm;
	}

	public void setProdNm(String prodNm) {
		this.prodNm = prodNm;
	}

	@Column(name = "FST_FIN_TX_NO", length = 20)
	public String getFstFinTxNo() {
		return this.fstFinTxNo;
	}

	public void setFstFinTxNo(String fstFinTxNo) {
		this.fstFinTxNo = fstFinTxNo;
	}

	@Column(name = "TERM_TYPE", length = 20)
	public String getTermType() {
		return this.termType;
	}

	public void setTermType(String termType) {
		this.termType = termType;
	}

	@Column(name = "CNT_PRTY", length = 20)
	public String getCntPrty() {
		return this.cntPrty;
	}

	public void setCntPrty(String cntPrty) {
		this.cntPrty = cntPrty;
	}

	@Column(name = "CNT_PRTY_NM", length = 100)
	public String getCntPrtyNm() {
		return this.cntPrtyNm;
	}

	public void setCntPrtyNm(String cntPrtyNm) {
		this.cntPrtyNm = cntPrtyNm;
	}

	@Column(name = "ACCT_NO", length = 25)
	public String getAcctNo() {
		return this.acctNo;
	}

	public void setAcctNo(String acctNo) {
		this.acctNo = acctNo;
	}

	@Column(name = "BUY_DATE", length = 20)
	public String getBuyDate() {
		return this.buyDate;
	}

	public void setBuyDate(String buyDate) {
		this.buyDate = buyDate;
	}

	@Column(name = "MATURITY_DATE", length = 20)
	public String getMaturityDate() {
		return this.maturityDate;
	}

	public void setMaturityDate(String maturityDate) {
		this.maturityDate = maturityDate;
	}

	@Column(name = "HOLDING_TERM", precision = 10, scale = 0)
	public Long getHoldingTerm() {
		return this.holdingTerm;
	}

	public void setHoldingTerm(Long holdingTerm) {
		this.holdingTerm = holdingTerm;
	}

	@Column(name = "HOLDING_AMT", precision = 20, scale = 0)
	public BigDecimal getHoldingAmt() {
		return this.holdingAmt;
	}

	public void setHoldingAmt(BigDecimal holdingAmt) {
		this.holdingAmt = holdingAmt;
	}

	@Column(name = "INT_RATE", precision = 10, scale = 8)
	public BigDecimal getIntRate() {
		return this.intRate;
	}

	public void setIntRate(BigDecimal intRate) {
		this.intRate = intRate;
	}

	@Column(name = "CRE_DTTM", length = 20)
	public String getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(String creDttm) {
		this.creDttm = creDttm;
	}

	@Column(name = "CHG_DTTM", length = 20)
	public String getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(String chgDttm) {
		this.chgDttm = chgDttm;
	}

	@Column(name = "EAI_PTTN", length = 1)
	public String getEaiPttn() {
		return this.eaiPttn;
	}

	public void setEaiPttn(String eaiPttn) {
		this.eaiPttn = eaiPttn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EAI_CRE_DTTM", length = 7)
	public Date getEaiCreDttm() {
		return this.eaiCreDttm;
	}

	public void setEaiCreDttm(Date eaiCreDttm) {
		this.eaiCreDttm = eaiCreDttm;
	}

	@Column(name = "EAI_TRST_TYPE", length = 1)
	public String getEaiTrstType() {
		return this.eaiTrstType;
	}

	public void setEaiTrstType(String eaiTrstType) {
		this.eaiTrstType = eaiTrstType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EAI_TRST_DTTM", length = 7)
	public Date getEaiTrstDttm() {
		return this.eaiTrstDttm;
	}

	public void setEaiTrstDttm(Date eaiTrstDttm) {
		this.eaiTrstDttm = eaiTrstDttm;
	}

	@Column(name = "ERR_MSG", length = 200)
	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

}
