package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NcmErpTxIfrTempId generated by hbm2java
 */
@Embeddable
public class NcmErpTxIfrTempId implements java.io.Serializable {

	private String cptlDivCd;
	private String finTxNo;

	public NcmErpTxIfrTempId() {
	}

	public NcmErpTxIfrTempId(String cptlDivCd, String finTxNo) {
		this.cptlDivCd = cptlDivCd;
		this.finTxNo = finTxNo;
	}

	@Column(name = "CPTL_DIV_CD", nullable = false, length = 10)
	public String getCptlDivCd() {
		return this.cptlDivCd;
	}

	public void setCptlDivCd(String cptlDivCd) {
		this.cptlDivCd = cptlDivCd;
	}

	@Column(name = "FIN_TX_NO", nullable = false, length = 20)
	public String getFinTxNo() {
		return this.finTxNo;
	}

	public void setFinTxNo(String finTxNo) {
		this.finTxNo = finTxNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmErpTxIfrTempId))
			return false;
		NcmErpTxIfrTempId castOther = (NcmErpTxIfrTempId) other;

		return ((this.getCptlDivCd() == castOther.getCptlDivCd()) || (this.getCptlDivCd() != null
				&& castOther.getCptlDivCd() != null && this.getCptlDivCd().equals(castOther.getCptlDivCd())))
				&& ((this.getFinTxNo() == castOther.getFinTxNo()) || (this.getFinTxNo() != null
						&& castOther.getFinTxNo() != null && this.getFinTxNo().equals(castOther.getFinTxNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCptlDivCd() == null ? 0 : this.getCptlDivCd().hashCode());
		result = 37 * result + (getFinTxNo() == null ? 0 : this.getFinTxNo().hashCode());
		return result;
	}

}
