package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmErpTxIfrTemp generated by hbm2java
 */
@Entity
@Table(name = "NCM_ERP_TX_IFR_TEMP", schema = "NCM")
public class NcmErpTxIfrTemp implements java.io.Serializable {

	private NcmErpTxIfrTempId id;
	private String bookingNo;
	private String issuerNm;
	private BigDecimal issuAmt;
	private String issuDate;
	private String matDate;
	private BigDecimal intRate;
	private String fstTxNo;
	private String div;
	private String prodNnm;

	public NcmErpTxIfrTemp() {
	}

	public NcmErpTxIfrTemp(NcmErpTxIfrTempId id) {
		this.id = id;
	}

	public NcmErpTxIfrTemp(NcmErpTxIfrTempId id, String bookingNo, String issuerNm, BigDecimal issuAmt, String issuDate,
			String matDate, BigDecimal intRate, String fstTxNo, String div, String prodNnm) {
		this.id = id;
		this.bookingNo = bookingNo;
		this.issuerNm = issuerNm;
		this.issuAmt = issuAmt;
		this.issuDate = issuDate;
		this.matDate = matDate;
		this.intRate = intRate;
		this.fstTxNo = fstTxNo;
		this.div = div;
		this.prodNnm = prodNnm;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cptlDivCd", column = @Column(name = "CPTL_DIV_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "finTxNo", column = @Column(name = "FIN_TX_NO", nullable = false, length = 20)) })
	public NcmErpTxIfrTempId getId() {
		return this.id;
	}

	public void setId(NcmErpTxIfrTempId id) {
		this.id = id;
	}

	@Column(name = "BOOKING_NO", length = 20)
	public String getBookingNo() {
		return this.bookingNo;
	}

	public void setBookingNo(String bookingNo) {
		this.bookingNo = bookingNo;
	}

	@Column(name = "ISSUER_NM", length = 100)
	public String getIssuerNm() {
		return this.issuerNm;
	}

	public void setIssuerNm(String issuerNm) {
		this.issuerNm = issuerNm;
	}

	@Column(name = "ISSU_AMT", precision = 20)
	public BigDecimal getIssuAmt() {
		return this.issuAmt;
	}

	public void setIssuAmt(BigDecimal issuAmt) {
		this.issuAmt = issuAmt;
	}

	@Column(name = "ISSU_DATE", length = 8)
	public String getIssuDate() {
		return this.issuDate;
	}

	public void setIssuDate(String issuDate) {
		this.issuDate = issuDate;
	}

	@Column(name = "MAT_DATE", length = 8)
	public String getMatDate() {
		return this.matDate;
	}

	public void setMatDate(String matDate) {
		this.matDate = matDate;
	}

	@Column(name = "INT_RATE", precision = 12, scale = 8)
	public BigDecimal getIntRate() {
		return this.intRate;
	}

	public void setIntRate(BigDecimal intRate) {
		this.intRate = intRate;
	}

	@Column(name = "FST_TX_NO", length = 20)
	public String getFstTxNo() {
		return this.fstTxNo;
	}

	public void setFstTxNo(String fstTxNo) {
		this.fstTxNo = fstTxNo;
	}

	@Column(name = "DIV", length = 10)
	public String getDiv() {
		return this.div;
	}

	public void setDiv(String div) {
		this.div = div;
	}

	@Column(name = "PROD_NNM", length = 100)
	public String getProdNnm() {
		return this.prodNnm;
	}

	public void setProdNnm(String prodNnm) {
		this.prodNnm = prodNnm;
	}

}
