package com.eugenefe.ncm;
// Generated Dec 8, 2016 3:49:34 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmKfrHoldingDetail generated by hbm2java
 */

@Entity
@IdClass(value = NcmKfrHoldingDetailId.class)
@Table(name = "NCM_KFR_HOLDING_DETAIL", schema = "NCM")
public class NcmKfrHoldingDetail implements java.io.Serializable, Navigatable {

	private String tradeday;
	private String mgrcode;
	private String fundmgrcode;
	private String itemcode;
	private int dataseq;
	private String itemkname;
	private String buydate;
	private String buyseq;
	private String positioncode;
	private String assetbclasscode;
	private String assetsclasscode;
	private long qty;
	private BigDecimal price;
	private long investamt;
	private long bookamt;
	private long evalamt;
	private Long evalpl;
	private Long accrudividamt;
	private BigDecimal buyyield;
	private BigDecimal ytm;
	private BigDecimal couprate;
	private String issueday;
	private String dueday;
	private String lastbuydate;
	private BigDecimal duration;
	private BigDecimal spread;
	private BigDecimal disprarate;
	private String creditgrade;
	private String isscorpno;
	private String isscorpname;
	private String evalcorpcode;
	private Date creDttm;
	private String creEmpNo;
	private Date chgDttm;
	private String chgEmpNo;
	private String workfilename;

	public NcmKfrHoldingDetail() {
	}

	@Id
	@Column(name = "TRADEDAY", nullable = false, length = 8)
	public String getTradeday() {
		return this.tradeday;
	}

	public void setTradeday(String tradeday) {
		this.tradeday = tradeday;
	}

	@Id
	@Column(name = "MGRCODE", nullable = false, length = 3)
	public String getMgrcode() {
		return this.mgrcode;
	}

	public void setMgrcode(String mgrcode) {
		this.mgrcode = mgrcode;
	}

	@Id
	@Column(name = "FUNDMGRCODE", nullable = false, length = 30)
	public String getFundmgrcode() {
		return this.fundmgrcode;
	}

	public void setFundmgrcode(String fundmgrcode) {
		this.fundmgrcode = fundmgrcode;
	}

	@Id
	@Column(name = "ITEMCODE", nullable = false, length = 50)
	public String getItemcode() {
		return this.itemcode;
	}

	public void setItemcode(String itemcode) {
		this.itemcode = itemcode;
	}

	@Id
	@Column(name = "DATASEQ", nullable = false, precision = 5, scale = 0)
	public int getDataseq() {
		return this.dataseq;
	}

	public void setDataseq(int dataseq) {
		this.dataseq = dataseq;
	}

	@Column(name = "ITEMKNAME", nullable = false, length = 100)
	public String getItemkname() {
		return this.itemkname;
	}

	public void setItemkname(String itemkname) {
		this.itemkname = itemkname;

	}

	@Column(name = "BUYDATE", length = 8)
	public String getBuydate() {
		return this.buydate;
	}

	public void setBuydate(String buydate) {
		this.buydate = buydate;

	}

	@Column(name = "BUYSEQ", length = 5)
	public String getBuyseq() {
		return this.buyseq;
	}

	public void setBuyseq(String buyseq) {
		this.buyseq = buyseq;

	}

	@Column(name = "POSITIONCODE", length = 1)
	public String getPositioncode() {
		return this.positioncode;
	}

	public void setPositioncode(String positioncode) {
		this.positioncode = positioncode;

	}

	@Column(name = "ASSETBCLASSCODE", nullable = false, length = 2)
	public String getAssetbclasscode() {
		return this.assetbclasscode;
	}

	public void setAssetbclasscode(String assetbclasscode) {
		this.assetbclasscode = assetbclasscode;

	}

	@Column(name = "ASSETSCLASSCODE", nullable = false, length = 2)
	public String getAssetsclasscode() {
		return this.assetsclasscode;
	}

	public void setAssetsclasscode(String assetsclasscode) {
		this.assetsclasscode = assetsclasscode;

	}

	@Column(name = "QTY", nullable = false, precision = 18, scale = 0)
	public long getQty() {
		return this.qty;
	}

	public void setQty(long qty) {
		this.qty = qty;

	}

	@Column(name = "PRICE", nullable = false, precision = 22, scale = 3)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;

	}

	@Column(name = "INVESTAMT", nullable = false, precision = 18, scale = 0)
	public long getInvestamt() {
		return this.investamt;
	}

	public void setInvestamt(long investamt) {
		this.investamt = investamt;

	}

	@Column(name = "BOOKAMT", nullable = false, precision = 18, scale = 0)
	public long getBookamt() {
		return this.bookamt;
	}

	public void setBookamt(long bookamt) {
		this.bookamt = bookamt;

	}

	@Column(name = "EVALAMT", nullable = false, precision = 18, scale = 0)
	public long getEvalamt() {
		return this.evalamt;
	}

	public void setEvalamt(long evalamt) {
		this.evalamt = evalamt;

	}

	@Column(name = "EVALPL", precision = 18, scale = 0)
	public Long getEvalpl() {
		return this.evalpl;
	}

	public void setEvalpl(Long evalpl) {
		this.evalpl = evalpl;

	}

	@Column(name = "ACCRUDIVIDAMT", precision = 18, scale = 0)
	public Long getAccrudividamt() {
		return this.accrudividamt;
	}

	public void setAccrudividamt(Long accrudividamt) {
		this.accrudividamt = accrudividamt;

	}

	@Column(name = "BUYYIELD", precision = 18)
	public BigDecimal getBuyyield() {
		return this.buyyield;
	}

	public void setBuyyield(BigDecimal buyyield) {
		this.buyyield = buyyield;

	}

	@Column(name = "YTM", nullable = false, precision = 32, scale = 6)
	public BigDecimal getYtm() {
		return this.ytm;
	}

	public void setYtm(BigDecimal ytm) {
		this.ytm = ytm;

	}

	@Column(name = "COUPRATE", nullable = false, precision = 18)
	public BigDecimal getCouprate() {
		return this.couprate;
	}

	public void setCouprate(BigDecimal couprate) {
		this.couprate = couprate;

	}

	@Column(name = "ISSUEDAY", length = 8)
	public String getIssueday() {
		return this.issueday;
	}

	public void setIssueday(String issueday) {
		this.issueday = issueday;

	}

	@Column(name = "DUEDAY", length = 8)
	public String getDueday() {
		return this.dueday;
	}

	public void setDueday(String dueday) {
		this.dueday = dueday;

	}

	@Column(name = "LASTBUYDATE", length = 8)
	public String getLastbuydate() {
		return this.lastbuydate;
	}

	public void setLastbuydate(String lastbuydate) {
		this.lastbuydate = lastbuydate;

	}

	@Column(name = "DURATION", nullable = false, precision = 20, scale = 12)
	public BigDecimal getDuration() {
		return this.duration;
	}

	public void setDuration(BigDecimal duration) {
		this.duration = duration;

	}

	@Column(name = "SPREAD", nullable = false, precision = 20, scale = 12)
	public BigDecimal getSpread() {
		return this.spread;
	}

	public void setSpread(BigDecimal spread) {
		this.spread = spread;

	}

	@Column(name = "DISPRARATE", nullable = false, precision = 20, scale = 12)
	public BigDecimal getDisprarate() {
		return this.disprarate;
	}

	public void setDisprarate(BigDecimal disprarate) {
		this.disprarate = disprarate;

	}

	@Column(name = "CREDITGRADE", length = 4)
	public String getCreditgrade() {
		return this.creditgrade;
	}

	public void setCreditgrade(String creditgrade) {
		this.creditgrade = creditgrade;

	}

	@Column(name = "ISSCORPNO", length = 13)
	public String getIsscorpno() {
		return this.isscorpno;
	}

	public void setIsscorpno(String isscorpno) {
		this.isscorpno = isscorpno;

	}

	@Column(name = "ISSCORPNAME", length = 50)
	public String getIsscorpname() {
		return this.isscorpname;
	}

	public void setIsscorpname(String isscorpname) {
		this.isscorpname = isscorpname;

	}

	@Column(name = "EVALCORPCODE", nullable = false, length = 4)
	public String getEvalcorpcode() {
		return this.evalcorpcode;
	}

	public void setEvalcorpcode(String evalcorpcode) {
		this.evalcorpcode = evalcorpcode;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRE_DTTM", length = 7)
	public Date getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm) {
		this.creDttm = creDttm;

	}

	@Column(name = "CRE_EMP_NO", length = 6)
	public String getCreEmpNo() {
		return this.creEmpNo;
	}

	public void setCreEmpNo(String creEmpNo) {
		this.creEmpNo = creEmpNo;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHG_DTTM", length = 7)
	public Date getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(Date chgDttm) {
		this.chgDttm = chgDttm;

	}

	@Column(name = "CHG_EMP_NO", length = 6)
	public String getChgEmpNo() {
		return this.chgEmpNo;
	}

	public void setChgEmpNo(String chgEmpNo) {
		this.chgEmpNo = chgEmpNo;

	}

	@Column(name = "WORKFILENAME", length = 30)
	public String getWorkfilename() {
		return this.workfilename;
	}

	public void setWorkfilename(String workfilename) {
		this.workfilename = workfilename;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getTradeday());
		buffer.append("#").append(getMgrcode());
		buffer.append("#").append(getFundmgrcode());
		buffer.append("#").append(getItemcode());
		buffer.append("#").append(getDataseq());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmKfrHoldingDetail))
			return false;
		NcmKfrHoldingDetail castOther = (NcmKfrHoldingDetail) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTradeday() == null ? 0 : this.getTradeday().hashCode());
		result = 37 * result + (getMgrcode() == null ? 0 : this.getMgrcode().hashCode());
		result = 37 * result + (getFundmgrcode() == null ? 0 : this.getFundmgrcode().hashCode());
		result = 37 * result + (getItemcode() == null ? 0 : this.getItemcode().hashCode());
		result = 37 * result + this.getDataseq();
		return result;
	}

}
