package com.eugenefe.ncm;
// Generated Dec 8, 2016 3:49:34 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

/**
 * NcmKfrHoldingDetailId generated by hbm2java
 */

public class NcmKfrHoldingDetailId implements java.io.Serializable, Navigatable {

	private String tradeday;
	private String mgrcode;
	private String fundmgrcode;
	private String itemcode;
	private int dataseq;

	public NcmKfrHoldingDetailId() {
	}

	public String getTradeday() {
		return this.tradeday;
	}

	public void setTradeday(String tradeday) {
		this.tradeday = tradeday;

	}

	public String getMgrcode() {
		return this.mgrcode;
	}

	public void setMgrcode(String mgrcode) {
		this.mgrcode = mgrcode;

	}

	public String getFundmgrcode() {
		return this.fundmgrcode;
	}

	public void setFundmgrcode(String fundmgrcode) {
		this.fundmgrcode = fundmgrcode;

	}

	public String getItemcode() {
		return this.itemcode;
	}

	public void setItemcode(String itemcode) {
		this.itemcode = itemcode;

	}

	public int getDataseq() {
		return this.dataseq;
	}

	public void setDataseq(int dataseq) {
		this.dataseq = dataseq;

	}

	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getTradeday());
		buffer.append("#").append(getMgrcode());
		buffer.append("#").append(getFundmgrcode());
		buffer.append("#").append(getItemcode());
		buffer.append("#").append(getDataseq());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmKfrHoldingDetailId))
			return false;
		NcmKfrHoldingDetailId castOther = (NcmKfrHoldingDetailId) other;

		return ((this.getTradeday() == castOther.getTradeday())
				|| (this.getTradeday() != null && castOther.getTradeday() != null && this.getTradeday().equals(castOther.getTradeday())))
				&& ((this.getMgrcode() == castOther.getMgrcode())
						|| (this.getMgrcode() != null && castOther.getMgrcode() != null && this.getMgrcode().equals(castOther.getMgrcode())))
				&& ((this.getFundmgrcode() == castOther.getFundmgrcode())
						|| (this.getFundmgrcode() != null && castOther.getFundmgrcode() != null && this.getFundmgrcode().equals(castOther.getFundmgrcode())))
				&& ((this.getItemcode() == castOther.getItemcode())
						|| (this.getItemcode() != null && castOther.getItemcode() != null && this.getItemcode().equals(castOther.getItemcode())))
				&& (this.getDataseq() == castOther.getDataseq());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTradeday() == null ? 0 : this.getTradeday().hashCode());
		result = 37 * result + (getMgrcode() == null ? 0 : this.getMgrcode().hashCode());
		result = 37 * result + (getFundmgrcode() == null ? 0 : this.getFundmgrcode().hashCode());
		result = 37 * result + (getItemcode() == null ? 0 : this.getItemcode().hashCode());
		result = 37 * result + this.getDataseq();
		return result;
	}

}
