package com.eugenefe.ncm;
// Generated Dec 8, 2016 3:49:34 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmKfrFundYield generated by hbm2java
 */

@Entity
@IdClass(value = NcmKfrFundYieldId.class)
@Table(name = "NCM_KFR_FUND_YIELD", schema = "NCM")
public class NcmKfrFundYield implements java.io.Serializable, Navigatable {

	private String tradeday;
	private String mgrcode;
	private String fundmgrcode;
	private BigDecimal fundret1d;
	private BigDecimal fundretidx;
	private BigDecimal fundret1m;
	private BigDecimal fundret3m;
	private BigDecimal fundret6m;
	private BigDecimal fundret1y;
	private BigDecimal fundretytd;
	private String evalcorpcode;
	private Date creDttm;
	private String creEmpNo;
	private Date chgDttm;
	private String chgEmpNo;
	private String workfilename;

	public NcmKfrFundYield() {
	}

	@Id
	@Column(name = "TRADEDAY", nullable = false, length = 8)
	public String getTradeday() {
		return this.tradeday;
	}

	public void setTradeday(String tradeday) {
		this.tradeday = tradeday;
	}

	@Id
	@Column(name = "MGRCODE", nullable = false, length = 3)
	public String getMgrcode() {
		return this.mgrcode;
	}

	public void setMgrcode(String mgrcode) {
		this.mgrcode = mgrcode;
	}

	@Id
	@Column(name = "FUNDMGRCODE", nullable = false, length = 30)
	public String getFundmgrcode() {
		return this.fundmgrcode;
	}

	public void setFundmgrcode(String fundmgrcode) {
		this.fundmgrcode = fundmgrcode;
	}

	@Column(name = "FUNDRET1D", nullable = false, precision = 20, scale = 12)
	public BigDecimal getFundret1d() {
		return this.fundret1d;
	}

	public void setFundret1d(BigDecimal fundret1d) {
		this.fundret1d = fundret1d;

	}

	@Column(name = "FUNDRETIDX", nullable = false, precision = 20, scale = 12)
	public BigDecimal getFundretidx() {
		return this.fundretidx;
	}

	public void setFundretidx(BigDecimal fundretidx) {
		this.fundretidx = fundretidx;

	}

	@Column(name = "FUNDRET1M", nullable = false, precision = 20, scale = 12)
	public BigDecimal getFundret1m() {
		return this.fundret1m;
	}

	public void setFundret1m(BigDecimal fundret1m) {
		this.fundret1m = fundret1m;

	}

	@Column(name = "FUNDRET3M", nullable = false, precision = 20, scale = 12)
	public BigDecimal getFundret3m() {
		return this.fundret3m;
	}

	public void setFundret3m(BigDecimal fundret3m) {
		this.fundret3m = fundret3m;

	}

	@Column(name = "FUNDRET6M", nullable = false, precision = 20, scale = 12)
	public BigDecimal getFundret6m() {
		return this.fundret6m;
	}

	public void setFundret6m(BigDecimal fundret6m) {
		this.fundret6m = fundret6m;

	}

	@Column(name = "FUNDRET1Y", nullable = false, precision = 20, scale = 12)
	public BigDecimal getFundret1y() {
		return this.fundret1y;
	}

	public void setFundret1y(BigDecimal fundret1y) {
		this.fundret1y = fundret1y;

	}

	@Column(name = "FUNDRETYTD", nullable = false, precision = 20, scale = 12)
	public BigDecimal getFundretytd() {
		return this.fundretytd;
	}

	public void setFundretytd(BigDecimal fundretytd) {
		this.fundretytd = fundretytd;

	}

	@Column(name = "EVALCORPCODE", nullable = false, length = 4)
	public String getEvalcorpcode() {
		return this.evalcorpcode;
	}

	public void setEvalcorpcode(String evalcorpcode) {
		this.evalcorpcode = evalcorpcode;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRE_DTTM", nullable = false, length = 7)
	public Date getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm) {
		this.creDttm = creDttm;

	}

	@Column(name = "CRE_EMP_NO", nullable = false, length = 6)
	public String getCreEmpNo() {
		return this.creEmpNo;
	}

	public void setCreEmpNo(String creEmpNo) {
		this.creEmpNo = creEmpNo;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHG_DTTM", nullable = false, length = 7)
	public Date getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(Date chgDttm) {
		this.chgDttm = chgDttm;

	}

	@Column(name = "CHG_EMP_NO", nullable = false, length = 6)
	public String getChgEmpNo() {
		return this.chgEmpNo;
	}

	public void setChgEmpNo(String chgEmpNo) {
		this.chgEmpNo = chgEmpNo;

	}

	@Column(name = "WORKFILENAME", length = 30)
	public String getWorkfilename() {
		return this.workfilename;
	}

	public void setWorkfilename(String workfilename) {
		this.workfilename = workfilename;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getTradeday());
		buffer.append("#").append(getMgrcode());
		buffer.append("#").append(getFundmgrcode());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmKfrFundYield))
			return false;
		NcmKfrFundYield castOther = (NcmKfrFundYield) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTradeday() == null ? 0 : this.getTradeday().hashCode());
		result = 37 * result + (getMgrcode() == null ? 0 : this.getMgrcode().hashCode());
		result = 37 * result + (getFundmgrcode() == null ? 0 : this.getFundmgrcode().hashCode());
		return result;
	}

}
