package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmKfrMarketIndex generated by hbm2java
 */
@Entity
@Table(name = "NCM_KFR_MARKET_INDEX", schema = "NCM")
public class NcmKfrMarketIndex implements java.io.Serializable {

	private NcmKfrMarketIndexId id;
	private String mktname;
	private String indextype;
	private BigDecimal idxval;
	private BigDecimal coupon;
	private String evalcorpcode;
	private Date creDttm;
	private String creEmpNo;
	private Date chgDttm;
	private String chgEmpNo;
	private String workfilename;

	public NcmKfrMarketIndex() {
	}

	public NcmKfrMarketIndex(NcmKfrMarketIndexId id, String mktname, String evalcorpcode, Date creDttm, String creEmpNo,
			Date chgDttm, String chgEmpNo) {
		this.id = id;
		this.mktname = mktname;
		this.evalcorpcode = evalcorpcode;
		this.creDttm = creDttm;
		this.creEmpNo = creEmpNo;
		this.chgDttm = chgDttm;
		this.chgEmpNo = chgEmpNo;
	}

	public NcmKfrMarketIndex(NcmKfrMarketIndexId id, String mktname, String indextype, BigDecimal idxval,
			BigDecimal coupon, String evalcorpcode, Date creDttm, String creEmpNo, Date chgDttm, String chgEmpNo,
			String workfilename) {
		this.id = id;
		this.mktname = mktname;
		this.indextype = indextype;
		this.idxval = idxval;
		this.coupon = coupon;
		this.evalcorpcode = evalcorpcode;
		this.creDttm = creDttm;
		this.creEmpNo = creEmpNo;
		this.chgDttm = chgDttm;
		this.chgEmpNo = chgEmpNo;
		this.workfilename = workfilename;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tradeday", column = @Column(name = "TRADEDAY", nullable = false, length = 8)),
			@AttributeOverride(name = "mktcode", column = @Column(name = "MKTCODE", nullable = false, length = 10)) })
	public NcmKfrMarketIndexId getId() {
		return this.id;
	}

	public void setId(NcmKfrMarketIndexId id) {
		this.id = id;
	}

	@Column(name = "MKTNAME", nullable = false, length = 50)
	public String getMktname() {
		return this.mktname;
	}

	public void setMktname(String mktname) {
		this.mktname = mktname;
	}

	@Column(name = "INDEXTYPE", length = 2)
	public String getIndextype() {
		return this.indextype;
	}

	public void setIndextype(String indextype) {
		this.indextype = indextype;
	}

	@Column(name = "IDXVAL", precision = 20, scale = 12)
	public BigDecimal getIdxval() {
		return this.idxval;
	}

	public void setIdxval(BigDecimal idxval) {
		this.idxval = idxval;
	}

	@Column(name = "COUPON", precision = 20, scale = 12)
	public BigDecimal getCoupon() {
		return this.coupon;
	}

	public void setCoupon(BigDecimal coupon) {
		this.coupon = coupon;
	}

	@Column(name = "EVALCORPCODE", nullable = false, length = 4)
	public String getEvalcorpcode() {
		return this.evalcorpcode;
	}

	public void setEvalcorpcode(String evalcorpcode) {
		this.evalcorpcode = evalcorpcode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRE_DTTM", nullable = false, length = 7)
	public Date getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm) {
		this.creDttm = creDttm;
	}

	@Column(name = "CRE_EMP_NO", nullable = false, length = 6)
	public String getCreEmpNo() {
		return this.creEmpNo;
	}

	public void setCreEmpNo(String creEmpNo) {
		this.creEmpNo = creEmpNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHG_DTTM", nullable = false, length = 7)
	public Date getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(Date chgDttm) {
		this.chgDttm = chgDttm;
	}

	@Column(name = "CHG_EMP_NO", nullable = false, length = 6)
	public String getChgEmpNo() {
		return this.chgEmpNo;
	}

	public void setChgEmpNo(String chgEmpNo) {
		this.chgEmpNo = chgEmpNo;
	}

	@Column(name = "WORKFILENAME", length = 30)
	public String getWorkfilename() {
		return this.workfilename;
	}

	public void setWorkfilename(String workfilename) {
		this.workfilename = workfilename;
	}

}
