package com.eugenefe.ncm;
// Generated Dec 8, 2016 3:49:34 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

/**
 * NcmKfrBmIndexId generated by hbm2java
 */

public class NcmKfrBmIndexId implements java.io.Serializable, Navigatable {

	private String baseday;
	private String tradeday;
	private String bmcode;

	public NcmKfrBmIndexId() {
	}

	public String getBaseday() {
		return this.baseday;
	}

	public void setBaseday(String baseday) {
		this.baseday = baseday;

	}

	public String getTradeday() {
		return this.tradeday;
	}

	public void setTradeday(String tradeday) {
		this.tradeday = tradeday;

	}

	public String getBmcode() {
		return this.bmcode;
	}

	public void setBmcode(String bmcode) {
		this.bmcode = bmcode;

	}

	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseday());
		buffer.append("#").append(getTradeday());
		buffer.append("#").append(getBmcode());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmKfrBmIndexId))
			return false;
		NcmKfrBmIndexId castOther = (NcmKfrBmIndexId) other;

		return ((this.getBaseday() == castOther.getBaseday()) || (this.getBaseday() != null && castOther.getBaseday() != null && this.getBaseday().equals(castOther.getBaseday())))
				&& ((this.getTradeday() == castOther.getTradeday())
						|| (this.getTradeday() != null && castOther.getTradeday() != null && this.getTradeday().equals(castOther.getTradeday())))
				&& ((this.getBmcode() == castOther.getBmcode()) || (this.getBmcode() != null && castOther.getBmcode() != null && this.getBmcode().equals(castOther.getBmcode())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseday() == null ? 0 : this.getBaseday().hashCode());
		result = 37 * result + (getTradeday() == null ? 0 : this.getTradeday().hashCode());
		result = 37 * result + (getBmcode() == null ? 0 : this.getBmcode().hashCode());
		return result;
	}

}
