package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmKfrYieldCurve generated by hbm2java
 */
@Entity
@Table(name = "NCM_KFR_YIELD_CURVE", schema = "NCM")
public class NcmKfrYieldCurve implements java.io.Serializable {

	private NcmKfrYieldCurveId id;
	private String bondclassname;
	private BigDecimal m003;
	private BigDecimal m006;
	private BigDecimal m009;
	private BigDecimal m012;
	private BigDecimal m018;
	private BigDecimal m024;
	private BigDecimal m030;
	private BigDecimal m036;
	private BigDecimal m048;
	private BigDecimal m060;
	private BigDecimal m084;
	private BigDecimal m120;
	private BigDecimal m180;
	private String evalcorpcode;
	private String bondclassnameb;
	private String bondclassnamem;
	private String bondclassnames;
	private String workfilename;

	public NcmKfrYieldCurve() {
	}

	public NcmKfrYieldCurve(NcmKfrYieldCurveId id, BigDecimal m003, BigDecimal m006, BigDecimal m009, BigDecimal m012,
			BigDecimal m018, BigDecimal m024, BigDecimal m030, BigDecimal m036, BigDecimal m048, BigDecimal m060,
			BigDecimal m084, BigDecimal m120, BigDecimal m180, String evalcorpcode) {
		this.id = id;
		this.m003 = m003;
		this.m006 = m006;
		this.m009 = m009;
		this.m012 = m012;
		this.m018 = m018;
		this.m024 = m024;
		this.m030 = m030;
		this.m036 = m036;
		this.m048 = m048;
		this.m060 = m060;
		this.m084 = m084;
		this.m120 = m120;
		this.m180 = m180;
		this.evalcorpcode = evalcorpcode;
	}

	public NcmKfrYieldCurve(NcmKfrYieldCurveId id, String bondclassname, BigDecimal m003, BigDecimal m006,
			BigDecimal m009, BigDecimal m012, BigDecimal m018, BigDecimal m024, BigDecimal m030, BigDecimal m036,
			BigDecimal m048, BigDecimal m060, BigDecimal m084, BigDecimal m120, BigDecimal m180, String evalcorpcode,
			String bondclassnameb, String bondclassnamem, String bondclassnames, String workfilename) {
		this.id = id;
		this.bondclassname = bondclassname;
		this.m003 = m003;
		this.m006 = m006;
		this.m009 = m009;
		this.m012 = m012;
		this.m018 = m018;
		this.m024 = m024;
		this.m030 = m030;
		this.m036 = m036;
		this.m048 = m048;
		this.m060 = m060;
		this.m084 = m084;
		this.m120 = m120;
		this.m180 = m180;
		this.evalcorpcode = evalcorpcode;
		this.bondclassnameb = bondclassnameb;
		this.bondclassnamem = bondclassnamem;
		this.bondclassnames = bondclassnames;
		this.workfilename = workfilename;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tradeday", column = @Column(name = "TRADEDAY", nullable = false, length = 8)),
			@AttributeOverride(name = "bondclasscode", column = @Column(name = "BONDCLASSCODE", nullable = false, length = 6)) })
	public NcmKfrYieldCurveId getId() {
		return this.id;
	}

	public void setId(NcmKfrYieldCurveId id) {
		this.id = id;
	}

	@Column(name = "BONDCLASSNAME", length = 200)
	public String getBondclassname() {
		return this.bondclassname;
	}

	public void setBondclassname(String bondclassname) {
		this.bondclassname = bondclassname;
	}

	@Column(name = "M003", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM003() {
		return this.m003;
	}

	public void setM003(BigDecimal m003) {
		this.m003 = m003;
	}

	@Column(name = "M006", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM006() {
		return this.m006;
	}

	public void setM006(BigDecimal m006) {
		this.m006 = m006;
	}

	@Column(name = "M009", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM009() {
		return this.m009;
	}

	public void setM009(BigDecimal m009) {
		this.m009 = m009;
	}

	@Column(name = "M012", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM012() {
		return this.m012;
	}

	public void setM012(BigDecimal m012) {
		this.m012 = m012;
	}

	@Column(name = "M018", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM018() {
		return this.m018;
	}

	public void setM018(BigDecimal m018) {
		this.m018 = m018;
	}

	@Column(name = "M024", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM024() {
		return this.m024;
	}

	public void setM024(BigDecimal m024) {
		this.m024 = m024;
	}

	@Column(name = "M030", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM030() {
		return this.m030;
	}

	public void setM030(BigDecimal m030) {
		this.m030 = m030;
	}

	@Column(name = "M036", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM036() {
		return this.m036;
	}

	public void setM036(BigDecimal m036) {
		this.m036 = m036;
	}

	@Column(name = "M048", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM048() {
		return this.m048;
	}

	public void setM048(BigDecimal m048) {
		this.m048 = m048;
	}

	@Column(name = "M060", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM060() {
		return this.m060;
	}

	public void setM060(BigDecimal m060) {
		this.m060 = m060;
	}

	@Column(name = "M084", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM084() {
		return this.m084;
	}

	public void setM084(BigDecimal m084) {
		this.m084 = m084;
	}

	@Column(name = "M120", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM120() {
		return this.m120;
	}

	public void setM120(BigDecimal m120) {
		this.m120 = m120;
	}

	@Column(name = "M180", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM180() {
		return this.m180;
	}

	public void setM180(BigDecimal m180) {
		this.m180 = m180;
	}

	@Column(name = "EVALCORPCODE", nullable = false, length = 2)
	public String getEvalcorpcode() {
		return this.evalcorpcode;
	}

	public void setEvalcorpcode(String evalcorpcode) {
		this.evalcorpcode = evalcorpcode;
	}

	@Column(name = "BONDCLASSNAMEB", length = 50)
	public String getBondclassnameb() {
		return this.bondclassnameb;
	}

	public void setBondclassnameb(String bondclassnameb) {
		this.bondclassnameb = bondclassnameb;
	}

	@Column(name = "BONDCLASSNAMEM", length = 50)
	public String getBondclassnamem() {
		return this.bondclassnamem;
	}

	public void setBondclassnamem(String bondclassnamem) {
		this.bondclassnamem = bondclassnamem;
	}

	@Column(name = "BONDCLASSNAMES", length = 50)
	public String getBondclassnames() {
		return this.bondclassnames;
	}

	public void setBondclassnames(String bondclassnames) {
		this.bondclassnames = bondclassnames;
	}

	@Column(name = "WORKFILENAME", length = 30)
	public String getWorkfilename() {
		return this.workfilename;
	}

	public void setWorkfilename(String workfilename) {
		this.workfilename = workfilename;
	}

}
