package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmKfrHoldingYield generated by hbm2java
 */
@Entity
@Table(name = "NCM_KFR_HOLDING_YIELD", schema = "NCM")
public class NcmKfrHoldingYield implements java.io.Serializable {

	private NcmKfrHoldingYieldId id;
	private String itemname;
	private Long amtcurr;
	private Long evalamt;
	private Long retvaltot;
	private Long wtvaltot;
	private BigDecimal rettot;
	private String evalcorpcode;
	private Date creDttm;
	private String creEmpNo;
	private Date chgDttm;
	private String chgEmpNo;
	private String workfilename;

	public NcmKfrHoldingYield() {
	}

	public NcmKfrHoldingYield(NcmKfrHoldingYieldId id) {
		this.id = id;
	}

	public NcmKfrHoldingYield(NcmKfrHoldingYieldId id, String itemname, Long amtcurr, Long evalamt, Long retvaltot,
			Long wtvaltot, BigDecimal rettot, String evalcorpcode, Date creDttm, String creEmpNo, Date chgDttm,
			String chgEmpNo, String workfilename) {
		this.id = id;
		this.itemname = itemname;
		this.amtcurr = amtcurr;
		this.evalamt = evalamt;
		this.retvaltot = retvaltot;
		this.wtvaltot = wtvaltot;
		this.rettot = rettot;
		this.evalcorpcode = evalcorpcode;
		this.creDttm = creDttm;
		this.creEmpNo = creEmpNo;
		this.chgDttm = chgDttm;
		this.chgEmpNo = chgEmpNo;
		this.workfilename = workfilename;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tradeday", column = @Column(name = "TRADEDAY", nullable = false, length = 8)),
			@AttributeOverride(name = "mgrcode", column = @Column(name = "MGRCODE", nullable = false, length = 3)),
			@AttributeOverride(name = "fundmgrcode", column = @Column(name = "FUNDMGRCODE", nullable = false, length = 30)),
			@AttributeOverride(name = "assetbclasscode", column = @Column(name = "ASSETBCLASSCODE", nullable = false, length = 2)),
			@AttributeOverride(name = "assetsclasscode", column = @Column(name = "ASSETSCLASSCODE", nullable = false, length = 2)),
			@AttributeOverride(name = "itemcode", column = @Column(name = "ITEMCODE", nullable = false, length = 50)) })
	public NcmKfrHoldingYieldId getId() {
		return this.id;
	}

	public void setId(NcmKfrHoldingYieldId id) {
		this.id = id;
	}

	@Column(name = "ITEMNAME", length = 100)
	public String getItemname() {
		return this.itemname;
	}

	public void setItemname(String itemname) {
		this.itemname = itemname;
	}

	@Column(name = "AMTCURR", precision = 18, scale = 0)
	public Long getAmtcurr() {
		return this.amtcurr;
	}

	public void setAmtcurr(Long amtcurr) {
		this.amtcurr = amtcurr;
	}

	@Column(name = "EVALAMT", precision = 18, scale = 0)
	public Long getEvalamt() {
		return this.evalamt;
	}

	public void setEvalamt(Long evalamt) {
		this.evalamt = evalamt;
	}

	@Column(name = "RETVALTOT", precision = 18, scale = 0)
	public Long getRetvaltot() {
		return this.retvaltot;
	}

	public void setRetvaltot(Long retvaltot) {
		this.retvaltot = retvaltot;
	}

	@Column(name = "WTVALTOT", precision = 18, scale = 0)
	public Long getWtvaltot() {
		return this.wtvaltot;
	}

	public void setWtvaltot(Long wtvaltot) {
		this.wtvaltot = wtvaltot;
	}

	@Column(name = "RETTOT", precision = 20, scale = 12)
	public BigDecimal getRettot() {
		return this.rettot;
	}

	public void setRettot(BigDecimal rettot) {
		this.rettot = rettot;
	}

	@Column(name = "EVALCORPCODE", length = 4)
	public String getEvalcorpcode() {
		return this.evalcorpcode;
	}

	public void setEvalcorpcode(String evalcorpcode) {
		this.evalcorpcode = evalcorpcode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRE_DTTM", length = 7)
	public Date getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm) {
		this.creDttm = creDttm;
	}

	@Column(name = "CRE_EMP_NO", length = 6)
	public String getCreEmpNo() {
		return this.creEmpNo;
	}

	public void setCreEmpNo(String creEmpNo) {
		this.creEmpNo = creEmpNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHG_DTTM", length = 7)
	public Date getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(Date chgDttm) {
		this.chgDttm = chgDttm;
	}

	@Column(name = "CHG_EMP_NO", length = 6)
	public String getChgEmpNo() {
		return this.chgEmpNo;
	}

	public void setChgEmpNo(String chgEmpNo) {
		this.chgEmpNo = chgEmpNo;
	}

	@Column(name = "WORKFILENAME", length = 30)
	public String getWorkfilename() {
		return this.workfilename;
	}

	public void setWorkfilename(String workfilename) {
		this.workfilename = workfilename;
	}

}
