package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmKfrTransaction generated by hbm2java
 */
@Entity
@Table(name = "NCM_KFR_TRANSACTION", schema = "NCM")
public class NcmKfrTransaction implements java.io.Serializable {

	private NcmKfrTransactionId id;
	private String fundname;
	private String assetname;
	private String itemkname;
	private String buydate;
	private String buyseq;
	private BigDecimal qty;
	private BigDecimal tradeprc;
	private BigDecimal tradeprice;
	private BigDecimal cost;
	private BigDecimal tradepl;
	private BigDecimal tradefee;
	private BigDecimal traderet;
	private BigDecimal avgtraderet;
	private String settledate;
	private String issuedate;
	private String exprdate;
	private String tradeconame;
	private String evalcorpcode;
	private String workfilename;

	public NcmKfrTransaction() {
	}

	public NcmKfrTransaction(NcmKfrTransactionId id) {
		this.id = id;
	}

	public NcmKfrTransaction(NcmKfrTransactionId id, String fundname, String assetname, String itemkname,
			String buydate, String buyseq, BigDecimal qty, BigDecimal tradeprc, BigDecimal tradeprice, BigDecimal cost,
			BigDecimal tradepl, BigDecimal tradefee, BigDecimal traderet, BigDecimal avgtraderet, String settledate,
			String issuedate, String exprdate, String tradeconame, String evalcorpcode, String workfilename) {
		this.id = id;
		this.fundname = fundname;
		this.assetname = assetname;
		this.itemkname = itemkname;
		this.buydate = buydate;
		this.buyseq = buyseq;
		this.qty = qty;
		this.tradeprc = tradeprc;
		this.tradeprice = tradeprice;
		this.cost = cost;
		this.tradepl = tradepl;
		this.tradefee = tradefee;
		this.traderet = traderet;
		this.avgtraderet = avgtraderet;
		this.settledate = settledate;
		this.issuedate = issuedate;
		this.exprdate = exprdate;
		this.tradeconame = tradeconame;
		this.evalcorpcode = evalcorpcode;
		this.workfilename = workfilename;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tradeday", column = @Column(name = "TRADEDAY", nullable = false, length = 8)),
			@AttributeOverride(name = "mgrcode", column = @Column(name = "MGRCODE", nullable = false, length = 3)),
			@AttributeOverride(name = "fundmgrcode", column = @Column(name = "FUNDMGRCODE", nullable = false, length = 30)),
			@AttributeOverride(name = "assetbclass", column = @Column(name = "ASSETBCLASS", nullable = false, length = 2)),
			@AttributeOverride(name = "assetsclass", column = @Column(name = "ASSETSCLASS", nullable = false, length = 2)),
			@AttributeOverride(name = "itemcode", column = @Column(name = "ITEMCODE", nullable = false, length = 50)),
			@AttributeOverride(name = "seq", column = @Column(name = "SEQ", nullable = false, length = 2)),
			@AttributeOverride(name = "tradecode", column = @Column(name = "TRADECODE", nullable = false, length = 2)) })
	public NcmKfrTransactionId getId() {
		return this.id;
	}

	public void setId(NcmKfrTransactionId id) {
		this.id = id;
	}

	@Column(name = "FUNDNAME", length = 200)
	public String getFundname() {
		return this.fundname;
	}

	public void setFundname(String fundname) {
		this.fundname = fundname;
	}

	@Column(name = "ASSETNAME", length = 200)
	public String getAssetname() {
		return this.assetname;
	}

	public void setAssetname(String assetname) {
		this.assetname = assetname;
	}

	@Column(name = "ITEMKNAME", length = 50)
	public String getItemkname() {
		return this.itemkname;
	}

	public void setItemkname(String itemkname) {
		this.itemkname = itemkname;
	}

	@Column(name = "BUYDATE", length = 8)
	public String getBuydate() {
		return this.buydate;
	}

	public void setBuydate(String buydate) {
		this.buydate = buydate;
	}

	@Column(name = "BUYSEQ", length = 5)
	public String getBuyseq() {
		return this.buyseq;
	}

	public void setBuyseq(String buyseq) {
		this.buyseq = buyseq;
	}

	@Column(name = "QTY", precision = 20, scale = 0)
	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Column(name = "TRADEPRC", precision = 20)
	public BigDecimal getTradeprc() {
		return this.tradeprc;
	}

	public void setTradeprc(BigDecimal tradeprc) {
		this.tradeprc = tradeprc;
	}

	@Column(name = "TRADEPRICE", precision = 22, scale = 0)
	public BigDecimal getTradeprice() {
		return this.tradeprice;
	}

	public void setTradeprice(BigDecimal tradeprice) {
		this.tradeprice = tradeprice;
	}

	@Column(name = "COST", precision = 20, scale = 0)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Column(name = "TRADEPL", precision = 20, scale = 0)
	public BigDecimal getTradepl() {
		return this.tradepl;
	}

	public void setTradepl(BigDecimal tradepl) {
		this.tradepl = tradepl;
	}

	@Column(name = "TRADEFEE", precision = 20, scale = 0)
	public BigDecimal getTradefee() {
		return this.tradefee;
	}

	public void setTradefee(BigDecimal tradefee) {
		this.tradefee = tradefee;
	}

	@Column(name = "TRADERET", precision = 20, scale = 12)
	public BigDecimal getTraderet() {
		return this.traderet;
	}

	public void setTraderet(BigDecimal traderet) {
		this.traderet = traderet;
	}

	@Column(name = "AVGTRADERET", precision = 20, scale = 12)
	public BigDecimal getAvgtraderet() {
		return this.avgtraderet;
	}

	public void setAvgtraderet(BigDecimal avgtraderet) {
		this.avgtraderet = avgtraderet;
	}

	@Column(name = "SETTLEDATE", length = 8)
	public String getSettledate() {
		return this.settledate;
	}

	public void setSettledate(String settledate) {
		this.settledate = settledate;
	}

	@Column(name = "ISSUEDATE", length = 8)
	public String getIssuedate() {
		return this.issuedate;
	}

	public void setIssuedate(String issuedate) {
		this.issuedate = issuedate;
	}

	@Column(name = "EXPRDATE", length = 8)
	public String getExprdate() {
		return this.exprdate;
	}

	public void setExprdate(String exprdate) {
		this.exprdate = exprdate;
	}

	@Column(name = "TRADECONAME", length = 50)
	public String getTradeconame() {
		return this.tradeconame;
	}

	public void setTradeconame(String tradeconame) {
		this.tradeconame = tradeconame;
	}

	@Column(name = "EVALCORPCODE", length = 2)
	public String getEvalcorpcode() {
		return this.evalcorpcode;
	}

	public void setEvalcorpcode(String evalcorpcode) {
		this.evalcorpcode = evalcorpcode;
	}

	@Column(name = "WORKFILENAME", length = 30)
	public String getWorkfilename() {
		return this.workfilename;
	}

	public void setWorkfilename(String workfilename) {
		this.workfilename = workfilename;
	}

}
