package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NcmKfrHoldingDetailId generated by hbm2java
 */
@Embeddable
public class NcmKfrHoldingDetailId implements java.io.Serializable {

	private String tradeday;
	private String mgrcode;
	private String fundmgrcode;
	private String itemcode;
	private int dataseq;

	public NcmKfrHoldingDetailId() {
	}

	public NcmKfrHoldingDetailId(String tradeday, String mgrcode, String fundmgrcode, String itemcode, int dataseq) {
		this.tradeday = tradeday;
		this.mgrcode = mgrcode;
		this.fundmgrcode = fundmgrcode;
		this.itemcode = itemcode;
		this.dataseq = dataseq;
	}

	@Column(name = "TRADEDAY", nullable = false, length = 8)
	public String getTradeday() {
		return this.tradeday;
	}

	public void setTradeday(String tradeday) {
		this.tradeday = tradeday;
	}

	@Column(name = "MGRCODE", nullable = false, length = 3)
	public String getMgrcode() {
		return this.mgrcode;
	}

	public void setMgrcode(String mgrcode) {
		this.mgrcode = mgrcode;
	}

	@Column(name = "FUNDMGRCODE", nullable = false, length = 30)
	public String getFundmgrcode() {
		return this.fundmgrcode;
	}

	public void setFundmgrcode(String fundmgrcode) {
		this.fundmgrcode = fundmgrcode;
	}

	@Column(name = "ITEMCODE", nullable = false, length = 50)
	public String getItemcode() {
		return this.itemcode;
	}

	public void setItemcode(String itemcode) {
		this.itemcode = itemcode;
	}

	@Column(name = "DATASEQ", nullable = false, precision = 5, scale = 0)
	public int getDataseq() {
		return this.dataseq;
	}

	public void setDataseq(int dataseq) {
		this.dataseq = dataseq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmKfrHoldingDetailId))
			return false;
		NcmKfrHoldingDetailId castOther = (NcmKfrHoldingDetailId) other;

		return ((this.getTradeday() == castOther.getTradeday()) || (this.getTradeday() != null
				&& castOther.getTradeday() != null && this.getTradeday().equals(castOther.getTradeday())))
				&& ((this.getMgrcode() == castOther.getMgrcode()) || (this.getMgrcode() != null
						&& castOther.getMgrcode() != null && this.getMgrcode().equals(castOther.getMgrcode())))
				&& ((this.getFundmgrcode() == castOther.getFundmgrcode())
						|| (this.getFundmgrcode() != null && castOther.getFundmgrcode() != null
								&& this.getFundmgrcode().equals(castOther.getFundmgrcode())))
				&& ((this.getItemcode() == castOther.getItemcode()) || (this.getItemcode() != null
						&& castOther.getItemcode() != null && this.getItemcode().equals(castOther.getItemcode())))
				&& (this.getDataseq() == castOther.getDataseq());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTradeday() == null ? 0 : this.getTradeday().hashCode());
		result = 37 * result + (getMgrcode() == null ? 0 : this.getMgrcode().hashCode());
		result = 37 * result + (getFundmgrcode() == null ? 0 : this.getFundmgrcode().hashCode());
		result = 37 * result + (getItemcode() == null ? 0 : this.getItemcode().hashCode());
		result = 37 * result + this.getDataseq();
		return result;
	}

}
