package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmKfrFundYield generated by hbm2java
 */
@Entity
@Table(name = "NCM_KFR_FUND_YIELD", schema = "NCM")
public class NcmKfrFundYield implements java.io.Serializable {

	private NcmKfrFundYieldId id;
	private BigDecimal fundret1d;
	private BigDecimal fundretidx;
	private BigDecimal fundret1m;
	private BigDecimal fundret3m;
	private BigDecimal fundret6m;
	private BigDecimal fundret1y;
	private BigDecimal fundretytd;
	private String evalcorpcode;
	private Date creDttm;
	private String creEmpNo;
	private Date chgDttm;
	private String chgEmpNo;
	private String workfilename;

	public NcmKfrFundYield() {
	}

	public NcmKfrFundYield(NcmKfrFundYieldId id, BigDecimal fundret1d, BigDecimal fundretidx, BigDecimal fundret1m,
			BigDecimal fundret3m, BigDecimal fundret6m, BigDecimal fundret1y, BigDecimal fundretytd,
			String evalcorpcode, Date creDttm, String creEmpNo, Date chgDttm, String chgEmpNo) {
		this.id = id;
		this.fundret1d = fundret1d;
		this.fundretidx = fundretidx;
		this.fundret1m = fundret1m;
		this.fundret3m = fundret3m;
		this.fundret6m = fundret6m;
		this.fundret1y = fundret1y;
		this.fundretytd = fundretytd;
		this.evalcorpcode = evalcorpcode;
		this.creDttm = creDttm;
		this.creEmpNo = creEmpNo;
		this.chgDttm = chgDttm;
		this.chgEmpNo = chgEmpNo;
	}

	public NcmKfrFundYield(NcmKfrFundYieldId id, BigDecimal fundret1d, BigDecimal fundretidx, BigDecimal fundret1m,
			BigDecimal fundret3m, BigDecimal fundret6m, BigDecimal fundret1y, BigDecimal fundretytd,
			String evalcorpcode, Date creDttm, String creEmpNo, Date chgDttm, String chgEmpNo, String workfilename) {
		this.id = id;
		this.fundret1d = fundret1d;
		this.fundretidx = fundretidx;
		this.fundret1m = fundret1m;
		this.fundret3m = fundret3m;
		this.fundret6m = fundret6m;
		this.fundret1y = fundret1y;
		this.fundretytd = fundretytd;
		this.evalcorpcode = evalcorpcode;
		this.creDttm = creDttm;
		this.creEmpNo = creEmpNo;
		this.chgDttm = chgDttm;
		this.chgEmpNo = chgEmpNo;
		this.workfilename = workfilename;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tradeday", column = @Column(name = "TRADEDAY", nullable = false, length = 8)),
			@AttributeOverride(name = "mgrcode", column = @Column(name = "MGRCODE", nullable = false, length = 3)),
			@AttributeOverride(name = "fundmgrcode", column = @Column(name = "FUNDMGRCODE", nullable = false, length = 30)) })
	public NcmKfrFundYieldId getId() {
		return this.id;
	}

	public void setId(NcmKfrFundYieldId id) {
		this.id = id;
	}

	@Column(name = "FUNDRET1D", nullable = false, precision = 20, scale = 12)
	public BigDecimal getFundret1d() {
		return this.fundret1d;
	}

	public void setFundret1d(BigDecimal fundret1d) {
		this.fundret1d = fundret1d;
	}

	@Column(name = "FUNDRETIDX", nullable = false, precision = 20, scale = 12)
	public BigDecimal getFundretidx() {
		return this.fundretidx;
	}

	public void setFundretidx(BigDecimal fundretidx) {
		this.fundretidx = fundretidx;
	}

	@Column(name = "FUNDRET1M", nullable = false, precision = 20, scale = 12)
	public BigDecimal getFundret1m() {
		return this.fundret1m;
	}

	public void setFundret1m(BigDecimal fundret1m) {
		this.fundret1m = fundret1m;
	}

	@Column(name = "FUNDRET3M", nullable = false, precision = 20, scale = 12)
	public BigDecimal getFundret3m() {
		return this.fundret3m;
	}

	public void setFundret3m(BigDecimal fundret3m) {
		this.fundret3m = fundret3m;
	}

	@Column(name = "FUNDRET6M", nullable = false, precision = 20, scale = 12)
	public BigDecimal getFundret6m() {
		return this.fundret6m;
	}

	public void setFundret6m(BigDecimal fundret6m) {
		this.fundret6m = fundret6m;
	}

	@Column(name = "FUNDRET1Y", nullable = false, precision = 20, scale = 12)
	public BigDecimal getFundret1y() {
		return this.fundret1y;
	}

	public void setFundret1y(BigDecimal fundret1y) {
		this.fundret1y = fundret1y;
	}

	@Column(name = "FUNDRETYTD", nullable = false, precision = 20, scale = 12)
	public BigDecimal getFundretytd() {
		return this.fundretytd;
	}

	public void setFundretytd(BigDecimal fundretytd) {
		this.fundretytd = fundretytd;
	}

	@Column(name = "EVALCORPCODE", nullable = false, length = 4)
	public String getEvalcorpcode() {
		return this.evalcorpcode;
	}

	public void setEvalcorpcode(String evalcorpcode) {
		this.evalcorpcode = evalcorpcode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRE_DTTM", nullable = false, length = 7)
	public Date getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm) {
		this.creDttm = creDttm;
	}

	@Column(name = "CRE_EMP_NO", nullable = false, length = 6)
	public String getCreEmpNo() {
		return this.creEmpNo;
	}

	public void setCreEmpNo(String creEmpNo) {
		this.creEmpNo = creEmpNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHG_DTTM", nullable = false, length = 7)
	public Date getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(Date chgDttm) {
		this.chgDttm = chgDttm;
	}

	@Column(name = "CHG_EMP_NO", nullable = false, length = 6)
	public String getChgEmpNo() {
		return this.chgEmpNo;
	}

	public void setChgEmpNo(String chgEmpNo) {
		this.chgEmpNo = chgEmpNo;
	}

	@Column(name = "WORKFILENAME", length = 30)
	public String getWorkfilename() {
		return this.workfilename;
	}

	public void setWorkfilename(String workfilename) {
		this.workfilename = workfilename;
	}

}
