package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * NcmKfrYieldCurve generated by hbm2java
 */

@Entity
@IdClass(value = NcmKfrYieldCurveId.class)
@Table(name = "NCM_KFR_YIELD_CURVE", schema = "NCM")
public class NcmKfrYieldCurve implements java.io.Serializable {

	private String tradeday;
	private String bondclasscode;
	private String bondclassname;
	private BigDecimal m003;
	private BigDecimal m006;
	private BigDecimal m009;
	private BigDecimal m012;
	private BigDecimal m018;
	private BigDecimal m024;
	private BigDecimal m030;
	private BigDecimal m036;
	private BigDecimal m048;
	private BigDecimal m060;
	private BigDecimal m084;
	private BigDecimal m120;
	private BigDecimal m180;
	private String evalcorpcode;
	private String bondclassnameb;
	private String bondclassnamem;
	private String bondclassnames;
	private String workfilename;

	public NcmKfrYieldCurve() {
	}

	@Id
	@Column(name = "TRADEDAY", nullable = false, length = 8)
	public String getTradeday() {
		return this.tradeday;
	}

	public void setTradeday(String tradeday) {
		this.tradeday = tradeday;
	}

	@Id
	@Column(name = "BONDCLASSCODE", nullable = false, length = 6)
	public String getBondclasscode() {
		return this.bondclasscode;
	}

	public void setBondclasscode(String bondclasscode) {
		this.bondclasscode = bondclasscode;
	}

	@Column(name = "BONDCLASSNAME", length = 200)
	public String getBondclassname() {
		return this.bondclassname;
	}

	public void setBondclassname(String bondclassname) {
		this.bondclassname = bondclassname;

	}

	@Column(name = "M003", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM003() {
		return this.m003;
	}

	public void setM003(BigDecimal m003) {
		this.m003 = m003;

	}

	@Column(name = "M006", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM006() {
		return this.m006;
	}

	public void setM006(BigDecimal m006) {
		this.m006 = m006;

	}

	@Column(name = "M009", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM009() {
		return this.m009;
	}

	public void setM009(BigDecimal m009) {
		this.m009 = m009;

	}

	@Column(name = "M012", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM012() {
		return this.m012;
	}

	public void setM012(BigDecimal m012) {
		this.m012 = m012;

	}

	@Column(name = "M018", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM018() {
		return this.m018;
	}

	public void setM018(BigDecimal m018) {
		this.m018 = m018;

	}

	@Column(name = "M024", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM024() {
		return this.m024;
	}

	public void setM024(BigDecimal m024) {
		this.m024 = m024;

	}

	@Column(name = "M030", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM030() {
		return this.m030;
	}

	public void setM030(BigDecimal m030) {
		this.m030 = m030;

	}

	@Column(name = "M036", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM036() {
		return this.m036;
	}

	public void setM036(BigDecimal m036) {
		this.m036 = m036;

	}

	@Column(name = "M048", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM048() {
		return this.m048;
	}

	public void setM048(BigDecimal m048) {
		this.m048 = m048;

	}

	@Column(name = "M060", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM060() {
		return this.m060;
	}

	public void setM060(BigDecimal m060) {
		this.m060 = m060;

	}

	@Column(name = "M084", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM084() {
		return this.m084;
	}

	public void setM084(BigDecimal m084) {
		this.m084 = m084;

	}

	@Column(name = "M120", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM120() {
		return this.m120;
	}

	public void setM120(BigDecimal m120) {
		this.m120 = m120;

	}

	@Column(name = "M180", nullable = false, precision = 20, scale = 12)
	public BigDecimal getM180() {
		return this.m180;
	}

	public void setM180(BigDecimal m180) {
		this.m180 = m180;

	}

	@Column(name = "EVALCORPCODE", nullable = false, length = 2)
	public String getEvalcorpcode() {
		return this.evalcorpcode;
	}

	public void setEvalcorpcode(String evalcorpcode) {
		this.evalcorpcode = evalcorpcode;

	}

	@Column(name = "BONDCLASSNAMEB", length = 50)
	public String getBondclassnameb() {
		return this.bondclassnameb;
	}

	public void setBondclassnameb(String bondclassnameb) {
		this.bondclassnameb = bondclassnameb;

	}

	@Column(name = "BONDCLASSNAMEM", length = 50)
	public String getBondclassnamem() {
		return this.bondclassnamem;
	}

	public void setBondclassnamem(String bondclassnamem) {
		this.bondclassnamem = bondclassnamem;

	}

	@Column(name = "BONDCLASSNAMES", length = 50)
	public String getBondclassnames() {
		return this.bondclassnames;
	}

	public void setBondclassnames(String bondclassnames) {
		this.bondclassnames = bondclassnames;

	}

	@Column(name = "WORKFILENAME", length = 30)
	public String getWorkfilename() {
		return this.workfilename;
	}

	public void setWorkfilename(String workfilename) {
		this.workfilename = workfilename;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getTradeday());
		buffer.append("#").append(getBondclasscode());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmKfrYieldCurve))
			return false;
		NcmKfrYieldCurve castOther = (NcmKfrYieldCurve) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTradeday() == null ? 0 : this.getTradeday().hashCode());
		result = 37 * result + (getBondclasscode() == null ? 0 : this.getBondclasscode().hashCode());
		return result;
	}

}
