package com.eugenefe.ncm;
// Generated Dec 8, 2016 3:49:34 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.util.Date;

/**
 * NcmLv1MmtDetailBackId generated by hbm2java
 */

public class NcmLv1MmtDetailBackId implements java.io.Serializable, Navigatable {

	private String mmtProdId;
	private String mmtChgProdId;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv1MmtDetailBackId() {
	}

	public String getMmtProdId() {
		return this.mmtProdId;
	}

	public void setMmtProdId(String mmtProdId) {
		this.mmtProdId = mmtProdId;

	}

	public String getMmtChgProdId() {
		return this.mmtChgProdId;
	}

	public void setMmtChgProdId(String mmtChgProdId) {
		this.mmtChgProdId = mmtChgProdId;

	}

	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getMmtProdId());
		buffer.append("#").append(getMmtChgProdId());
		buffer.append("#").append(getSrcTable());
		buffer.append("#").append(getUpdateId());
		buffer.append("#").append(getLastUpdate());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmLv1MmtDetailBackId))
			return false;
		NcmLv1MmtDetailBackId castOther = (NcmLv1MmtDetailBackId) other;

		return ((this.getMmtProdId() == castOther.getMmtProdId())
				|| (this.getMmtProdId() != null && castOther.getMmtProdId() != null && this.getMmtProdId().equals(castOther.getMmtProdId())))
				&& ((this.getMmtChgProdId() == castOther.getMmtChgProdId())
						|| (this.getMmtChgProdId() != null && castOther.getMmtChgProdId() != null && this.getMmtChgProdId().equals(castOther.getMmtChgProdId())))
				&& ((this.getSrcTable() == castOther.getSrcTable())
						|| (this.getSrcTable() != null && castOther.getSrcTable() != null && this.getSrcTable().equals(castOther.getSrcTable())))
				&& ((this.getUpdateId() == castOther.getUpdateId())
						|| (this.getUpdateId() != null && castOther.getUpdateId() != null && this.getUpdateId().equals(castOther.getUpdateId())))
				&& ((this.getLastUpdate() == castOther.getLastUpdate())
						|| (this.getLastUpdate() != null && castOther.getLastUpdate() != null && this.getLastUpdate().equals(castOther.getLastUpdate())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMmtProdId() == null ? 0 : this.getMmtProdId().hashCode());
		result = 37 * result + (getMmtChgProdId() == null ? 0 : this.getMmtChgProdId().hashCode());
		result = 37 * result + (getSrcTable() == null ? 0 : this.getSrcTable().hashCode());
		result = 37 * result + (getUpdateId() == null ? 0 : this.getUpdateId().hashCode());
		result = 37 * result + (getLastUpdate() == null ? 0 : this.getLastUpdate().hashCode());
		return result;
	}

}
