package com.eugenefe.ncm;
// Generated Dec 8, 2016 3:49:34 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

/**
 * NcmLv1MmfDetailId generated by hbm2java
 */

public class NcmLv1MmfDetailId implements java.io.Serializable, Navigatable {

	private String baseDate;
	private String finProdId;
	private String hldProdId;

	public NcmLv1MmfDetailId() {
	}

	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;

	}

	public String getFinProdId() {
		return this.finProdId;
	}

	public void setFinProdId(String finProdId) {
		this.finProdId = finProdId;

	}

	public String getHldProdId() {
		return this.hldProdId;
	}

	public void setHldProdId(String hldProdId) {
		this.hldProdId = hldProdId;

	}

	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getFinProdId());
		buffer.append("#").append(getHldProdId());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmLv1MmfDetailId))
			return false;
		NcmLv1MmfDetailId castOther = (NcmLv1MmfDetailId) other;

		return ((this.getBaseDate() == castOther.getBaseDate())
				|| (this.getBaseDate() != null && castOther.getBaseDate() != null && this.getBaseDate().equals(castOther.getBaseDate())))
				&& ((this.getFinProdId() == castOther.getFinProdId())
						|| (this.getFinProdId() != null && castOther.getFinProdId() != null && this.getFinProdId().equals(castOther.getFinProdId())))
				&& ((this.getHldProdId() == castOther.getHldProdId())
						|| (this.getHldProdId() != null && castOther.getHldProdId() != null && this.getHldProdId().equals(castOther.getHldProdId())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getFinProdId() == null ? 0 : this.getFinProdId().hashCode());
		result = 37 * result + (getHldProdId() == null ? 0 : this.getHldProdId().hashCode());
		return result;
	}

}
