package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv2PortRisk generated by hbm2java
 */

@Entity
@IdClass(value = NcmLv2PortRiskId.class)
@Table(name = "NCM_LV2_PORT_RISK", schema = "NCM")
public class NcmLv2PortRisk implements java.io.Serializable {

	private String baseDate;
	private String cptlDivCd;
	private String yieldLclssCd;
	private String yieldDivCd;
	private String timeHorizonCd;
	private String confiLevelCd;
	private BigDecimal avgYield;
	private BigDecimal stdev;
	private BigDecimal eta;
	private BigDecimal var;
	private BigDecimal te;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv2PortRisk() {
	}

	@Id
	@Column(name = "BASE_DATE", nullable = false, length = 8)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Id
	@Column(name = "CPTL_DIV_CD", nullable = false, length = 10)
	public String getCptlDivCd() {
		return this.cptlDivCd;
	}

	public void setCptlDivCd(String cptlDivCd) {
		this.cptlDivCd = cptlDivCd;
	}

	@Id
	@Column(name = "YIELD_LCLSS_CD", nullable = false, length = 10)
	public String getYieldLclssCd() {
		return this.yieldLclssCd;
	}

	public void setYieldLclssCd(String yieldLclssCd) {
		this.yieldLclssCd = yieldLclssCd;
	}

	@Id
	@Column(name = "YIELD_DIV_CD", nullable = false, length = 20)
	public String getYieldDivCd() {
		return this.yieldDivCd;
	}

	public void setYieldDivCd(String yieldDivCd) {
		this.yieldDivCd = yieldDivCd;
	}

	@Id
	@Column(name = "TIME_HORIZON_CD", nullable = false, length = 10)
	public String getTimeHorizonCd() {
		return this.timeHorizonCd;
	}

	public void setTimeHorizonCd(String timeHorizonCd) {
		this.timeHorizonCd = timeHorizonCd;
	}

	@Id
	@Column(name = "CONFI_LEVEL_CD", nullable = false, length = 10)
	public String getConfiLevelCd() {
		return this.confiLevelCd;
	}

	public void setConfiLevelCd(String confiLevelCd) {
		this.confiLevelCd = confiLevelCd;
	}

	@Column(name = "AVG_YIELD", precision = 20, scale = 8)
	public BigDecimal getAvgYield() {
		return this.avgYield;
	}

	public void setAvgYield(BigDecimal avgYield) {
		this.avgYield = avgYield;

	}

	@Column(name = "STDEV", precision = 20, scale = 8)
	public BigDecimal getStdev() {
		return this.stdev;
	}

	public void setStdev(BigDecimal stdev) {
		this.stdev = stdev;

	}

	@Column(name = "ETA", precision = 20, scale = 8)
	public BigDecimal getEta() {
		return this.eta;
	}

	public void setEta(BigDecimal eta) {
		this.eta = eta;

	}

	@Column(name = "VAR", precision = 20, scale = 8)
	public BigDecimal getVar() {
		return this.var;
	}

	public void setVar(BigDecimal var) {
		this.var = var;

	}

	@Column(name = "TE", precision = 20, scale = 8)
	public BigDecimal getTe() {
		return this.te;
	}

	public void setTe(BigDecimal te) {
		this.te = te;

	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getCptlDivCd());
		buffer.append("#").append(getYieldLclssCd());
		buffer.append("#").append(getYieldDivCd());
		buffer.append("#").append(getTimeHorizonCd());
		buffer.append("#").append(getConfiLevelCd());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmLv2PortRisk))
			return false;
		NcmLv2PortRisk castOther = (NcmLv2PortRisk) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getCptlDivCd() == null ? 0 : this.getCptlDivCd().hashCode());
		result = 37 * result + (getYieldLclssCd() == null ? 0 : this.getYieldLclssCd().hashCode());
		result = 37 * result + (getYieldDivCd() == null ? 0 : this.getYieldDivCd().hashCode());
		result = 37 * result + (getTimeHorizonCd() == null ? 0 : this.getTimeHorizonCd().hashCode());
		result = 37 * result + (getConfiLevelCd() == null ? 0 : this.getConfiLevelCd().hashCode());
		return result;
	}

}
