package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NcmLv1TxSaaId generated by hbm2java
 */
@Embeddable
public class NcmLv1TxSaaId implements java.io.Serializable {

	private String baseDate;
	private String finTxNo;
	private String applyStDate;

	public NcmLv1TxSaaId() {
	}

	public NcmLv1TxSaaId(String baseDate, String finTxNo, String applyStDate) {
		this.baseDate = baseDate;
		this.finTxNo = finTxNo;
		this.applyStDate = applyStDate;
	}

	@Column(name = "BASE_DATE", nullable = false, length = 8)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Column(name = "FIN_TX_NO", nullable = false, length = 20)
	public String getFinTxNo() {
		return this.finTxNo;
	}

	public void setFinTxNo(String finTxNo) {
		this.finTxNo = finTxNo;
	}

	@Column(name = "APPLY_ST_DATE", nullable = false, length = 8)
	public String getApplyStDate() {
		return this.applyStDate;
	}

	public void setApplyStDate(String applyStDate) {
		this.applyStDate = applyStDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmLv1TxSaaId))
			return false;
		NcmLv1TxSaaId castOther = (NcmLv1TxSaaId) other;

		return ((this.getBaseDate() == castOther.getBaseDate()) || (this.getBaseDate() != null
				&& castOther.getBaseDate() != null && this.getBaseDate().equals(castOther.getBaseDate())))
				&& ((this.getFinTxNo() == castOther.getFinTxNo()) || (this.getFinTxNo() != null
						&& castOther.getFinTxNo() != null && this.getFinTxNo().equals(castOther.getFinTxNo())))
				&& ((this.getApplyStDate() == castOther.getApplyStDate())
						|| (this.getApplyStDate() != null && castOther.getApplyStDate() != null
								&& this.getApplyStDate().equals(castOther.getApplyStDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getFinTxNo() == null ? 0 : this.getFinTxNo().hashCode());
		result = 37 * result + (getApplyStDate() == null ? 0 : this.getApplyStDate().hashCode());
		return result;
	}

}
