package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmLv2PortAmt20161018 generated by hbm2java
 */
@Entity
@Table(name = "NCM_LV2_PORT_AMT_20161018", schema = "NCM")
public class NcmLv2PortAmt20161018 implements java.io.Serializable {

	private NcmLv2PortAmt20161018Id id;

	public NcmLv2PortAmt20161018() {
	}

	public NcmLv2PortAmt20161018(NcmLv2PortAmt20161018Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "cptlDivCd", column = @Column(name = "CPTL_DIV_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "yieldLclssCd", column = @Column(name = "YIELD_LCLSS_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "yieldDivCd", column = @Column(name = "YIELD_DIV_CD", nullable = false, length = 20)),
			@AttributeOverride(name = "prodTypeCd", column = @Column(name = "PROD_TYPE_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "hldAmt", column = @Column(name = "HLD_AMT", precision = 22, scale = 0)),
			@AttributeOverride(name = "bookAmt", column = @Column(name = "BOOK_AMT", precision = 22, scale = 0)),
			@AttributeOverride(name = "mktEvalAmt", column = @Column(name = "MKT_EVAL_AMT", precision = 22, scale = 0)),
			@AttributeOverride(name = "bdayEvalAmt", column = @Column(name = "BDAY_EVAL_AMT", precision = 22, scale = 0)),
			@AttributeOverride(name = "intInflowAmt", column = @Column(name = "INT_INFLOW_AMT", precision = 22, scale = 0)),
			@AttributeOverride(name = "accumRealPl", column = @Column(name = "ACCUM_REAL_PL", precision = 22, scale = 0)),
			@AttributeOverride(name = "evalPl", column = @Column(name = "EVAL_PL", precision = 22, scale = 0)),
			@AttributeOverride(name = "evalPlInc", column = @Column(name = "EVAL_PL_INC", precision = 22, scale = 0)),
			@AttributeOverride(name = "todayBuyAmt", column = @Column(name = "TODAY_BUY_AMT", precision = 22, scale = 0)),
			@AttributeOverride(name = "todaySellAmt", column = @Column(name = "TODAY_SELL_AMT", precision = 22, scale = 0)),
			@AttributeOverride(name = "dbaseEvalAmt", column = @Column(name = "DBASE_EVAL_AMT", precision = 22, scale = 0)),
			@AttributeOverride(name = "nbaseEvalAmt", column = @Column(name = "NBASE_EVAL_AMT", precision = 22, scale = 0)),
			@AttributeOverride(name = "hldAmtWght", column = @Column(name = "HLD_AMT_WGHT", precision = 12, scale = 8)),
			@AttributeOverride(name = "mktEvalWght", column = @Column(name = "MKT_EVAL_WGHT", precision = 12, scale = 8)),
			@AttributeOverride(name = "todayTwghtYield", column = @Column(name = "TODAY_TWGHT_YIELD", precision = 12, scale = 8)),
			@AttributeOverride(name = "accumTwghtYield", column = @Column(name = "ACCUM_TWGHT_YIELD", precision = 12, scale = 8)),
			@AttributeOverride(name = "accumEvalAmt", column = @Column(name = "ACCUM_EVAL_AMT", precision = 22, scale = 0)),
			@AttributeOverride(name = "accumHldWght", column = @Column(name = "ACCUM_HLD_WGHT", precision = 12, scale = 8)),
			@AttributeOverride(name = "accumEvalWght", column = @Column(name = "ACCUM_EVAL_WGHT", precision = 12, scale = 8)),
			@AttributeOverride(name = "hldCnt", column = @Column(name = "HLD_CNT", precision = 22, scale = 0)),
			@AttributeOverride(name = "srcTable", column = @Column(name = "SRC_TABLE", length = 20)),
			@AttributeOverride(name = "updateId", column = @Column(name = "UPDATE_ID", length = 20)),
			@AttributeOverride(name = "lastUpdate", column = @Column(name = "LAST_UPDATE", length = 7)) })
	public NcmLv2PortAmt20161018Id getId() {
		return this.id;
	}

	public void setId(NcmLv2PortAmt20161018Id id) {
		this.id = id;
	}

}
