package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv1TxSaa generated by hbm2java
 */
@Entity
@Table(name = "NCM_LV1_TX_SAA", schema = "NCM")
public class NcmLv1TxSaa implements java.io.Serializable {

	private NcmLv1TxSaaId id;
	private String saaCd;
	private String applyEndDate;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv1TxSaa() {
	}

	public NcmLv1TxSaa(NcmLv1TxSaaId id) {
		this.id = id;
	}

	public NcmLv1TxSaa(NcmLv1TxSaaId id, String saaCd, String applyEndDate, String srcTable, String updateId,
			Date lastUpdate) {
		this.id = id;
		this.saaCd = saaCd;
		this.applyEndDate = applyEndDate;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "finTxNo", column = @Column(name = "FIN_TX_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "applyStDate", column = @Column(name = "APPLY_ST_DATE", nullable = false, length = 8)) })
	public NcmLv1TxSaaId getId() {
		return this.id;
	}

	public void setId(NcmLv1TxSaaId id) {
		this.id = id;
	}

	@Column(name = "SAA_CD", length = 10)
	public String getSaaCd() {
		return this.saaCd;
	}

	public void setSaaCd(String saaCd) {
		this.saaCd = saaCd;
	}

	@Column(name = "APPLY_END_DATE", length = 8)
	public String getApplyEndDate() {
		return this.applyEndDate;
	}

	public void setApplyEndDate(String applyEndDate) {
		this.applyEndDate = applyEndDate;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
