package com.eugenefe.ncm;
// Generated Dec 8, 2016 3:49:34 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv1RpColl generated by hbm2java
 */

@Entity
@Table(name = "NCM_LV1_RP_COLL", schema = "NCM")
public class NcmLv1RpColl implements java.io.Serializable, Navigatable {

	private String rpProdId;
	private String rpCollProdId;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv1RpColl() {
	}

	@Id
	@Column(name = "RP_PROD_ID", unique = true, nullable = false, length = 20)
	public String getRpProdId() {
		return this.rpProdId;
	}

	public void setRpProdId(String rpProdId) {
		this.rpProdId = rpProdId;

	}

	@Column(name = "RP_COLL_PROD_ID", length = 20)
	public String getRpCollProdId() {
		return this.rpCollProdId;
	}

	public void setRpCollProdId(String rpCollProdId) {
		this.rpCollProdId = rpCollProdId;

	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getRpProdId());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmLv1RpColl))
			return false;
		NcmLv1RpColl castOther = (NcmLv1RpColl) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (idString() == null ? 0 : this.idString().hashCode());
		return result;
	}

}
