package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv1CreditGrade generated by hbm2java
 */
@Entity
@Table(name = "NCM_LV1_CREDIT_GRADE", schema = "NCM")
public class NcmLv1CreditGrade implements java.io.Serializable {

	private NcmLv1CreditGradeId id;
	private String corpNm;
	private String creditCd;
	private String creditOrgCd;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv1CreditGrade() {
	}

	public NcmLv1CreditGrade(NcmLv1CreditGradeId id) {
		this.id = id;
	}

	public NcmLv1CreditGrade(NcmLv1CreditGradeId id, String corpNm, String creditCd, String creditOrgCd,
			String srcTable, String updateId, Date lastUpdate) {
		this.id = id;
		this.corpNm = corpNm;
		this.creditCd = creditCd;
		this.creditOrgCd = creditOrgCd;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "corpNo", column = @Column(name = "CORP_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "creditTypeCd", column = @Column(name = "CREDIT_TYPE_CD", nullable = false, length = 10)) })
	public NcmLv1CreditGradeId getId() {
		return this.id;
	}

	public void setId(NcmLv1CreditGradeId id) {
		this.id = id;
	}

	@Column(name = "CORP_NM", length = 100)
	public String getCorpNm() {
		return this.corpNm;
	}

	public void setCorpNm(String corpNm) {
		this.corpNm = corpNm;
	}

	@Column(name = "CREDIT_CD", length = 10)
	public String getCreditCd() {
		return this.creditCd;
	}

	public void setCreditCd(String creditCd) {
		this.creditCd = creditCd;
	}

	@Column(name = "CREDIT_ORG_CD", length = 10)
	public String getCreditOrgCd() {
		return this.creditOrgCd;
	}

	public void setCreditOrgCd(String creditOrgCd) {
		this.creditOrgCd = creditOrgCd;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
