package com.eugenefe.ncm;
// Generated Dec 8, 2016 3:49:34 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * NcmLv1CreditGradeSub generated by hbm2java
 */

@Entity
@IdClass(value = NcmLv1CreditGradeSubId.class)
@Table(name = "NCM_LV1_CREDIT_GRADE_SUB", schema = "NCM")
public class NcmLv1CreditGradeSub implements java.io.Serializable, Navigatable {

	private String corpNo;
	private String creditTypeCd;
	private String corpNm;
	private String creditCd;

	public NcmLv1CreditGradeSub() {
	}

	@Id
	@Column(name = "CORP_NO", nullable = false, length = 20)
	public String getCorpNo() {
		return this.corpNo;
	}

	public void setCorpNo(String corpNo) {
		this.corpNo = corpNo;
	}

	@Id
	@Column(name = "CREDIT_TYPE_CD", nullable = false, length = 10)
	public String getCreditTypeCd() {
		return this.creditTypeCd;
	}

	public void setCreditTypeCd(String creditTypeCd) {
		this.creditTypeCd = creditTypeCd;
	}

	@Column(name = "CORP_NM", length = 100)
	public String getCorpNm() {
		return this.corpNm;
	}

	public void setCorpNm(String corpNm) {
		this.corpNm = corpNm;

	}

	@Column(name = "CREDIT_CD", length = 10)
	public String getCreditCd() {
		return this.creditCd;
	}

	public void setCreditCd(String creditCd) {
		this.creditCd = creditCd;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getCorpNo());
		buffer.append("#").append(getCreditTypeCd());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmLv1CreditGradeSub))
			return false;
		NcmLv1CreditGradeSub castOther = (NcmLv1CreditGradeSub) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCorpNo() == null ? 0 : this.getCorpNo().hashCode());
		result = 37 * result + (getCreditTypeCd() == null ? 0 : this.getCreditTypeCd().hashCode());
		return result;
	}

}
