package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv1ProdHis generated by hbm2java
 */
@Entity
@Table(name = "NCM_LV1_PROD_HIS", schema = "NCM")
public class NcmLv1ProdHis implements java.io.Serializable {

	private NcmLv1ProdHisId id;
	private String finProdNm;
	private String prodTypeCd;
	private String prodTypeNm;
	private String issuCorpNo;
	private String issuerNm;
	private BigDecimal issuAmt;
	private String issuDate;
	private String matDate;
	private BigDecimal intRate;
	private String chgDesc;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv1ProdHis() {
	}

	public NcmLv1ProdHis(NcmLv1ProdHisId id) {
		this.id = id;
	}

	public NcmLv1ProdHis(NcmLv1ProdHisId id, String finProdNm, String prodTypeCd, String prodTypeNm, String issuCorpNo,
			String issuerNm, BigDecimal issuAmt, String issuDate, String matDate, BigDecimal intRate, String chgDesc,
			String srcTable, String updateId, Date lastUpdate) {
		this.id = id;
		this.finProdNm = finProdNm;
		this.prodTypeCd = prodTypeCd;
		this.prodTypeNm = prodTypeNm;
		this.issuCorpNo = issuCorpNo;
		this.issuerNm = issuerNm;
		this.issuAmt = issuAmt;
		this.issuDate = issuDate;
		this.matDate = matDate;
		this.intRate = intRate;
		this.chgDesc = chgDesc;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "chgDate", column = @Column(name = "CHG_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "finProdId", column = @Column(name = "FIN_PROD_ID", nullable = false, length = 50)) })
	public NcmLv1ProdHisId getId() {
		return this.id;
	}

	public void setId(NcmLv1ProdHisId id) {
		this.id = id;
	}

	@Column(name = "FIN_PROD_NM", length = 100)
	public String getFinProdNm() {
		return this.finProdNm;
	}

	public void setFinProdNm(String finProdNm) {
		this.finProdNm = finProdNm;
	}

	@Column(name = "PROD_TYPE_CD", length = 10)
	public String getProdTypeCd() {
		return this.prodTypeCd;
	}

	public void setProdTypeCd(String prodTypeCd) {
		this.prodTypeCd = prodTypeCd;
	}

	@Column(name = "PROD_TYPE_NM", length = 100)
	public String getProdTypeNm() {
		return this.prodTypeNm;
	}

	public void setProdTypeNm(String prodTypeNm) {
		this.prodTypeNm = prodTypeNm;
	}

	@Column(name = "ISSU_CORP_NO", length = 20)
	public String getIssuCorpNo() {
		return this.issuCorpNo;
	}

	public void setIssuCorpNo(String issuCorpNo) {
		this.issuCorpNo = issuCorpNo;
	}

	@Column(name = "ISSUER_NM", length = 100)
	public String getIssuerNm() {
		return this.issuerNm;
	}

	public void setIssuerNm(String issuerNm) {
		this.issuerNm = issuerNm;
	}

	@Column(name = "ISSU_AMT", precision = 20)
	public BigDecimal getIssuAmt() {
		return this.issuAmt;
	}

	public void setIssuAmt(BigDecimal issuAmt) {
		this.issuAmt = issuAmt;
	}

	@Column(name = "ISSU_DATE", length = 8)
	public String getIssuDate() {
		return this.issuDate;
	}

	public void setIssuDate(String issuDate) {
		this.issuDate = issuDate;
	}

	@Column(name = "MAT_DATE", length = 8)
	public String getMatDate() {
		return this.matDate;
	}

	public void setMatDate(String matDate) {
		this.matDate = matDate;
	}

	@Column(name = "INT_RATE", precision = 12, scale = 8)
	public BigDecimal getIntRate() {
		return this.intRate;
	}

	public void setIntRate(BigDecimal intRate) {
		this.intRate = intRate;
	}

	@Column(name = "CHG_DESC", length = 100)
	public String getChgDesc() {
		return this.chgDesc;
	}

	public void setChgDesc(String chgDesc) {
		this.chgDesc = chgDesc;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
