package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmLv1CreditGradeSub generated by hbm2java
 */
@Entity
@Table(name = "NCM_LV1_CREDIT_GRADE_SUB", schema = "NCM")
public class NcmLv1CreditGradeSub implements java.io.Serializable {

	private NcmLv1CreditGradeSubId id;
	private String corpNm;
	private String creditCd;

	public NcmLv1CreditGradeSub() {
	}

	public NcmLv1CreditGradeSub(NcmLv1CreditGradeSubId id) {
		this.id = id;
	}

	public NcmLv1CreditGradeSub(NcmLv1CreditGradeSubId id, String corpNm, String creditCd) {
		this.id = id;
		this.corpNm = corpNm;
		this.creditCd = creditCd;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "corpNo", column = @Column(name = "CORP_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "creditTypeCd", column = @Column(name = "CREDIT_TYPE_CD", nullable = false, length = 10)) })
	public NcmLv1CreditGradeSubId getId() {
		return this.id;
	}

	public void setId(NcmLv1CreditGradeSubId id) {
		this.id = id;
	}

	@Column(name = "CORP_NM", length = 100)
	public String getCorpNm() {
		return this.corpNm;
	}

	public void setCorpNm(String corpNm) {
		this.corpNm = corpNm;
	}

	@Column(name = "CREDIT_CD", length = 10)
	public String getCreditCd() {
		return this.creditCd;
	}

	public void setCreditCd(String creditCd) {
		this.creditCd = creditCd;
	}

}
