package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmLv2PortReturn20161018 generated by hbm2java
 */
@Entity
@Table(name = "NCM_LV2_PORT_RETURN_20161018", schema = "NCM")
public class NcmLv2PortReturn20161018 implements java.io.Serializable {

	private NcmLv2PortReturn20161018Id id;

	public NcmLv2PortReturn20161018() {
	}

	public NcmLv2PortReturn20161018(NcmLv2PortReturn20161018Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "cptlDivCd", column = @Column(name = "CPTL_DIV_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "yieldLclssCd", column = @Column(name = "YIELD_LCLSS_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "yieldDivCd", column = @Column(name = "YIELD_DIV_CD", nullable = false, length = 20)),
			@AttributeOverride(name = "prodTypeCd", column = @Column(name = "PROD_TYPE_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "m01Yield", column = @Column(name = "M01_YIELD", precision = 12, scale = 8)),
			@AttributeOverride(name = "m03Yield", column = @Column(name = "M03_YIELD", precision = 12, scale = 8)),
			@AttributeOverride(name = "m06Yield", column = @Column(name = "M06_YIELD", precision = 12, scale = 8)),
			@AttributeOverride(name = "m12Yield", column = @Column(name = "M12_YIELD", precision = 12, scale = 8)),
			@AttributeOverride(name = "m24Yield", column = @Column(name = "M24_YIELD", precision = 12, scale = 8)),
			@AttributeOverride(name = "m36Yield", column = @Column(name = "M36_YIELD", precision = 12, scale = 8)),
			@AttributeOverride(name = "ytdYield", column = @Column(name = "YTD_YIELD", precision = 12, scale = 8)),
			@AttributeOverride(name = "qtdYield", column = @Column(name = "QTD_YIELD", precision = 12, scale = 8)),
			@AttributeOverride(name = "mtdYield", column = @Column(name = "MTD_YIELD", precision = 12, scale = 8)),
			@AttributeOverride(name = "m01Awght", column = @Column(name = "M01_AWGHT", precision = 12, scale = 8)),
			@AttributeOverride(name = "m03Awght", column = @Column(name = "M03_AWGHT", precision = 12, scale = 8)),
			@AttributeOverride(name = "m06Awght", column = @Column(name = "M06_AWGHT", precision = 12, scale = 8)),
			@AttributeOverride(name = "m12Awght", column = @Column(name = "M12_AWGHT", precision = 12, scale = 8)),
			@AttributeOverride(name = "m24Awght", column = @Column(name = "M24_AWGHT", precision = 12, scale = 8)),
			@AttributeOverride(name = "m36Awght", column = @Column(name = "M36_AWGHT", precision = 12, scale = 8)),
			@AttributeOverride(name = "ytdAwght", column = @Column(name = "YTD_AWGHT", precision = 12, scale = 8)),
			@AttributeOverride(name = "qtdAwght", column = @Column(name = "QTD_AWGHT", precision = 12, scale = 8)),
			@AttributeOverride(name = "mtdAwght", column = @Column(name = "MTD_AWGHT", precision = 12, scale = 8)),
			@AttributeOverride(name = "m01Pl", column = @Column(name = "M01_PL", precision = 22, scale = 0)),
			@AttributeOverride(name = "m03Pl", column = @Column(name = "M03_PL", precision = 22, scale = 0)),
			@AttributeOverride(name = "m06Pl", column = @Column(name = "M06_PL", precision = 22, scale = 0)),
			@AttributeOverride(name = "m12Pl", column = @Column(name = "M12_PL", precision = 22, scale = 0)),
			@AttributeOverride(name = "m24Pl", column = @Column(name = "M24_PL", precision = 22, scale = 0)),
			@AttributeOverride(name = "m36Pl", column = @Column(name = "M36_PL", precision = 22, scale = 0)),
			@AttributeOverride(name = "ytdPl", column = @Column(name = "YTD_PL", precision = 22, scale = 0)),
			@AttributeOverride(name = "qtdPl", column = @Column(name = "QTD_PL", precision = 22, scale = 0)),
			@AttributeOverride(name = "mtdPl", column = @Column(name = "MTD_PL", precision = 22, scale = 0)),
			@AttributeOverride(name = "m01Cnt", column = @Column(name = "M01_CNT", precision = 5, scale = 0)),
			@AttributeOverride(name = "m03Cnt", column = @Column(name = "M03_CNT", precision = 5, scale = 0)),
			@AttributeOverride(name = "m06Cnt", column = @Column(name = "M06_CNT", precision = 5, scale = 0)),
			@AttributeOverride(name = "m12Cnt", column = @Column(name = "M12_CNT", precision = 5, scale = 0)),
			@AttributeOverride(name = "m24Cnt", column = @Column(name = "M24_CNT", precision = 5, scale = 0)),
			@AttributeOverride(name = "m36Cnt", column = @Column(name = "M36_CNT", precision = 5, scale = 0)),
			@AttributeOverride(name = "ytdCnt", column = @Column(name = "YTD_CNT", precision = 5, scale = 0)),
			@AttributeOverride(name = "qtdCnt", column = @Column(name = "QTD_CNT", precision = 5, scale = 0)),
			@AttributeOverride(name = "mtdCnt", column = @Column(name = "MTD_CNT", precision = 5, scale = 0)),
			@AttributeOverride(name = "fy1Yield", column = @Column(name = "FY1_YIELD", precision = 12, scale = 8)),
			@AttributeOverride(name = "fy2Yield", column = @Column(name = "FY2_YIELD", precision = 12, scale = 8)),
			@AttributeOverride(name = "fy3Yield", column = @Column(name = "FY3_YIELD", precision = 12, scale = 8)),
			@AttributeOverride(name = "srcTable", column = @Column(name = "SRC_TABLE", length = 20)),
			@AttributeOverride(name = "updateId", column = @Column(name = "UPDATE_ID", length = 20)),
			@AttributeOverride(name = "lastUpdate", column = @Column(name = "LAST_UPDATE", length = 7)) })
	public NcmLv2PortReturn20161018Id getId() {
		return this.id;
	}

	public void setId(NcmLv2PortReturn20161018Id id) {
		this.id = id;
	}

}
