package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv2SubRisk generated by hbm2java
 */
@Entity
@Table(name = "NCM_LV2_SUB_RISK", schema = "NCM")
public class NcmLv2SubRisk implements java.io.Serializable {

	private NcmLv2SubRiskId id;
	private BigDecimal stdev;
	private BigDecimal var;
	private BigDecimal te;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv2SubRisk() {
	}

	public NcmLv2SubRisk(NcmLv2SubRiskId id, BigDecimal stdev, BigDecimal var, BigDecimal te) {
		this.id = id;
		this.stdev = stdev;
		this.var = var;
		this.te = te;
	}

	public NcmLv2SubRisk(NcmLv2SubRiskId id, BigDecimal stdev, BigDecimal var, BigDecimal te, String srcTable,
			String updateId, Date lastUpdate) {
		this.id = id;
		this.stdev = stdev;
		this.var = var;
		this.te = te;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "posId", column = @Column(name = "POS_ID", nullable = false, length = 20)) })
	public NcmLv2SubRiskId getId() {
		return this.id;
	}

	public void setId(NcmLv2SubRiskId id) {
		this.id = id;
	}

	@Column(name = "STDEV", nullable = false, precision = 12, scale = 8)
	public BigDecimal getStdev() {
		return this.stdev;
	}

	public void setStdev(BigDecimal stdev) {
		this.stdev = stdev;
	}

	@Column(name = "VAR", nullable = false, precision = 20)
	public BigDecimal getVar() {
		return this.var;
	}

	public void setVar(BigDecimal var) {
		this.var = var;
	}

	@Column(name = "TE", nullable = false, precision = 12, scale = 8)
	public BigDecimal getTe() {
		return this.te;
	}

	public void setTe(BigDecimal te) {
		this.te = te;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
