package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv1SubTransaction generated by hbm2java
 */
@Entity
@Table(name = "NCM_LV1_SUB_TRANSACTION", schema = "NCM")
public class NcmLv1SubTransaction implements java.io.Serializable {

	private NcmLv1SubTransactionId id;
	private String finProdId;
	private String mngFinOrg;
	private String txTypeCd;
	private String hldProdId;
	private String buySellDivCd;
	private String cpartyCorpNo;
	private String cpartyCorpNm;
	private BigDecimal txAmt;
	private BigDecimal txQty;
	private BigDecimal txPrice;
	private String sttlDate;
	private BigDecimal tradePl;
	private BigDecimal tradeYield;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv1SubTransaction() {
	}

	public NcmLv1SubTransaction(NcmLv1SubTransactionId id, String finProdId, String mngFinOrg, String txTypeCd,
			String hldProdId, BigDecimal txAmt, BigDecimal txQty, BigDecimal txPrice, BigDecimal tradePl,
			BigDecimal tradeYield) {
		this.id = id;
		this.finProdId = finProdId;
		this.mngFinOrg = mngFinOrg;
		this.txTypeCd = txTypeCd;
		this.hldProdId = hldProdId;
		this.txAmt = txAmt;
		this.txQty = txQty;
		this.txPrice = txPrice;
		this.tradePl = tradePl;
		this.tradeYield = tradeYield;
	}

	public NcmLv1SubTransaction(NcmLv1SubTransactionId id, String finProdId, String mngFinOrg, String txTypeCd,
			String hldProdId, String buySellDivCd, String cpartyCorpNo, String cpartyCorpNm, BigDecimal txAmt,
			BigDecimal txQty, BigDecimal txPrice, String sttlDate, BigDecimal tradePl, BigDecimal tradeYield,
			String srcTable, String updateId, Date lastUpdate) {
		this.id = id;
		this.finProdId = finProdId;
		this.mngFinOrg = mngFinOrg;
		this.txTypeCd = txTypeCd;
		this.hldProdId = hldProdId;
		this.buySellDivCd = buySellDivCd;
		this.cpartyCorpNo = cpartyCorpNo;
		this.cpartyCorpNm = cpartyCorpNm;
		this.txAmt = txAmt;
		this.txQty = txQty;
		this.txPrice = txPrice;
		this.sttlDate = sttlDate;
		this.tradePl = tradePl;
		this.tradeYield = tradeYield;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "txNo", column = @Column(name = "TX_NO", nullable = false, length = 100)) })
	public NcmLv1SubTransactionId getId() {
		return this.id;
	}

	public void setId(NcmLv1SubTransactionId id) {
		this.id = id;
	}

	@Column(name = "FIN_PROD_ID", nullable = false, length = 50)
	public String getFinProdId() {
		return this.finProdId;
	}

	public void setFinProdId(String finProdId) {
		this.finProdId = finProdId;
	}

	@Column(name = "MNG_FIN_ORG", nullable = false, length = 20)
	public String getMngFinOrg() {
		return this.mngFinOrg;
	}

	public void setMngFinOrg(String mngFinOrg) {
		this.mngFinOrg = mngFinOrg;
	}

	@Column(name = "TX_TYPE_CD", nullable = false, length = 10)
	public String getTxTypeCd() {
		return this.txTypeCd;
	}

	public void setTxTypeCd(String txTypeCd) {
		this.txTypeCd = txTypeCd;
	}

	@Column(name = "HLD_PROD_ID", nullable = false, length = 20)
	public String getHldProdId() {
		return this.hldProdId;
	}

	public void setHldProdId(String hldProdId) {
		this.hldProdId = hldProdId;
	}

	@Column(name = "BUY_SELL_DIV_CD", length = 10)
	public String getBuySellDivCd() {
		return this.buySellDivCd;
	}

	public void setBuySellDivCd(String buySellDivCd) {
		this.buySellDivCd = buySellDivCd;
	}

	@Column(name = "CPARTY_CORP_NO", length = 20)
	public String getCpartyCorpNo() {
		return this.cpartyCorpNo;
	}

	public void setCpartyCorpNo(String cpartyCorpNo) {
		this.cpartyCorpNo = cpartyCorpNo;
	}

	@Column(name = "CPARTY_CORP_NM", length = 200)
	public String getCpartyCorpNm() {
		return this.cpartyCorpNm;
	}

	public void setCpartyCorpNm(String cpartyCorpNm) {
		this.cpartyCorpNm = cpartyCorpNm;
	}

	@Column(name = "TX_AMT", nullable = false, precision = 20)
	public BigDecimal getTxAmt() {
		return this.txAmt;
	}

	public void setTxAmt(BigDecimal txAmt) {
		this.txAmt = txAmt;
	}

	@Column(name = "TX_QTY", nullable = false, precision = 20)
	public BigDecimal getTxQty() {
		return this.txQty;
	}

	public void setTxQty(BigDecimal txQty) {
		this.txQty = txQty;
	}

	@Column(name = "TX_PRICE", nullable = false, precision = 20)
	public BigDecimal getTxPrice() {
		return this.txPrice;
	}

	public void setTxPrice(BigDecimal txPrice) {
		this.txPrice = txPrice;
	}

	@Column(name = "STTL_DATE", length = 8)
	public String getSttlDate() {
		return this.sttlDate;
	}

	public void setSttlDate(String sttlDate) {
		this.sttlDate = sttlDate;
	}

	@Column(name = "TRADE_PL", nullable = false, precision = 20)
	public BigDecimal getTradePl() {
		return this.tradePl;
	}

	public void setTradePl(BigDecimal tradePl) {
		this.tradePl = tradePl;
	}

	@Column(name = "TRADE_YIELD", nullable = false, precision = 12, scale = 8)
	public BigDecimal getTradeYield() {
		return this.tradeYield;
	}

	public void setTradeYield(BigDecimal tradeYield) {
		this.tradeYield = tradeYield;
	}

	@Column(name = "SRC_TABLE", length = 50)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 50)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
