package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv2ComplRst generated by hbm2java
 */
@Entity
@Table(name = "NCM_LV2_COMPL_RST", schema = "NCM")
public class NcmLv2ComplRst implements java.io.Serializable {

	private NcmLv2ComplRstId id;
	private String complApplyNm;
	private BigDecimal applyAmt;
	private BigDecimal lmtMinAmt;
	private BigDecimal lmtMaxAmt;
	private BigDecimal torlError;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv2ComplRst() {
	}

	public NcmLv2ComplRst(NcmLv2ComplRstId id, BigDecimal lmtMinAmt, BigDecimal lmtMaxAmt) {
		this.id = id;
		this.lmtMinAmt = lmtMinAmt;
		this.lmtMaxAmt = lmtMaxAmt;
	}

	public NcmLv2ComplRst(NcmLv2ComplRstId id, String complApplyNm, BigDecimal applyAmt, BigDecimal lmtMinAmt,
			BigDecimal lmtMaxAmt, BigDecimal torlError, String srcTable, String updateId, Date lastUpdate) {
		this.id = id;
		this.complApplyNm = complApplyNm;
		this.applyAmt = applyAmt;
		this.lmtMinAmt = lmtMinAmt;
		this.lmtMaxAmt = lmtMaxAmt;
		this.torlError = torlError;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "applyDivCd", column = @Column(name = "APPLY_DIV_CD", nullable = false, length = 20)),
			@AttributeOverride(name = "applyCd", column = @Column(name = "APPLY_CD", nullable = false, length = 20)),
			@AttributeOverride(name = "complTypeCd", column = @Column(name = "COMPL_TYPE_CD", nullable = false, length = 20)),
			@AttributeOverride(name = "seq", column = @Column(name = "SEQ", nullable = false, precision = 4, scale = 0)) })
	public NcmLv2ComplRstId getId() {
		return this.id;
	}

	public void setId(NcmLv2ComplRstId id) {
		this.id = id;
	}

	@Column(name = "COMPL_APPLY_NM", length = 100)
	public String getComplApplyNm() {
		return this.complApplyNm;
	}

	public void setComplApplyNm(String complApplyNm) {
		this.complApplyNm = complApplyNm;
	}

	@Column(name = "APPLY_AMT", precision = 20, scale = 4)
	public BigDecimal getApplyAmt() {
		return this.applyAmt;
	}

	public void setApplyAmt(BigDecimal applyAmt) {
		this.applyAmt = applyAmt;
	}

	@Column(name = "LMT_MIN_AMT", nullable = false, precision = 20, scale = 4)
	public BigDecimal getLmtMinAmt() {
		return this.lmtMinAmt;
	}

	public void setLmtMinAmt(BigDecimal lmtMinAmt) {
		this.lmtMinAmt = lmtMinAmt;
	}

	@Column(name = "LMT_MAX_AMT", nullable = false, precision = 20, scale = 4)
	public BigDecimal getLmtMaxAmt() {
		return this.lmtMaxAmt;
	}

	public void setLmtMaxAmt(BigDecimal lmtMaxAmt) {
		this.lmtMaxAmt = lmtMaxAmt;
	}

	@Column(name = "TORL_ERROR", precision = 20, scale = 4)
	public BigDecimal getTorlError() {
		return this.torlError;
	}

	public void setTorlError(BigDecimal torlError) {
		this.torlError = torlError;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
