package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv1BmIndex generated by hbm2java
 */
@Entity
@Table(name = "NCM_LV1_BM_INDEX", schema = "NCM")
public class NcmLv1BmIndex implements java.io.Serializable {

	private NcmLv1BmIndexId id;
	private BigDecimal bmYield;
	private BigDecimal bmIdx;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv1BmIndex() {
	}

	public NcmLv1BmIndex(NcmLv1BmIndexId id) {
		this.id = id;
	}

	public NcmLv1BmIndex(NcmLv1BmIndexId id, BigDecimal bmYield, BigDecimal bmIdx, String srcTable, String updateId,
			Date lastUpdate) {
		this.id = id;
		this.bmYield = bmYield;
		this.bmIdx = bmIdx;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "bmId", column = @Column(name = "BM_ID", nullable = false, length = 20)) })
	public NcmLv1BmIndexId getId() {
		return this.id;
	}

	public void setId(NcmLv1BmIndexId id) {
		this.id = id;
	}

	@Column(name = "BM_YIELD", precision = 20, scale = 12)
	public BigDecimal getBmYield() {
		return this.bmYield;
	}

	public void setBmYield(BigDecimal bmYield) {
		this.bmYield = bmYield;
	}

	@Column(name = "BM_IDX", precision = 20, scale = 12)
	public BigDecimal getBmIdx() {
		return this.bmIdx;
	}

	public void setBmIdx(BigDecimal bmIdx) {
		this.bmIdx = bmIdx;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
