package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv1FundDetail generated by hbm2java
 */
@Entity
@Table(name = "NCM_LV1_FUND_DETAIL", schema = "NCM")
public class NcmLv1FundDetail implements java.io.Serializable {

	private String finProdId;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv1FundDetail() {
	}

	public NcmLv1FundDetail(String finProdId) {
		this.finProdId = finProdId;
	}

	public NcmLv1FundDetail(String finProdId, String srcTable, String updateId, Date lastUpdate) {
		this.finProdId = finProdId;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@Id

	@Column(name = "FIN_PROD_ID", unique = true, nullable = false, length = 20)
	public String getFinProdId() {
		return this.finProdId;
	}

	public void setFinProdId(String finProdId) {
		this.finProdId = finProdId;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
