package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv1BmIndex generated by hbm2java
 */

@Entity
@IdClass(value = NcmLv1BmIndexId.class)
@Table(name = "NCM_LV1_BM_INDEX", schema = "NCM")
public class NcmLv1BmIndex implements java.io.Serializable {

	private String baseDate;
	private String bmId;
	private BigDecimal bmYield;
	private BigDecimal bmIdx;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv1BmIndex() {
	}

	@Id
	@Column(name = "BASE_DATE", nullable = false, length = 8)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Id
	@Column(name = "BM_ID", nullable = false, length = 20)
	public String getBmId() {
		return this.bmId;
	}

	public void setBmId(String bmId) {
		this.bmId = bmId;
	}

	@Column(name = "BM_YIELD", precision = 20, scale = 12)
	public BigDecimal getBmYield() {
		return this.bmYield;
	}

	public void setBmYield(BigDecimal bmYield) {
		this.bmYield = bmYield;

	}

	@Column(name = "BM_IDX", precision = 20, scale = 12)
	public BigDecimal getBmIdx() {
		return this.bmIdx;
	}

	public void setBmIdx(BigDecimal bmIdx) {
		this.bmIdx = bmIdx;

	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getBmId());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmLv1BmIndex))
			return false;
		NcmLv1BmIndex castOther = (NcmLv1BmIndex) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getBmId() == null ? 0 : this.getBmId().hashCode());
		return result;
	}

}
