package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv2PortRisk generated by hbm2java
 */
@Entity
@Table(name = "NCM_LV2_PORT_RISK", schema = "NCM")
public class NcmLv2PortRisk implements java.io.Serializable {

	private NcmLv2PortRiskId id;
	private BigDecimal avgYield;
	private BigDecimal stdev;
	private BigDecimal eta;
	private BigDecimal var;
	private BigDecimal te;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv2PortRisk() {
	}

	public NcmLv2PortRisk(NcmLv2PortRiskId id) {
		this.id = id;
	}

	public NcmLv2PortRisk(NcmLv2PortRiskId id, BigDecimal avgYield, BigDecimal stdev, BigDecimal eta, BigDecimal var,
			BigDecimal te, String srcTable, String updateId, Date lastUpdate) {
		this.id = id;
		this.avgYield = avgYield;
		this.stdev = stdev;
		this.eta = eta;
		this.var = var;
		this.te = te;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "cptlDivCd", column = @Column(name = "CPTL_DIV_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "yieldLclssCd", column = @Column(name = "YIELD_LCLSS_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "yieldDivCd", column = @Column(name = "YIELD_DIV_CD", nullable = false, length = 20)),
			@AttributeOverride(name = "timeHorizonCd", column = @Column(name = "TIME_HORIZON_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "confiLevelCd", column = @Column(name = "CONFI_LEVEL_CD", nullable = false, length = 10)) })
	public NcmLv2PortRiskId getId() {
		return this.id;
	}

	public void setId(NcmLv2PortRiskId id) {
		this.id = id;
	}

	@Column(name = "AVG_YIELD", precision = 20, scale = 8)
	public BigDecimal getAvgYield() {
		return this.avgYield;
	}

	public void setAvgYield(BigDecimal avgYield) {
		this.avgYield = avgYield;
	}

	@Column(name = "STDEV", precision = 20, scale = 8)
	public BigDecimal getStdev() {
		return this.stdev;
	}

	public void setStdev(BigDecimal stdev) {
		this.stdev = stdev;
	}

	@Column(name = "ETA", precision = 20, scale = 8)
	public BigDecimal getEta() {
		return this.eta;
	}

	public void setEta(BigDecimal eta) {
		this.eta = eta;
	}

	@Column(name = "VAR", precision = 20, scale = 8)
	public BigDecimal getVar() {
		return this.var;
	}

	public void setVar(BigDecimal var) {
		this.var = var;
	}

	@Column(name = "TE", precision = 20, scale = 8)
	public BigDecimal getTe() {
		return this.te;
	}

	public void setTe(BigDecimal te) {
		this.te = te;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
