package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NcmLv2PortReturn20161018Id generated by hbm2java
 */
@Embeddable
public class NcmLv2PortReturn20161018Id implements java.io.Serializable {

	private String baseDate;
	private String cptlDivCd;
	private String yieldLclssCd;
	private String yieldDivCd;
	private String prodTypeCd;
	private BigDecimal m01Yield;
	private BigDecimal m03Yield;
	private BigDecimal m06Yield;
	private BigDecimal m12Yield;
	private BigDecimal m24Yield;
	private BigDecimal m36Yield;
	private BigDecimal ytdYield;
	private BigDecimal qtdYield;
	private BigDecimal mtdYield;
	private BigDecimal m01Awght;
	private BigDecimal m03Awght;
	private BigDecimal m06Awght;
	private BigDecimal m12Awght;
	private BigDecimal m24Awght;
	private BigDecimal m36Awght;
	private BigDecimal ytdAwght;
	private BigDecimal qtdAwght;
	private BigDecimal mtdAwght;
	private BigDecimal m01Pl;
	private BigDecimal m03Pl;
	private BigDecimal m06Pl;
	private BigDecimal m12Pl;
	private BigDecimal m24Pl;
	private BigDecimal m36Pl;
	private BigDecimal ytdPl;
	private BigDecimal qtdPl;
	private BigDecimal mtdPl;
	private Integer m01Cnt;
	private Integer m03Cnt;
	private Integer m06Cnt;
	private Integer m12Cnt;
	private Integer m24Cnt;
	private Integer m36Cnt;
	private Integer ytdCnt;
	private Integer qtdCnt;
	private Integer mtdCnt;
	private BigDecimal fy1Yield;
	private BigDecimal fy2Yield;
	private BigDecimal fy3Yield;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv2PortReturn20161018Id() {
	}

	public NcmLv2PortReturn20161018Id(String baseDate, String cptlDivCd, String yieldLclssCd, String yieldDivCd,
			String prodTypeCd) {
		this.baseDate = baseDate;
		this.cptlDivCd = cptlDivCd;
		this.yieldLclssCd = yieldLclssCd;
		this.yieldDivCd = yieldDivCd;
		this.prodTypeCd = prodTypeCd;
	}

	public NcmLv2PortReturn20161018Id(String baseDate, String cptlDivCd, String yieldLclssCd, String yieldDivCd,
			String prodTypeCd, BigDecimal m01Yield, BigDecimal m03Yield, BigDecimal m06Yield, BigDecimal m12Yield,
			BigDecimal m24Yield, BigDecimal m36Yield, BigDecimal ytdYield, BigDecimal qtdYield, BigDecimal mtdYield,
			BigDecimal m01Awght, BigDecimal m03Awght, BigDecimal m06Awght, BigDecimal m12Awght, BigDecimal m24Awght,
			BigDecimal m36Awght, BigDecimal ytdAwght, BigDecimal qtdAwght, BigDecimal mtdAwght, BigDecimal m01Pl,
			BigDecimal m03Pl, BigDecimal m06Pl, BigDecimal m12Pl, BigDecimal m24Pl, BigDecimal m36Pl, BigDecimal ytdPl,
			BigDecimal qtdPl, BigDecimal mtdPl, Integer m01Cnt, Integer m03Cnt, Integer m06Cnt, Integer m12Cnt,
			Integer m24Cnt, Integer m36Cnt, Integer ytdCnt, Integer qtdCnt, Integer mtdCnt, BigDecimal fy1Yield,
			BigDecimal fy2Yield, BigDecimal fy3Yield, String srcTable, String updateId, Date lastUpdate) {
		this.baseDate = baseDate;
		this.cptlDivCd = cptlDivCd;
		this.yieldLclssCd = yieldLclssCd;
		this.yieldDivCd = yieldDivCd;
		this.prodTypeCd = prodTypeCd;
		this.m01Yield = m01Yield;
		this.m03Yield = m03Yield;
		this.m06Yield = m06Yield;
		this.m12Yield = m12Yield;
		this.m24Yield = m24Yield;
		this.m36Yield = m36Yield;
		this.ytdYield = ytdYield;
		this.qtdYield = qtdYield;
		this.mtdYield = mtdYield;
		this.m01Awght = m01Awght;
		this.m03Awght = m03Awght;
		this.m06Awght = m06Awght;
		this.m12Awght = m12Awght;
		this.m24Awght = m24Awght;
		this.m36Awght = m36Awght;
		this.ytdAwght = ytdAwght;
		this.qtdAwght = qtdAwght;
		this.mtdAwght = mtdAwght;
		this.m01Pl = m01Pl;
		this.m03Pl = m03Pl;
		this.m06Pl = m06Pl;
		this.m12Pl = m12Pl;
		this.m24Pl = m24Pl;
		this.m36Pl = m36Pl;
		this.ytdPl = ytdPl;
		this.qtdPl = qtdPl;
		this.mtdPl = mtdPl;
		this.m01Cnt = m01Cnt;
		this.m03Cnt = m03Cnt;
		this.m06Cnt = m06Cnt;
		this.m12Cnt = m12Cnt;
		this.m24Cnt = m24Cnt;
		this.m36Cnt = m36Cnt;
		this.ytdCnt = ytdCnt;
		this.qtdCnt = qtdCnt;
		this.mtdCnt = mtdCnt;
		this.fy1Yield = fy1Yield;
		this.fy2Yield = fy2Yield;
		this.fy3Yield = fy3Yield;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "BASE_DATE", nullable = false, length = 8)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Column(name = "CPTL_DIV_CD", nullable = false, length = 10)
	public String getCptlDivCd() {
		return this.cptlDivCd;
	}

	public void setCptlDivCd(String cptlDivCd) {
		this.cptlDivCd = cptlDivCd;
	}

	@Column(name = "YIELD_LCLSS_CD", nullable = false, length = 10)
	public String getYieldLclssCd() {
		return this.yieldLclssCd;
	}

	public void setYieldLclssCd(String yieldLclssCd) {
		this.yieldLclssCd = yieldLclssCd;
	}

	@Column(name = "YIELD_DIV_CD", nullable = false, length = 20)
	public String getYieldDivCd() {
		return this.yieldDivCd;
	}

	public void setYieldDivCd(String yieldDivCd) {
		this.yieldDivCd = yieldDivCd;
	}

	@Column(name = "PROD_TYPE_CD", nullable = false, length = 10)
	public String getProdTypeCd() {
		return this.prodTypeCd;
	}

	public void setProdTypeCd(String prodTypeCd) {
		this.prodTypeCd = prodTypeCd;
	}

	@Column(name = "M01_YIELD", precision = 12, scale = 8)
	public BigDecimal getM01Yield() {
		return this.m01Yield;
	}

	public void setM01Yield(BigDecimal m01Yield) {
		this.m01Yield = m01Yield;
	}

	@Column(name = "M03_YIELD", precision = 12, scale = 8)
	public BigDecimal getM03Yield() {
		return this.m03Yield;
	}

	public void setM03Yield(BigDecimal m03Yield) {
		this.m03Yield = m03Yield;
	}

	@Column(name = "M06_YIELD", precision = 12, scale = 8)
	public BigDecimal getM06Yield() {
		return this.m06Yield;
	}

	public void setM06Yield(BigDecimal m06Yield) {
		this.m06Yield = m06Yield;
	}

	@Column(name = "M12_YIELD", precision = 12, scale = 8)
	public BigDecimal getM12Yield() {
		return this.m12Yield;
	}

	public void setM12Yield(BigDecimal m12Yield) {
		this.m12Yield = m12Yield;
	}

	@Column(name = "M24_YIELD", precision = 12, scale = 8)
	public BigDecimal getM24Yield() {
		return this.m24Yield;
	}

	public void setM24Yield(BigDecimal m24Yield) {
		this.m24Yield = m24Yield;
	}

	@Column(name = "M36_YIELD", precision = 12, scale = 8)
	public BigDecimal getM36Yield() {
		return this.m36Yield;
	}

	public void setM36Yield(BigDecimal m36Yield) {
		this.m36Yield = m36Yield;
	}

	@Column(name = "YTD_YIELD", precision = 12, scale = 8)
	public BigDecimal getYtdYield() {
		return this.ytdYield;
	}

	public void setYtdYield(BigDecimal ytdYield) {
		this.ytdYield = ytdYield;
	}

	@Column(name = "QTD_YIELD", precision = 12, scale = 8)
	public BigDecimal getQtdYield() {
		return this.qtdYield;
	}

	public void setQtdYield(BigDecimal qtdYield) {
		this.qtdYield = qtdYield;
	}

	@Column(name = "MTD_YIELD", precision = 12, scale = 8)
	public BigDecimal getMtdYield() {
		return this.mtdYield;
	}

	public void setMtdYield(BigDecimal mtdYield) {
		this.mtdYield = mtdYield;
	}

	@Column(name = "M01_AWGHT", precision = 12, scale = 8)
	public BigDecimal getM01Awght() {
		return this.m01Awght;
	}

	public void setM01Awght(BigDecimal m01Awght) {
		this.m01Awght = m01Awght;
	}

	@Column(name = "M03_AWGHT", precision = 12, scale = 8)
	public BigDecimal getM03Awght() {
		return this.m03Awght;
	}

	public void setM03Awght(BigDecimal m03Awght) {
		this.m03Awght = m03Awght;
	}

	@Column(name = "M06_AWGHT", precision = 12, scale = 8)
	public BigDecimal getM06Awght() {
		return this.m06Awght;
	}

	public void setM06Awght(BigDecimal m06Awght) {
		this.m06Awght = m06Awght;
	}

	@Column(name = "M12_AWGHT", precision = 12, scale = 8)
	public BigDecimal getM12Awght() {
		return this.m12Awght;
	}

	public void setM12Awght(BigDecimal m12Awght) {
		this.m12Awght = m12Awght;
	}

	@Column(name = "M24_AWGHT", precision = 12, scale = 8)
	public BigDecimal getM24Awght() {
		return this.m24Awght;
	}

	public void setM24Awght(BigDecimal m24Awght) {
		this.m24Awght = m24Awght;
	}

	@Column(name = "M36_AWGHT", precision = 12, scale = 8)
	public BigDecimal getM36Awght() {
		return this.m36Awght;
	}

	public void setM36Awght(BigDecimal m36Awght) {
		this.m36Awght = m36Awght;
	}

	@Column(name = "YTD_AWGHT", precision = 12, scale = 8)
	public BigDecimal getYtdAwght() {
		return this.ytdAwght;
	}

	public void setYtdAwght(BigDecimal ytdAwght) {
		this.ytdAwght = ytdAwght;
	}

	@Column(name = "QTD_AWGHT", precision = 12, scale = 8)
	public BigDecimal getQtdAwght() {
		return this.qtdAwght;
	}

	public void setQtdAwght(BigDecimal qtdAwght) {
		this.qtdAwght = qtdAwght;
	}

	@Column(name = "MTD_AWGHT", precision = 12, scale = 8)
	public BigDecimal getMtdAwght() {
		return this.mtdAwght;
	}

	public void setMtdAwght(BigDecimal mtdAwght) {
		this.mtdAwght = mtdAwght;
	}

	@Column(name = "M01_PL", precision = 22, scale = 0)
	public BigDecimal getM01Pl() {
		return this.m01Pl;
	}

	public void setM01Pl(BigDecimal m01Pl) {
		this.m01Pl = m01Pl;
	}

	@Column(name = "M03_PL", precision = 22, scale = 0)
	public BigDecimal getM03Pl() {
		return this.m03Pl;
	}

	public void setM03Pl(BigDecimal m03Pl) {
		this.m03Pl = m03Pl;
	}

	@Column(name = "M06_PL", precision = 22, scale = 0)
	public BigDecimal getM06Pl() {
		return this.m06Pl;
	}

	public void setM06Pl(BigDecimal m06Pl) {
		this.m06Pl = m06Pl;
	}

	@Column(name = "M12_PL", precision = 22, scale = 0)
	public BigDecimal getM12Pl() {
		return this.m12Pl;
	}

	public void setM12Pl(BigDecimal m12Pl) {
		this.m12Pl = m12Pl;
	}

	@Column(name = "M24_PL", precision = 22, scale = 0)
	public BigDecimal getM24Pl() {
		return this.m24Pl;
	}

	public void setM24Pl(BigDecimal m24Pl) {
		this.m24Pl = m24Pl;
	}

	@Column(name = "M36_PL", precision = 22, scale = 0)
	public BigDecimal getM36Pl() {
		return this.m36Pl;
	}

	public void setM36Pl(BigDecimal m36Pl) {
		this.m36Pl = m36Pl;
	}

	@Column(name = "YTD_PL", precision = 22, scale = 0)
	public BigDecimal getYtdPl() {
		return this.ytdPl;
	}

	public void setYtdPl(BigDecimal ytdPl) {
		this.ytdPl = ytdPl;
	}

	@Column(name = "QTD_PL", precision = 22, scale = 0)
	public BigDecimal getQtdPl() {
		return this.qtdPl;
	}

	public void setQtdPl(BigDecimal qtdPl) {
		this.qtdPl = qtdPl;
	}

	@Column(name = "MTD_PL", precision = 22, scale = 0)
	public BigDecimal getMtdPl() {
		return this.mtdPl;
	}

	public void setMtdPl(BigDecimal mtdPl) {
		this.mtdPl = mtdPl;
	}

	@Column(name = "M01_CNT", precision = 5, scale = 0)
	public Integer getM01Cnt() {
		return this.m01Cnt;
	}

	public void setM01Cnt(Integer m01Cnt) {
		this.m01Cnt = m01Cnt;
	}

	@Column(name = "M03_CNT", precision = 5, scale = 0)
	public Integer getM03Cnt() {
		return this.m03Cnt;
	}

	public void setM03Cnt(Integer m03Cnt) {
		this.m03Cnt = m03Cnt;
	}

	@Column(name = "M06_CNT", precision = 5, scale = 0)
	public Integer getM06Cnt() {
		return this.m06Cnt;
	}

	public void setM06Cnt(Integer m06Cnt) {
		this.m06Cnt = m06Cnt;
	}

	@Column(name = "M12_CNT", precision = 5, scale = 0)
	public Integer getM12Cnt() {
		return this.m12Cnt;
	}

	public void setM12Cnt(Integer m12Cnt) {
		this.m12Cnt = m12Cnt;
	}

	@Column(name = "M24_CNT", precision = 5, scale = 0)
	public Integer getM24Cnt() {
		return this.m24Cnt;
	}

	public void setM24Cnt(Integer m24Cnt) {
		this.m24Cnt = m24Cnt;
	}

	@Column(name = "M36_CNT", precision = 5, scale = 0)
	public Integer getM36Cnt() {
		return this.m36Cnt;
	}

	public void setM36Cnt(Integer m36Cnt) {
		this.m36Cnt = m36Cnt;
	}

	@Column(name = "YTD_CNT", precision = 5, scale = 0)
	public Integer getYtdCnt() {
		return this.ytdCnt;
	}

	public void setYtdCnt(Integer ytdCnt) {
		this.ytdCnt = ytdCnt;
	}

	@Column(name = "QTD_CNT", precision = 5, scale = 0)
	public Integer getQtdCnt() {
		return this.qtdCnt;
	}

	public void setQtdCnt(Integer qtdCnt) {
		this.qtdCnt = qtdCnt;
	}

	@Column(name = "MTD_CNT", precision = 5, scale = 0)
	public Integer getMtdCnt() {
		return this.mtdCnt;
	}

	public void setMtdCnt(Integer mtdCnt) {
		this.mtdCnt = mtdCnt;
	}

	@Column(name = "FY1_YIELD", precision = 12, scale = 8)
	public BigDecimal getFy1Yield() {
		return this.fy1Yield;
	}

	public void setFy1Yield(BigDecimal fy1Yield) {
		this.fy1Yield = fy1Yield;
	}

	@Column(name = "FY2_YIELD", precision = 12, scale = 8)
	public BigDecimal getFy2Yield() {
		return this.fy2Yield;
	}

	public void setFy2Yield(BigDecimal fy2Yield) {
		this.fy2Yield = fy2Yield;
	}

	@Column(name = "FY3_YIELD", precision = 12, scale = 8)
	public BigDecimal getFy3Yield() {
		return this.fy3Yield;
	}

	public void setFy3Yield(BigDecimal fy3Yield) {
		this.fy3Yield = fy3Yield;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmLv2PortReturn20161018Id))
			return false;
		NcmLv2PortReturn20161018Id castOther = (NcmLv2PortReturn20161018Id) other;

		return ((this.getBaseDate() == castOther.getBaseDate()) || (this.getBaseDate() != null
				&& castOther.getBaseDate() != null && this.getBaseDate().equals(castOther.getBaseDate())))
				&& ((this.getCptlDivCd() == castOther.getCptlDivCd()) || (this.getCptlDivCd() != null
						&& castOther.getCptlDivCd() != null && this.getCptlDivCd().equals(castOther.getCptlDivCd())))
				&& ((this.getYieldLclssCd() == castOther.getYieldLclssCd())
						|| (this.getYieldLclssCd() != null && castOther.getYieldLclssCd() != null
								&& this.getYieldLclssCd().equals(castOther.getYieldLclssCd())))
				&& ((this.getYieldDivCd() == castOther.getYieldDivCd()) || (this.getYieldDivCd() != null
						&& castOther.getYieldDivCd() != null && this.getYieldDivCd().equals(castOther.getYieldDivCd())))
				&& ((this.getProdTypeCd() == castOther.getProdTypeCd()) || (this.getProdTypeCd() != null
						&& castOther.getProdTypeCd() != null && this.getProdTypeCd().equals(castOther.getProdTypeCd())))
				&& ((this.getM01Yield() == castOther.getM01Yield()) || (this.getM01Yield() != null
						&& castOther.getM01Yield() != null && this.getM01Yield().equals(castOther.getM01Yield())))
				&& ((this.getM03Yield() == castOther.getM03Yield()) || (this.getM03Yield() != null
						&& castOther.getM03Yield() != null && this.getM03Yield().equals(castOther.getM03Yield())))
				&& ((this.getM06Yield() == castOther.getM06Yield()) || (this.getM06Yield() != null
						&& castOther.getM06Yield() != null && this.getM06Yield().equals(castOther.getM06Yield())))
				&& ((this.getM12Yield() == castOther.getM12Yield()) || (this.getM12Yield() != null
						&& castOther.getM12Yield() != null && this.getM12Yield().equals(castOther.getM12Yield())))
				&& ((this.getM24Yield() == castOther.getM24Yield()) || (this.getM24Yield() != null
						&& castOther.getM24Yield() != null && this.getM24Yield().equals(castOther.getM24Yield())))
				&& ((this.getM36Yield() == castOther.getM36Yield()) || (this.getM36Yield() != null
						&& castOther.getM36Yield() != null && this.getM36Yield().equals(castOther.getM36Yield())))
				&& ((this.getYtdYield() == castOther.getYtdYield()) || (this.getYtdYield() != null
						&& castOther.getYtdYield() != null && this.getYtdYield().equals(castOther.getYtdYield())))
				&& ((this.getQtdYield() == castOther.getQtdYield()) || (this.getQtdYield() != null
						&& castOther.getQtdYield() != null && this.getQtdYield().equals(castOther.getQtdYield())))
				&& ((this.getMtdYield() == castOther.getMtdYield()) || (this.getMtdYield() != null
						&& castOther.getMtdYield() != null && this.getMtdYield().equals(castOther.getMtdYield())))
				&& ((this.getM01Awght() == castOther.getM01Awght()) || (this.getM01Awght() != null
						&& castOther.getM01Awght() != null && this.getM01Awght().equals(castOther.getM01Awght())))
				&& ((this.getM03Awght() == castOther.getM03Awght()) || (this.getM03Awght() != null
						&& castOther.getM03Awght() != null && this.getM03Awght().equals(castOther.getM03Awght())))
				&& ((this.getM06Awght() == castOther.getM06Awght()) || (this.getM06Awght() != null
						&& castOther.getM06Awght() != null && this.getM06Awght().equals(castOther.getM06Awght())))
				&& ((this.getM12Awght() == castOther.getM12Awght()) || (this.getM12Awght() != null
						&& castOther.getM12Awght() != null && this.getM12Awght().equals(castOther.getM12Awght())))
				&& ((this.getM24Awght() == castOther.getM24Awght()) || (this.getM24Awght() != null
						&& castOther.getM24Awght() != null && this.getM24Awght().equals(castOther.getM24Awght())))
				&& ((this.getM36Awght() == castOther.getM36Awght()) || (this.getM36Awght() != null
						&& castOther.getM36Awght() != null && this.getM36Awght().equals(castOther.getM36Awght())))
				&& ((this.getYtdAwght() == castOther.getYtdAwght()) || (this.getYtdAwght() != null
						&& castOther.getYtdAwght() != null && this.getYtdAwght().equals(castOther.getYtdAwght())))
				&& ((this.getQtdAwght() == castOther.getQtdAwght()) || (this.getQtdAwght() != null
						&& castOther.getQtdAwght() != null && this.getQtdAwght().equals(castOther.getQtdAwght())))
				&& ((this.getMtdAwght() == castOther.getMtdAwght()) || (this.getMtdAwght() != null
						&& castOther.getMtdAwght() != null && this.getMtdAwght().equals(castOther.getMtdAwght())))
				&& ((this.getM01Pl() == castOther.getM01Pl()) || (this.getM01Pl() != null
						&& castOther.getM01Pl() != null && this.getM01Pl().equals(castOther.getM01Pl())))
				&& ((this.getM03Pl() == castOther.getM03Pl()) || (this.getM03Pl() != null
						&& castOther.getM03Pl() != null && this.getM03Pl().equals(castOther.getM03Pl())))
				&& ((this.getM06Pl() == castOther.getM06Pl()) || (this.getM06Pl() != null
						&& castOther.getM06Pl() != null && this.getM06Pl().equals(castOther.getM06Pl())))
				&& ((this.getM12Pl() == castOther.getM12Pl()) || (this.getM12Pl() != null
						&& castOther.getM12Pl() != null && this.getM12Pl().equals(castOther.getM12Pl())))
				&& ((this.getM24Pl() == castOther.getM24Pl()) || (this.getM24Pl() != null
						&& castOther.getM24Pl() != null && this.getM24Pl().equals(castOther.getM24Pl())))
				&& ((this.getM36Pl() == castOther.getM36Pl()) || (this.getM36Pl() != null
						&& castOther.getM36Pl() != null && this.getM36Pl().equals(castOther.getM36Pl())))
				&& ((this.getYtdPl() == castOther.getYtdPl()) || (this.getYtdPl() != null
						&& castOther.getYtdPl() != null && this.getYtdPl().equals(castOther.getYtdPl())))
				&& ((this.getQtdPl() == castOther.getQtdPl()) || (this.getQtdPl() != null
						&& castOther.getQtdPl() != null && this.getQtdPl().equals(castOther.getQtdPl())))
				&& ((this.getMtdPl() == castOther.getMtdPl()) || (this.getMtdPl() != null
						&& castOther.getMtdPl() != null && this.getMtdPl().equals(castOther.getMtdPl())))
				&& ((this.getM01Cnt() == castOther.getM01Cnt()) || (this.getM01Cnt() != null
						&& castOther.getM01Cnt() != null && this.getM01Cnt().equals(castOther.getM01Cnt())))
				&& ((this.getM03Cnt() == castOther.getM03Cnt()) || (this.getM03Cnt() != null
						&& castOther.getM03Cnt() != null && this.getM03Cnt().equals(castOther.getM03Cnt())))
				&& ((this.getM06Cnt() == castOther.getM06Cnt()) || (this.getM06Cnt() != null
						&& castOther.getM06Cnt() != null && this.getM06Cnt().equals(castOther.getM06Cnt())))
				&& ((this.getM12Cnt() == castOther.getM12Cnt()) || (this.getM12Cnt() != null
						&& castOther.getM12Cnt() != null && this.getM12Cnt().equals(castOther.getM12Cnt())))
				&& ((this.getM24Cnt() == castOther.getM24Cnt()) || (this.getM24Cnt() != null
						&& castOther.getM24Cnt() != null && this.getM24Cnt().equals(castOther.getM24Cnt())))
				&& ((this.getM36Cnt() == castOther.getM36Cnt()) || (this.getM36Cnt() != null
						&& castOther.getM36Cnt() != null && this.getM36Cnt().equals(castOther.getM36Cnt())))
				&& ((this.getYtdCnt() == castOther.getYtdCnt()) || (this.getYtdCnt() != null
						&& castOther.getYtdCnt() != null && this.getYtdCnt().equals(castOther.getYtdCnt())))
				&& ((this.getQtdCnt() == castOther.getQtdCnt()) || (this.getQtdCnt() != null
						&& castOther.getQtdCnt() != null && this.getQtdCnt().equals(castOther.getQtdCnt())))
				&& ((this.getMtdCnt() == castOther.getMtdCnt()) || (this.getMtdCnt() != null
						&& castOther.getMtdCnt() != null && this.getMtdCnt().equals(castOther.getMtdCnt())))
				&& ((this.getFy1Yield() == castOther.getFy1Yield()) || (this.getFy1Yield() != null
						&& castOther.getFy1Yield() != null && this.getFy1Yield().equals(castOther.getFy1Yield())))
				&& ((this.getFy2Yield() == castOther.getFy2Yield()) || (this.getFy2Yield() != null
						&& castOther.getFy2Yield() != null && this.getFy2Yield().equals(castOther.getFy2Yield())))
				&& ((this.getFy3Yield() == castOther.getFy3Yield()) || (this.getFy3Yield() != null
						&& castOther.getFy3Yield() != null && this.getFy3Yield().equals(castOther.getFy3Yield())))
				&& ((this.getSrcTable() == castOther.getSrcTable()) || (this.getSrcTable() != null
						&& castOther.getSrcTable() != null && this.getSrcTable().equals(castOther.getSrcTable())))
				&& ((this.getUpdateId() == castOther.getUpdateId()) || (this.getUpdateId() != null
						&& castOther.getUpdateId() != null && this.getUpdateId().equals(castOther.getUpdateId())))
				&& ((this.getLastUpdate() == castOther.getLastUpdate())
						|| (this.getLastUpdate() != null && castOther.getLastUpdate() != null
								&& this.getLastUpdate().equals(castOther.getLastUpdate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getCptlDivCd() == null ? 0 : this.getCptlDivCd().hashCode());
		result = 37 * result + (getYieldLclssCd() == null ? 0 : this.getYieldLclssCd().hashCode());
		result = 37 * result + (getYieldDivCd() == null ? 0 : this.getYieldDivCd().hashCode());
		result = 37 * result + (getProdTypeCd() == null ? 0 : this.getProdTypeCd().hashCode());
		result = 37 * result + (getM01Yield() == null ? 0 : this.getM01Yield().hashCode());
		result = 37 * result + (getM03Yield() == null ? 0 : this.getM03Yield().hashCode());
		result = 37 * result + (getM06Yield() == null ? 0 : this.getM06Yield().hashCode());
		result = 37 * result + (getM12Yield() == null ? 0 : this.getM12Yield().hashCode());
		result = 37 * result + (getM24Yield() == null ? 0 : this.getM24Yield().hashCode());
		result = 37 * result + (getM36Yield() == null ? 0 : this.getM36Yield().hashCode());
		result = 37 * result + (getYtdYield() == null ? 0 : this.getYtdYield().hashCode());
		result = 37 * result + (getQtdYield() == null ? 0 : this.getQtdYield().hashCode());
		result = 37 * result + (getMtdYield() == null ? 0 : this.getMtdYield().hashCode());
		result = 37 * result + (getM01Awght() == null ? 0 : this.getM01Awght().hashCode());
		result = 37 * result + (getM03Awght() == null ? 0 : this.getM03Awght().hashCode());
		result = 37 * result + (getM06Awght() == null ? 0 : this.getM06Awght().hashCode());
		result = 37 * result + (getM12Awght() == null ? 0 : this.getM12Awght().hashCode());
		result = 37 * result + (getM24Awght() == null ? 0 : this.getM24Awght().hashCode());
		result = 37 * result + (getM36Awght() == null ? 0 : this.getM36Awght().hashCode());
		result = 37 * result + (getYtdAwght() == null ? 0 : this.getYtdAwght().hashCode());
		result = 37 * result + (getQtdAwght() == null ? 0 : this.getQtdAwght().hashCode());
		result = 37 * result + (getMtdAwght() == null ? 0 : this.getMtdAwght().hashCode());
		result = 37 * result + (getM01Pl() == null ? 0 : this.getM01Pl().hashCode());
		result = 37 * result + (getM03Pl() == null ? 0 : this.getM03Pl().hashCode());
		result = 37 * result + (getM06Pl() == null ? 0 : this.getM06Pl().hashCode());
		result = 37 * result + (getM12Pl() == null ? 0 : this.getM12Pl().hashCode());
		result = 37 * result + (getM24Pl() == null ? 0 : this.getM24Pl().hashCode());
		result = 37 * result + (getM36Pl() == null ? 0 : this.getM36Pl().hashCode());
		result = 37 * result + (getYtdPl() == null ? 0 : this.getYtdPl().hashCode());
		result = 37 * result + (getQtdPl() == null ? 0 : this.getQtdPl().hashCode());
		result = 37 * result + (getMtdPl() == null ? 0 : this.getMtdPl().hashCode());
		result = 37 * result + (getM01Cnt() == null ? 0 : this.getM01Cnt().hashCode());
		result = 37 * result + (getM03Cnt() == null ? 0 : this.getM03Cnt().hashCode());
		result = 37 * result + (getM06Cnt() == null ? 0 : this.getM06Cnt().hashCode());
		result = 37 * result + (getM12Cnt() == null ? 0 : this.getM12Cnt().hashCode());
		result = 37 * result + (getM24Cnt() == null ? 0 : this.getM24Cnt().hashCode());
		result = 37 * result + (getM36Cnt() == null ? 0 : this.getM36Cnt().hashCode());
		result = 37 * result + (getYtdCnt() == null ? 0 : this.getYtdCnt().hashCode());
		result = 37 * result + (getQtdCnt() == null ? 0 : this.getQtdCnt().hashCode());
		result = 37 * result + (getMtdCnt() == null ? 0 : this.getMtdCnt().hashCode());
		result = 37 * result + (getFy1Yield() == null ? 0 : this.getFy1Yield().hashCode());
		result = 37 * result + (getFy2Yield() == null ? 0 : this.getFy2Yield().hashCode());
		result = 37 * result + (getFy3Yield() == null ? 0 : this.getFy3Yield().hashCode());
		result = 37 * result + (getSrcTable() == null ? 0 : this.getSrcTable().hashCode());
		result = 37 * result + (getUpdateId() == null ? 0 : this.getUpdateId().hashCode());
		result = 37 * result + (getLastUpdate() == null ? 0 : this.getLastUpdate().hashCode());
		return result;
	}

}
