package com.eugenefe.ncm;
// Generated Dec 8, 2016 3:49:34 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

/**
 * NcmLv1CashId generated by hbm2java
 */

public class NcmLv1CashId implements java.io.Serializable, Navigatable {

	private String baseDate;
	private String cashCd;

	public NcmLv1CashId() {
	}

	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;

	}

	public String getCashCd() {
		return this.cashCd;
	}

	public void setCashCd(String cashCd) {
		this.cashCd = cashCd;

	}

	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getCashCd());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmLv1CashId))
			return false;
		NcmLv1CashId castOther = (NcmLv1CashId) other;

		return ((this.getBaseDate() == castOther.getBaseDate())
				|| (this.getBaseDate() != null && castOther.getBaseDate() != null && this.getBaseDate().equals(castOther.getBaseDate())))
				&& ((this.getCashCd() == castOther.getCashCd()) || (this.getCashCd() != null && castOther.getCashCd() != null && this.getCashCd().equals(castOther.getCashCd())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getCashCd() == null ? 0 : this.getCashCd().hashCode());
		return result;
	}

}
