package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv2RiskAdj generated by hbm2java
 */
@Entity
@Table(name = "NCM_LV2_RISK_ADJ", schema = "NCM")
public class NcmLv2RiskAdj implements java.io.Serializable {

	private NcmLv2RiskAdjId id;
	private BigDecimal avgYield;
	private BigDecimal bmAvgYield;
	private BigDecimal rfAvgYield;
	private BigDecimal stdev;
	private BigDecimal bmStdev;
	private BigDecimal sharpe;
	private BigDecimal bmSharpe;
	private BigDecimal semiStdev;
	private BigDecimal bmSemiStdev;
	private BigDecimal sortino;
	private BigDecimal bmSortino;
	private BigDecimal te;
	private BigDecimal ir;
	private Integer yieldCnt;
	private Integer bmCnt;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv2RiskAdj() {
	}

	public NcmLv2RiskAdj(NcmLv2RiskAdjId id) {
		this.id = id;
	}

	public NcmLv2RiskAdj(NcmLv2RiskAdjId id, BigDecimal avgYield, BigDecimal bmAvgYield, BigDecimal rfAvgYield,
			BigDecimal stdev, BigDecimal bmStdev, BigDecimal sharpe, BigDecimal bmSharpe, BigDecimal semiStdev,
			BigDecimal bmSemiStdev, BigDecimal sortino, BigDecimal bmSortino, BigDecimal te, BigDecimal ir,
			Integer yieldCnt, Integer bmCnt, String srcTable, String updateId, Date lastUpdate) {
		this.id = id;
		this.avgYield = avgYield;
		this.bmAvgYield = bmAvgYield;
		this.rfAvgYield = rfAvgYield;
		this.stdev = stdev;
		this.bmStdev = bmStdev;
		this.sharpe = sharpe;
		this.bmSharpe = bmSharpe;
		this.semiStdev = semiStdev;
		this.bmSemiStdev = bmSemiStdev;
		this.sortino = sortino;
		this.bmSortino = bmSortino;
		this.te = te;
		this.ir = ir;
		this.yieldCnt = yieldCnt;
		this.bmCnt = bmCnt;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "cptlDivCd", column = @Column(name = "CPTL_DIV_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "yieldLclssCd", column = @Column(name = "YIELD_LCLSS_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "yieldDivCd", column = @Column(name = "YIELD_DIV_CD", nullable = false, length = 20)),
			@AttributeOverride(name = "prodTypeCd", column = @Column(name = "PROD_TYPE_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "matCd", column = @Column(name = "MAT_CD", nullable = false, length = 10)) })
	public NcmLv2RiskAdjId getId() {
		return this.id;
	}

	public void setId(NcmLv2RiskAdjId id) {
		this.id = id;
	}

	@Column(name = "AVG_YIELD", precision = 22, scale = 8)
	public BigDecimal getAvgYield() {
		return this.avgYield;
	}

	public void setAvgYield(BigDecimal avgYield) {
		this.avgYield = avgYield;
	}

	@Column(name = "BM_AVG_YIELD", precision = 22, scale = 8)
	public BigDecimal getBmAvgYield() {
		return this.bmAvgYield;
	}

	public void setBmAvgYield(BigDecimal bmAvgYield) {
		this.bmAvgYield = bmAvgYield;
	}

	@Column(name = "RF_AVG_YIELD", precision = 22, scale = 8)
	public BigDecimal getRfAvgYield() {
		return this.rfAvgYield;
	}

	public void setRfAvgYield(BigDecimal rfAvgYield) {
		this.rfAvgYield = rfAvgYield;
	}

	@Column(name = "STDEV", precision = 22, scale = 8)
	public BigDecimal getStdev() {
		return this.stdev;
	}

	public void setStdev(BigDecimal stdev) {
		this.stdev = stdev;
	}

	@Column(name = "BM_STDEV", precision = 22, scale = 8)
	public BigDecimal getBmStdev() {
		return this.bmStdev;
	}

	public void setBmStdev(BigDecimal bmStdev) {
		this.bmStdev = bmStdev;
	}

	@Column(name = "SHARPE", precision = 22, scale = 8)
	public BigDecimal getSharpe() {
		return this.sharpe;
	}

	public void setSharpe(BigDecimal sharpe) {
		this.sharpe = sharpe;
	}

	@Column(name = "BM_SHARPE", precision = 22, scale = 8)
	public BigDecimal getBmSharpe() {
		return this.bmSharpe;
	}

	public void setBmSharpe(BigDecimal bmSharpe) {
		this.bmSharpe = bmSharpe;
	}

	@Column(name = "SEMI_STDEV", precision = 22, scale = 8)
	public BigDecimal getSemiStdev() {
		return this.semiStdev;
	}

	public void setSemiStdev(BigDecimal semiStdev) {
		this.semiStdev = semiStdev;
	}

	@Column(name = "BM_SEMI_STDEV", precision = 22, scale = 8)
	public BigDecimal getBmSemiStdev() {
		return this.bmSemiStdev;
	}

	public void setBmSemiStdev(BigDecimal bmSemiStdev) {
		this.bmSemiStdev = bmSemiStdev;
	}

	@Column(name = "SORTINO", precision = 22, scale = 8)
	public BigDecimal getSortino() {
		return this.sortino;
	}

	public void setSortino(BigDecimal sortino) {
		this.sortino = sortino;
	}

	@Column(name = "BM_SORTINO", precision = 22, scale = 8)
	public BigDecimal getBmSortino() {
		return this.bmSortino;
	}

	public void setBmSortino(BigDecimal bmSortino) {
		this.bmSortino = bmSortino;
	}

	@Column(name = "TE", precision = 22, scale = 8)
	public BigDecimal getTe() {
		return this.te;
	}

	public void setTe(BigDecimal te) {
		this.te = te;
	}

	@Column(name = "IR", precision = 22, scale = 8)
	public BigDecimal getIr() {
		return this.ir;
	}

	public void setIr(BigDecimal ir) {
		this.ir = ir;
	}

	@Column(name = "YIELD_CNT", precision = 5, scale = 0)
	public Integer getYieldCnt() {
		return this.yieldCnt;
	}

	public void setYieldCnt(Integer yieldCnt) {
		this.yieldCnt = yieldCnt;
	}

	@Column(name = "BM_CNT", precision = 5, scale = 0)
	public Integer getBmCnt() {
		return this.bmCnt;
	}

	public void setBmCnt(Integer bmCnt) {
		this.bmCnt = bmCnt;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
