package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv2ComplRst generated by hbm2java
 */

@Entity
@IdClass(value = NcmLv2ComplRstId.class)
@Table(name = "NCM_LV2_COMPL_RST", schema = "NCM")
public class NcmLv2ComplRst implements java.io.Serializable {

	private String baseDate;
	private String applyDivCd;
	private String applyCd;
	private String complTypeCd;
	private short seq;
	private String complApplyNm;
	private BigDecimal applyAmt;
	private BigDecimal lmtMinAmt;
	private BigDecimal lmtMaxAmt;
	private BigDecimal torlError;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv2ComplRst() {
	}

	@Id
	@Column(name = "BASE_DATE", nullable = false, length = 8)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Id
	@Column(name = "APPLY_DIV_CD", nullable = false, length = 20)
	public String getApplyDivCd() {
		return this.applyDivCd;
	}

	public void setApplyDivCd(String applyDivCd) {
		this.applyDivCd = applyDivCd;
	}

	@Id
	@Column(name = "APPLY_CD", nullable = false, length = 20)
	public String getApplyCd() {
		return this.applyCd;
	}

	public void setApplyCd(String applyCd) {
		this.applyCd = applyCd;
	}

	@Id
	@Column(name = "COMPL_TYPE_CD", nullable = false, length = 20)
	public String getComplTypeCd() {
		return this.complTypeCd;
	}

	public void setComplTypeCd(String complTypeCd) {
		this.complTypeCd = complTypeCd;
	}

	@Id
	@Column(name = "SEQ", nullable = false, precision = 4, scale = 0)
	public short getSeq() {
		return this.seq;
	}

	public void setSeq(short seq) {
		this.seq = seq;
	}

	@Column(name = "COMPL_APPLY_NM", length = 100)
	public String getComplApplyNm() {
		return this.complApplyNm;
	}

	public void setComplApplyNm(String complApplyNm) {
		this.complApplyNm = complApplyNm;

	}

	@Column(name = "APPLY_AMT", precision = 20, scale = 4)
	public BigDecimal getApplyAmt() {
		return this.applyAmt;
	}

	public void setApplyAmt(BigDecimal applyAmt) {
		this.applyAmt = applyAmt;

	}

	@Column(name = "LMT_MIN_AMT", nullable = false, precision = 20, scale = 4)
	public BigDecimal getLmtMinAmt() {
		return this.lmtMinAmt;
	}

	public void setLmtMinAmt(BigDecimal lmtMinAmt) {
		this.lmtMinAmt = lmtMinAmt;

	}

	@Column(name = "LMT_MAX_AMT", nullable = false, precision = 20, scale = 4)
	public BigDecimal getLmtMaxAmt() {
		return this.lmtMaxAmt;
	}

	public void setLmtMaxAmt(BigDecimal lmtMaxAmt) {
		this.lmtMaxAmt = lmtMaxAmt;

	}

	@Column(name = "TORL_ERROR", precision = 20, scale = 4)
	public BigDecimal getTorlError() {
		return this.torlError;
	}

	public void setTorlError(BigDecimal torlError) {
		this.torlError = torlError;

	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getApplyDivCd());
		buffer.append("#").append(getApplyCd());
		buffer.append("#").append(getComplTypeCd());
		buffer.append("#").append(getSeq());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmLv2ComplRst))
			return false;
		NcmLv2ComplRst castOther = (NcmLv2ComplRst) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getApplyDivCd() == null ? 0 : this.getApplyDivCd().hashCode());
		result = 37 * result + (getApplyCd() == null ? 0 : this.getApplyCd().hashCode());
		result = 37 * result + (getComplTypeCd() == null ? 0 : this.getComplTypeCd().hashCode());
		result = 37 * result + this.getSeq();
		return result;
	}

}
