package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv1Cash generated by hbm2java
 */
@Entity
@Table(name = "NCM_LV1_CASH", schema = "NCM")
public class NcmLv1Cash implements java.io.Serializable {

	private NcmLv1CashId id;
	private BigDecimal todayInflowAmt;
	private BigDecimal todayOutflowAmt;
	private BigDecimal monBal;
	private BigDecimal accuBal;
	private BigDecimal continuBal;
	private BigDecimal bdayAccuBal;
	private BigDecimal bdayContinuBal;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv1Cash() {
	}

	public NcmLv1Cash(NcmLv1CashId id) {
		this.id = id;
	}

	public NcmLv1Cash(NcmLv1CashId id, BigDecimal todayInflowAmt, BigDecimal todayOutflowAmt, BigDecimal monBal,
			BigDecimal accuBal, BigDecimal continuBal, BigDecimal bdayAccuBal, BigDecimal bdayContinuBal,
			String srcTable, String updateId, Date lastUpdate) {
		this.id = id;
		this.todayInflowAmt = todayInflowAmt;
		this.todayOutflowAmt = todayOutflowAmt;
		this.monBal = monBal;
		this.accuBal = accuBal;
		this.continuBal = continuBal;
		this.bdayAccuBal = bdayAccuBal;
		this.bdayContinuBal = bdayContinuBal;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "cashCd", column = @Column(name = "CASH_CD", nullable = false, length = 20)) })
	public NcmLv1CashId getId() {
		return this.id;
	}

	public void setId(NcmLv1CashId id) {
		this.id = id;
	}

	@Column(name = "TODAY_INFLOW_AMT", precision = 20)
	public BigDecimal getTodayInflowAmt() {
		return this.todayInflowAmt;
	}

	public void setTodayInflowAmt(BigDecimal todayInflowAmt) {
		this.todayInflowAmt = todayInflowAmt;
	}

	@Column(name = "TODAY_OUTFLOW_AMT", precision = 20)
	public BigDecimal getTodayOutflowAmt() {
		return this.todayOutflowAmt;
	}

	public void setTodayOutflowAmt(BigDecimal todayOutflowAmt) {
		this.todayOutflowAmt = todayOutflowAmt;
	}

	@Column(name = "MON_BAL", precision = 20)
	public BigDecimal getMonBal() {
		return this.monBal;
	}

	public void setMonBal(BigDecimal monBal) {
		this.monBal = monBal;
	}

	@Column(name = "ACCU_BAL", precision = 20)
	public BigDecimal getAccuBal() {
		return this.accuBal;
	}

	public void setAccuBal(BigDecimal accuBal) {
		this.accuBal = accuBal;
	}

	@Column(name = "CONTINU_BAL", precision = 20)
	public BigDecimal getContinuBal() {
		return this.continuBal;
	}

	public void setContinuBal(BigDecimal continuBal) {
		this.continuBal = continuBal;
	}

	@Column(name = "BDAY_ACCU_BAL", precision = 20)
	public BigDecimal getBdayAccuBal() {
		return this.bdayAccuBal;
	}

	public void setBdayAccuBal(BigDecimal bdayAccuBal) {
		this.bdayAccuBal = bdayAccuBal;
	}

	@Column(name = "BDAY_CONTINU_BAL", precision = 20)
	public BigDecimal getBdayContinuBal() {
		return this.bdayContinuBal;
	}

	public void setBdayContinuBal(BigDecimal bdayContinuBal) {
		this.bdayContinuBal = bdayContinuBal;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
