package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmLv1ProductStg generated by hbm2java
 */
@Entity
@Table(name = "NCM_LV1_PRODUCT_STG", schema = "NCM")
public class NcmLv1ProductStg implements java.io.Serializable {

	private NcmLv1ProductStgId id;

	public NcmLv1ProductStg() {
	}

	public NcmLv1ProductStg(NcmLv1ProductStgId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "finProdId", column = @Column(name = "FIN_PROD_ID", nullable = false, length = 50)),
			@AttributeOverride(name = "finProdNm", column = @Column(name = "FIN_PROD_NM", length = 100)),
			@AttributeOverride(name = "termTypeCd", column = @Column(name = "TERM_TYPE_CD", length = 20)),
			@AttributeOverride(name = "prodTypeCd", column = @Column(name = "PROD_TYPE_CD", length = 10)),
			@AttributeOverride(name = "prodTypeNm", column = @Column(name = "PROD_TYPE_NM", length = 100)),
			@AttributeOverride(name = "issuCorpNo", column = @Column(name = "ISSU_CORP_NO", length = 20)),
			@AttributeOverride(name = "issuerNm", column = @Column(name = "ISSUER_NM", length = 100)),
			@AttributeOverride(name = "issuAmt", column = @Column(name = "ISSU_AMT", precision = 20)),
			@AttributeOverride(name = "issuDate", column = @Column(name = "ISSU_DATE", length = 8)),
			@AttributeOverride(name = "matDate", column = @Column(name = "MAT_DATE", length = 8)),
			@AttributeOverride(name = "intRate", column = @Column(name = "INT_RATE", precision = 12, scale = 8)),
			@AttributeOverride(name = "srcTable", column = @Column(name = "SRC_TABLE", length = 20)),
			@AttributeOverride(name = "updateId", column = @Column(name = "UPDATE_ID", length = 20)),
			@AttributeOverride(name = "lastUpdate", column = @Column(name = "LAST_UPDATE", length = 7)) })
	public NcmLv1ProductStgId getId() {
		return this.id;
	}

	public void setId(NcmLv1ProductStgId id) {
		this.id = id;
	}

}
