package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmLv1MmtDetailBack generated by hbm2java
 */
@Entity
@Table(name = "NCM_LV1_MMT_DETAIL_BACK", schema = "NCM")
public class NcmLv1MmtDetailBack implements java.io.Serializable {

	private NcmLv1MmtDetailBackId id;

	public NcmLv1MmtDetailBack() {
	}

	public NcmLv1MmtDetailBack(NcmLv1MmtDetailBackId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "mmtProdId", column = @Column(name = "MMT_PROD_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "mmtChgProdId", column = @Column(name = "MMT_CHG_PROD_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "srcTable", column = @Column(name = "SRC_TABLE", length = 20)),
			@AttributeOverride(name = "updateId", column = @Column(name = "UPDATE_ID", length = 20)),
			@AttributeOverride(name = "lastUpdate", column = @Column(name = "LAST_UPDATE", length = 7)) })
	public NcmLv1MmtDetailBackId getId() {
		return this.id;
	}

	public void setId(NcmLv1MmtDetailBackId id) {
		this.id = id;
	}

}
