package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NcmLv1SubPositionId generated by hbm2java
 */
@Embeddable
public class NcmLv1SubPositionId implements java.io.Serializable {

	private String baseDate;
	private String posId;
	private String finProdId;
	private String mngOrgCorpNo;
	private String hldProdId;

	public NcmLv1SubPositionId() {
	}

	public NcmLv1SubPositionId(String baseDate, String posId, String finProdId, String mngOrgCorpNo, String hldProdId) {
		this.baseDate = baseDate;
		this.posId = posId;
		this.finProdId = finProdId;
		this.mngOrgCorpNo = mngOrgCorpNo;
		this.hldProdId = hldProdId;
	}

	@Column(name = "BASE_DATE", nullable = false, length = 8)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Column(name = "POS_ID", nullable = false, length = 100)
	public String getPosId() {
		return this.posId;
	}

	public void setPosId(String posId) {
		this.posId = posId;
	}

	@Column(name = "FIN_PROD_ID", nullable = false, length = 50)
	public String getFinProdId() {
		return this.finProdId;
	}

	public void setFinProdId(String finProdId) {
		this.finProdId = finProdId;
	}

	@Column(name = "MNG_ORG_CORP_NO", nullable = false, length = 20)
	public String getMngOrgCorpNo() {
		return this.mngOrgCorpNo;
	}

	public void setMngOrgCorpNo(String mngOrgCorpNo) {
		this.mngOrgCorpNo = mngOrgCorpNo;
	}

	@Column(name = "HLD_PROD_ID", nullable = false, length = 20)
	public String getHldProdId() {
		return this.hldProdId;
	}

	public void setHldProdId(String hldProdId) {
		this.hldProdId = hldProdId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmLv1SubPositionId))
			return false;
		NcmLv1SubPositionId castOther = (NcmLv1SubPositionId) other;

		return ((this.getBaseDate() == castOther.getBaseDate()) || (this.getBaseDate() != null
				&& castOther.getBaseDate() != null && this.getBaseDate().equals(castOther.getBaseDate())))
				&& ((this.getPosId() == castOther.getPosId()) || (this.getPosId() != null
						&& castOther.getPosId() != null && this.getPosId().equals(castOther.getPosId())))
				&& ((this.getFinProdId() == castOther.getFinProdId()) || (this.getFinProdId() != null
						&& castOther.getFinProdId() != null && this.getFinProdId().equals(castOther.getFinProdId())))
				&& ((this.getMngOrgCorpNo() == castOther.getMngOrgCorpNo())
						|| (this.getMngOrgCorpNo() != null && castOther.getMngOrgCorpNo() != null
								&& this.getMngOrgCorpNo().equals(castOther.getMngOrgCorpNo())))
				&& ((this.getHldProdId() == castOther.getHldProdId()) || (this.getHldProdId() != null
						&& castOther.getHldProdId() != null && this.getHldProdId().equals(castOther.getHldProdId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getPosId() == null ? 0 : this.getPosId().hashCode());
		result = 37 * result + (getFinProdId() == null ? 0 : this.getFinProdId().hashCode());
		result = 37 * result + (getMngOrgCorpNo() == null ? 0 : this.getMngOrgCorpNo().hashCode());
		result = 37 * result + (getHldProdId() == null ? 0 : this.getHldProdId().hashCode());
		return result;
	}

}
