package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NcmLv2PortAmt20161018Id generated by hbm2java
 */
@Embeddable
public class NcmLv2PortAmt20161018Id implements java.io.Serializable {

	private String baseDate;
	private String cptlDivCd;
	private String yieldLclssCd;
	private String yieldDivCd;
	private String prodTypeCd;
	private BigDecimal hldAmt;
	private BigDecimal bookAmt;
	private BigDecimal mktEvalAmt;
	private BigDecimal bdayEvalAmt;
	private BigDecimal intInflowAmt;
	private BigDecimal accumRealPl;
	private BigDecimal evalPl;
	private BigDecimal evalPlInc;
	private BigDecimal todayBuyAmt;
	private BigDecimal todaySellAmt;
	private BigDecimal dbaseEvalAmt;
	private BigDecimal nbaseEvalAmt;
	private BigDecimal hldAmtWght;
	private BigDecimal mktEvalWght;
	private BigDecimal todayTwghtYield;
	private BigDecimal accumTwghtYield;
	private BigDecimal accumEvalAmt;
	private BigDecimal accumHldWght;
	private BigDecimal accumEvalWght;
	private BigDecimal hldCnt;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv2PortAmt20161018Id() {
	}

	public NcmLv2PortAmt20161018Id(String baseDate, String cptlDivCd, String yieldLclssCd, String yieldDivCd,
			String prodTypeCd) {
		this.baseDate = baseDate;
		this.cptlDivCd = cptlDivCd;
		this.yieldLclssCd = yieldLclssCd;
		this.yieldDivCd = yieldDivCd;
		this.prodTypeCd = prodTypeCd;
	}

	public NcmLv2PortAmt20161018Id(String baseDate, String cptlDivCd, String yieldLclssCd, String yieldDivCd,
			String prodTypeCd, BigDecimal hldAmt, BigDecimal bookAmt, BigDecimal mktEvalAmt, BigDecimal bdayEvalAmt,
			BigDecimal intInflowAmt, BigDecimal accumRealPl, BigDecimal evalPl, BigDecimal evalPlInc,
			BigDecimal todayBuyAmt, BigDecimal todaySellAmt, BigDecimal dbaseEvalAmt, BigDecimal nbaseEvalAmt,
			BigDecimal hldAmtWght, BigDecimal mktEvalWght, BigDecimal todayTwghtYield, BigDecimal accumTwghtYield,
			BigDecimal accumEvalAmt, BigDecimal accumHldWght, BigDecimal accumEvalWght, BigDecimal hldCnt,
			String srcTable, String updateId, Date lastUpdate) {
		this.baseDate = baseDate;
		this.cptlDivCd = cptlDivCd;
		this.yieldLclssCd = yieldLclssCd;
		this.yieldDivCd = yieldDivCd;
		this.prodTypeCd = prodTypeCd;
		this.hldAmt = hldAmt;
		this.bookAmt = bookAmt;
		this.mktEvalAmt = mktEvalAmt;
		this.bdayEvalAmt = bdayEvalAmt;
		this.intInflowAmt = intInflowAmt;
		this.accumRealPl = accumRealPl;
		this.evalPl = evalPl;
		this.evalPlInc = evalPlInc;
		this.todayBuyAmt = todayBuyAmt;
		this.todaySellAmt = todaySellAmt;
		this.dbaseEvalAmt = dbaseEvalAmt;
		this.nbaseEvalAmt = nbaseEvalAmt;
		this.hldAmtWght = hldAmtWght;
		this.mktEvalWght = mktEvalWght;
		this.todayTwghtYield = todayTwghtYield;
		this.accumTwghtYield = accumTwghtYield;
		this.accumEvalAmt = accumEvalAmt;
		this.accumHldWght = accumHldWght;
		this.accumEvalWght = accumEvalWght;
		this.hldCnt = hldCnt;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "BASE_DATE", nullable = false, length = 8)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Column(name = "CPTL_DIV_CD", nullable = false, length = 10)
	public String getCptlDivCd() {
		return this.cptlDivCd;
	}

	public void setCptlDivCd(String cptlDivCd) {
		this.cptlDivCd = cptlDivCd;
	}

	@Column(name = "YIELD_LCLSS_CD", nullable = false, length = 10)
	public String getYieldLclssCd() {
		return this.yieldLclssCd;
	}

	public void setYieldLclssCd(String yieldLclssCd) {
		this.yieldLclssCd = yieldLclssCd;
	}

	@Column(name = "YIELD_DIV_CD", nullable = false, length = 20)
	public String getYieldDivCd() {
		return this.yieldDivCd;
	}

	public void setYieldDivCd(String yieldDivCd) {
		this.yieldDivCd = yieldDivCd;
	}

	@Column(name = "PROD_TYPE_CD", nullable = false, length = 10)
	public String getProdTypeCd() {
		return this.prodTypeCd;
	}

	public void setProdTypeCd(String prodTypeCd) {
		this.prodTypeCd = prodTypeCd;
	}

	@Column(name = "HLD_AMT", precision = 22, scale = 0)
	public BigDecimal getHldAmt() {
		return this.hldAmt;
	}

	public void setHldAmt(BigDecimal hldAmt) {
		this.hldAmt = hldAmt;
	}

	@Column(name = "BOOK_AMT", precision = 22, scale = 0)
	public BigDecimal getBookAmt() {
		return this.bookAmt;
	}

	public void setBookAmt(BigDecimal bookAmt) {
		this.bookAmt = bookAmt;
	}

	@Column(name = "MKT_EVAL_AMT", precision = 22, scale = 0)
	public BigDecimal getMktEvalAmt() {
		return this.mktEvalAmt;
	}

	public void setMktEvalAmt(BigDecimal mktEvalAmt) {
		this.mktEvalAmt = mktEvalAmt;
	}

	@Column(name = "BDAY_EVAL_AMT", precision = 22, scale = 0)
	public BigDecimal getBdayEvalAmt() {
		return this.bdayEvalAmt;
	}

	public void setBdayEvalAmt(BigDecimal bdayEvalAmt) {
		this.bdayEvalAmt = bdayEvalAmt;
	}

	@Column(name = "INT_INFLOW_AMT", precision = 22, scale = 0)
	public BigDecimal getIntInflowAmt() {
		return this.intInflowAmt;
	}

	public void setIntInflowAmt(BigDecimal intInflowAmt) {
		this.intInflowAmt = intInflowAmt;
	}

	@Column(name = "ACCUM_REAL_PL", precision = 22, scale = 0)
	public BigDecimal getAccumRealPl() {
		return this.accumRealPl;
	}

	public void setAccumRealPl(BigDecimal accumRealPl) {
		this.accumRealPl = accumRealPl;
	}

	@Column(name = "EVAL_PL", precision = 22, scale = 0)
	public BigDecimal getEvalPl() {
		return this.evalPl;
	}

	public void setEvalPl(BigDecimal evalPl) {
		this.evalPl = evalPl;
	}

	@Column(name = "EVAL_PL_INC", precision = 22, scale = 0)
	public BigDecimal getEvalPlInc() {
		return this.evalPlInc;
	}

	public void setEvalPlInc(BigDecimal evalPlInc) {
		this.evalPlInc = evalPlInc;
	}

	@Column(name = "TODAY_BUY_AMT", precision = 22, scale = 0)
	public BigDecimal getTodayBuyAmt() {
		return this.todayBuyAmt;
	}

	public void setTodayBuyAmt(BigDecimal todayBuyAmt) {
		this.todayBuyAmt = todayBuyAmt;
	}

	@Column(name = "TODAY_SELL_AMT", precision = 22, scale = 0)
	public BigDecimal getTodaySellAmt() {
		return this.todaySellAmt;
	}

	public void setTodaySellAmt(BigDecimal todaySellAmt) {
		this.todaySellAmt = todaySellAmt;
	}

	@Column(name = "DBASE_EVAL_AMT", precision = 22, scale = 0)
	public BigDecimal getDbaseEvalAmt() {
		return this.dbaseEvalAmt;
	}

	public void setDbaseEvalAmt(BigDecimal dbaseEvalAmt) {
		this.dbaseEvalAmt = dbaseEvalAmt;
	}

	@Column(name = "NBASE_EVAL_AMT", precision = 22, scale = 0)
	public BigDecimal getNbaseEvalAmt() {
		return this.nbaseEvalAmt;
	}

	public void setNbaseEvalAmt(BigDecimal nbaseEvalAmt) {
		this.nbaseEvalAmt = nbaseEvalAmt;
	}

	@Column(name = "HLD_AMT_WGHT", precision = 12, scale = 8)
	public BigDecimal getHldAmtWght() {
		return this.hldAmtWght;
	}

	public void setHldAmtWght(BigDecimal hldAmtWght) {
		this.hldAmtWght = hldAmtWght;
	}

	@Column(name = "MKT_EVAL_WGHT", precision = 12, scale = 8)
	public BigDecimal getMktEvalWght() {
		return this.mktEvalWght;
	}

	public void setMktEvalWght(BigDecimal mktEvalWght) {
		this.mktEvalWght = mktEvalWght;
	}

	@Column(name = "TODAY_TWGHT_YIELD", precision = 12, scale = 8)
	public BigDecimal getTodayTwghtYield() {
		return this.todayTwghtYield;
	}

	public void setTodayTwghtYield(BigDecimal todayTwghtYield) {
		this.todayTwghtYield = todayTwghtYield;
	}

	@Column(name = "ACCUM_TWGHT_YIELD", precision = 12, scale = 8)
	public BigDecimal getAccumTwghtYield() {
		return this.accumTwghtYield;
	}

	public void setAccumTwghtYield(BigDecimal accumTwghtYield) {
		this.accumTwghtYield = accumTwghtYield;
	}

	@Column(name = "ACCUM_EVAL_AMT", precision = 22, scale = 0)
	public BigDecimal getAccumEvalAmt() {
		return this.accumEvalAmt;
	}

	public void setAccumEvalAmt(BigDecimal accumEvalAmt) {
		this.accumEvalAmt = accumEvalAmt;
	}

	@Column(name = "ACCUM_HLD_WGHT", precision = 12, scale = 8)
	public BigDecimal getAccumHldWght() {
		return this.accumHldWght;
	}

	public void setAccumHldWght(BigDecimal accumHldWght) {
		this.accumHldWght = accumHldWght;
	}

	@Column(name = "ACCUM_EVAL_WGHT", precision = 12, scale = 8)
	public BigDecimal getAccumEvalWght() {
		return this.accumEvalWght;
	}

	public void setAccumEvalWght(BigDecimal accumEvalWght) {
		this.accumEvalWght = accumEvalWght;
	}

	@Column(name = "HLD_CNT", precision = 22, scale = 0)
	public BigDecimal getHldCnt() {
		return this.hldCnt;
	}

	public void setHldCnt(BigDecimal hldCnt) {
		this.hldCnt = hldCnt;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmLv2PortAmt20161018Id))
			return false;
		NcmLv2PortAmt20161018Id castOther = (NcmLv2PortAmt20161018Id) other;

		return ((this.getBaseDate() == castOther.getBaseDate()) || (this.getBaseDate() != null
				&& castOther.getBaseDate() != null && this.getBaseDate().equals(castOther.getBaseDate())))
				&& ((this.getCptlDivCd() == castOther.getCptlDivCd()) || (this.getCptlDivCd() != null
						&& castOther.getCptlDivCd() != null && this.getCptlDivCd().equals(castOther.getCptlDivCd())))
				&& ((this.getYieldLclssCd() == castOther.getYieldLclssCd())
						|| (this.getYieldLclssCd() != null && castOther.getYieldLclssCd() != null
								&& this.getYieldLclssCd().equals(castOther.getYieldLclssCd())))
				&& ((this.getYieldDivCd() == castOther.getYieldDivCd()) || (this.getYieldDivCd() != null
						&& castOther.getYieldDivCd() != null && this.getYieldDivCd().equals(castOther.getYieldDivCd())))
				&& ((this.getProdTypeCd() == castOther.getProdTypeCd()) || (this.getProdTypeCd() != null
						&& castOther.getProdTypeCd() != null && this.getProdTypeCd().equals(castOther.getProdTypeCd())))
				&& ((this.getHldAmt() == castOther.getHldAmt()) || (this.getHldAmt() != null
						&& castOther.getHldAmt() != null && this.getHldAmt().equals(castOther.getHldAmt())))
				&& ((this.getBookAmt() == castOther.getBookAmt()) || (this.getBookAmt() != null
						&& castOther.getBookAmt() != null && this.getBookAmt().equals(castOther.getBookAmt())))
				&& ((this.getMktEvalAmt() == castOther.getMktEvalAmt()) || (this.getMktEvalAmt() != null
						&& castOther.getMktEvalAmt() != null && this.getMktEvalAmt().equals(castOther.getMktEvalAmt())))
				&& ((this.getBdayEvalAmt() == castOther.getBdayEvalAmt())
						|| (this.getBdayEvalAmt() != null && castOther.getBdayEvalAmt() != null
								&& this.getBdayEvalAmt().equals(castOther.getBdayEvalAmt())))
				&& ((this.getIntInflowAmt() == castOther.getIntInflowAmt())
						|| (this.getIntInflowAmt() != null && castOther.getIntInflowAmt() != null
								&& this.getIntInflowAmt().equals(castOther.getIntInflowAmt())))
				&& ((this.getAccumRealPl() == castOther.getAccumRealPl())
						|| (this.getAccumRealPl() != null && castOther.getAccumRealPl() != null
								&& this.getAccumRealPl().equals(castOther.getAccumRealPl())))
				&& ((this.getEvalPl() == castOther.getEvalPl()) || (this.getEvalPl() != null
						&& castOther.getEvalPl() != null && this.getEvalPl().equals(castOther.getEvalPl())))
				&& ((this.getEvalPlInc() == castOther.getEvalPlInc()) || (this.getEvalPlInc() != null
						&& castOther.getEvalPlInc() != null && this.getEvalPlInc().equals(castOther.getEvalPlInc())))
				&& ((this.getTodayBuyAmt() == castOther.getTodayBuyAmt())
						|| (this.getTodayBuyAmt() != null && castOther.getTodayBuyAmt() != null
								&& this.getTodayBuyAmt().equals(castOther.getTodayBuyAmt())))
				&& ((this.getTodaySellAmt() == castOther.getTodaySellAmt())
						|| (this.getTodaySellAmt() != null && castOther.getTodaySellAmt() != null
								&& this.getTodaySellAmt().equals(castOther.getTodaySellAmt())))
				&& ((this.getDbaseEvalAmt() == castOther.getDbaseEvalAmt())
						|| (this.getDbaseEvalAmt() != null && castOther.getDbaseEvalAmt() != null
								&& this.getDbaseEvalAmt().equals(castOther.getDbaseEvalAmt())))
				&& ((this.getNbaseEvalAmt() == castOther.getNbaseEvalAmt())
						|| (this.getNbaseEvalAmt() != null && castOther.getNbaseEvalAmt() != null
								&& this.getNbaseEvalAmt().equals(castOther.getNbaseEvalAmt())))
				&& ((this.getHldAmtWght() == castOther.getHldAmtWght()) || (this.getHldAmtWght() != null
						&& castOther.getHldAmtWght() != null && this.getHldAmtWght().equals(castOther.getHldAmtWght())))
				&& ((this.getMktEvalWght() == castOther.getMktEvalWght())
						|| (this.getMktEvalWght() != null && castOther.getMktEvalWght() != null
								&& this.getMktEvalWght().equals(castOther.getMktEvalWght())))
				&& ((this.getTodayTwghtYield() == castOther.getTodayTwghtYield())
						|| (this.getTodayTwghtYield() != null && castOther.getTodayTwghtYield() != null
								&& this.getTodayTwghtYield().equals(castOther.getTodayTwghtYield())))
				&& ((this.getAccumTwghtYield() == castOther.getAccumTwghtYield())
						|| (this.getAccumTwghtYield() != null && castOther.getAccumTwghtYield() != null
								&& this.getAccumTwghtYield().equals(castOther.getAccumTwghtYield())))
				&& ((this.getAccumEvalAmt() == castOther.getAccumEvalAmt())
						|| (this.getAccumEvalAmt() != null && castOther.getAccumEvalAmt() != null
								&& this.getAccumEvalAmt().equals(castOther.getAccumEvalAmt())))
				&& ((this.getAccumHldWght() == castOther.getAccumHldWght())
						|| (this.getAccumHldWght() != null && castOther.getAccumHldWght() != null
								&& this.getAccumHldWght().equals(castOther.getAccumHldWght())))
				&& ((this.getAccumEvalWght() == castOther.getAccumEvalWght())
						|| (this.getAccumEvalWght() != null && castOther.getAccumEvalWght() != null
								&& this.getAccumEvalWght().equals(castOther.getAccumEvalWght())))
				&& ((this.getHldCnt() == castOther.getHldCnt()) || (this.getHldCnt() != null
						&& castOther.getHldCnt() != null && this.getHldCnt().equals(castOther.getHldCnt())))
				&& ((this.getSrcTable() == castOther.getSrcTable()) || (this.getSrcTable() != null
						&& castOther.getSrcTable() != null && this.getSrcTable().equals(castOther.getSrcTable())))
				&& ((this.getUpdateId() == castOther.getUpdateId()) || (this.getUpdateId() != null
						&& castOther.getUpdateId() != null && this.getUpdateId().equals(castOther.getUpdateId())))
				&& ((this.getLastUpdate() == castOther.getLastUpdate())
						|| (this.getLastUpdate() != null && castOther.getLastUpdate() != null
								&& this.getLastUpdate().equals(castOther.getLastUpdate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getCptlDivCd() == null ? 0 : this.getCptlDivCd().hashCode());
		result = 37 * result + (getYieldLclssCd() == null ? 0 : this.getYieldLclssCd().hashCode());
		result = 37 * result + (getYieldDivCd() == null ? 0 : this.getYieldDivCd().hashCode());
		result = 37 * result + (getProdTypeCd() == null ? 0 : this.getProdTypeCd().hashCode());
		result = 37 * result + (getHldAmt() == null ? 0 : this.getHldAmt().hashCode());
		result = 37 * result + (getBookAmt() == null ? 0 : this.getBookAmt().hashCode());
		result = 37 * result + (getMktEvalAmt() == null ? 0 : this.getMktEvalAmt().hashCode());
		result = 37 * result + (getBdayEvalAmt() == null ? 0 : this.getBdayEvalAmt().hashCode());
		result = 37 * result + (getIntInflowAmt() == null ? 0 : this.getIntInflowAmt().hashCode());
		result = 37 * result + (getAccumRealPl() == null ? 0 : this.getAccumRealPl().hashCode());
		result = 37 * result + (getEvalPl() == null ? 0 : this.getEvalPl().hashCode());
		result = 37 * result + (getEvalPlInc() == null ? 0 : this.getEvalPlInc().hashCode());
		result = 37 * result + (getTodayBuyAmt() == null ? 0 : this.getTodayBuyAmt().hashCode());
		result = 37 * result + (getTodaySellAmt() == null ? 0 : this.getTodaySellAmt().hashCode());
		result = 37 * result + (getDbaseEvalAmt() == null ? 0 : this.getDbaseEvalAmt().hashCode());
		result = 37 * result + (getNbaseEvalAmt() == null ? 0 : this.getNbaseEvalAmt().hashCode());
		result = 37 * result + (getHldAmtWght() == null ? 0 : this.getHldAmtWght().hashCode());
		result = 37 * result + (getMktEvalWght() == null ? 0 : this.getMktEvalWght().hashCode());
		result = 37 * result + (getTodayTwghtYield() == null ? 0 : this.getTodayTwghtYield().hashCode());
		result = 37 * result + (getAccumTwghtYield() == null ? 0 : this.getAccumTwghtYield().hashCode());
		result = 37 * result + (getAccumEvalAmt() == null ? 0 : this.getAccumEvalAmt().hashCode());
		result = 37 * result + (getAccumHldWght() == null ? 0 : this.getAccumHldWght().hashCode());
		result = 37 * result + (getAccumEvalWght() == null ? 0 : this.getAccumEvalWght().hashCode());
		result = 37 * result + (getHldCnt() == null ? 0 : this.getHldCnt().hashCode());
		result = 37 * result + (getSrcTable() == null ? 0 : this.getSrcTable().hashCode());
		result = 37 * result + (getUpdateId() == null ? 0 : this.getUpdateId().hashCode());
		result = 37 * result + (getLastUpdate() == null ? 0 : this.getLastUpdate().hashCode());
		return result;
	}

}
