package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmMstLimitSettingTmp generated by hbm2java
 */
@Entity
@Table(name = "NCM_MST_LIMIT_SETTING_TMP", schema = "NCM")
public class NcmMstLimitSettingTmp implements java.io.Serializable {

	private NcmMstLimitSettingTmpId id;

	public NcmMstLimitSettingTmp() {
	}

	public NcmMstLimitSettingTmp(NcmMstLimitSettingTmpId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "applyStDate", column = @Column(name = "APPLY_ST_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "applyCd", column = @Column(name = "APPLY_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "lmtTypeCd", column = @Column(name = "LMT_TYPE_CD", nullable = false, length = 20)),
			@AttributeOverride(name = "applyEndDate", column = @Column(name = "APPLY_END_DATE", length = 8)),
			@AttributeOverride(name = "lmtMinAmt", column = @Column(name = "LMT_MIN_AMT", nullable = false, precision = 20)),
			@AttributeOverride(name = "lmtMaxAmt", column = @Column(name = "LMT_MAX_AMT", nullable = false, precision = 20)),
			@AttributeOverride(name = "useYn", column = @Column(name = "USE_YN", length = 1)),
			@AttributeOverride(name = "srcTable", column = @Column(name = "SRC_TABLE", length = 20)),
			@AttributeOverride(name = "updateId", column = @Column(name = "UPDATE_ID", length = 20)),
			@AttributeOverride(name = "lastUpdate", column = @Column(name = "LAST_UPDATE", length = 7)) })
	public NcmMstLimitSettingTmpId getId() {
		return this.id;
	}

	public void setId(NcmMstLimitSettingTmpId id) {
		this.id = id;
	}

}
