package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMmtTransaction generated by hbm2java
 */
@Entity
@Table(name = "NCM_MMT_TRANSACTION", schema = "NCM")
public class NcmMmtTransaction implements java.io.Serializable {

	private NcmMmtTransactionId id;
	private Long trdCnt;
	private BigDecimal unitPrice;
	private Long trdPrice;
	private BigDecimal trdRet;
	private String setDt;
	private String exprDt;
	private String tranNo;
	private Date creDttm;
	private String creEmpNo;
	private Date chgDttm;
	private String chgEmpNo;
	private String workfilename;

	public NcmMmtTransaction() {
	}

	public NcmMmtTransaction(NcmMmtTransactionId id) {
		this.id = id;
	}

	public NcmMmtTransaction(NcmMmtTransactionId id, Long trdCnt, BigDecimal unitPrice, Long trdPrice,
			BigDecimal trdRet, String setDt, String exprDt, String tranNo, Date creDttm, String creEmpNo, Date chgDttm,
			String chgEmpNo, String workfilename) {
		this.id = id;
		this.trdCnt = trdCnt;
		this.unitPrice = unitPrice;
		this.trdPrice = trdPrice;
		this.trdRet = trdRet;
		this.setDt = setDt;
		this.exprDt = exprDt;
		this.tranNo = tranNo;
		this.creDttm = creDttm;
		this.creEmpNo = creEmpNo;
		this.chgDttm = chgDttm;
		this.chgEmpNo = chgEmpNo;
		this.workfilename = workfilename;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "seqNo", column = @Column(name = "SEQ_NO", nullable = false, length = 7)),
			@AttributeOverride(name = "trdDt", column = @Column(name = "TRD_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "stockCd", column = @Column(name = "STOCK_CD", nullable = false, length = 13)),
			@AttributeOverride(name = "acctCd", column = @Column(name = "ACCT_CD", nullable = false, length = 30)),
			@AttributeOverride(name = "assetCd", column = @Column(name = "ASSET_CD", nullable = false, length = 12)),
			@AttributeOverride(name = "trdGb", column = @Column(name = "TRD_GB", nullable = false, length = 1)) })
	public NcmMmtTransactionId getId() {
		return this.id;
	}

	public void setId(NcmMmtTransactionId id) {
		this.id = id;
	}

	@Column(name = "TRD_CNT", precision = 15, scale = 0)
	public Long getTrdCnt() {
		return this.trdCnt;
	}

	public void setTrdCnt(Long trdCnt) {
		this.trdCnt = trdCnt;
	}

	@Column(name = "UNIT_PRICE", precision = 15)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "TRD_PRICE", precision = 15, scale = 0)
	public Long getTrdPrice() {
		return this.trdPrice;
	}

	public void setTrdPrice(Long trdPrice) {
		this.trdPrice = trdPrice;
	}

	@Column(name = "TRD_RET", precision = 7, scale = 3)
	public BigDecimal getTrdRet() {
		return this.trdRet;
	}

	public void setTrdRet(BigDecimal trdRet) {
		this.trdRet = trdRet;
	}

	@Column(name = "SET_DT", length = 8)
	public String getSetDt() {
		return this.setDt;
	}

	public void setSetDt(String setDt) {
		this.setDt = setDt;
	}

	@Column(name = "EXPR_DT", length = 8)
	public String getExprDt() {
		return this.exprDt;
	}

	public void setExprDt(String exprDt) {
		this.exprDt = exprDt;
	}

	@Column(name = "TRAN_NO", length = 15)
	public String getTranNo() {
		return this.tranNo;
	}

	public void setTranNo(String tranNo) {
		this.tranNo = tranNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRE_DTTM", length = 7)
	public Date getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm) {
		this.creDttm = creDttm;
	}

	@Column(name = "CRE_EMP_NO", length = 6)
	public String getCreEmpNo() {
		return this.creEmpNo;
	}

	public void setCreEmpNo(String creEmpNo) {
		this.creEmpNo = creEmpNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHG_DTTM", length = 7)
	public Date getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(Date chgDttm) {
		this.chgDttm = chgDttm;
	}

	@Column(name = "CHG_EMP_NO", length = 6)
	public String getChgEmpNo() {
		return this.chgEmpNo;
	}

	public void setChgEmpNo(String chgEmpNo) {
		this.chgEmpNo = chgEmpNo;
	}

	@Column(name = "WORKFILENAME", length = 30)
	public String getWorkfilename() {
		return this.workfilename;
	}

	public void setWorkfilename(String workfilename) {
		this.workfilename = workfilename;
	}

}
