package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMstProdType generated by hbm2java
 */
@Entity
@Table(name = "NCM_MST_PROD_TYPE", schema = "NCM")
public class NcmMstProdType implements java.io.Serializable {

	private String prodTypeCd;
	private String prodTypeNm;
	private String prodLclssCd;
	private String fixIntYn;
	private String guarYn;
	private String dmstDivCd;
	private String prodHldYn;
	private String hedgeDivCd;
	private String useYn;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMstProdType() {
	}

	public NcmMstProdType(String prodTypeCd) {
		this.prodTypeCd = prodTypeCd;
	}

	public NcmMstProdType(String prodTypeCd, String prodTypeNm, String prodLclssCd, String fixIntYn, String guarYn,
			String dmstDivCd, String prodHldYn, String hedgeDivCd, String useYn, String srcTable, String updateId,
			Date lastUpdate) {
		this.prodTypeCd = prodTypeCd;
		this.prodTypeNm = prodTypeNm;
		this.prodLclssCd = prodLclssCd;
		this.fixIntYn = fixIntYn;
		this.guarYn = guarYn;
		this.dmstDivCd = dmstDivCd;
		this.prodHldYn = prodHldYn;
		this.hedgeDivCd = hedgeDivCd;
		this.useYn = useYn;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@Id

	@Column(name = "PROD_TYPE_CD", unique = true, nullable = false, length = 10)
	public String getProdTypeCd() {
		return this.prodTypeCd;
	}

	public void setProdTypeCd(String prodTypeCd) {
		this.prodTypeCd = prodTypeCd;
	}

	@Column(name = "PROD_TYPE_NM", length = 100)
	public String getProdTypeNm() {
		return this.prodTypeNm;
	}

	public void setProdTypeNm(String prodTypeNm) {
		this.prodTypeNm = prodTypeNm;
	}

	@Column(name = "PROD_LCLSS_CD", length = 10)
	public String getProdLclssCd() {
		return this.prodLclssCd;
	}

	public void setProdLclssCd(String prodLclssCd) {
		this.prodLclssCd = prodLclssCd;
	}

	@Column(name = "FIX_INT_YN", length = 1)
	public String getFixIntYn() {
		return this.fixIntYn;
	}

	public void setFixIntYn(String fixIntYn) {
		this.fixIntYn = fixIntYn;
	}

	@Column(name = "GUAR_YN", length = 1)
	public String getGuarYn() {
		return this.guarYn;
	}

	public void setGuarYn(String guarYn) {
		this.guarYn = guarYn;
	}

	@Column(name = "DMST_DIV_CD", length = 10)
	public String getDmstDivCd() {
		return this.dmstDivCd;
	}

	public void setDmstDivCd(String dmstDivCd) {
		this.dmstDivCd = dmstDivCd;
	}

	@Column(name = "PROD_HLD_YN", length = 1)
	public String getProdHldYn() {
		return this.prodHldYn;
	}

	public void setProdHldYn(String prodHldYn) {
		this.prodHldYn = prodHldYn;
	}

	@Column(name = "HEDGE_DIV_CD", length = 10)
	public String getHedgeDivCd() {
		return this.hedgeDivCd;
	}

	public void setHedgeDivCd(String hedgeDivCd) {
		this.hedgeDivCd = hedgeDivCd;
	}

	@Column(name = "USE_YN", length = 1)
	public String getUseYn() {
		return this.useYn;
	}

	public void setUseYn(String useYn) {
		this.useYn = useYn;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
