package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMapCntParty generated by hbm2java
 */
@Entity
@Table(name = "NCM_MAP_CNT_PARTY", schema = "NCM")
public class NcmMapCntParty implements java.io.Serializable {

	private NcmMapCntPartyId id;
	private String srcCpartyNm;
	private String corpNo;
	private String updateId;
	private Date lastUpdate;

	public NcmMapCntParty() {
	}

	public NcmMapCntParty(NcmMapCntPartyId id) {
		this.id = id;
	}

	public NcmMapCntParty(NcmMapCntPartyId id, String srcCpartyNm, String corpNo, String updateId, Date lastUpdate) {
		this.id = id;
		this.srcCpartyNm = srcCpartyNm;
		this.corpNo = corpNo;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "srcTable", column = @Column(name = "SRC_TABLE", nullable = false, length = 20)),
			@AttributeOverride(name = "srcCparty", column = @Column(name = "SRC_CPARTY", nullable = false, length = 100)) })
	public NcmMapCntPartyId getId() {
		return this.id;
	}

	public void setId(NcmMapCntPartyId id) {
		this.id = id;
	}

	@Column(name = "SRC_CPARTY_NM", length = 100)
	public String getSrcCpartyNm() {
		return this.srcCpartyNm;
	}

	public void setSrcCpartyNm(String srcCpartyNm) {
		this.srcCpartyNm = srcCpartyNm;
	}

	@Column(name = "CORP_NO", length = 20)
	public String getCorpNo() {
		return this.corpNo;
	}

	public void setCorpNo(String corpNo) {
		this.corpNo = corpNo;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
