package com.eugenefe.ncm;
// Generated Dec 8, 2016 3:49:34 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMstSaaCode generated by hbm2java
 */

@Entity
@Table(name = "NCM_MST_SAA_CODE", schema = "NCM")
public class NcmMstSaaCode implements java.io.Serializable, Navigatable {

	private String saaCd;
	private String saaCdNm;
	private String upperSaaCd;
	private String hierSaaCdNm;
	private Short saaLevel;
	private String cptlDivCd;
	private String applyStDate;
	private String applyEndDate;
	private String userFixYn;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMstSaaCode() {
	}

	@Id
	@Column(name = "SAA_CD", unique = true, nullable = false, length = 10)
	public String getSaaCd() {
		return this.saaCd;
	}

	public void setSaaCd(String saaCd) {
		this.saaCd = saaCd;

	}

	@Column(name = "SAA_CD_NM", length = 100)
	public String getSaaCdNm() {
		return this.saaCdNm;
	}

	public void setSaaCdNm(String saaCdNm) {
		this.saaCdNm = saaCdNm;

	}

	@Column(name = "UPPER_SAA_CD", length = 10)
	public String getUpperSaaCd() {
		return this.upperSaaCd;
	}

	public void setUpperSaaCd(String upperSaaCd) {
		this.upperSaaCd = upperSaaCd;

	}

	@Column(name = "HIER_SAA_CD_NM", length = 500)
	public String getHierSaaCdNm() {
		return this.hierSaaCdNm;
	}

	public void setHierSaaCdNm(String hierSaaCdNm) {
		this.hierSaaCdNm = hierSaaCdNm;

	}

	@Column(name = "SAA_LEVEL", precision = 4, scale = 0)
	public Short getSaaLevel() {
		return this.saaLevel;
	}

	public void setSaaLevel(Short saaLevel) {
		this.saaLevel = saaLevel;

	}

	@Column(name = "CPTL_DIV_CD", length = 10)
	public String getCptlDivCd() {
		return this.cptlDivCd;
	}

	public void setCptlDivCd(String cptlDivCd) {
		this.cptlDivCd = cptlDivCd;

	}

	@Column(name = "APPLY_ST_DATE", length = 8)
	public String getApplyStDate() {
		return this.applyStDate;
	}

	public void setApplyStDate(String applyStDate) {
		this.applyStDate = applyStDate;

	}

	@Column(name = "APPLY_END_DATE", length = 8)
	public String getApplyEndDate() {
		return this.applyEndDate;
	}

	public void setApplyEndDate(String applyEndDate) {
		this.applyEndDate = applyEndDate;

	}

	@Column(name = "USER_FIX_YN", length = 1)
	public String getUserFixYn() {
		return this.userFixYn;
	}

	public void setUserFixYn(String userFixYn) {
		this.userFixYn = userFixYn;

	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getSaaCd());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstSaaCode))
			return false;
		NcmMstSaaCode castOther = (NcmMstSaaCode) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (idString() == null ? 0 : this.idString().hashCode());
		return result;
	}

}
