package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NcmMmtPositionId generated by hbm2java
 */
@Embeddable
public class NcmMmtPositionId implements java.io.Serializable {

	private String seqNo;
	private String bizDt;
	private String stockCd;
	private String acctCd;
	private String cptlGb;
	private String termGb;

	public NcmMmtPositionId() {
	}

	public NcmMmtPositionId(String seqNo, String bizDt, String stockCd, String acctCd, String cptlGb, String termGb) {
		this.seqNo = seqNo;
		this.bizDt = bizDt;
		this.stockCd = stockCd;
		this.acctCd = acctCd;
		this.cptlGb = cptlGb;
		this.termGb = termGb;
	}

	@Column(name = "SEQ_NO", nullable = false, length = 7)
	public String getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(String seqNo) {
		this.seqNo = seqNo;
	}

	@Column(name = "BIZ_DT", nullable = false, length = 8)
	public String getBizDt() {
		return this.bizDt;
	}

	public void setBizDt(String bizDt) {
		this.bizDt = bizDt;
	}

	@Column(name = "STOCK_CD", nullable = false, length = 13)
	public String getStockCd() {
		return this.stockCd;
	}

	public void setStockCd(String stockCd) {
		this.stockCd = stockCd;
	}

	@Column(name = "ACCT_CD", nullable = false, length = 30)
	public String getAcctCd() {
		return this.acctCd;
	}

	public void setAcctCd(String acctCd) {
		this.acctCd = acctCd;
	}

	@Column(name = "CPTL_GB", nullable = false, length = 2)
	public String getCptlGb() {
		return this.cptlGb;
	}

	public void setCptlGb(String cptlGb) {
		this.cptlGb = cptlGb;
	}

	@Column(name = "TERM_GB", nullable = false, length = 2)
	public String getTermGb() {
		return this.termGb;
	}

	public void setTermGb(String termGb) {
		this.termGb = termGb;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMmtPositionId))
			return false;
		NcmMmtPositionId castOther = (NcmMmtPositionId) other;

		return ((this.getSeqNo() == castOther.getSeqNo()) || (this.getSeqNo() != null && castOther.getSeqNo() != null
				&& this.getSeqNo().equals(castOther.getSeqNo())))
				&& ((this.getBizDt() == castOther.getBizDt()) || (this.getBizDt() != null
						&& castOther.getBizDt() != null && this.getBizDt().equals(castOther.getBizDt())))
				&& ((this.getStockCd() == castOther.getStockCd()) || (this.getStockCd() != null
						&& castOther.getStockCd() != null && this.getStockCd().equals(castOther.getStockCd())))
				&& ((this.getAcctCd() == castOther.getAcctCd()) || (this.getAcctCd() != null
						&& castOther.getAcctCd() != null && this.getAcctCd().equals(castOther.getAcctCd())))
				&& ((this.getCptlGb() == castOther.getCptlGb()) || (this.getCptlGb() != null
						&& castOther.getCptlGb() != null && this.getCptlGb().equals(castOther.getCptlGb())))
				&& ((this.getTermGb() == castOther.getTermGb()) || (this.getTermGb() != null
						&& castOther.getTermGb() != null && this.getTermGb().equals(castOther.getTermGb())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSeqNo() == null ? 0 : this.getSeqNo().hashCode());
		result = 37 * result + (getBizDt() == null ? 0 : this.getBizDt().hashCode());
		result = 37 * result + (getStockCd() == null ? 0 : this.getStockCd().hashCode());
		result = 37 * result + (getAcctCd() == null ? 0 : this.getAcctCd().hashCode());
		result = 37 * result + (getCptlGb() == null ? 0 : this.getCptlGb().hashCode());
		result = 37 * result + (getTermGb() == null ? 0 : this.getTermGb().hashCode());
		return result;
	}

}
