package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMapProdType generated by hbm2java
 */
@Entity
@Table(name = "NCM_MAP_PROD_TYPE", schema = "NCM")
public class NcmMapProdType implements java.io.Serializable {

	private NcmMapProdTypeId id;
	private String srcProdTypeNm;
	private String prodTypeCd;
	private String updateId;
	private Date lastUpdate;

	public NcmMapProdType() {
	}

	public NcmMapProdType(NcmMapProdTypeId id) {
		this.id = id;
	}

	public NcmMapProdType(NcmMapProdTypeId id, String srcProdTypeNm, String prodTypeCd, String updateId,
			Date lastUpdate) {
		this.id = id;
		this.srcProdTypeNm = srcProdTypeNm;
		this.prodTypeCd = prodTypeCd;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "srcTable", column = @Column(name = "SRC_TABLE", nullable = false, length = 20)),
			@AttributeOverride(name = "srcProdTypeCd", column = @Column(name = "SRC_PROD_TYPE_CD", nullable = false, length = 10)) })
	public NcmMapProdTypeId getId() {
		return this.id;
	}

	public void setId(NcmMapProdTypeId id) {
		this.id = id;
	}

	@Column(name = "SRC_PROD_TYPE_NM", length = 100)
	public String getSrcProdTypeNm() {
		return this.srcProdTypeNm;
	}

	public void setSrcProdTypeNm(String srcProdTypeNm) {
		this.srcProdTypeNm = srcProdTypeNm;
	}

	@Column(name = "PROD_TYPE_CD", length = 10)
	public String getProdTypeCd() {
		return this.prodTypeCd;
	}

	public void setProdTypeCd(String prodTypeCd) {
		this.prodTypeCd = prodTypeCd;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
