package com.eugenefe.ncm;
// Generated Dec 8, 2016 3:49:34 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

/**
 * NcmMstLimitSettingId generated by hbm2java
 */

public class NcmMstLimitSettingId implements java.io.Serializable, Navigatable {

	private String applyStDate;
	private String applyGroup;
	private String applyCd;
	private String lmtTypeCd;

	public NcmMstLimitSettingId() {
	}

	public String getApplyStDate() {
		return this.applyStDate;
	}

	public void setApplyStDate(String applyStDate) {
		this.applyStDate = applyStDate;

	}

	public String getApplyGroup() {
		return this.applyGroup;
	}

	public void setApplyGroup(String applyGroup) {
		this.applyGroup = applyGroup;

	}

	public String getApplyCd() {
		return this.applyCd;
	}

	public void setApplyCd(String applyCd) {
		this.applyCd = applyCd;

	}

	public String getLmtTypeCd() {
		return this.lmtTypeCd;
	}

	public void setLmtTypeCd(String lmtTypeCd) {
		this.lmtTypeCd = lmtTypeCd;

	}

	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getApplyStDate());
		buffer.append("#").append(getApplyGroup());
		buffer.append("#").append(getApplyCd());
		buffer.append("#").append(getLmtTypeCd());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstLimitSettingId))
			return false;
		NcmMstLimitSettingId castOther = (NcmMstLimitSettingId) other;

		return ((this.getApplyStDate() == castOther.getApplyStDate())
				|| (this.getApplyStDate() != null && castOther.getApplyStDate() != null && this.getApplyStDate().equals(castOther.getApplyStDate())))
				&& ((this.getApplyGroup() == castOther.getApplyGroup())
						|| (this.getApplyGroup() != null && castOther.getApplyGroup() != null && this.getApplyGroup().equals(castOther.getApplyGroup())))
				&& ((this.getApplyCd() == castOther.getApplyCd())
						|| (this.getApplyCd() != null && castOther.getApplyCd() != null && this.getApplyCd().equals(castOther.getApplyCd())))
				&& ((this.getLmtTypeCd() == castOther.getLmtTypeCd())
						|| (this.getLmtTypeCd() != null && castOther.getLmtTypeCd() != null && this.getLmtTypeCd().equals(castOther.getLmtTypeCd())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getApplyStDate() == null ? 0 : this.getApplyStDate().hashCode());
		result = 37 * result + (getApplyGroup() == null ? 0 : this.getApplyGroup().hashCode());
		result = 37 * result + (getApplyCd() == null ? 0 : this.getApplyCd().hashCode());
		result = 37 * result + (getLmtTypeCd() == null ? 0 : this.getLmtTypeCd().hashCode());
		return result;
	}

}
