package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;

/**
 * NcmMstCodeId generated by hbm2java
 */

public class NcmMstCodeId implements java.io.Serializable {

	private String codeGroup;
	private String codeId;

	public NcmMstCodeId() {
	}

	public String getCodeGroup() {
		return this.codeGroup;
	}

	public void setCodeGroup(String codeGroup) {
		this.codeGroup = codeGroup;

	}

	public String getCodeId() {
		return this.codeId;
	}

	public void setCodeId(String codeId) {
		this.codeId = codeId;

	}

	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getCodeGroup());
		buffer.append("#").append(getCodeId());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstCodeId))
			return false;
		NcmMstCodeId castOther = (NcmMstCodeId) other;

		return ((this.getCodeGroup() == castOther.getCodeGroup())
				|| (this.getCodeGroup() != null && castOther.getCodeGroup() != null && this.getCodeGroup().equals(castOther.getCodeGroup())))
				&& ((this.getCodeId() == castOther.getCodeId()) || (this.getCodeId() != null && castOther.getCodeId() != null && this.getCodeId().equals(castOther.getCodeId())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodeGroup() == null ? 0 : this.getCodeGroup().hashCode());
		result = 37 * result + (getCodeId() == null ? 0 : this.getCodeId().hashCode());
		return result;
	}

}
