package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMstCntParty generated by hbm2java
 */
@Entity
@Table(name = "NCM_MST_CNT_PARTY", schema = "NCM")
public class NcmMstCntParty implements java.io.Serializable {

	private String corpNo;
	private String cpartyNm;
	private String cpartyTypeCd;
	private String groupCorpNo;
	private String userFixYn;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMstCntParty() {
	}

	public NcmMstCntParty(String corpNo) {
		this.corpNo = corpNo;
	}

	public NcmMstCntParty(String corpNo, String cpartyNm, String cpartyTypeCd, String groupCorpNo, String userFixYn,
			String srcTable, String updateId, Date lastUpdate) {
		this.corpNo = corpNo;
		this.cpartyNm = cpartyNm;
		this.cpartyTypeCd = cpartyTypeCd;
		this.groupCorpNo = groupCorpNo;
		this.userFixYn = userFixYn;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@Id

	@Column(name = "CORP_NO", unique = true, nullable = false, length = 20)
	public String getCorpNo() {
		return this.corpNo;
	}

	public void setCorpNo(String corpNo) {
		this.corpNo = corpNo;
	}

	@Column(name = "CPARTY_NM", length = 100)
	public String getCpartyNm() {
		return this.cpartyNm;
	}

	public void setCpartyNm(String cpartyNm) {
		this.cpartyNm = cpartyNm;
	}

	@Column(name = "CPARTY_TYPE_CD", length = 10)
	public String getCpartyTypeCd() {
		return this.cpartyTypeCd;
	}

	public void setCpartyTypeCd(String cpartyTypeCd) {
		this.cpartyTypeCd = cpartyTypeCd;
	}

	@Column(name = "GROUP_CORP_NO", length = 20)
	public String getGroupCorpNo() {
		return this.groupCorpNo;
	}

	public void setGroupCorpNo(String groupCorpNo) {
		this.groupCorpNo = groupCorpNo;
	}

	@Column(name = "USER_FIX_YN", length = 1)
	public String getUserFixYn() {
		return this.userFixYn;
	}

	public void setUserFixYn(String userFixYn) {
		this.userFixYn = userFixYn;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
