package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMktMarketVariable generated by hbm2java
 */
@Entity
@Table(name = "NCM_MKT_MARKET_VARIABLE", schema = "NCM")
public class NcmMktMarketVariable implements java.io.Serializable {

	private String mvId;
	private String mvNm;
	private String mvTypeCd;
	private String creaOrgId;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMktMarketVariable() {
	}

	public NcmMktMarketVariable(String mvId) {
		this.mvId = mvId;
	}

	public NcmMktMarketVariable(String mvId, String mvNm, String mvTypeCd, String creaOrgId, String srcTable,
			String updateId, Date lastUpdate) {
		this.mvId = mvId;
		this.mvNm = mvNm;
		this.mvTypeCd = mvTypeCd;
		this.creaOrgId = creaOrgId;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@Id

	@Column(name = "MV_ID", unique = true, nullable = false, length = 20)
	public String getMvId() {
		return this.mvId;
	}

	public void setMvId(String mvId) {
		this.mvId = mvId;
	}

	@Column(name = "MV_NM", length = 100)
	public String getMvNm() {
		return this.mvNm;
	}

	public void setMvNm(String mvNm) {
		this.mvNm = mvNm;
	}

	@Column(name = "MV_TYPE_CD", length = 10)
	public String getMvTypeCd() {
		return this.mvTypeCd;
	}

	public void setMvTypeCd(String mvTypeCd) {
		this.mvTypeCd = mvTypeCd;
	}

	@Column(name = "CREA_ORG_ID", length = 20)
	public String getCreaOrgId() {
		return this.creaOrgId;
	}

	public void setCreaOrgId(String creaOrgId) {
		this.creaOrgId = creaOrgId;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
