package com.eugenefe.ncm;
// Generated Dec 8, 2016 3:49:34 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * NcmMapMmtAccountSub generated by hbm2java
 */

@Entity
@IdClass(value = NcmMapMmtAccountSubId.class)
@Table(name = "NCM_MAP_MMT_ACCOUNT_SUB", schema = "NCM")
public class NcmMapMmtAccountSub implements java.io.Serializable, Navigatable {

	private String srcAcctNo;
	private String srcFinTxNo;
	private String srcCaptDiv;
	private String srcCaptDivNm;
	private String srcTxType;
	private String srcTxTypeNm;
	private String srcTermType;
	private String srcCparty;
	private String srcCpartyNm;
	private String srcBuyDate;
	private String srcMaturityDate;
	private BigDecimal holdingAmt;
	private String acctCd;

	public NcmMapMmtAccountSub() {
	}

	@Id
	@Column(name = "SRC_ACCT_NO", nullable = false, length = 50)
	public String getSrcAcctNo() {
		return this.srcAcctNo;
	}

	public void setSrcAcctNo(String srcAcctNo) {
		this.srcAcctNo = srcAcctNo;
	}

	@Id
	@Column(name = "SRC_FIN_TX_NO", nullable = false, length = 20)
	public String getSrcFinTxNo() {
		return this.srcFinTxNo;
	}

	public void setSrcFinTxNo(String srcFinTxNo) {
		this.srcFinTxNo = srcFinTxNo;
	}

	@Column(name = "SRC_CAPT_DIV", nullable = false, length = 20)
	public String getSrcCaptDiv() {
		return this.srcCaptDiv;
	}

	public void setSrcCaptDiv(String srcCaptDiv) {
		this.srcCaptDiv = srcCaptDiv;

	}

	@Column(name = "SRC_CAPT_DIV_NM", length = 100)
	public String getSrcCaptDivNm() {
		return this.srcCaptDivNm;
	}

	public void setSrcCaptDivNm(String srcCaptDivNm) {
		this.srcCaptDivNm = srcCaptDivNm;

	}

	@Column(name = "SRC_TX_TYPE", length = 10)
	public String getSrcTxType() {
		return this.srcTxType;
	}

	public void setSrcTxType(String srcTxType) {
		this.srcTxType = srcTxType;

	}

	@Column(name = "SRC_TX_TYPE_NM", length = 100)
	public String getSrcTxTypeNm() {
		return this.srcTxTypeNm;
	}

	public void setSrcTxTypeNm(String srcTxTypeNm) {
		this.srcTxTypeNm = srcTxTypeNm;

	}

	@Column(name = "SRC_TERM_TYPE", length = 10)
	public String getSrcTermType() {
		return this.srcTermType;
	}

	public void setSrcTermType(String srcTermType) {
		this.srcTermType = srcTermType;

	}

	@Column(name = "SRC_CPARTY", length = 100)
	public String getSrcCparty() {
		return this.srcCparty;
	}

	public void setSrcCparty(String srcCparty) {
		this.srcCparty = srcCparty;

	}

	@Column(name = "SRC_CPARTY_NM", length = 100)
	public String getSrcCpartyNm() {
		return this.srcCpartyNm;
	}

	public void setSrcCpartyNm(String srcCpartyNm) {
		this.srcCpartyNm = srcCpartyNm;

	}

	@Column(name = "SRC_BUY_DATE", length = 8)
	public String getSrcBuyDate() {
		return this.srcBuyDate;
	}

	public void setSrcBuyDate(String srcBuyDate) {
		this.srcBuyDate = srcBuyDate;

	}

	@Column(name = "SRC_MATURITY_DATE", length = 8)
	public String getSrcMaturityDate() {
		return this.srcMaturityDate;
	}

	public void setSrcMaturityDate(String srcMaturityDate) {
		this.srcMaturityDate = srcMaturityDate;

	}

	@Column(name = "HOLDING_AMT", precision = 20, scale = 0)
	public BigDecimal getHoldingAmt() {
		return this.holdingAmt;
	}

	public void setHoldingAmt(BigDecimal holdingAmt) {
		this.holdingAmt = holdingAmt;

	}

	@Column(name = "ACCT_CD", length = 100)
	public String getAcctCd() {
		return this.acctCd;
	}

	public void setAcctCd(String acctCd) {
		this.acctCd = acctCd;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getSrcAcctNo());
		buffer.append("#").append(getSrcFinTxNo());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMapMmtAccountSub))
			return false;
		NcmMapMmtAccountSub castOther = (NcmMapMmtAccountSub) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSrcAcctNo() == null ? 0 : this.getSrcAcctNo().hashCode());
		result = 37 * result + (getSrcFinTxNo() == null ? 0 : this.getSrcFinTxNo().hashCode());
		return result;
	}

}
