package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMktMvDaily generated by hbm2java
 */
@Entity
@Table(name = "NCM_MKT_MV_DAILY", schema = "NCM")
public class NcmMktMvDaily implements java.io.Serializable {

	private NcmMktMvDailyId id;
	private BigDecimal mvIdx;
	private BigDecimal mvInt;
	private BigDecimal mvDiff;
	private BigDecimal mvDailyYield;
	private BigDecimal mvMtdYield;
	private BigDecimal mvQtdYield;
	private BigDecimal mvYtdYield;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMktMvDaily() {
	}

	public NcmMktMvDaily(NcmMktMvDailyId id, BigDecimal mvIdx, BigDecimal mvInt) {
		this.id = id;
		this.mvIdx = mvIdx;
		this.mvInt = mvInt;
	}

	public NcmMktMvDaily(NcmMktMvDailyId id, BigDecimal mvIdx, BigDecimal mvInt, BigDecimal mvDiff,
			BigDecimal mvDailyYield, BigDecimal mvMtdYield, BigDecimal mvQtdYield, BigDecimal mvYtdYield,
			String srcTable, String updateId, Date lastUpdate) {
		this.id = id;
		this.mvIdx = mvIdx;
		this.mvInt = mvInt;
		this.mvDiff = mvDiff;
		this.mvDailyYield = mvDailyYield;
		this.mvMtdYield = mvMtdYield;
		this.mvQtdYield = mvQtdYield;
		this.mvYtdYield = mvYtdYield;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "mvId", column = @Column(name = "MV_ID", nullable = false, length = 20)) })
	public NcmMktMvDailyId getId() {
		return this.id;
	}

	public void setId(NcmMktMvDailyId id) {
		this.id = id;
	}

	@Column(name = "MV_IDX", nullable = false, precision = 20, scale = 12)
	public BigDecimal getMvIdx() {
		return this.mvIdx;
	}

	public void setMvIdx(BigDecimal mvIdx) {
		this.mvIdx = mvIdx;
	}

	@Column(name = "MV_INT", nullable = false, precision = 20, scale = 12)
	public BigDecimal getMvInt() {
		return this.mvInt;
	}

	public void setMvInt(BigDecimal mvInt) {
		this.mvInt = mvInt;
	}

	@Column(name = "MV_DIFF", precision = 20, scale = 12)
	public BigDecimal getMvDiff() {
		return this.mvDiff;
	}

	public void setMvDiff(BigDecimal mvDiff) {
		this.mvDiff = mvDiff;
	}

	@Column(name = "MV_DAILY_YIELD", precision = 20, scale = 12)
	public BigDecimal getMvDailyYield() {
		return this.mvDailyYield;
	}

	public void setMvDailyYield(BigDecimal mvDailyYield) {
		this.mvDailyYield = mvDailyYield;
	}

	@Column(name = "MV_MTD_YIELD", precision = 20, scale = 12)
	public BigDecimal getMvMtdYield() {
		return this.mvMtdYield;
	}

	public void setMvMtdYield(BigDecimal mvMtdYield) {
		this.mvMtdYield = mvMtdYield;
	}

	@Column(name = "MV_QTD_YIELD", precision = 20, scale = 12)
	public BigDecimal getMvQtdYield() {
		return this.mvQtdYield;
	}

	public void setMvQtdYield(BigDecimal mvQtdYield) {
		this.mvQtdYield = mvQtdYield;
	}

	@Column(name = "MV_YTD_YIELD", precision = 20, scale = 12)
	public BigDecimal getMvYtdYield() {
		return this.mvYtdYield;
	}

	public void setMvYtdYield(BigDecimal mvYtdYield) {
		this.mvYtdYield = mvYtdYield;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
