package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * NcmMmtCode generated by hbm2java
 */

@Entity
@IdClass(value = NcmMmtCodeId.class)
@Table(name = "NCM_MMT_CODE", schema = "NCM")
public class NcmMmtCode implements java.io.Serializable {

	private String baseCdPttn;
	private String baseCdClass1;
	private String baseCdClass2;
	private String baseCdPttnNm;
	private String baseCdCmnt;

	public NcmMmtCode() {
	}

	@Id
	@Column(name = "BASE_CD_PTTN", nullable = false, length = 10)
	public String getBaseCdPttn() {
		return this.baseCdPttn;
	}

	public void setBaseCdPttn(String baseCdPttn) {
		this.baseCdPttn = baseCdPttn;
	}

	@Id
	@Column(name = "BASE_CD_CLASS1", nullable = false, length = 10)
	public String getBaseCdClass1() {
		return this.baseCdClass1;
	}

	public void setBaseCdClass1(String baseCdClass1) {
		this.baseCdClass1 = baseCdClass1;
	}

	@Id
	@Column(name = "BASE_CD_CLASS2", nullable = false, length = 20)
	public String getBaseCdClass2() {
		return this.baseCdClass2;
	}

	public void setBaseCdClass2(String baseCdClass2) {
		this.baseCdClass2 = baseCdClass2;
	}

	@Column(name = "BASE_CD_PTTN_NM", length = 20)
	public String getBaseCdPttnNm() {
		return this.baseCdPttnNm;
	}

	public void setBaseCdPttnNm(String baseCdPttnNm) {
		this.baseCdPttnNm = baseCdPttnNm;

	}

	@Column(name = "BASE_CD_CMNT", length = 30)
	public String getBaseCdCmnt() {
		return this.baseCdCmnt;
	}

	public void setBaseCdCmnt(String baseCdCmnt) {
		this.baseCdCmnt = baseCdCmnt;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseCdPttn());
		buffer.append("#").append(getBaseCdClass1());
		buffer.append("#").append(getBaseCdClass2());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMmtCode))
			return false;
		NcmMmtCode castOther = (NcmMmtCode) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseCdPttn() == null ? 0 : this.getBaseCdPttn().hashCode());
		result = 37 * result + (getBaseCdClass1() == null ? 0 : this.getBaseCdClass1().hashCode());
		result = 37 * result + (getBaseCdClass2() == null ? 0 : this.getBaseCdClass2().hashCode());
		return result;
	}

}
