package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMstAccount generated by hbm2java
 */
@Entity
@Table(name = "NCM_MST_ACCOUNT", schema = "NCM")
public class NcmMstAccount implements java.io.Serializable {

	private NcmMstAccountId id;
	private String acctNoNm;
	private String bizDivCd;
	private String acctDivCd;
	private String cptlDivCd;
	private String mngFinOrg;
	private String stusDivCd;
	private String acctStDate;
	private String acctEndDate;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMstAccount() {
	}

	public NcmMstAccount(NcmMstAccountId id) {
		this.id = id;
	}

	public NcmMstAccount(NcmMstAccountId id, String acctNoNm, String bizDivCd, String acctDivCd, String cptlDivCd,
			String mngFinOrg, String stusDivCd, String acctStDate, String acctEndDate, String srcTable, String updateId,
			Date lastUpdate) {
		this.id = id;
		this.acctNoNm = acctNoNm;
		this.bizDivCd = bizDivCd;
		this.acctDivCd = acctDivCd;
		this.cptlDivCd = cptlDivCd;
		this.mngFinOrg = mngFinOrg;
		this.stusDivCd = stusDivCd;
		this.acctStDate = acctStDate;
		this.acctEndDate = acctEndDate;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "acctNo", column = @Column(name = "ACCT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "prodTypeCd", column = @Column(name = "PROD_TYPE_CD", nullable = false, length = 10)) })
	public NcmMstAccountId getId() {
		return this.id;
	}

	public void setId(NcmMstAccountId id) {
		this.id = id;
	}

	@Column(name = "ACCT_NO_NM", length = 100)
	public String getAcctNoNm() {
		return this.acctNoNm;
	}

	public void setAcctNoNm(String acctNoNm) {
		this.acctNoNm = acctNoNm;
	}

	@Column(name = "BIZ_DIV_CD", length = 10)
	public String getBizDivCd() {
		return this.bizDivCd;
	}

	public void setBizDivCd(String bizDivCd) {
		this.bizDivCd = bizDivCd;
	}

	@Column(name = "ACCT_DIV_CD", length = 10)
	public String getAcctDivCd() {
		return this.acctDivCd;
	}

	public void setAcctDivCd(String acctDivCd) {
		this.acctDivCd = acctDivCd;
	}

	@Column(name = "CPTL_DIV_CD", length = 10)
	public String getCptlDivCd() {
		return this.cptlDivCd;
	}

	public void setCptlDivCd(String cptlDivCd) {
		this.cptlDivCd = cptlDivCd;
	}

	@Column(name = "MNG_FIN_ORG", length = 20)
	public String getMngFinOrg() {
		return this.mngFinOrg;
	}

	public void setMngFinOrg(String mngFinOrg) {
		this.mngFinOrg = mngFinOrg;
	}

	@Column(name = "STUS_DIV_CD", length = 10)
	public String getStusDivCd() {
		return this.stusDivCd;
	}

	public void setStusDivCd(String stusDivCd) {
		this.stusDivCd = stusDivCd;
	}

	@Column(name = "ACCT_ST_DATE", length = 8)
	public String getAcctStDate() {
		return this.acctStDate;
	}

	public void setAcctStDate(String acctStDate) {
		this.acctStDate = acctStDate;
	}

	@Column(name = "ACCT_END_DATE", length = 8)
	public String getAcctEndDate() {
		return this.acctEndDate;
	}

	public void setAcctEndDate(String acctEndDate) {
		this.acctEndDate = acctEndDate;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
