package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmMstSaaCodeTemp generated by hbm2java
 */
@Entity
@Table(name = "NCM_MST_SAA_CODE_TEMP", schema = "NCM")
public class NcmMstSaaCodeTemp implements java.io.Serializable {

	private NcmMstSaaCodeTempId id;

	public NcmMstSaaCodeTemp() {
	}

	public NcmMstSaaCodeTemp(NcmMstSaaCodeTempId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "saaCd", column = @Column(name = "SAA_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "saaCdNm", column = @Column(name = "SAA_CD_NM", length = 100)),
			@AttributeOverride(name = "upperSaaCd", column = @Column(name = "UPPER_SAA_CD", length = 10)),
			@AttributeOverride(name = "hierSaaCdNm", column = @Column(name = "HIER_SAA_CD_NM", length = 500)),
			@AttributeOverride(name = "saaLevel", column = @Column(name = "SAA_LEVEL", precision = 4, scale = 0)),
			@AttributeOverride(name = "cptlDivCd", column = @Column(name = "CPTL_DIV_CD", length = 10)),
			@AttributeOverride(name = "applyStDate", column = @Column(name = "APPLY_ST_DATE", length = 8)),
			@AttributeOverride(name = "applyEndDate", column = @Column(name = "APPLY_END_DATE", length = 8)),
			@AttributeOverride(name = "userFixYn", column = @Column(name = "USER_FIX_YN", length = 1)),
			@AttributeOverride(name = "srcTable", column = @Column(name = "SRC_TABLE", length = 20)),
			@AttributeOverride(name = "updateId", column = @Column(name = "UPDATE_ID", length = 20)),
			@AttributeOverride(name = "lastUpdate", column = @Column(name = "LAST_UPDATE", length = 7)) })
	public NcmMstSaaCodeTempId getId() {
		return this.id;
	}

	public void setId(NcmMstSaaCodeTempId id) {
		this.id = id;
	}

}
