package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMstSaaWght generated by hbm2java
 */
@Entity
@Table(name = "NCM_MST_SAA_WGHT", schema = "NCM")
public class NcmMstSaaWght implements java.io.Serializable {

	private NcmMstSaaWghtId id;
	private Short saaOrder;
	private Short saaLevel;
	private BigDecimal targetYield;
	private BigDecimal targetWght;
	private BigDecimal torlError;
	private BigDecimal varLimit;
	private BigDecimal teLimit;
	private String bmId;
	private String applyEndDate;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMstSaaWght() {
	}

	public NcmMstSaaWght(NcmMstSaaWghtId id) {
		this.id = id;
	}

	public NcmMstSaaWght(NcmMstSaaWghtId id, Short saaOrder, Short saaLevel, BigDecimal targetYield,
			BigDecimal targetWght, BigDecimal torlError, BigDecimal varLimit, BigDecimal teLimit, String bmId,
			String applyEndDate, String srcTable, String updateId, Date lastUpdate) {
		this.id = id;
		this.saaOrder = saaOrder;
		this.saaLevel = saaLevel;
		this.targetYield = targetYield;
		this.targetWght = targetWght;
		this.torlError = torlError;
		this.varLimit = varLimit;
		this.teLimit = teLimit;
		this.bmId = bmId;
		this.applyEndDate = applyEndDate;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "applyStDate", column = @Column(name = "APPLY_ST_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "saaCd", column = @Column(name = "SAA_CD", nullable = false, length = 10)) })
	public NcmMstSaaWghtId getId() {
		return this.id;
	}

	public void setId(NcmMstSaaWghtId id) {
		this.id = id;
	}

	@Column(name = "SAA_ORDER", precision = 4, scale = 0)
	public Short getSaaOrder() {
		return this.saaOrder;
	}

	public void setSaaOrder(Short saaOrder) {
		this.saaOrder = saaOrder;
	}

	@Column(name = "SAA_LEVEL", precision = 4, scale = 0)
	public Short getSaaLevel() {
		return this.saaLevel;
	}

	public void setSaaLevel(Short saaLevel) {
		this.saaLevel = saaLevel;
	}

	@Column(name = "TARGET_YIELD", precision = 12, scale = 8)
	public BigDecimal getTargetYield() {
		return this.targetYield;
	}

	public void setTargetYield(BigDecimal targetYield) {
		this.targetYield = targetYield;
	}

	@Column(name = "TARGET_WGHT", precision = 12, scale = 8)
	public BigDecimal getTargetWght() {
		return this.targetWght;
	}

	public void setTargetWght(BigDecimal targetWght) {
		this.targetWght = targetWght;
	}

	@Column(name = "TORL_ERROR", precision = 12, scale = 8)
	public BigDecimal getTorlError() {
		return this.torlError;
	}

	public void setTorlError(BigDecimal torlError) {
		this.torlError = torlError;
	}

	@Column(name = "VAR_LIMIT", precision = 12, scale = 8)
	public BigDecimal getVarLimit() {
		return this.varLimit;
	}

	public void setVarLimit(BigDecimal varLimit) {
		this.varLimit = varLimit;
	}

	@Column(name = "TE_LIMIT", precision = 12, scale = 8)
	public BigDecimal getTeLimit() {
		return this.teLimit;
	}

	public void setTeLimit(BigDecimal teLimit) {
		this.teLimit = teLimit;
	}

	@Column(name = "BM_ID", length = 20)
	public String getBmId() {
		return this.bmId;
	}

	public void setBmId(String bmId) {
		this.bmId = bmId;
	}

	@Column(name = "APPLY_END_DATE", length = 8)
	public String getApplyEndDate() {
		return this.applyEndDate;
	}

	public void setApplyEndDate(String applyEndDate) {
		this.applyEndDate = applyEndDate;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
