package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMstCompliance generated by hbm2java
 */

@Entity
@IdClass(value = NcmMstComplianceId.class)
@Table(name = "NCM_MST_COMPLIANCE", schema = "NCM")
public class NcmMstCompliance implements java.io.Serializable {

	private String applyStDate;
	private String applyDivCd;
	private String applyCd;
	private String complTypeCd;
	private String applyEndDate;
	private BigDecimal lmtMinAmt;
	private BigDecimal lmtMaxAmt;
	private String useYn;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMstCompliance() {
	}

	@Id
	@Column(name = "APPLY_ST_DATE", nullable = false, length = 8)
	public String getApplyStDate() {
		return this.applyStDate;
	}

	public void setApplyStDate(String applyStDate) {
		this.applyStDate = applyStDate;
	}

	@Id
	@Column(name = "APPLY_DIV_CD", nullable = false, length = 20)
	public String getApplyDivCd() {
		return this.applyDivCd;
	}

	public void setApplyDivCd(String applyDivCd) {
		this.applyDivCd = applyDivCd;
	}

	@Id
	@Column(name = "APPLY_CD", nullable = false, length = 20)
	public String getApplyCd() {
		return this.applyCd;
	}

	public void setApplyCd(String applyCd) {
		this.applyCd = applyCd;
	}

	@Id
	@Column(name = "COMPL_TYPE_CD", nullable = false, length = 50)
	public String getComplTypeCd() {
		return this.complTypeCd;
	}

	public void setComplTypeCd(String complTypeCd) {
		this.complTypeCd = complTypeCd;
	}

	@Column(name = "APPLY_END_DATE", length = 8)
	public String getApplyEndDate() {
		return this.applyEndDate;
	}

	public void setApplyEndDate(String applyEndDate) {
		this.applyEndDate = applyEndDate;

	}

	@Column(name = "LMT_MIN_AMT", nullable = false, precision = 22, scale = 4)
	public BigDecimal getLmtMinAmt() {
		return this.lmtMinAmt;
	}

	public void setLmtMinAmt(BigDecimal lmtMinAmt) {
		this.lmtMinAmt = lmtMinAmt;

	}

	@Column(name = "LMT_MAX_AMT", nullable = false, precision = 22, scale = 4)
	public BigDecimal getLmtMaxAmt() {
		return this.lmtMaxAmt;
	}

	public void setLmtMaxAmt(BigDecimal lmtMaxAmt) {
		this.lmtMaxAmt = lmtMaxAmt;

	}

	@Column(name = "USE_YN", length = 1)
	public String getUseYn() {
		return this.useYn;
	}

	public void setUseYn(String useYn) {
		this.useYn = useYn;

	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getApplyStDate());
		buffer.append("#").append(getApplyDivCd());
		buffer.append("#").append(getApplyCd());
		buffer.append("#").append(getComplTypeCd());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstCompliance))
			return false;
		NcmMstCompliance castOther = (NcmMstCompliance) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getApplyStDate() == null ? 0 : this.getApplyStDate().hashCode());
		result = 37 * result + (getApplyDivCd() == null ? 0 : this.getApplyDivCd().hashCode());
		result = 37 * result + (getApplyCd() == null ? 0 : this.getApplyCd().hashCode());
		result = 37 * result + (getComplTypeCd() == null ? 0 : this.getComplTypeCd().hashCode());
		return result;
	}

}
