package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMstLimitSetting generated by hbm2java
 */
@Entity
@Table(name = "NCM_MST_LIMIT_SETTING", schema = "NCM")
public class NcmMstLimitSetting implements java.io.Serializable {

	private NcmMstLimitSettingId id;
	private String applyEndDate;
	private BigDecimal lmtMinAmt;
	private BigDecimal lmtMaxAmt;
	private String useYn;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMstLimitSetting() {
	}

	public NcmMstLimitSetting(NcmMstLimitSettingId id, BigDecimal lmtMinAmt, BigDecimal lmtMaxAmt) {
		this.id = id;
		this.lmtMinAmt = lmtMinAmt;
		this.lmtMaxAmt = lmtMaxAmt;
	}

	public NcmMstLimitSetting(NcmMstLimitSettingId id, String applyEndDate, BigDecimal lmtMinAmt, BigDecimal lmtMaxAmt,
			String useYn, String srcTable, String updateId, Date lastUpdate) {
		this.id = id;
		this.applyEndDate = applyEndDate;
		this.lmtMinAmt = lmtMinAmt;
		this.lmtMaxAmt = lmtMaxAmt;
		this.useYn = useYn;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "applyStDate", column = @Column(name = "APPLY_ST_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "applyGroup", column = @Column(name = "APPLY_GROUP", nullable = false, length = 20)),
			@AttributeOverride(name = "applyCd", column = @Column(name = "APPLY_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "lmtTypeCd", column = @Column(name = "LMT_TYPE_CD", nullable = false, length = 20)) })
	public NcmMstLimitSettingId getId() {
		return this.id;
	}

	public void setId(NcmMstLimitSettingId id) {
		this.id = id;
	}

	@Column(name = "APPLY_END_DATE", length = 8)
	public String getApplyEndDate() {
		return this.applyEndDate;
	}

	public void setApplyEndDate(String applyEndDate) {
		this.applyEndDate = applyEndDate;
	}

	@Column(name = "LMT_MIN_AMT", nullable = false, precision = 20)
	public BigDecimal getLmtMinAmt() {
		return this.lmtMinAmt;
	}

	public void setLmtMinAmt(BigDecimal lmtMinAmt) {
		this.lmtMinAmt = lmtMinAmt;
	}

	@Column(name = "LMT_MAX_AMT", nullable = false, precision = 20)
	public BigDecimal getLmtMaxAmt() {
		return this.lmtMaxAmt;
	}

	public void setLmtMaxAmt(BigDecimal lmtMaxAmt) {
		this.lmtMaxAmt = lmtMaxAmt;
	}

	@Column(name = "USE_YN", length = 1)
	public String getUseYn() {
		return this.useYn;
	}

	public void setUseYn(String useYn) {
		this.useYn = useYn;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
