package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMmtUnderCds generated by hbm2java
 */
@Entity
@Table(name = "NCM_MMT_UNDER_CDS", schema = "NCM")
public class NcmMmtUnderCds implements java.io.Serializable {

	private NcmMmtUnderCdsId id;
	private String priorGb;
	private String stdAgNm;
	private String cdsTrdNo;
	private String stdAgNo;
	private String stdAgCrdt;
	private String crdtGrdEval;
	private String crdtGrdType;
	private String detailLst;
	private String trigg;
	private Date creDttm;
	private String creEmpNo;
	private Date chgDttm;
	private String chgEmpNo;
	private String workfilename;

	public NcmMmtUnderCds() {
	}

	public NcmMmtUnderCds(NcmMmtUnderCdsId id, String priorGb) {
		this.id = id;
		this.priorGb = priorGb;
	}

	public NcmMmtUnderCds(NcmMmtUnderCdsId id, String priorGb, String stdAgNm, String cdsTrdNo, String stdAgNo,
			String stdAgCrdt, String crdtGrdEval, String crdtGrdType, String detailLst, String trigg, Date creDttm,
			String creEmpNo, Date chgDttm, String chgEmpNo, String workfilename) {
		this.id = id;
		this.priorGb = priorGb;
		this.stdAgNm = stdAgNm;
		this.cdsTrdNo = cdsTrdNo;
		this.stdAgNo = stdAgNo;
		this.stdAgCrdt = stdAgCrdt;
		this.crdtGrdEval = crdtGrdEval;
		this.crdtGrdType = crdtGrdType;
		this.detailLst = detailLst;
		this.trigg = trigg;
		this.creDttm = creDttm;
		this.creEmpNo = creEmpNo;
		this.chgDttm = chgDttm;
		this.chgEmpNo = chgEmpNo;
		this.workfilename = workfilename;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "seqNo", column = @Column(name = "SEQ_NO", nullable = false, length = 7)),
			@AttributeOverride(name = "bizDt", column = @Column(name = "BIZ_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "stockCd", column = @Column(name = "STOCK_CD", nullable = false, length = 13)),
			@AttributeOverride(name = "acctCd", column = @Column(name = "ACCT_CD", nullable = false, length = 30)),
			@AttributeOverride(name = "assetCd", column = @Column(name = "ASSET_CD", nullable = false, length = 12)),
			@AttributeOverride(name = "unastCd", column = @Column(name = "UNAST_CD", nullable = false, length = 14)),
			@AttributeOverride(name = "ordGb", column = @Column(name = "ORD_GB", nullable = false, precision = 8, scale = 0)) })
	public NcmMmtUnderCdsId getId() {
		return this.id;
	}

	public void setId(NcmMmtUnderCdsId id) {
		this.id = id;
	}

	@Column(name = "PRIOR_GB", nullable = false, length = 2)
	public String getPriorGb() {
		return this.priorGb;
	}

	public void setPriorGb(String priorGb) {
		this.priorGb = priorGb;
	}

	@Column(name = "STD_AG_NM", length = 100)
	public String getStdAgNm() {
		return this.stdAgNm;
	}

	public void setStdAgNm(String stdAgNm) {
		this.stdAgNm = stdAgNm;
	}

	@Column(name = "CDS_TRD_NO", length = 13)
	public String getCdsTrdNo() {
		return this.cdsTrdNo;
	}

	public void setCdsTrdNo(String cdsTrdNo) {
		this.cdsTrdNo = cdsTrdNo;
	}

	@Column(name = "STD_AG_NO", length = 13)
	public String getStdAgNo() {
		return this.stdAgNo;
	}

	public void setStdAgNo(String stdAgNo) {
		this.stdAgNo = stdAgNo;
	}

	@Column(name = "STD_AG_CRDT", length = 4)
	public String getStdAgCrdt() {
		return this.stdAgCrdt;
	}

	public void setStdAgCrdt(String stdAgCrdt) {
		this.stdAgCrdt = stdAgCrdt;
	}

	@Column(name = "CRDT_GRD_EVAL", length = 2)
	public String getCrdtGrdEval() {
		return this.crdtGrdEval;
	}

	public void setCrdtGrdEval(String crdtGrdEval) {
		this.crdtGrdEval = crdtGrdEval;
	}

	@Column(name = "CRDT_GRD_TYPE", length = 2)
	public String getCrdtGrdType() {
		return this.crdtGrdType;
	}

	public void setCrdtGrdType(String crdtGrdType) {
		this.crdtGrdType = crdtGrdType;
	}

	@Column(name = "DETAIL_LST", length = 500)
	public String getDetailLst() {
		return this.detailLst;
	}

	public void setDetailLst(String detailLst) {
		this.detailLst = detailLst;
	}

	@Column(name = "TRIGG", length = 500)
	public String getTrigg() {
		return this.trigg;
	}

	public void setTrigg(String trigg) {
		this.trigg = trigg;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRE_DTTM", length = 7)
	public Date getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm) {
		this.creDttm = creDttm;
	}

	@Column(name = "CRE_EMP_NO", length = 6)
	public String getCreEmpNo() {
		return this.creEmpNo;
	}

	public void setCreEmpNo(String creEmpNo) {
		this.creEmpNo = creEmpNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHG_DTTM", length = 7)
	public Date getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(Date chgDttm) {
		this.chgDttm = chgDttm;
	}

	@Column(name = "CHG_EMP_NO", length = 6)
	public String getChgEmpNo() {
		return this.chgEmpNo;
	}

	public void setChgEmpNo(String chgEmpNo) {
		this.chgEmpNo = chgEmpNo;
	}

	@Column(name = "WORKFILENAME", length = 30)
	public String getWorkfilename() {
		return this.workfilename;
	}

	public void setWorkfilename(String workfilename) {
		this.workfilename = workfilename;
	}

}
