package com.eugenefe.ncm;
// Generated Dec 8, 2016 3:49:34 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMapMmtAccount generated by hbm2java
 */

@Entity
@IdClass(value = NcmMapMmtAccountId.class)
@Table(name = "NCM_MAP_MMT_ACCOUNT", schema = "NCM")
public class NcmMapMmtAccount implements java.io.Serializable, Navigatable {

	private String srcTable;
	private String srcAcctNo;
	private String srcFinTxNo;
	private String srcProdTypeCd;
	private String srcProdTypeNm;
	private String srcCparty;
	private String srcCpartyNm;
	private String srcBuyDate;
	private String srcMaturityDate;
	private BigDecimal srcIssuAmt;
	private BigDecimal srcIntRate;
	private String finProdId;
	private String updateId;
	private Date lastUpdate;

	public NcmMapMmtAccount() {
	}

	@Id
	@Column(name = "SRC_TABLE", nullable = false, length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Id
	@Column(name = "SRC_ACCT_NO", nullable = false, length = 50)
	public String getSrcAcctNo() {
		return this.srcAcctNo;
	}

	public void setSrcAcctNo(String srcAcctNo) {
		this.srcAcctNo = srcAcctNo;
	}

	@Id
	@Column(name = "SRC_FIN_TX_NO", nullable = false, length = 20)
	public String getSrcFinTxNo() {
		return this.srcFinTxNo;
	}

	public void setSrcFinTxNo(String srcFinTxNo) {
		this.srcFinTxNo = srcFinTxNo;
	}

	@Column(name = "SRC_PROD_TYPE_CD", nullable = false, length = 10)
	public String getSrcProdTypeCd() {
		return this.srcProdTypeCd;
	}

	public void setSrcProdTypeCd(String srcProdTypeCd) {
		this.srcProdTypeCd = srcProdTypeCd;

	}

	@Column(name = "SRC_PROD_TYPE_NM", length = 100)
	public String getSrcProdTypeNm() {
		return this.srcProdTypeNm;
	}

	public void setSrcProdTypeNm(String srcProdTypeNm) {
		this.srcProdTypeNm = srcProdTypeNm;

	}

	@Column(name = "SRC_CPARTY", length = 100)
	public String getSrcCparty() {
		return this.srcCparty;
	}

	public void setSrcCparty(String srcCparty) {
		this.srcCparty = srcCparty;

	}

	@Column(name = "SRC_CPARTY_NM", length = 100)
	public String getSrcCpartyNm() {
		return this.srcCpartyNm;
	}

	public void setSrcCpartyNm(String srcCpartyNm) {
		this.srcCpartyNm = srcCpartyNm;

	}

	@Column(name = "SRC_BUY_DATE", length = 8)
	public String getSrcBuyDate() {
		return this.srcBuyDate;
	}

	public void setSrcBuyDate(String srcBuyDate) {
		this.srcBuyDate = srcBuyDate;

	}

	@Column(name = "SRC_MATURITY_DATE", length = 8)
	public String getSrcMaturityDate() {
		return this.srcMaturityDate;
	}

	public void setSrcMaturityDate(String srcMaturityDate) {
		this.srcMaturityDate = srcMaturityDate;

	}

	@Column(name = "SRC_ISSU_AMT", precision = 20)
	public BigDecimal getSrcIssuAmt() {
		return this.srcIssuAmt;
	}

	public void setSrcIssuAmt(BigDecimal srcIssuAmt) {
		this.srcIssuAmt = srcIssuAmt;

	}

	@Column(name = "SRC_INT_RATE", precision = 12, scale = 8)
	public BigDecimal getSrcIntRate() {
		return this.srcIntRate;
	}

	public void setSrcIntRate(BigDecimal srcIntRate) {
		this.srcIntRate = srcIntRate;

	}

	@Column(name = "FIN_PROD_ID", length = 100)
	public String getFinProdId() {
		return this.finProdId;
	}

	public void setFinProdId(String finProdId) {
		this.finProdId = finProdId;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getSrcTable());
		buffer.append("#").append(getSrcAcctNo());
		buffer.append("#").append(getSrcFinTxNo());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMapMmtAccount))
			return false;
		NcmMapMmtAccount castOther = (NcmMapMmtAccount) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSrcTable() == null ? 0 : this.getSrcTable().hashCode());
		result = 37 * result + (getSrcAcctNo() == null ? 0 : this.getSrcAcctNo().hashCode());
		result = 37 * result + (getSrcFinTxNo() == null ? 0 : this.getSrcFinTxNo().hashCode());
		return result;
	}

}
