package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * NcmMstCodeTmp generated by hbm2java
 */

@Entity
@IdClass(value = NcmMstCodeTmpId.class)
@Table(name = "NCM_MST_CODE_TMP", schema = "NCM")
public class NcmMstCodeTmp implements java.io.Serializable {

	private String codeGroup;
	private String codeId;
	private String codeNm;
	private String codeRemark;
	private String codeGroupNm;
	private BigDecimal codeOrder;
	private String updateId;
	private Date lastUpdate;

	public NcmMstCodeTmp() {
	}

	@Id
	@Column(name = "CODE_GROUP", length = 20)
	public String getCodeGroup() {
		return this.codeGroup;
	}

	public void setCodeGroup(String codeGroup) {
		this.codeGroup = codeGroup;
	}

	@Id
	@Column(name = "CODE_ID", length = 100)
	public String getCodeId() {
		return this.codeId;
	}

	public void setCodeId(String codeId) {
		this.codeId = codeId;
	}

	@Id
	@Column(name = "CODE_NM", length = 100)
	public String getCodeNm() {
		return this.codeNm;
	}

	public void setCodeNm(String codeNm) {
		this.codeNm = codeNm;
	}

	@Id
	@Column(name = "CODE_REMARK", length = 100)
	public String getCodeRemark() {
		return this.codeRemark;
	}

	public void setCodeRemark(String codeRemark) {
		this.codeRemark = codeRemark;
	}

	@Id
	@Column(name = "CODE_GROUP_NM", length = 100)
	public String getCodeGroupNm() {
		return this.codeGroupNm;
	}

	public void setCodeGroupNm(String codeGroupNm) {
		this.codeGroupNm = codeGroupNm;
	}

	@Id
	@Column(name = "CODE_ORDER", precision = 22, scale = 0)
	public BigDecimal getCodeOrder() {
		return this.codeOrder;
	}

	public void setCodeOrder(BigDecimal codeOrder) {
		this.codeOrder = codeOrder;
	}

	@Id
	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Id
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getCodeGroup());
		buffer.append("#").append(getCodeId());
		buffer.append("#").append(getCodeNm());
		buffer.append("#").append(getCodeRemark());
		buffer.append("#").append(getCodeGroupNm());
		buffer.append("#").append(getCodeOrder());
		buffer.append("#").append(getUpdateId());
		buffer.append("#").append(getLastUpdate());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstCodeTmp))
			return false;
		NcmMstCodeTmp castOther = (NcmMstCodeTmp) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodeGroup() == null ? 0 : this.getCodeGroup().hashCode());
		result = 37 * result + (getCodeId() == null ? 0 : this.getCodeId().hashCode());
		result = 37 * result + (getCodeNm() == null ? 0 : this.getCodeNm().hashCode());
		result = 37 * result + (getCodeRemark() == null ? 0 : this.getCodeRemark().hashCode());
		result = 37 * result + (getCodeGroupNm() == null ? 0 : this.getCodeGroupNm().hashCode());
		result = 37 * result + (getCodeOrder() == null ? 0 : this.getCodeOrder().hashCode());
		result = 37 * result + (getUpdateId() == null ? 0 : this.getUpdateId().hashCode());
		result = 37 * result + (getLastUpdate() == null ? 0 : this.getLastUpdate().hashCode());
		return result;
	}

}
