package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NcmMstSaaCodeTempId generated by hbm2java
 */
@Embeddable
public class NcmMstSaaCodeTempId implements java.io.Serializable {

	private String saaCd;
	private String saaCdNm;
	private String upperSaaCd;
	private String hierSaaCdNm;
	private Short saaLevel;
	private String cptlDivCd;
	private String applyStDate;
	private String applyEndDate;
	private String userFixYn;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMstSaaCodeTempId() {
	}

	public NcmMstSaaCodeTempId(String saaCd) {
		this.saaCd = saaCd;
	}

	public NcmMstSaaCodeTempId(String saaCd, String saaCdNm, String upperSaaCd, String hierSaaCdNm, Short saaLevel,
			String cptlDivCd, String applyStDate, String applyEndDate, String userFixYn, String srcTable,
			String updateId, Date lastUpdate) {
		this.saaCd = saaCd;
		this.saaCdNm = saaCdNm;
		this.upperSaaCd = upperSaaCd;
		this.hierSaaCdNm = hierSaaCdNm;
		this.saaLevel = saaLevel;
		this.cptlDivCd = cptlDivCd;
		this.applyStDate = applyStDate;
		this.applyEndDate = applyEndDate;
		this.userFixYn = userFixYn;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "SAA_CD", nullable = false, length = 10)
	public String getSaaCd() {
		return this.saaCd;
	}

	public void setSaaCd(String saaCd) {
		this.saaCd = saaCd;
	}

	@Column(name = "SAA_CD_NM", length = 100)
	public String getSaaCdNm() {
		return this.saaCdNm;
	}

	public void setSaaCdNm(String saaCdNm) {
		this.saaCdNm = saaCdNm;
	}

	@Column(name = "UPPER_SAA_CD", length = 10)
	public String getUpperSaaCd() {
		return this.upperSaaCd;
	}

	public void setUpperSaaCd(String upperSaaCd) {
		this.upperSaaCd = upperSaaCd;
	}

	@Column(name = "HIER_SAA_CD_NM", length = 500)
	public String getHierSaaCdNm() {
		return this.hierSaaCdNm;
	}

	public void setHierSaaCdNm(String hierSaaCdNm) {
		this.hierSaaCdNm = hierSaaCdNm;
	}

	@Column(name = "SAA_LEVEL", precision = 4, scale = 0)
	public Short getSaaLevel() {
		return this.saaLevel;
	}

	public void setSaaLevel(Short saaLevel) {
		this.saaLevel = saaLevel;
	}

	@Column(name = "CPTL_DIV_CD", length = 10)
	public String getCptlDivCd() {
		return this.cptlDivCd;
	}

	public void setCptlDivCd(String cptlDivCd) {
		this.cptlDivCd = cptlDivCd;
	}

	@Column(name = "APPLY_ST_DATE", length = 8)
	public String getApplyStDate() {
		return this.applyStDate;
	}

	public void setApplyStDate(String applyStDate) {
		this.applyStDate = applyStDate;
	}

	@Column(name = "APPLY_END_DATE", length = 8)
	public String getApplyEndDate() {
		return this.applyEndDate;
	}

	public void setApplyEndDate(String applyEndDate) {
		this.applyEndDate = applyEndDate;
	}

	@Column(name = "USER_FIX_YN", length = 1)
	public String getUserFixYn() {
		return this.userFixYn;
	}

	public void setUserFixYn(String userFixYn) {
		this.userFixYn = userFixYn;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstSaaCodeTempId))
			return false;
		NcmMstSaaCodeTempId castOther = (NcmMstSaaCodeTempId) other;

		return ((this.getSaaCd() == castOther.getSaaCd()) || (this.getSaaCd() != null && castOther.getSaaCd() != null
				&& this.getSaaCd().equals(castOther.getSaaCd())))
				&& ((this.getSaaCdNm() == castOther.getSaaCdNm()) || (this.getSaaCdNm() != null
						&& castOther.getSaaCdNm() != null && this.getSaaCdNm().equals(castOther.getSaaCdNm())))
				&& ((this.getUpperSaaCd() == castOther.getUpperSaaCd()) || (this.getUpperSaaCd() != null
						&& castOther.getUpperSaaCd() != null && this.getUpperSaaCd().equals(castOther.getUpperSaaCd())))
				&& ((this.getHierSaaCdNm() == castOther.getHierSaaCdNm())
						|| (this.getHierSaaCdNm() != null && castOther.getHierSaaCdNm() != null
								&& this.getHierSaaCdNm().equals(castOther.getHierSaaCdNm())))
				&& ((this.getSaaLevel() == castOther.getSaaLevel()) || (this.getSaaLevel() != null
						&& castOther.getSaaLevel() != null && this.getSaaLevel().equals(castOther.getSaaLevel())))
				&& ((this.getCptlDivCd() == castOther.getCptlDivCd()) || (this.getCptlDivCd() != null
						&& castOther.getCptlDivCd() != null && this.getCptlDivCd().equals(castOther.getCptlDivCd())))
				&& ((this.getApplyStDate() == castOther.getApplyStDate())
						|| (this.getApplyStDate() != null && castOther.getApplyStDate() != null
								&& this.getApplyStDate().equals(castOther.getApplyStDate())))
				&& ((this.getApplyEndDate() == castOther.getApplyEndDate())
						|| (this.getApplyEndDate() != null && castOther.getApplyEndDate() != null
								&& this.getApplyEndDate().equals(castOther.getApplyEndDate())))
				&& ((this.getUserFixYn() == castOther.getUserFixYn()) || (this.getUserFixYn() != null
						&& castOther.getUserFixYn() != null && this.getUserFixYn().equals(castOther.getUserFixYn())))
				&& ((this.getSrcTable() == castOther.getSrcTable()) || (this.getSrcTable() != null
						&& castOther.getSrcTable() != null && this.getSrcTable().equals(castOther.getSrcTable())))
				&& ((this.getUpdateId() == castOther.getUpdateId()) || (this.getUpdateId() != null
						&& castOther.getUpdateId() != null && this.getUpdateId().equals(castOther.getUpdateId())))
				&& ((this.getLastUpdate() == castOther.getLastUpdate())
						|| (this.getLastUpdate() != null && castOther.getLastUpdate() != null
								&& this.getLastUpdate().equals(castOther.getLastUpdate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSaaCd() == null ? 0 : this.getSaaCd().hashCode());
		result = 37 * result + (getSaaCdNm() == null ? 0 : this.getSaaCdNm().hashCode());
		result = 37 * result + (getUpperSaaCd() == null ? 0 : this.getUpperSaaCd().hashCode());
		result = 37 * result + (getHierSaaCdNm() == null ? 0 : this.getHierSaaCdNm().hashCode());
		result = 37 * result + (getSaaLevel() == null ? 0 : this.getSaaLevel().hashCode());
		result = 37 * result + (getCptlDivCd() == null ? 0 : this.getCptlDivCd().hashCode());
		result = 37 * result + (getApplyStDate() == null ? 0 : this.getApplyStDate().hashCode());
		result = 37 * result + (getApplyEndDate() == null ? 0 : this.getApplyEndDate().hashCode());
		result = 37 * result + (getUserFixYn() == null ? 0 : this.getUserFixYn().hashCode());
		result = 37 * result + (getSrcTable() == null ? 0 : this.getSrcTable().hashCode());
		result = 37 * result + (getUpdateId() == null ? 0 : this.getUpdateId().hashCode());
		result = 37 * result + (getLastUpdate() == null ? 0 : this.getLastUpdate().hashCode());
		return result;
	}

}
