package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMapTxType generated by hbm2java
 */
@Entity
@Table(name = "NCM_MAP_TX_TYPE", schema = "NCM")
@IdClass(value= NcmMapTxTypePk.class)
public class NcmMapTxType implements java.io.Serializable {

//	private NcmMapTxTypeId id;
	private String srcTable;
	private String srcProdTypeCd;
	private String srcTradeTypeCd;
	
	private String srcProdTypeNm;
	private String srcTradeTypeNm;
	private String txTypeCd;
	private String updateId;
	private Date lastUpdate;

	public NcmMapTxType() {
	}

	/*public NcmMapTxType(NcmMapTxTypeId id) {
		this.id = id;
	}

	public NcmMapTxType(NcmMapTxTypeId id, String srcProdTypeNm, String srcTradeTypeNm, String txTypeCd,
			String updateId, Date lastUpdate) {
		this.id = id;
		this.srcProdTypeNm = srcProdTypeNm;
		this.srcTradeTypeNm = srcTradeTypeNm;
		this.txTypeCd = txTypeCd;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "srcTable", column = @Column(name = "SRC_TABLE", nullable = false, length = 20)),
			@AttributeOverride(name = "srcProdTypeCd", column = @Column(name = "SRC_PROD_TYPE_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "srcTradeTypeCd", column = @Column(name = "SRC_TRADE_TYPE_CD", nullable = false, length = 10)) })
	public NcmMapTxTypeId getId() {
		return this.id;
	}

	public void setId(NcmMapTxTypeId id) {
		this.id = id;
	}*/
	@Id
	@Column(name = "SRC_TABLE", length = 100)
	public String getSrcTable() {
		return srcTable;
	}
	
	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Id
	@Column(name = "SRC_PROD_TYPE_CD", length = 100)
	public String getSrcProdTypeCd() {
		return srcProdTypeCd;
	}

	public void setSrcProdTypeCd(String srcProdTypeCd) {
		this.srcProdTypeCd = srcProdTypeCd;
	}

	@Id
	@Column(name = "SRC_TRADE_TYPE_CD")
	public String getSrcTradeTypeCd() {
		return srcTradeTypeCd;
	}

	public void setSrcTradeTypeCd(String srcTradeTypeCd) {
		this.srcTradeTypeCd = srcTradeTypeCd;
	}

	

	@Column(name = "SRC_PROD_TYPE_NM", length = 100)
	public String getSrcProdTypeNm() {
		return this.srcProdTypeNm;
	}

	public void setSrcProdTypeNm(String srcProdTypeNm) {
		this.srcProdTypeNm = srcProdTypeNm;
	}

	

	@Column(name = "SRC_TRADE_TYPE_NM", length = 100)
	public String getSrcTradeTypeNm() {
		return this.srcTradeTypeNm;
	}

	public void setSrcTradeTypeNm(String srcTradeTypeNm) {
		this.srcTradeTypeNm = srcTradeTypeNm;
	}

	@Column(name = "TX_TYPE_CD", length = 10)
	public String getTxTypeCd() {
		return this.txTypeCd;
	}

	public void setTxTypeCd(String txTypeCd) {
		this.txTypeCd = txTypeCd;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
