package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMapCptlDiv generated by hbm2java
 */
@Entity
@Table(name = "NCM_MAP_CPTL_DIV", schema = "NCM")
public class NcmMapCptlDiv implements java.io.Serializable {

	private NcmMapCptlDivId id;
	private String srcCptlDivNm;
	private String cptlDivCd;
	private String updateId;
	private Date lastUpdate;

	public NcmMapCptlDiv() {
	}

	public NcmMapCptlDiv(NcmMapCptlDivId id) {
		this.id = id;
	}

	public NcmMapCptlDiv(NcmMapCptlDivId id, String srcCptlDivNm, String cptlDivCd, String updateId, Date lastUpdate) {
		this.id = id;
		this.srcCptlDivNm = srcCptlDivNm;
		this.cptlDivCd = cptlDivCd;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "srcTable", column = @Column(name = "SRC_TABLE", nullable = false, length = 20)),
			@AttributeOverride(name = "srcCptlDivCd", column = @Column(name = "SRC_CPTL_DIV_CD", nullable = false, length = 10)) })
	public NcmMapCptlDivId getId() {
		return this.id;
	}

	public void setId(NcmMapCptlDivId id) {
		this.id = id;
	}

	@Column(name = "SRC_CPTL_DIV_NM", length = 100)
	public String getSrcCptlDivNm() {
		return this.srcCptlDivNm;
	}

	public void setSrcCptlDivNm(String srcCptlDivNm) {
		this.srcCptlDivNm = srcCptlDivNm;
	}

	@Column(name = "CPTL_DIV_CD", length = 10)
	public String getCptlDivCd() {
		return this.cptlDivCd;
	}

	public void setCptlDivCd(String cptlDivCd) {
		this.cptlDivCd = cptlDivCd;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
