package com.eugenefe.ncm;
// Generated Dec 8, 2016 3:49:34 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * NcmMstSaaCodeTemp generated by hbm2java
 */

@Entity
@IdClass(value = NcmMstSaaCodeTempId.class)
@Table(name = "NCM_MST_SAA_CODE_TEMP", schema = "NCM")
public class NcmMstSaaCodeTemp implements java.io.Serializable, Navigatable {

	private String saaCd;
	private String saaCdNm;
	private String upperSaaCd;
	private String hierSaaCdNm;
	private Short saaLevel;
	private String cptlDivCd;
	private String applyStDate;
	private String applyEndDate;
	private String userFixYn;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMstSaaCodeTemp() {
	}

	@Id
	@Column(name = "SAA_CD", nullable = false, length = 10)
	public String getSaaCd() {
		return this.saaCd;
	}

	public void setSaaCd(String saaCd) {
		this.saaCd = saaCd;
	}

	@Id
	@Column(name = "SAA_CD_NM", length = 100)
	public String getSaaCdNm() {
		return this.saaCdNm;
	}

	public void setSaaCdNm(String saaCdNm) {
		this.saaCdNm = saaCdNm;
	}

	@Id
	@Column(name = "UPPER_SAA_CD", length = 10)
	public String getUpperSaaCd() {
		return this.upperSaaCd;
	}

	public void setUpperSaaCd(String upperSaaCd) {
		this.upperSaaCd = upperSaaCd;
	}

	@Id
	@Column(name = "HIER_SAA_CD_NM", length = 500)
	public String getHierSaaCdNm() {
		return this.hierSaaCdNm;
	}

	public void setHierSaaCdNm(String hierSaaCdNm) {
		this.hierSaaCdNm = hierSaaCdNm;
	}

	@Id
	@Column(name = "SAA_LEVEL", precision = 4, scale = 0)
	public Short getSaaLevel() {
		return this.saaLevel;
	}

	public void setSaaLevel(Short saaLevel) {
		this.saaLevel = saaLevel;
	}

	@Id
	@Column(name = "CPTL_DIV_CD", length = 10)
	public String getCptlDivCd() {
		return this.cptlDivCd;
	}

	public void setCptlDivCd(String cptlDivCd) {
		this.cptlDivCd = cptlDivCd;
	}

	@Id
	@Column(name = "APPLY_ST_DATE", length = 8)
	public String getApplyStDate() {
		return this.applyStDate;
	}

	public void setApplyStDate(String applyStDate) {
		this.applyStDate = applyStDate;
	}

	@Id
	@Column(name = "APPLY_END_DATE", length = 8)
	public String getApplyEndDate() {
		return this.applyEndDate;
	}

	public void setApplyEndDate(String applyEndDate) {
		this.applyEndDate = applyEndDate;
	}

	@Id
	@Column(name = "USER_FIX_YN", length = 1)
	public String getUserFixYn() {
		return this.userFixYn;
	}

	public void setUserFixYn(String userFixYn) {
		this.userFixYn = userFixYn;
	}

	@Id
	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Id
	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Id
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getSaaCd());
		buffer.append("#").append(getSaaCdNm());
		buffer.append("#").append(getUpperSaaCd());
		buffer.append("#").append(getHierSaaCdNm());
		buffer.append("#").append(getSaaLevel());
		buffer.append("#").append(getCptlDivCd());
		buffer.append("#").append(getApplyStDate());
		buffer.append("#").append(getApplyEndDate());
		buffer.append("#").append(getUserFixYn());
		buffer.append("#").append(getSrcTable());
		buffer.append("#").append(getUpdateId());
		buffer.append("#").append(getLastUpdate());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstSaaCodeTemp))
			return false;
		NcmMstSaaCodeTemp castOther = (NcmMstSaaCodeTemp) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSaaCd() == null ? 0 : this.getSaaCd().hashCode());
		result = 37 * result + (getSaaCdNm() == null ? 0 : this.getSaaCdNm().hashCode());
		result = 37 * result + (getUpperSaaCd() == null ? 0 : this.getUpperSaaCd().hashCode());
		result = 37 * result + (getHierSaaCdNm() == null ? 0 : this.getHierSaaCdNm().hashCode());
		result = 37 * result + (getSaaLevel() == null ? 0 : this.getSaaLevel().hashCode());
		result = 37 * result + (getCptlDivCd() == null ? 0 : this.getCptlDivCd().hashCode());
		result = 37 * result + (getApplyStDate() == null ? 0 : this.getApplyStDate().hashCode());
		result = 37 * result + (getApplyEndDate() == null ? 0 : this.getApplyEndDate().hashCode());
		result = 37 * result + (getUserFixYn() == null ? 0 : this.getUserFixYn().hashCode());
		result = 37 * result + (getSrcTable() == null ? 0 : this.getSrcTable().hashCode());
		result = 37 * result + (getUpdateId() == null ? 0 : this.getUpdateId().hashCode());
		result = 37 * result + (getLastUpdate() == null ? 0 : this.getLastUpdate().hashCode());
		return result;
	}

}
