package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmMstProdTypeTmp generated by hbm2java
 */
@Entity
@Table(name = "NCM_MST_PROD_TYPE_TMP", schema = "NCM")
public class NcmMstProdTypeTmp implements java.io.Serializable {

	private NcmMstProdTypeTmpId id;

	public NcmMstProdTypeTmp() {
	}

	public NcmMstProdTypeTmp(NcmMstProdTypeTmpId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "prodTypeCd", column = @Column(name = "PROD_TYPE_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "prodTypeNm", column = @Column(name = "PROD_TYPE_NM", length = 100)),
			@AttributeOverride(name = "prodLclssCd", column = @Column(name = "PROD_LCLSS_CD", length = 10)),
			@AttributeOverride(name = "fixIntYn", column = @Column(name = "FIX_INT_YN", length = 1)),
			@AttributeOverride(name = "guarYn", column = @Column(name = "GUAR_YN", length = 1)),
			@AttributeOverride(name = "dmstDivCd", column = @Column(name = "DMST_DIV_CD", length = 10)),
			@AttributeOverride(name = "prodHldYn", column = @Column(name = "PROD_HLD_YN", length = 1)),
			@AttributeOverride(name = "hedgeDivCd", column = @Column(name = "HEDGE_DIV_CD", length = 10)),
			@AttributeOverride(name = "srcTable", column = @Column(name = "SRC_TABLE", length = 20)),
			@AttributeOverride(name = "updateId", column = @Column(name = "UPDATE_ID", length = 20)),
			@AttributeOverride(name = "lastUpdate", column = @Column(name = "LAST_UPDATE", length = 7)) })
	public NcmMstProdTypeTmpId getId() {
		return this.id;
	}

	public void setId(NcmMstProdTypeTmpId id) {
		this.id = id;
	}

}
