package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmMstSaaWghtTmp generated by hbm2java
 */
@Entity
@Table(name = "NCM_MST_SAA_WGHT_TMP", schema = "NCM")
public class NcmMstSaaWghtTmp implements java.io.Serializable {

	private NcmMstSaaWghtTmpId id;

	public NcmMstSaaWghtTmp() {
	}

	public NcmMstSaaWghtTmp(NcmMstSaaWghtTmpId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "applyStDate", column = @Column(name = "APPLY_ST_DATE", length = 8)),
			@AttributeOverride(name = "saaCd", column = @Column(name = "SAA_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "saaOrder", column = @Column(name = "SAA_ORDER", precision = 4, scale = 0)),
			@AttributeOverride(name = "saaLevel", column = @Column(name = "SAA_LEVEL", precision = 4, scale = 0)),
			@AttributeOverride(name = "targetYield", column = @Column(name = "TARGET_YIELD", precision = 12, scale = 8)),
			@AttributeOverride(name = "targetWght", column = @Column(name = "TARGET_WGHT", precision = 12, scale = 8)),
			@AttributeOverride(name = "torlError", column = @Column(name = "TORL_ERROR", precision = 12, scale = 8)),
			@AttributeOverride(name = "bmId", column = @Column(name = "BM_ID", length = 20)),
			@AttributeOverride(name = "applyEndDate", column = @Column(name = "APPLY_END_DATE", length = 8)),
			@AttributeOverride(name = "srcTable", column = @Column(name = "SRC_TABLE", length = 20)),
			@AttributeOverride(name = "updateId", column = @Column(name = "UPDATE_ID", length = 20)),
			@AttributeOverride(name = "lastUpdate", column = @Column(name = "LAST_UPDATE", length = 7)) })
	public NcmMstSaaWghtTmpId getId() {
		return this.id;
	}

	public void setId(NcmMstSaaWghtTmpId id) {
		this.id = id;
	}

}
