package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMstSaaTerm generated by hbm2java
 */
@Entity
@Table(name = "NCM_MST_SAA_TERM", schema = "NCM")
public class NcmMstSaaTerm implements java.io.Serializable {

	private String applyStDate;
	private String applyEndDate;
	private String descTxt;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMstSaaTerm() {
	}

	public NcmMstSaaTerm(String applyStDate) {
		this.applyStDate = applyStDate;
	}

	public NcmMstSaaTerm(String applyStDate, String applyEndDate, String descTxt, String srcTable, String updateId,
			Date lastUpdate) {
		this.applyStDate = applyStDate;
		this.applyEndDate = applyEndDate;
		this.descTxt = descTxt;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@Id

	@Column(name = "APPLY_ST_DATE", unique = true, nullable = false, length = 8)
	public String getApplyStDate() {
		return this.applyStDate;
	}

	public void setApplyStDate(String applyStDate) {
		this.applyStDate = applyStDate;
	}

	@Column(name = "APPLY_END_DATE", length = 8)
	public String getApplyEndDate() {
		return this.applyEndDate;
	}

	public void setApplyEndDate(String applyEndDate) {
		this.applyEndDate = applyEndDate;
	}

	@Column(name = "DESC_TXT", length = 100)
	public String getDescTxt() {
		return this.descTxt;
	}

	public void setDescTxt(String descTxt) {
		this.descTxt = descTxt;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
