package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;

/**
 * NcmMstDateId generated by hbm2java
 */

public class NcmMstDateId implements java.io.Serializable {

	private String calDate;
	private String calDivCd;

	public NcmMstDateId() {
	}

	public String getCalDate() {
		return this.calDate;
	}

	public void setCalDate(String calDate) {
		this.calDate = calDate;

	}

	public String getCalDivCd() {
		return this.calDivCd;
	}

	public void setCalDivCd(String calDivCd) {
		this.calDivCd = calDivCd;

	}

	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getCalDate());
		buffer.append("#").append(getCalDivCd());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstDateId))
			return false;
		NcmMstDateId castOther = (NcmMstDateId) other;

		return ((this.getCalDate() == castOther.getCalDate()) || (this.getCalDate() != null && castOther.getCalDate() != null && this.getCalDate().equals(castOther.getCalDate())))
				&& ((this.getCalDivCd() == castOther.getCalDivCd())
						|| (this.getCalDivCd() != null && castOther.getCalDivCd() != null && this.getCalDivCd().equals(castOther.getCalDivCd())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCalDate() == null ? 0 : this.getCalDate().hashCode());
		result = 37 * result + (getCalDivCd() == null ? 0 : this.getCalDivCd().hashCode());
		return result;
	}

}
