package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmMstBmcompositeTmp generated by hbm2java
 */
@Entity
@Table(name = "NCM_MST_BMCOMPOSITE_TMP", schema = "NCM")
public class NcmMstBmcompositeTmp implements java.io.Serializable {

	private NcmMstBmcompositeTmpId id;

	public NcmMstBmcompositeTmp() {
	}

	public NcmMstBmcompositeTmp(NcmMstBmcompositeTmpId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "bmId", column = @Column(name = "BM_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "bmAppoint", column = @Column(name = "BM_APPOINT", length = 2)),
			@AttributeOverride(name = "subBmId", column = @Column(name = "SUB_BM_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "compRatio", column = @Column(name = "COMP_RATIO", precision = 10, scale = 5)),
			@AttributeOverride(name = "applyStDate", column = @Column(name = "APPLY_ST_DATE", length = 8)),
			@AttributeOverride(name = "applyEndDate", column = @Column(name = "APPLY_END_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "srcTable", column = @Column(name = "SRC_TABLE", length = 20)),
			@AttributeOverride(name = "updateId", column = @Column(name = "UPDATE_ID", length = 20)),
			@AttributeOverride(name = "lastUpdate", column = @Column(name = "LAST_UPDATE", length = 7)) })
	public NcmMstBmcompositeTmpId getId() {
		return this.id;
	}

	public void setId(NcmMstBmcompositeTmpId id) {
		this.id = id;
	}

}
