package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMstPrgm generated by hbm2java
 */
@Entity
@Table(name = "NCM_MST_PRGM", schema = "NCM")
public class NcmMstPrgm implements java.io.Serializable {

	private String prgmId;
	private String menuId;
	private BigDecimal seqNo;
	private String menuNm;
	private String updateId;
	private Date lastUpdate;
	private String completeYn;

	public NcmMstPrgm() {
	}

	public NcmMstPrgm(String prgmId) {
		this.prgmId = prgmId;
	}

	public NcmMstPrgm(String prgmId, String menuId, BigDecimal seqNo, String menuNm, String updateId, Date lastUpdate,
			String completeYn) {
		this.prgmId = prgmId;
		this.menuId = menuId;
		this.seqNo = seqNo;
		this.menuNm = menuNm;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
		this.completeYn = completeYn;
	}

	@Id

	@Column(name = "PRGM_ID", unique = true, nullable = false, length = 100)
	public String getPrgmId() {
		return this.prgmId;
	}

	public void setPrgmId(String prgmId) {
		this.prgmId = prgmId;
	}

	@Column(name = "MENU_ID", length = 20)
	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	@Column(name = "SEQ_NO", precision = 22, scale = 0)
	public BigDecimal getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(BigDecimal seqNo) {
		this.seqNo = seqNo;
	}

	@Column(name = "MENU_NM", length = 100)
	public String getMenuNm() {
		return this.menuNm;
	}

	public void setMenuNm(String menuNm) {
		this.menuNm = menuNm;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "COMPLETE_YN", length = 1)
	public String getCompleteYn() {
		return this.completeYn;
	}

	public void setCompleteYn(String completeYn) {
		this.completeYn = completeYn;
	}

}
