package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMstProdType generated by hbm2java
 */

@Entity
@Table(name = "NCM_MST_PROD_TYPE", schema = "NCM")
public class NcmMstProdType implements java.io.Serializable {

	private String prodTypeCd;
	private String prodTypeNm;
	private String prodLclssCd;
	private String fixIntYn;
	private String guarYn;
	private String dmstDivCd;
	private String prodHldYn;
	private String hedgeDivCd;
	private String useYn;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMstProdType() {
	}

	@Id
	@Column(name = "PROD_TYPE_CD", unique = true, nullable = false, length = 10)
	public String getProdTypeCd() {
		return this.prodTypeCd;
	}

	public void setProdTypeCd(String prodTypeCd) {
		this.prodTypeCd = prodTypeCd;

	}

	@Column(name = "PROD_TYPE_NM", length = 100)
	public String getProdTypeNm() {
		return this.prodTypeNm;
	}

	public void setProdTypeNm(String prodTypeNm) {
		this.prodTypeNm = prodTypeNm;

	}

	@Column(name = "PROD_LCLSS_CD", length = 10)
	public String getProdLclssCd() {
		return this.prodLclssCd;
	}

	public void setProdLclssCd(String prodLclssCd) {
		this.prodLclssCd = prodLclssCd;

	}

	@Column(name = "FIX_INT_YN", length = 1)
	public String getFixIntYn() {
		return this.fixIntYn;
	}

	public void setFixIntYn(String fixIntYn) {
		this.fixIntYn = fixIntYn;

	}

	@Column(name = "GUAR_YN", length = 1)
	public String getGuarYn() {
		return this.guarYn;
	}

	public void setGuarYn(String guarYn) {
		this.guarYn = guarYn;

	}

	@Column(name = "DMST_DIV_CD", length = 10)
	public String getDmstDivCd() {
		return this.dmstDivCd;
	}

	public void setDmstDivCd(String dmstDivCd) {
		this.dmstDivCd = dmstDivCd;

	}

	@Column(name = "PROD_HLD_YN", length = 1)
	public String getProdHldYn() {
		return this.prodHldYn;
	}

	public void setProdHldYn(String prodHldYn) {
		this.prodHldYn = prodHldYn;

	}

	@Column(name = "HEDGE_DIV_CD", length = 10)
	public String getHedgeDivCd() {
		return this.hedgeDivCd;
	}

	public void setHedgeDivCd(String hedgeDivCd) {
		this.hedgeDivCd = hedgeDivCd;

	}

	@Column(name = "USE_YN", length = 1)
	public String getUseYn() {
		return this.useYn;
	}

	public void setUseYn(String useYn) {
		this.useYn = useYn;

	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getProdTypeCd());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstProdType))
			return false;
		NcmMstProdType castOther = (NcmMstProdType) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (idString() == null ? 0 : this.idString().hashCode());
		return result;
	}

}
