package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMmtTransaction generated by hbm2java
 */

@Entity
@IdClass(value = NcmMmtTransactionId.class)
@Table(name = "NCM_MMT_TRANSACTION", schema = "NCM")
public class NcmMmtTransaction implements java.io.Serializable {

	private String seqNo;
	private String trdDt;
	private String stockCd;
	private String acctCd;
	private String assetCd;
	private String trdGb;
	private Long trdCnt;
	private BigDecimal unitPrice;
	private Long trdPrice;
	private BigDecimal trdRet;
	private String setDt;
	private String exprDt;
	private String tranNo;
	private Date creDttm;
	private String creEmpNo;
	private Date chgDttm;
	private String chgEmpNo;
	private String workfilename;

	public NcmMmtTransaction() {
	}

	@Id
	@Column(name = "SEQ_NO", nullable = false, length = 7)
	public String getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(String seqNo) {
		this.seqNo = seqNo;
	}

	@Id
	@Column(name = "TRD_DT", nullable = false, length = 8)
	public String getTrdDt() {
		return this.trdDt;
	}

	public void setTrdDt(String trdDt) {
		this.trdDt = trdDt;
	}

	@Id
	@Column(name = "STOCK_CD", nullable = false, length = 13)
	public String getStockCd() {
		return this.stockCd;
	}

	public void setStockCd(String stockCd) {
		this.stockCd = stockCd;
	}

	@Id
	@Column(name = "ACCT_CD", nullable = false, length = 30)
	public String getAcctCd() {
		return this.acctCd;
	}

	public void setAcctCd(String acctCd) {
		this.acctCd = acctCd;
	}

	@Id
	@Column(name = "ASSET_CD", nullable = false, length = 12)
	public String getAssetCd() {
		return this.assetCd;
	}

	public void setAssetCd(String assetCd) {
		this.assetCd = assetCd;
	}

	@Id
	@Column(name = "TRD_GB", nullable = false, length = 1)
	public String getTrdGb() {
		return this.trdGb;
	}

	public void setTrdGb(String trdGb) {
		this.trdGb = trdGb;
	}

	@Column(name = "TRD_CNT", precision = 15, scale = 0)
	public Long getTrdCnt() {
		return this.trdCnt;
	}

	public void setTrdCnt(Long trdCnt) {
		this.trdCnt = trdCnt;

	}

	@Column(name = "UNIT_PRICE", precision = 15)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;

	}

	@Column(name = "TRD_PRICE", precision = 15, scale = 0)
	public Long getTrdPrice() {
		return this.trdPrice;
	}

	public void setTrdPrice(Long trdPrice) {
		this.trdPrice = trdPrice;

	}

	@Column(name = "TRD_RET", precision = 7, scale = 3)
	public BigDecimal getTrdRet() {
		return this.trdRet;
	}

	public void setTrdRet(BigDecimal trdRet) {
		this.trdRet = trdRet;

	}

	@Column(name = "SET_DT", length = 8)
	public String getSetDt() {
		return this.setDt;
	}

	public void setSetDt(String setDt) {
		this.setDt = setDt;

	}

	@Column(name = "EXPR_DT", length = 8)
	public String getExprDt() {
		return this.exprDt;
	}

	public void setExprDt(String exprDt) {
		this.exprDt = exprDt;

	}

	@Column(name = "TRAN_NO", length = 15)
	public String getTranNo() {
		return this.tranNo;
	}

	public void setTranNo(String tranNo) {
		this.tranNo = tranNo;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRE_DTTM", length = 7)
	public Date getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm) {
		this.creDttm = creDttm;

	}

	@Column(name = "CRE_EMP_NO", length = 6)
	public String getCreEmpNo() {
		return this.creEmpNo;
	}

	public void setCreEmpNo(String creEmpNo) {
		this.creEmpNo = creEmpNo;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHG_DTTM", length = 7)
	public Date getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(Date chgDttm) {
		this.chgDttm = chgDttm;

	}

	@Column(name = "CHG_EMP_NO", length = 6)
	public String getChgEmpNo() {
		return this.chgEmpNo;
	}

	public void setChgEmpNo(String chgEmpNo) {
		this.chgEmpNo = chgEmpNo;

	}

	@Column(name = "WORKFILENAME", length = 30)
	public String getWorkfilename() {
		return this.workfilename;
	}

	public void setWorkfilename(String workfilename) {
		this.workfilename = workfilename;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getSeqNo());
		buffer.append("#").append(getTrdDt());
		buffer.append("#").append(getStockCd());
		buffer.append("#").append(getAcctCd());
		buffer.append("#").append(getAssetCd());
		buffer.append("#").append(getTrdGb());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMmtTransaction))
			return false;
		NcmMmtTransaction castOther = (NcmMmtTransaction) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSeqNo() == null ? 0 : this.getSeqNo().hashCode());
		result = 37 * result + (getTrdDt() == null ? 0 : this.getTrdDt().hashCode());
		result = 37 * result + (getStockCd() == null ? 0 : this.getStockCd().hashCode());
		result = 37 * result + (getAcctCd() == null ? 0 : this.getAcctCd().hashCode());
		result = 37 * result + (getAssetCd() == null ? 0 : this.getAssetCd().hashCode());
		result = 37 * result + (getTrdGb() == null ? 0 : this.getTrdGb().hashCode());
		return result;
	}

}
