package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMstBmComp generated by hbm2java
 */

@Entity
@IdClass(value = NcmMstBmCompId.class)
@Table(name = "NCM_MST_BM_COMP", schema = "NCM")
public class NcmMstBmComp implements java.io.Serializable {

	private String bmId;
	private String applyStDate;
	private String subBmId;
	private BigDecimal subBmWght;
	private String applyEndDate;
	private String bmCreaTypeCd;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMstBmComp() {
	}

	@Id
	@Column(name = "BM_ID", nullable = false, length = 20)
	public String getBmId() {
		return this.bmId;
	}

	public void setBmId(String bmId) {
		this.bmId = bmId;
	}

	@Id
	@Column(name = "APPLY_ST_DATE", nullable = false, length = 8)
	public String getApplyStDate() {
		return this.applyStDate;
	}

	public void setApplyStDate(String applyStDate) {
		this.applyStDate = applyStDate;
	}

	@Id
	@Column(name = "SUB_BM_ID", nullable = false, length = 20)
	public String getSubBmId() {
		return this.subBmId;
	}

	public void setSubBmId(String subBmId) {
		this.subBmId = subBmId;
	}

	@Column(name = "SUB_BM_WGHT", precision = 10, scale = 5)
	public BigDecimal getSubBmWght() {
		return this.subBmWght;
	}

	public void setSubBmWght(BigDecimal subBmWght) {
		this.subBmWght = subBmWght;

	}

	@Column(name = "APPLY_END_DATE", nullable = false, length = 8)
	public String getApplyEndDate() {
		return this.applyEndDate;
	}

	public void setApplyEndDate(String applyEndDate) {
		this.applyEndDate = applyEndDate;

	}

	@Column(name = "BM_CREA_TYPE_CD", length = 10)
	public String getBmCreaTypeCd() {
		return this.bmCreaTypeCd;
	}

	public void setBmCreaTypeCd(String bmCreaTypeCd) {
		this.bmCreaTypeCd = bmCreaTypeCd;

	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBmId());
		buffer.append("#").append(getApplyStDate());
		buffer.append("#").append(getSubBmId());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstBmComp))
			return false;
		NcmMstBmComp castOther = (NcmMstBmComp) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBmId() == null ? 0 : this.getBmId().hashCode());
		result = 37 * result + (getApplyStDate() == null ? 0 : this.getApplyStDate().hashCode());
		result = 37 * result + (getSubBmId() == null ? 0 : this.getSubBmId().hashCode());
		return result;
	}

}
