package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMmtUnderPf generated by hbm2java
 */
@Entity
@Table(name = "NCM_MMT_UNDER_PF", schema = "NCM")
public class NcmMmtUnderPf implements java.io.Serializable {

	private NcmMmtUnderPfId id;
	private String pfCd;
	private String pfDetailCd;
	private String crdtGrdEval;
	private String pfAgNo;
	private String pfAgNm;
	private String pfAgCrdt;
	private String crdtGrdType;
	private String detailLst;
	private Date creDttm;
	private String creEmpNo;
	private Date chgDttm;
	private String chgEmpNo;
	private String workfilename;

	public NcmMmtUnderPf() {
	}

	public NcmMmtUnderPf(NcmMmtUnderPfId id, String pfCd, String pfDetailCd) {
		this.id = id;
		this.pfCd = pfCd;
		this.pfDetailCd = pfDetailCd;
	}

	public NcmMmtUnderPf(NcmMmtUnderPfId id, String pfCd, String pfDetailCd, String crdtGrdEval, String pfAgNo,
			String pfAgNm, String pfAgCrdt, String crdtGrdType, String detailLst, Date creDttm, String creEmpNo,
			Date chgDttm, String chgEmpNo, String workfilename) {
		this.id = id;
		this.pfCd = pfCd;
		this.pfDetailCd = pfDetailCd;
		this.crdtGrdEval = crdtGrdEval;
		this.pfAgNo = pfAgNo;
		this.pfAgNm = pfAgNm;
		this.pfAgCrdt = pfAgCrdt;
		this.crdtGrdType = crdtGrdType;
		this.detailLst = detailLst;
		this.creDttm = creDttm;
		this.creEmpNo = creEmpNo;
		this.chgDttm = chgDttm;
		this.chgEmpNo = chgEmpNo;
		this.workfilename = workfilename;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "seqNo", column = @Column(name = "SEQ_NO", nullable = false, length = 7)),
			@AttributeOverride(name = "bizDt", column = @Column(name = "BIZ_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "stockCd", column = @Column(name = "STOCK_CD", nullable = false, length = 13)),
			@AttributeOverride(name = "acctCd", column = @Column(name = "ACCT_CD", nullable = false, length = 30)),
			@AttributeOverride(name = "assetCd", column = @Column(name = "ASSET_CD", nullable = false, length = 12)),
			@AttributeOverride(name = "unastCd", column = @Column(name = "UNAST_CD", nullable = false, length = 14)),
			@AttributeOverride(name = "ordGb", column = @Column(name = "ORD_GB", nullable = false, precision = 8, scale = 0)) })
	public NcmMmtUnderPfId getId() {
		return this.id;
	}

	public void setId(NcmMmtUnderPfId id) {
		this.id = id;
	}

	@Column(name = "PF_CD", nullable = false, length = 2)
	public String getPfCd() {
		return this.pfCd;
	}

	public void setPfCd(String pfCd) {
		this.pfCd = pfCd;
	}

	@Column(name = "PF_DETAIL_CD", nullable = false, length = 2)
	public String getPfDetailCd() {
		return this.pfDetailCd;
	}

	public void setPfDetailCd(String pfDetailCd) {
		this.pfDetailCd = pfDetailCd;
	}

	@Column(name = "CRDT_GRD_EVAL", length = 2)
	public String getCrdtGrdEval() {
		return this.crdtGrdEval;
	}

	public void setCrdtGrdEval(String crdtGrdEval) {
		this.crdtGrdEval = crdtGrdEval;
	}

	@Column(name = "PF_AG_NO", length = 13)
	public String getPfAgNo() {
		return this.pfAgNo;
	}

	public void setPfAgNo(String pfAgNo) {
		this.pfAgNo = pfAgNo;
	}

	@Column(name = "PF_AG_NM", length = 30)
	public String getPfAgNm() {
		return this.pfAgNm;
	}

	public void setPfAgNm(String pfAgNm) {
		this.pfAgNm = pfAgNm;
	}

	@Column(name = "PF_AG_CRDT", length = 4)
	public String getPfAgCrdt() {
		return this.pfAgCrdt;
	}

	public void setPfAgCrdt(String pfAgCrdt) {
		this.pfAgCrdt = pfAgCrdt;
	}

	@Column(name = "CRDT_GRD_TYPE", length = 2)
	public String getCrdtGrdType() {
		return this.crdtGrdType;
	}

	public void setCrdtGrdType(String crdtGrdType) {
		this.crdtGrdType = crdtGrdType;
	}

	@Column(name = "DETAIL_LST", length = 500)
	public String getDetailLst() {
		return this.detailLst;
	}

	public void setDetailLst(String detailLst) {
		this.detailLst = detailLst;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRE_DTTM", length = 7)
	public Date getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm) {
		this.creDttm = creDttm;
	}

	@Column(name = "CRE_EMP_NO", length = 6)
	public String getCreEmpNo() {
		return this.creEmpNo;
	}

	public void setCreEmpNo(String creEmpNo) {
		this.creEmpNo = creEmpNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHG_DTTM", length = 7)
	public Date getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(Date chgDttm) {
		this.chgDttm = chgDttm;
	}

	@Column(name = "CHG_EMP_NO", length = 6)
	public String getChgEmpNo() {
		return this.chgEmpNo;
	}

	public void setChgEmpNo(String chgEmpNo) {
		this.chgEmpNo = chgEmpNo;
	}

	@Column(name = "WORKFILENAME", length = 30)
	public String getWorkfilename() {
		return this.workfilename;
	}

	public void setWorkfilename(String workfilename) {
		this.workfilename = workfilename;
	}

}
