package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * NcmMstProdTypeTmp generated by hbm2java
 */

@Entity
@IdClass(value = NcmMstProdTypeTmpId.class)
@Table(name = "NCM_MST_PROD_TYPE_TMP", schema = "NCM")
public class NcmMstProdTypeTmp implements java.io.Serializable {

	private String prodTypeCd;
	private String prodTypeNm;
	private String prodLclssCd;
	private String fixIntYn;
	private String guarYn;
	private String dmstDivCd;
	private String prodHldYn;
	private String hedgeDivCd;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMstProdTypeTmp() {
	}

	@Id
	@Column(name = "PROD_TYPE_CD", nullable = false, length = 10)
	public String getProdTypeCd() {
		return this.prodTypeCd;
	}

	public void setProdTypeCd(String prodTypeCd) {
		this.prodTypeCd = prodTypeCd;
	}

	@Id
	@Column(name = "PROD_TYPE_NM", length = 100)
	public String getProdTypeNm() {
		return this.prodTypeNm;
	}

	public void setProdTypeNm(String prodTypeNm) {
		this.prodTypeNm = prodTypeNm;
	}

	@Id
	@Column(name = "PROD_LCLSS_CD", length = 10)
	public String getProdLclssCd() {
		return this.prodLclssCd;
	}

	public void setProdLclssCd(String prodLclssCd) {
		this.prodLclssCd = prodLclssCd;
	}

	@Id
	@Column(name = "FIX_INT_YN", length = 1)
	public String getFixIntYn() {
		return this.fixIntYn;
	}

	public void setFixIntYn(String fixIntYn) {
		this.fixIntYn = fixIntYn;
	}

	@Id
	@Column(name = "GUAR_YN", length = 1)
	public String getGuarYn() {
		return this.guarYn;
	}

	public void setGuarYn(String guarYn) {
		this.guarYn = guarYn;
	}

	@Id
	@Column(name = "DMST_DIV_CD", length = 10)
	public String getDmstDivCd() {
		return this.dmstDivCd;
	}

	public void setDmstDivCd(String dmstDivCd) {
		this.dmstDivCd = dmstDivCd;
	}

	@Id
	@Column(name = "PROD_HLD_YN", length = 1)
	public String getProdHldYn() {
		return this.prodHldYn;
	}

	public void setProdHldYn(String prodHldYn) {
		this.prodHldYn = prodHldYn;
	}

	@Id
	@Column(name = "HEDGE_DIV_CD", length = 10)
	public String getHedgeDivCd() {
		return this.hedgeDivCd;
	}

	public void setHedgeDivCd(String hedgeDivCd) {
		this.hedgeDivCd = hedgeDivCd;
	}

	@Id
	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Id
	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Id
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getProdTypeCd());
		buffer.append("#").append(getProdTypeNm());
		buffer.append("#").append(getProdLclssCd());
		buffer.append("#").append(getFixIntYn());
		buffer.append("#").append(getGuarYn());
		buffer.append("#").append(getDmstDivCd());
		buffer.append("#").append(getProdHldYn());
		buffer.append("#").append(getHedgeDivCd());
		buffer.append("#").append(getSrcTable());
		buffer.append("#").append(getUpdateId());
		buffer.append("#").append(getLastUpdate());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstProdTypeTmp))
			return false;
		NcmMstProdTypeTmp castOther = (NcmMstProdTypeTmp) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProdTypeCd() == null ? 0 : this.getProdTypeCd().hashCode());
		result = 37 * result + (getProdTypeNm() == null ? 0 : this.getProdTypeNm().hashCode());
		result = 37 * result + (getProdLclssCd() == null ? 0 : this.getProdLclssCd().hashCode());
		result = 37 * result + (getFixIntYn() == null ? 0 : this.getFixIntYn().hashCode());
		result = 37 * result + (getGuarYn() == null ? 0 : this.getGuarYn().hashCode());
		result = 37 * result + (getDmstDivCd() == null ? 0 : this.getDmstDivCd().hashCode());
		result = 37 * result + (getProdHldYn() == null ? 0 : this.getProdHldYn().hashCode());
		result = 37 * result + (getHedgeDivCd() == null ? 0 : this.getHedgeDivCd().hashCode());
		result = 37 * result + (getSrcTable() == null ? 0 : this.getSrcTable().hashCode());
		result = 37 * result + (getUpdateId() == null ? 0 : this.getUpdateId().hashCode());
		result = 37 * result + (getLastUpdate() == null ? 0 : this.getLastUpdate().hashCode());
		return result;
	}

}
