package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmRptSaaPosStgTemp generated by hbm2java
 */
@Entity
@Table(name = "NCM_RPT_SAA_POS_STG_TEMP", schema = "NCM")
public class NcmRptSaaPosStgTemp implements java.io.Serializable {

	private NcmRptSaaPosStgTempId id;

	public NcmRptSaaPosStgTemp() {
	}

	public NcmRptSaaPosStgTemp(NcmRptSaaPosStgTempId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "prodTypeCd", column = @Column(name = "PROD_TYPE_CD", length = 10)),
			@AttributeOverride(name = "matCd", column = @Column(name = "MAT_CD", length = 10)),
			@AttributeOverride(name = "acctDivCd", column = @Column(name = "ACCT_DIV_CD", length = 10)),
			@AttributeOverride(name = "cptlDivCd", column = @Column(name = "CPTL_DIV_CD", length = 10)),
			@AttributeOverride(name = "mngOrgCorpNo", column = @Column(name = "MNG_ORG_CORP_NO", length = 20)),
			@AttributeOverride(name = "issuCorpNo", column = @Column(name = "ISSU_CORP_NO", length = 20)),
			@AttributeOverride(name = "saaCd", column = @Column(name = "SAA_CD", length = 20)),
			@AttributeOverride(name = "saaCdNm", column = @Column(name = "SAA_CD_NM", length = 100)),
			@AttributeOverride(name = "upperSaaCd", column = @Column(name = "UPPER_SAA_CD", length = 20)),
			@AttributeOverride(name = "invAmt", column = @Column(name = "INV_AMT", precision = 20)),
			@AttributeOverride(name = "subInvAmt", column = @Column(name = "SUB_INV_AMT", precision = 20)),
			@AttributeOverride(name = "srcTable", column = @Column(name = "SRC_TABLE", length = 20)),
			@AttributeOverride(name = "updateId", column = @Column(name = "UPDATE_ID", length = 20)),
			@AttributeOverride(name = "lastUpdate", column = @Column(name = "LAST_UPDATE", length = 7)) })
	public NcmRptSaaPosStgTempId getId() {
		return this.id;
	}

	public void setId(NcmRptSaaPosStgTempId id) {
		this.id = id;
	}

}
