package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmRptSaaPosOrg generated by hbm2java
 */

@Entity
@IdClass(value = NcmRptSaaPosOrgId.class)
@Table(name = "NCM_RPT_SAA_POS_ORG", schema = "NCM")
public class NcmRptSaaPosOrg implements java.io.Serializable {

	private String baseDate;
	private String cptlDivCd;
	private String mngOrgCorpNo;
	private String saaCd;
	private String saaCdNm;
	private String upperSaaCd;
	private Short saaOrder;
	private Short saaLv;
	private BigDecimal invAmt;
	private BigDecimal accuInvAmt;
	private BigDecimal mktEvalAmt;
	private BigDecimal accuMktEvalAmt;
	private BigDecimal adjDurAmt;
	private BigDecimal accuAdjDurAmt;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmRptSaaPosOrg() {
	}

	@Id
	@Column(name = "BASE_DATE", nullable = false, length = 8)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Id
	@Column(name = "CPTL_DIV_CD", nullable = false, length = 10)
	public String getCptlDivCd() {
		return this.cptlDivCd;
	}

	public void setCptlDivCd(String cptlDivCd) {
		this.cptlDivCd = cptlDivCd;
	}

	@Id
	@Column(name = "MNG_ORG_CORP_NO", nullable = false, length = 20)
	public String getMngOrgCorpNo() {
		return this.mngOrgCorpNo;
	}

	public void setMngOrgCorpNo(String mngOrgCorpNo) {
		this.mngOrgCorpNo = mngOrgCorpNo;
	}

	@Id
	@Column(name = "SAA_CD", nullable = false, length = 20)
	public String getSaaCd() {
		return this.saaCd;
	}

	public void setSaaCd(String saaCd) {
		this.saaCd = saaCd;
	}

	@Column(name = "SAA_CD_NM", length = 100)
	public String getSaaCdNm() {
		return this.saaCdNm;
	}

	public void setSaaCdNm(String saaCdNm) {
		this.saaCdNm = saaCdNm;

	}

	@Column(name = "UPPER_SAA_CD", length = 20)
	public String getUpperSaaCd() {
		return this.upperSaaCd;
	}

	public void setUpperSaaCd(String upperSaaCd) {
		this.upperSaaCd = upperSaaCd;

	}

	@Column(name = "SAA_ORDER", precision = 4, scale = 0)
	public Short getSaaOrder() {
		return this.saaOrder;
	}

	public void setSaaOrder(Short saaOrder) {
		this.saaOrder = saaOrder;

	}

	@Column(name = "SAA_LV", precision = 4, scale = 0)
	public Short getSaaLv() {
		return this.saaLv;
	}

	public void setSaaLv(Short saaLv) {
		this.saaLv = saaLv;

	}

	@Column(name = "INV_AMT", precision = 20)
	public BigDecimal getInvAmt() {
		return this.invAmt;
	}

	public void setInvAmt(BigDecimal invAmt) {
		this.invAmt = invAmt;

	}

	@Column(name = "ACCU_INV_AMT", precision = 20)
	public BigDecimal getAccuInvAmt() {
		return this.accuInvAmt;
	}

	public void setAccuInvAmt(BigDecimal accuInvAmt) {
		this.accuInvAmt = accuInvAmt;

	}

	@Column(name = "MKT_EVAL_AMT", precision = 20)
	public BigDecimal getMktEvalAmt() {
		return this.mktEvalAmt;
	}

	public void setMktEvalAmt(BigDecimal mktEvalAmt) {
		this.mktEvalAmt = mktEvalAmt;

	}

	@Column(name = "ACCU_MKT_EVAL_AMT", precision = 20)
	public BigDecimal getAccuMktEvalAmt() {
		return this.accuMktEvalAmt;
	}

	public void setAccuMktEvalAmt(BigDecimal accuMktEvalAmt) {
		this.accuMktEvalAmt = accuMktEvalAmt;

	}

	@Column(name = "ADJ_DUR_AMT", precision = 20)
	public BigDecimal getAdjDurAmt() {
		return this.adjDurAmt;
	}

	public void setAdjDurAmt(BigDecimal adjDurAmt) {
		this.adjDurAmt = adjDurAmt;

	}

	@Column(name = "ACCU_ADJ_DUR_AMT", precision = 20)
	public BigDecimal getAccuAdjDurAmt() {
		return this.accuAdjDurAmt;
	}

	public void setAccuAdjDurAmt(BigDecimal accuAdjDurAmt) {
		this.accuAdjDurAmt = accuAdjDurAmt;

	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getCptlDivCd());
		buffer.append("#").append(getMngOrgCorpNo());
		buffer.append("#").append(getSaaCd());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmRptSaaPosOrg))
			return false;
		NcmRptSaaPosOrg castOther = (NcmRptSaaPosOrg) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getCptlDivCd() == null ? 0 : this.getCptlDivCd().hashCode());
		result = 37 * result + (getMngOrgCorpNo() == null ? 0 : this.getMngOrgCorpNo().hashCode());
		result = 37 * result + (getSaaCd() == null ? 0 : this.getSaaCd().hashCode());
		return result;
	}

}
