package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmRptSaaPosOrg generated by hbm2java
 */
@Entity
@Table(name = "NCM_RPT_SAA_POS_ORG", schema = "NCM")
public class NcmRptSaaPosOrg implements java.io.Serializable {

	private NcmRptSaaPosOrgId id;
	private String saaCdNm;
	private String upperSaaCd;
	private Short saaOrder;
	private Short saaLv;
	private BigDecimal invAmt;
	private BigDecimal accuInvAmt;
	private BigDecimal mktEvalAmt;
	private BigDecimal accuMktEvalAmt;
	private BigDecimal adjDurAmt;
	private BigDecimal accuAdjDurAmt;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmRptSaaPosOrg() {
	}

	public NcmRptSaaPosOrg(NcmRptSaaPosOrgId id) {
		this.id = id;
	}

	public NcmRptSaaPosOrg(NcmRptSaaPosOrgId id, String saaCdNm, String upperSaaCd, Short saaOrder, Short saaLv,
			BigDecimal invAmt, BigDecimal accuInvAmt, BigDecimal mktEvalAmt, BigDecimal accuMktEvalAmt,
			BigDecimal adjDurAmt, BigDecimal accuAdjDurAmt, String srcTable, String updateId, Date lastUpdate) {
		this.id = id;
		this.saaCdNm = saaCdNm;
		this.upperSaaCd = upperSaaCd;
		this.saaOrder = saaOrder;
		this.saaLv = saaLv;
		this.invAmt = invAmt;
		this.accuInvAmt = accuInvAmt;
		this.mktEvalAmt = mktEvalAmt;
		this.accuMktEvalAmt = accuMktEvalAmt;
		this.adjDurAmt = adjDurAmt;
		this.accuAdjDurAmt = accuAdjDurAmt;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "cptlDivCd", column = @Column(name = "CPTL_DIV_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "mngOrgCorpNo", column = @Column(name = "MNG_ORG_CORP_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "saaCd", column = @Column(name = "SAA_CD", nullable = false, length = 20)) })
	public NcmRptSaaPosOrgId getId() {
		return this.id;
	}

	public void setId(NcmRptSaaPosOrgId id) {
		this.id = id;
	}

	@Column(name = "SAA_CD_NM", length = 100)
	public String getSaaCdNm() {
		return this.saaCdNm;
	}

	public void setSaaCdNm(String saaCdNm) {
		this.saaCdNm = saaCdNm;
	}

	@Column(name = "UPPER_SAA_CD", length = 20)
	public String getUpperSaaCd() {
		return this.upperSaaCd;
	}

	public void setUpperSaaCd(String upperSaaCd) {
		this.upperSaaCd = upperSaaCd;
	}

	@Column(name = "SAA_ORDER", precision = 4, scale = 0)
	public Short getSaaOrder() {
		return this.saaOrder;
	}

	public void setSaaOrder(Short saaOrder) {
		this.saaOrder = saaOrder;
	}

	@Column(name = "SAA_LV", precision = 4, scale = 0)
	public Short getSaaLv() {
		return this.saaLv;
	}

	public void setSaaLv(Short saaLv) {
		this.saaLv = saaLv;
	}

	@Column(name = "INV_AMT", precision = 20)
	public BigDecimal getInvAmt() {
		return this.invAmt;
	}

	public void setInvAmt(BigDecimal invAmt) {
		this.invAmt = invAmt;
	}

	@Column(name = "ACCU_INV_AMT", precision = 20)
	public BigDecimal getAccuInvAmt() {
		return this.accuInvAmt;
	}

	public void setAccuInvAmt(BigDecimal accuInvAmt) {
		this.accuInvAmt = accuInvAmt;
	}

	@Column(name = "MKT_EVAL_AMT", precision = 20)
	public BigDecimal getMktEvalAmt() {
		return this.mktEvalAmt;
	}

	public void setMktEvalAmt(BigDecimal mktEvalAmt) {
		this.mktEvalAmt = mktEvalAmt;
	}

	@Column(name = "ACCU_MKT_EVAL_AMT", precision = 20)
	public BigDecimal getAccuMktEvalAmt() {
		return this.accuMktEvalAmt;
	}

	public void setAccuMktEvalAmt(BigDecimal accuMktEvalAmt) {
		this.accuMktEvalAmt = accuMktEvalAmt;
	}

	@Column(name = "ADJ_DUR_AMT", precision = 20)
	public BigDecimal getAdjDurAmt() {
		return this.adjDurAmt;
	}

	public void setAdjDurAmt(BigDecimal adjDurAmt) {
		this.adjDurAmt = adjDurAmt;
	}

	@Column(name = "ACCU_ADJ_DUR_AMT", precision = 20)
	public BigDecimal getAccuAdjDurAmt() {
		return this.accuAdjDurAmt;
	}

	public void setAccuAdjDurAmt(BigDecimal accuAdjDurAmt) {
		this.accuAdjDurAmt = accuAdjDurAmt;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
