package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmRptSaaPosStg generated by hbm2java
 */
@Entity
@Table(name = "NCM_RPT_SAA_POS_STG", schema = "NCM")
public class NcmRptSaaPosStg implements java.io.Serializable {

	private NcmRptSaaPosStgId id;
	private String saaCdNm;
	private String upperSaaCd;
	private BigDecimal invAmt;
	private BigDecimal bookAmt;
	private BigDecimal mktEvalAmt;
	private BigDecimal adjDurAmt;
	private BigDecimal ytmAmt;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmRptSaaPosStg() {
	}

	public NcmRptSaaPosStg(NcmRptSaaPosStgId id) {
		this.id = id;
	}

	public NcmRptSaaPosStg(NcmRptSaaPosStgId id, String saaCdNm, String upperSaaCd, BigDecimal invAmt,
			BigDecimal bookAmt, BigDecimal mktEvalAmt, BigDecimal adjDurAmt, BigDecimal ytmAmt, String srcTable,
			String updateId, Date lastUpdate) {
		this.id = id;
		this.saaCdNm = saaCdNm;
		this.upperSaaCd = upperSaaCd;
		this.invAmt = invAmt;
		this.bookAmt = bookAmt;
		this.mktEvalAmt = mktEvalAmt;
		this.adjDurAmt = adjDurAmt;
		this.ytmAmt = ytmAmt;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "prodTypeCd", column = @Column(name = "PROD_TYPE_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "matCd", column = @Column(name = "MAT_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "acctDivCd", column = @Column(name = "ACCT_DIV_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "cptlDivCd", column = @Column(name = "CPTL_DIV_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "mngOrgCorpNo", column = @Column(name = "MNG_ORG_CORP_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "issuCorpNo", column = @Column(name = "ISSU_CORP_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "saaCd", column = @Column(name = "SAA_CD", nullable = false, length = 20)) })
	public NcmRptSaaPosStgId getId() {
		return this.id;
	}

	public void setId(NcmRptSaaPosStgId id) {
		this.id = id;
	}

	@Column(name = "SAA_CD_NM", length = 100)
	public String getSaaCdNm() {
		return this.saaCdNm;
	}

	public void setSaaCdNm(String saaCdNm) {
		this.saaCdNm = saaCdNm;
	}

	@Column(name = "UPPER_SAA_CD", length = 20)
	public String getUpperSaaCd() {
		return this.upperSaaCd;
	}

	public void setUpperSaaCd(String upperSaaCd) {
		this.upperSaaCd = upperSaaCd;
	}

	@Column(name = "INV_AMT", precision = 20)
	public BigDecimal getInvAmt() {
		return this.invAmt;
	}

	public void setInvAmt(BigDecimal invAmt) {
		this.invAmt = invAmt;
	}

	@Column(name = "BOOK_AMT", precision = 20)
	public BigDecimal getBookAmt() {
		return this.bookAmt;
	}

	public void setBookAmt(BigDecimal bookAmt) {
		this.bookAmt = bookAmt;
	}

	@Column(name = "MKT_EVAL_AMT", precision = 20)
	public BigDecimal getMktEvalAmt() {
		return this.mktEvalAmt;
	}

	public void setMktEvalAmt(BigDecimal mktEvalAmt) {
		this.mktEvalAmt = mktEvalAmt;
	}

	@Column(name = "ADJ_DUR_AMT", precision = 20, scale = 6)
	public BigDecimal getAdjDurAmt() {
		return this.adjDurAmt;
	}

	public void setAdjDurAmt(BigDecimal adjDurAmt) {
		this.adjDurAmt = adjDurAmt;
	}

	@Column(name = "YTM_AMT", precision = 20, scale = 6)
	public BigDecimal getYtmAmt() {
		return this.ytmAmt;
	}

	public void setYtmAmt(BigDecimal ytmAmt) {
		this.ytmAmt = ytmAmt;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
