package com.eugenefe.ncm;
// Generated Dec 8, 2016 3:49:34 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

/**
 * NcmRptPosDetailId generated by hbm2java
 */

public class NcmRptPosDetailId implements java.io.Serializable, Navigatable {

	private String baseDate;
	private String posDiv;
	private String posId;
	private String subProdId;
	private String finTxNo;

	public NcmRptPosDetailId() {
	}

	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;

	}

	public String getPosDiv() {
		return this.posDiv;
	}

	public void setPosDiv(String posDiv) {
		this.posDiv = posDiv;

	}

	public String getPosId() {
		return this.posId;
	}

	public void setPosId(String posId) {
		this.posId = posId;

	}

	public String getSubProdId() {
		return this.subProdId;
	}

	public void setSubProdId(String subProdId) {
		this.subProdId = subProdId;

	}

	public String getFinTxNo() {
		return this.finTxNo;
	}

	public void setFinTxNo(String finTxNo) {
		this.finTxNo = finTxNo;

	}

	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getPosDiv());
		buffer.append("#").append(getPosId());
		buffer.append("#").append(getSubProdId());
		buffer.append("#").append(getFinTxNo());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmRptPosDetailId))
			return false;
		NcmRptPosDetailId castOther = (NcmRptPosDetailId) other;

		return ((this.getBaseDate() == castOther.getBaseDate())
				|| (this.getBaseDate() != null && castOther.getBaseDate() != null && this.getBaseDate().equals(castOther.getBaseDate())))
				&& ((this.getPosDiv() == castOther.getPosDiv()) || (this.getPosDiv() != null && castOther.getPosDiv() != null && this.getPosDiv().equals(castOther.getPosDiv())))
				&& ((this.getPosId() == castOther.getPosId()) || (this.getPosId() != null && castOther.getPosId() != null && this.getPosId().equals(castOther.getPosId())))
				&& ((this.getSubProdId() == castOther.getSubProdId())
						|| (this.getSubProdId() != null && castOther.getSubProdId() != null && this.getSubProdId().equals(castOther.getSubProdId())))
				&& ((this.getFinTxNo() == castOther.getFinTxNo())
						|| (this.getFinTxNo() != null && castOther.getFinTxNo() != null && this.getFinTxNo().equals(castOther.getFinTxNo())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getPosDiv() == null ? 0 : this.getPosDiv().hashCode());
		result = 37 * result + (getPosId() == null ? 0 : this.getPosId().hashCode());
		result = 37 * result + (getSubProdId() == null ? 0 : this.getSubProdId().hashCode());
		result = 37 * result + (getFinTxNo() == null ? 0 : this.getFinTxNo().hashCode());
		return result;
	}

}
