package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmRptSaaSubpos generated by hbm2java
 */
@Entity
@Table(name = "NCM_RPT_SAA_SUBPOS", schema = "NCM")
public class NcmRptSaaSubpos implements java.io.Serializable {

	private NcmRptSaaSubposId id;
	private String cptlDivCd;
	private String saaCdNm;
	private String upperSaaCd;
	private BigDecimal invAmt;
	private BigDecimal subInvAmt;
	private BigDecimal accuInvAmt;
	private BigDecimal accuSubInvAmt;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmRptSaaSubpos() {
	}

	public NcmRptSaaSubpos(NcmRptSaaSubposId id) {
		this.id = id;
	}

	public NcmRptSaaSubpos(NcmRptSaaSubposId id, String cptlDivCd, String saaCdNm, String upperSaaCd, BigDecimal invAmt,
			BigDecimal subInvAmt, BigDecimal accuInvAmt, BigDecimal accuSubInvAmt, String srcTable, String updateId,
			Date lastUpdate) {
		this.id = id;
		this.cptlDivCd = cptlDivCd;
		this.saaCdNm = saaCdNm;
		this.upperSaaCd = upperSaaCd;
		this.invAmt = invAmt;
		this.subInvAmt = subInvAmt;
		this.accuInvAmt = accuInvAmt;
		this.accuSubInvAmt = accuSubInvAmt;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "prodTypeCd", column = @Column(name = "PROD_TYPE_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "matCd", column = @Column(name = "MAT_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "acctDivCd", column = @Column(name = "ACCT_DIV_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "mngOrgCorpNo", column = @Column(name = "MNG_ORG_CORP_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "issuCorpNo", column = @Column(name = "ISSU_CORP_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "subProdTypeCd", column = @Column(name = "SUB_PROD_TYPE_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "saaCd", column = @Column(name = "SAA_CD", nullable = false, length = 20)) })
	public NcmRptSaaSubposId getId() {
		return this.id;
	}

	public void setId(NcmRptSaaSubposId id) {
		this.id = id;
	}

	@Column(name = "CPTL_DIV_CD", length = 10)
	public String getCptlDivCd() {
		return this.cptlDivCd;
	}

	public void setCptlDivCd(String cptlDivCd) {
		this.cptlDivCd = cptlDivCd;
	}

	@Column(name = "SAA_CD_NM", length = 100)
	public String getSaaCdNm() {
		return this.saaCdNm;
	}

	public void setSaaCdNm(String saaCdNm) {
		this.saaCdNm = saaCdNm;
	}

	@Column(name = "UPPER_SAA_CD", length = 20)
	public String getUpperSaaCd() {
		return this.upperSaaCd;
	}

	public void setUpperSaaCd(String upperSaaCd) {
		this.upperSaaCd = upperSaaCd;
	}

	@Column(name = "INV_AMT", precision = 20)
	public BigDecimal getInvAmt() {
		return this.invAmt;
	}

	public void setInvAmt(BigDecimal invAmt) {
		this.invAmt = invAmt;
	}

	@Column(name = "SUB_INV_AMT", precision = 20)
	public BigDecimal getSubInvAmt() {
		return this.subInvAmt;
	}

	public void setSubInvAmt(BigDecimal subInvAmt) {
		this.subInvAmt = subInvAmt;
	}

	@Column(name = "ACCU_INV_AMT", precision = 20)
	public BigDecimal getAccuInvAmt() {
		return this.accuInvAmt;
	}

	public void setAccuInvAmt(BigDecimal accuInvAmt) {
		this.accuInvAmt = accuInvAmt;
	}

	@Column(name = "ACCU_SUB_INV_AMT", precision = 20)
	public BigDecimal getAccuSubInvAmt() {
		return this.accuSubInvAmt;
	}

	public void setAccuSubInvAmt(BigDecimal accuSubInvAmt) {
		this.accuSubInvAmt = accuSubInvAmt;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
