package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmRptSaaSubposStg generated by hbm2java
 */
@Entity
@Table(name = "NCM_RPT_SAA_SUBPOS_STG", schema = "NCM")
public class NcmRptSaaSubposStg implements java.io.Serializable {

	private NcmRptSaaSubposStgId id;
	private String saaCdNm;
	private String upperSaaCd;
	private BigDecimal invAmt;
	private BigDecimal subInvAmt;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmRptSaaSubposStg() {
	}

	public NcmRptSaaSubposStg(NcmRptSaaSubposStgId id) {
		this.id = id;
	}

	public NcmRptSaaSubposStg(NcmRptSaaSubposStgId id, String saaCdNm, String upperSaaCd, BigDecimal invAmt,
			BigDecimal subInvAmt, String srcTable, String updateId, Date lastUpdate) {
		this.id = id;
		this.saaCdNm = saaCdNm;
		this.upperSaaCd = upperSaaCd;
		this.invAmt = invAmt;
		this.subInvAmt = subInvAmt;
		this.srcTable = srcTable;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 8)),
			@AttributeOverride(name = "prodTypeCd", column = @Column(name = "PROD_TYPE_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "matCd", column = @Column(name = "MAT_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "acctDivCd", column = @Column(name = "ACCT_DIV_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "cptlDivCd", column = @Column(name = "CPTL_DIV_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "mngOrgCorpNo", column = @Column(name = "MNG_ORG_CORP_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "issuCorpNo", column = @Column(name = "ISSU_CORP_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "subProdTypeCd", column = @Column(name = "SUB_PROD_TYPE_CD", nullable = false, length = 10)),
			@AttributeOverride(name = "saaCd", column = @Column(name = "SAA_CD", nullable = false, length = 20)) })
	public NcmRptSaaSubposStgId getId() {
		return this.id;
	}

	public void setId(NcmRptSaaSubposStgId id) {
		this.id = id;
	}

	@Column(name = "SAA_CD_NM", length = 100)
	public String getSaaCdNm() {
		return this.saaCdNm;
	}

	public void setSaaCdNm(String saaCdNm) {
		this.saaCdNm = saaCdNm;
	}

	@Column(name = "UPPER_SAA_CD", length = 20)
	public String getUpperSaaCd() {
		return this.upperSaaCd;
	}

	public void setUpperSaaCd(String upperSaaCd) {
		this.upperSaaCd = upperSaaCd;
	}

	@Column(name = "INV_AMT", precision = 20)
	public BigDecimal getInvAmt() {
		return this.invAmt;
	}

	public void setInvAmt(BigDecimal invAmt) {
		this.invAmt = invAmt;
	}

	@Column(name = "SUB_INV_AMT", precision = 20)
	public BigDecimal getSubInvAmt() {
		return this.subInvAmt;
	}

	public void setSubInvAmt(BigDecimal subInvAmt) {
		this.subInvAmt = subInvAmt;
	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
