package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NcmRptPosDetailId generated by hbm2java
 */
@Embeddable
public class NcmRptPosDetailId implements java.io.Serializable {

	private String baseDate;
	private String posDiv;
	private String posId;
	private String subProdId;
	private String finTxNo;

	public NcmRptPosDetailId() {
	}

	public NcmRptPosDetailId(String baseDate, String posDiv, String posId, String subProdId, String finTxNo) {
		this.baseDate = baseDate;
		this.posDiv = posDiv;
		this.posId = posId;
		this.subProdId = subProdId;
		this.finTxNo = finTxNo;
	}

	@Column(name = "BASE_DATE", nullable = false, length = 8)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Column(name = "POS_DIV", nullable = false, length = 10)
	public String getPosDiv() {
		return this.posDiv;
	}

	public void setPosDiv(String posDiv) {
		this.posDiv = posDiv;
	}

	@Column(name = "POS_ID", nullable = false, length = 100)
	public String getPosId() {
		return this.posId;
	}

	public void setPosId(String posId) {
		this.posId = posId;
	}

	@Column(name = "SUB_PROD_ID", nullable = false, length = 100)
	public String getSubProdId() {
		return this.subProdId;
	}

	public void setSubProdId(String subProdId) {
		this.subProdId = subProdId;
	}

	@Column(name = "FIN_TX_NO", nullable = false, length = 10)
	public String getFinTxNo() {
		return this.finTxNo;
	}

	public void setFinTxNo(String finTxNo) {
		this.finTxNo = finTxNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmRptPosDetailId))
			return false;
		NcmRptPosDetailId castOther = (NcmRptPosDetailId) other;

		return ((this.getBaseDate() == castOther.getBaseDate()) || (this.getBaseDate() != null
				&& castOther.getBaseDate() != null && this.getBaseDate().equals(castOther.getBaseDate())))
				&& ((this.getPosDiv() == castOther.getPosDiv()) || (this.getPosDiv() != null
						&& castOther.getPosDiv() != null && this.getPosDiv().equals(castOther.getPosDiv())))
				&& ((this.getPosId() == castOther.getPosId()) || (this.getPosId() != null
						&& castOther.getPosId() != null && this.getPosId().equals(castOther.getPosId())))
				&& ((this.getSubProdId() == castOther.getSubProdId()) || (this.getSubProdId() != null
						&& castOther.getSubProdId() != null && this.getSubProdId().equals(castOther.getSubProdId())))
				&& ((this.getFinTxNo() == castOther.getFinTxNo()) || (this.getFinTxNo() != null
						&& castOther.getFinTxNo() != null && this.getFinTxNo().equals(castOther.getFinTxNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getPosDiv() == null ? 0 : this.getPosDiv().hashCode());
		result = 37 * result + (getPosId() == null ? 0 : this.getPosId().hashCode());
		result = 37 * result + (getSubProdId() == null ? 0 : this.getSubProdId().hashCode());
		result = 37 * result + (getFinTxNo() == null ? 0 : this.getFinTxNo().hashCode());
		return result;
	}

}
