package com.eugenefe.ncm;
// Generated Dec 7, 2016 4:47:20 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;

/**
 * NcmVldRstId generated by hbm2java
 */

public class NcmVldRstId implements java.io.Serializable {

	private String baseDate;
	private String vldTypeCd;
	private short seq;

	public NcmVldRstId() {
	}

	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;

	}

	public String getVldTypeCd() {
		return this.vldTypeCd;
	}

	public void setVldTypeCd(String vldTypeCd) {
		this.vldTypeCd = vldTypeCd;

	}

	public short getSeq() {
		return this.seq;
	}

	public void setSeq(short seq) {
		this.seq = seq;

	}

	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getVldTypeCd());
		buffer.append("#").append(getSeq());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmVldRstId))
			return false;
		NcmVldRstId castOther = (NcmVldRstId) other;

		return ((this.getBaseDate() == castOther.getBaseDate())
				|| (this.getBaseDate() != null && castOther.getBaseDate() != null && this.getBaseDate().equals(castOther.getBaseDate())))
				&& ((this.getVldTypeCd() == castOther.getVldTypeCd())
						|| (this.getVldTypeCd() != null && castOther.getVldTypeCd() != null && this.getVldTypeCd().equals(castOther.getVldTypeCd())))
				&& (this.getSeq() == castOther.getSeq());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getVldTypeCd() == null ? 0 : this.getVldTypeCd().hashCode());
		result = 37 * result + this.getSeq();
		return result;
	}

}
