package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmWebUsrRstrctRes generated by hbm2java
 */
@Entity
@Table(name = "NCM_WEB_USR_RSTRCT_RES", schema = "NCM")
public class NcmWebUsrRstrctRes implements java.io.Serializable {

	private NcmWebUsrRstrctResId id;
	private Date creatDt;

	public NcmWebUsrRstrctRes() {
	}

	public NcmWebUsrRstrctRes(NcmWebUsrRstrctResId id, Date creatDt) {
		this.id = id;
		this.creatDt = creatDt;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "resId", column = @Column(name = "RES_ID", nullable = false, length = 200)),
			@AttributeOverride(name = "empNo", column = @Column(name = "EMP_NO", nullable = false, length = 20)) })
	public NcmWebUsrRstrctResId getId() {
		return this.id;
	}

	public void setId(NcmWebUsrRstrctResId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREAT_DT", nullable = false, length = 7)
	public Date getCreatDt() {
		return this.creatDt;
	}

	public void setCreatDt(Date creatDt) {
		this.creatDt = creatDt;
	}

}
