package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NcmWebBoard generated by hbm2java
 */
@Entity
@Table(name = "NCM_WEB_BOARD", schema = "NCM")
public class NcmWebBoard implements java.io.Serializable {

	private String idx;
	private String schdDivCd;
	private String schdDivLv;
	private String fromdate;
	private String fromhhmm;
	private String todate;
	private String tohhmm;
	private String createdId;
	private String title;
	private String contentsTxt;
	private String createdDate;
	private Integer hitCnt;
	private String delYn;

	public NcmWebBoard() {
	}

	public NcmWebBoard(String idx) {
		this.idx = idx;
	}

	public NcmWebBoard(String idx, String schdDivCd, String schdDivLv, String fromdate, String fromhhmm, String todate,
			String tohhmm, String createdId, String title, String contentsTxt, String createdDate, Integer hitCnt,
			String delYn) {
		this.idx = idx;
		this.schdDivCd = schdDivCd;
		this.schdDivLv = schdDivLv;
		this.fromdate = fromdate;
		this.fromhhmm = fromhhmm;
		this.todate = todate;
		this.tohhmm = tohhmm;
		this.createdId = createdId;
		this.title = title;
		this.contentsTxt = contentsTxt;
		this.createdDate = createdDate;
		this.hitCnt = hitCnt;
		this.delYn = delYn;
	}

	@Id

	@Column(name = "IDX", unique = true, nullable = false, length = 100)
	public String getIdx() {
		return this.idx;
	}

	public void setIdx(String idx) {
		this.idx = idx;
	}

	@Column(name = "SCHD_DIV_CD", length = 10)
	public String getSchdDivCd() {
		return this.schdDivCd;
	}

	public void setSchdDivCd(String schdDivCd) {
		this.schdDivCd = schdDivCd;
	}

	@Column(name = "SCHD_DIV_LV", length = 4)
	public String getSchdDivLv() {
		return this.schdDivLv;
	}

	public void setSchdDivLv(String schdDivLv) {
		this.schdDivLv = schdDivLv;
	}

	@Column(name = "FROMDATE", length = 8)
	public String getFromdate() {
		return this.fromdate;
	}

	public void setFromdate(String fromdate) {
		this.fromdate = fromdate;
	}

	@Column(name = "FROMHHMM", length = 4)
	public String getFromhhmm() {
		return this.fromhhmm;
	}

	public void setFromhhmm(String fromhhmm) {
		this.fromhhmm = fromhhmm;
	}

	@Column(name = "TODATE", length = 8)
	public String getTodate() {
		return this.todate;
	}

	public void setTodate(String todate) {
		this.todate = todate;
	}

	@Column(name = "TOHHMM", length = 4)
	public String getTohhmm() {
		return this.tohhmm;
	}

	public void setTohhmm(String tohhmm) {
		this.tohhmm = tohhmm;
	}

	@Column(name = "CREATED_ID", length = 1000)
	public String getCreatedId() {
		return this.createdId;
	}

	public void setCreatedId(String createdId) {
		this.createdId = createdId;
	}

	@Column(name = "TITLE", length = 4000)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "CONTENTS_TXT", length = 4000)
	public String getContentsTxt() {
		return this.contentsTxt;
	}

	public void setContentsTxt(String contentsTxt) {
		this.contentsTxt = contentsTxt;
	}

	@Column(name = "CREATED_DATE", length = 1000)
	public String getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "HIT_CNT", precision = 8, scale = 0)
	public Integer getHitCnt() {
		return this.hitCnt;
	}

	public void setHitCnt(Integer hitCnt) {
		this.hitCnt = hitCnt;
	}

	@Column(name = "DEL_YN", length = 2)
	public String getDelYn() {
		return this.delYn;
	}

	public void setDelYn(String delYn) {
		this.delYn = delYn;
	}

}
