package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmWebExcelLog generated by hbm2java
 */
@Entity
@Table(name = "NCM_WEB_EXCEL_LOG", schema = "NCM")
public class NcmWebExcelLog implements java.io.Serializable {

	private NcmWebExcelLogId id;

	public NcmWebExcelLog() {
	}

	public NcmWebExcelLog(NcmWebExcelLogId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "empNo", column = @Column(name = "EMP_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "xlsCd", column = @Column(name = "XLS_CD", nullable = false, length = 20)),
			@AttributeOverride(name = "lastUpdate", column = @Column(name = "LAST_UPDATE", length = 7)) })
	public NcmWebExcelLogId getId() {
		return this.id;
	}

	public void setId(NcmWebExcelLogId id) {
		this.id = id;
	}

}
