package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmWebSchedule generated by hbm2java
 */
@Entity
@Table(name = "NCM_WEB_SCHEDULE", schema = "NCM")
public class NcmWebSchedule implements java.io.Serializable {

	private NcmWebScheduleId id;

	public NcmWebSchedule() {
	}

	public NcmWebSchedule(NcmWebScheduleId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "title", column = @Column(name = "TITLE", length = 4000)),
			@AttributeOverride(name = "description", column = @Column(name = "DESCRIPTION", length = 4000)),
			@AttributeOverride(name = "icon", column = @Column(name = "ICON", length = 4000)),
			@AttributeOverride(name = "classname", column = @Column(name = "CLASSNAME", length = 4000)),
			@AttributeOverride(name = "DStart", column = @Column(name = "D_START", length = 4000)),
			@AttributeOverride(name = "DEnd", column = @Column(name = "D_END", length = 4000)) })
	public NcmWebScheduleId getId() {
		return this.id;
	}

	public void setId(NcmWebScheduleId id) {
		this.id = id;
	}

}
