package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NcmWebStockTempId generated by hbm2java
 */
@Embeddable
public class NcmWebStockTempId implements java.io.Serializable {

	private String baseDate;
	private String bizDiv;
	private String sum;

	public NcmWebStockTempId() {
	}

	public NcmWebStockTempId(String baseDate, String bizDiv, String sum) {
		this.baseDate = baseDate;
		this.bizDiv = bizDiv;
		this.sum = sum;
	}

	@Column(name = "BASE_DATE", length = 3000)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Column(name = "BIZ_DIV", length = 3000)
	public String getBizDiv() {
		return this.bizDiv;
	}

	public void setBizDiv(String bizDiv) {
		this.bizDiv = bizDiv;
	}

	@Column(name = "SUM", length = 3000)
	public String getSum() {
		return this.sum;
	}

	public void setSum(String sum) {
		this.sum = sum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmWebStockTempId))
			return false;
		NcmWebStockTempId castOther = (NcmWebStockTempId) other;

		return ((this.getBaseDate() == castOther.getBaseDate()) || (this.getBaseDate() != null
				&& castOther.getBaseDate() != null && this.getBaseDate().equals(castOther.getBaseDate())))
				&& ((this.getBizDiv() == castOther.getBizDiv()) || (this.getBizDiv() != null
						&& castOther.getBizDiv() != null && this.getBizDiv().equals(castOther.getBizDiv())))
				&& ((this.getSum() == castOther.getSum()) || (this.getSum() != null && castOther.getSum() != null
						&& this.getSum().equals(castOther.getSum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getBizDiv() == null ? 0 : this.getBizDiv().hashCode());
		result = 37 * result + (getSum() == null ? 0 : this.getSum().hashCode());
		return result;
	}

}
