package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmWebStockTemp generated by hbm2java
 */
@Entity
@Table(name = "NCM_WEB_STOCK_TEMP", schema = "NCM")
public class NcmWebStockTemp implements java.io.Serializable {

	private NcmWebStockTempId id;

	public NcmWebStockTemp() {
	}

	public NcmWebStockTemp(NcmWebStockTempId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", length = 3000)),
			@AttributeOverride(name = "bizDiv", column = @Column(name = "BIZ_DIV", length = 3000)),
			@AttributeOverride(name = "sum", column = @Column(name = "SUM", length = 3000)) })
	public NcmWebStockTempId getId() {
		return this.id;
	}

	public void setId(NcmWebStockTempId id) {
		this.id = id;
	}

}
