package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NcmWebDept generated by hbm2java
 */
@Entity
@Table(name = "NCM_WEB_DEPT", schema = "NCM")
public class NcmWebDept implements java.io.Serializable {

	private String deptCd;
	private String deptNm;
	private String deptDsc;
	private Set<NcmWebUser> ncmWebUsers = new HashSet<NcmWebUser>(0);

	public NcmWebDept() {
	}

	public NcmWebDept(String deptCd, String deptNm) {
		this.deptCd = deptCd;
		this.deptNm = deptNm;
	}

	public NcmWebDept(String deptCd, String deptNm, String deptDsc, Set<NcmWebUser> ncmWebUsers) {
		this.deptCd = deptCd;
		this.deptNm = deptNm;
		this.deptDsc = deptDsc;
		this.ncmWebUsers = ncmWebUsers;
	}

	@Id

	@Column(name = "DEPT_CD", unique = true, nullable = false, length = 4)
	public String getDeptCd() {
		return this.deptCd;
	}

	public void setDeptCd(String deptCd) {
		this.deptCd = deptCd;
	}

	@Column(name = "DEPT_NM", nullable = false, length = 60)
	public String getDeptNm() {
		return this.deptNm;
	}

	public void setDeptNm(String deptNm) {
		this.deptNm = deptNm;
	}

	@Column(name = "DEPT_DSC", length = 100)
	public String getDeptDsc() {
		return this.deptDsc;
	}

	public void setDeptDsc(String deptDsc) {
		this.deptDsc = deptDsc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ncmWebDept")
	public Set<NcmWebUser> getNcmWebUsers() {
		return this.ncmWebUsers;
	}

	public void setNcmWebUsers(Set<NcmWebUser> ncmWebUsers) {
		this.ncmWebUsers = ncmWebUsers;
	}

}
