package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NcmWebRes generated by hbm2java
 */
@Entity
@Table(name = "NCM_WEB_RES", schema = "NCM")
public class NcmWebRes implements java.io.Serializable {

	private NcmWebResId id;

	public NcmWebRes() {
	}

	public NcmWebRes(NcmWebResId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "resId", column = @Column(name = "RES_ID", nullable = false, length = 200)),
			@AttributeOverride(name = "type", column = @Column(name = "TYPE", nullable = false, length = 10)),
			@AttributeOverride(name = "pattern", column = @Column(name = "PATTERN", nullable = false, length = 300)),
			@AttributeOverride(name = "creatDt", column = @Column(name = "CREAT_DT", length = 7)),
			@AttributeOverride(name = "mod", column = @Column(name = "MOD", precision = 22, scale = 0)) })
	public NcmWebResId getId() {
		return this.id;
	}

	public void setId(NcmWebResId id) {
		this.id = id;
	}

}
