package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NcmWebUsrscrst generated by hbm2java
 */
@Entity
@Table(name = "NCM_WEB_USRSCRST", schema = "NCM")
public class NcmWebUsrscrst implements java.io.Serializable {

	private String empNo;
	private NcmWebAuthor ncmWebAuthor;

	public NcmWebUsrscrst() {
	}

	public NcmWebUsrscrst(String empNo, NcmWebAuthor ncmWebAuthor) {
		this.empNo = empNo;
		this.ncmWebAuthor = ncmWebAuthor;
	}

	@Id

	@Column(name = "EMP_NO", unique = true, nullable = false, length = 20)
	public String getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(String empNo) {
		this.empNo = empNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AUTHOR_CODE", nullable = false)
	public NcmWebAuthor getNcmWebAuthor() {
		return this.ncmWebAuthor;
	}

	public void setNcmWebAuthor(NcmWebAuthor ncmWebAuthor) {
		this.ncmWebAuthor = ncmWebAuthor;
	}

}
