package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NcmWebScheduleId generated by hbm2java
 */
@Embeddable
public class NcmWebScheduleId implements java.io.Serializable {

	private String title;
	private String description;
	private String icon;
	private String classname;
	private String DStart;
	private String DEnd;

	public NcmWebScheduleId() {
	}

	public NcmWebScheduleId(String title, String description, String icon, String classname, String DStart,
			String DEnd) {
		this.title = title;
		this.description = description;
		this.icon = icon;
		this.classname = classname;
		this.DStart = DStart;
		this.DEnd = DEnd;
	}

	@Column(name = "TITLE", length = 4000)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DESCRIPTION", length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ICON", length = 4000)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "CLASSNAME", length = 4000)
	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	@Column(name = "D_START", length = 4000)
	public String getDStart() {
		return this.DStart;
	}

	public void setDStart(String DStart) {
		this.DStart = DStart;
	}

	@Column(name = "D_END", length = 4000)
	public String getDEnd() {
		return this.DEnd;
	}

	public void setDEnd(String DEnd) {
		this.DEnd = DEnd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmWebScheduleId))
			return false;
		NcmWebScheduleId castOther = (NcmWebScheduleId) other;

		return ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null && castOther.getTitle() != null
				&& this.getTitle().equals(castOther.getTitle())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& ((this.getIcon() == castOther.getIcon()) || (this.getIcon() != null && castOther.getIcon() != null
						&& this.getIcon().equals(castOther.getIcon())))
				&& ((this.getClassname() == castOther.getClassname()) || (this.getClassname() != null
						&& castOther.getClassname() != null && this.getClassname().equals(castOther.getClassname())))
				&& ((this.getDStart() == castOther.getDStart()) || (this.getDStart() != null
						&& castOther.getDStart() != null && this.getDStart().equals(castOther.getDStart())))
				&& ((this.getDEnd() == castOther.getDEnd()) || (this.getDEnd() != null && castOther.getDEnd() != null
						&& this.getDEnd().equals(castOther.getDEnd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (getIcon() == null ? 0 : this.getIcon().hashCode());
		result = 37 * result + (getClassname() == null ? 0 : this.getClassname().hashCode());
		result = 37 * result + (getDStart() == null ? 0 : this.getDStart().hashCode());
		result = 37 * result + (getDEnd() == null ? 0 : this.getDEnd().hashCode());
		return result;
	}

}
