package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmWebExcel generated by hbm2java
 */
@Entity
@Table(name = "NCM_WEB_EXCEL", schema = "NCM")
public class NcmWebExcel implements java.io.Serializable {

	private String xlsCd;
	private String xlsNm;
	private String xlsDesc;
	private String updateId;
	private Date lastUpdate;

	public NcmWebExcel() {
	}

	public NcmWebExcel(String xlsCd) {
		this.xlsCd = xlsCd;
	}

	public NcmWebExcel(String xlsCd, String xlsNm, String xlsDesc, String updateId, Date lastUpdate) {
		this.xlsCd = xlsCd;
		this.xlsNm = xlsNm;
		this.xlsDesc = xlsDesc;
		this.updateId = updateId;
		this.lastUpdate = lastUpdate;
	}

	@Id

	@Column(name = "XLS_CD", unique = true, nullable = false, length = 20)
	public String getXlsCd() {
		return this.xlsCd;
	}

	public void setXlsCd(String xlsCd) {
		this.xlsCd = xlsCd;
	}

	@Column(name = "XLS_NM", length = 50)
	public String getXlsNm() {
		return this.xlsNm;
	}

	public void setXlsNm(String xlsNm) {
		this.xlsNm = xlsNm;
	}

	@Column(name = "XLS_DESC", length = 100)
	public String getXlsDesc() {
		return this.xlsDesc;
	}

	public void setXlsDesc(String xlsDesc) {
		this.xlsDesc = xlsDesc;
	}

	@Column(name = "UPDATE_ID", length = 10)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
