package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmWebBoardFile generated by hbm2java
 */
@Entity
@Table(name = "NCM_WEB_BOARD_FILE", schema = "NCM")
public class NcmWebBoardFile implements java.io.Serializable {

	private String idx;
	private String boardIdx;
	private String createdId;
	private String originalFileName;
	private String storedFileName;
	private String fileSize;
	private Date createdDate;
	private String delYn;

	public NcmWebBoardFile() {
	}

	public NcmWebBoardFile(String idx, String boardIdx) {
		this.idx = idx;
		this.boardIdx = boardIdx;
	}

	public NcmWebBoardFile(String idx, String boardIdx, String createdId, String originalFileName,
			String storedFileName, String fileSize, Date createdDate, String delYn) {
		this.idx = idx;
		this.boardIdx = boardIdx;
		this.createdId = createdId;
		this.originalFileName = originalFileName;
		this.storedFileName = storedFileName;
		this.fileSize = fileSize;
		this.createdDate = createdDate;
		this.delYn = delYn;
	}

	@Id

	@Column(name = "IDX", unique = true, nullable = false, length = 100)
	public String getIdx() {
		return this.idx;
	}

	public void setIdx(String idx) {
		this.idx = idx;
	}

	@Column(name = "BOARD_IDX", nullable = false, length = 100)
	public String getBoardIdx() {
		return this.boardIdx;
	}

	public void setBoardIdx(String boardIdx) {
		this.boardIdx = boardIdx;
	}

	@Column(name = "CREATED_ID", length = 1000)
	public String getCreatedId() {
		return this.createdId;
	}

	public void setCreatedId(String createdId) {
		this.createdId = createdId;
	}

	@Column(name = "ORIGINAL_FILE_NAME", length = 4000)
	public String getOriginalFileName() {
		return this.originalFileName;
	}

	public void setOriginalFileName(String originalFileName) {
		this.originalFileName = originalFileName;
	}

	@Column(name = "STORED_FILE_NAME", length = 4000)
	public String getStoredFileName() {
		return this.storedFileName;
	}

	public void setStoredFileName(String storedFileName) {
		this.storedFileName = storedFileName;
	}

	@Column(name = "FILE_SIZE", length = 1000)
	public String getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(String fileSize) {
		this.fileSize = fileSize;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "DEL_YN", length = 2)
	public String getDelYn() {
		return this.delYn;
	}

	public void setDelYn(String delYn) {
		this.delYn = delYn;
	}

}
