package com.eugenefe.ncm;
// Generated Nov 1, 2016 1:37:21 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NcmWebAuthor generated by hbm2java
 */
@Entity
@Table(name = "NCM_WEB_AUTHOR", schema = "NCM")
public class NcmWebAuthor implements java.io.Serializable {

	private String authorCode;
	private String authorNm;
	private String dsc;
	private Set<NcmWebUsrscrst> ncmWebUsrscrsts = new HashSet<NcmWebUsrscrst>(0);
	private Set<NcmWebMenuItem> ncmWebMenuItems = new HashSet<NcmWebMenuItem>(0);

	public NcmWebAuthor() {
	}

	public NcmWebAuthor(String authorCode, String authorNm) {
		this.authorCode = authorCode;
		this.authorNm = authorNm;
	}

	public NcmWebAuthor(String authorCode, String authorNm, String dsc, Set<NcmWebUsrscrst> ncmWebUsrscrsts,
			Set<NcmWebMenuItem> ncmWebMenuItems) {
		this.authorCode = authorCode;
		this.authorNm = authorNm;
		this.dsc = dsc;
		this.ncmWebUsrscrsts = ncmWebUsrscrsts;
		this.ncmWebMenuItems = ncmWebMenuItems;
	}

	@Id

	@Column(name = "AUTHOR_CODE", unique = true, nullable = false, length = 60)
	public String getAuthorCode() {
		return this.authorCode;
	}

	public void setAuthorCode(String authorCode) {
		this.authorCode = authorCode;
	}

	@Column(name = "AUTHOR_NM", nullable = false, length = 60)
	public String getAuthorNm() {
		return this.authorNm;
	}

	public void setAuthorNm(String authorNm) {
		this.authorNm = authorNm;
	}

	@Column(name = "DSC", length = 200)
	public String getDsc() {
		return this.dsc;
	}

	public void setDsc(String dsc) {
		this.dsc = dsc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ncmWebAuthor")
	public Set<NcmWebUsrscrst> getNcmWebUsrscrsts() {
		return this.ncmWebUsrscrsts;
	}

	public void setNcmWebUsrscrsts(Set<NcmWebUsrscrst> ncmWebUsrscrsts) {
		this.ncmWebUsrscrsts = ncmWebUsrscrsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ncmWebAuthor")
	public Set<NcmWebMenuItem> getNcmWebMenuItems() {
		return this.ncmWebMenuItems;
	}

	public void setNcmWebMenuItems(Set<NcmWebMenuItem> ncmWebMenuItems) {
		this.ncmWebMenuItems = ncmWebMenuItems;
	}

}
