package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

/**
 * NcmErpTxIfrTempId generated by hbm2java
 */

public class NcmErpTxIfrTempId implements java.io.Serializable, Navigatable {

	private String cptlDivCd;
	private String finTxNo;

	public NcmErpTxIfrTempId() {
	}

	public String getCptlDivCd() {
		return this.cptlDivCd;
	}

	public void setCptlDivCd(String cptlDivCd) {
		this.cptlDivCd = cptlDivCd;

	}

	public String getFinTxNo() {
		return this.finTxNo;
	}

	public void setFinTxNo(String finTxNo) {
		this.finTxNo = finTxNo;

	}

	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getCptlDivCd());
		buffer.append("#").append(getFinTxNo());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmErpTxIfrTempId))
			return false;
		NcmErpTxIfrTempId castOther = (NcmErpTxIfrTempId) other;

		return ((this.getCptlDivCd() == castOther.getCptlDivCd())
				|| (this.getCptlDivCd() != null && castOther.getCptlDivCd() != null && this.getCptlDivCd().equals(castOther.getCptlDivCd())))
				&& ((this.getFinTxNo() == castOther.getFinTxNo())
						|| (this.getFinTxNo() != null && castOther.getFinTxNo() != null && this.getFinTxNo().equals(castOther.getFinTxNo())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCptlDivCd() == null ? 0 : this.getCptlDivCd().hashCode());
		result = 37 * result + (getFinTxNo() == null ? 0 : this.getFinTxNo().hashCode());
		return result;
	}

}
