package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmErpTxIfr generated by hbm2java
 */

@Entity(name = "NaviNcmErpTxIfr")
@IdClass(value = NcmErpTxIfrId.class)
@Table(name = "NCM_ERP_TX_IFR", schema = "NCM")
public class NcmErpTxIfr implements java.io.Serializable, Navigatable {

	private long eaiSeqNo;
	private String baseDate;
	private String finTxNo;
	private String bizDiv;
	private String bizDivNm;
	private String captDiv;
	private String captDivNm;
	private String txType;
	private String txTypeNm;
	private String prodNm;
	private String fstFinTxNo;
	private String cntPrty;
	private String cntPrtyNm;
	private String acctNo;
	private String termStDate;
	private String termEdDate;
	private BigDecimal origAmt;
	private String acctCode;
	private String acctCodeNm;
	private BigDecimal payAmt;
	private BigDecimal intAmt;
	private BigDecimal corpTaxAmt;
	private BigDecimal muniTaxAmt;
	private BigDecimal residualAmt;
	private String bookingDate;
	private String bookingNo;
	private String creDttm;
	private String chgDttm;
	private String eaiPttn;
	private Date eaiCreDttm;
	private String eaiTrstType;
	private Date eaiTrstDttm;
	private String errMsg;

	public NcmErpTxIfr() {
	}

	@Id
	@Column(name = "EAI_SEQ_NO", nullable = false, precision = 15, scale = 0)
	public long getEaiSeqNo() {
		return this.eaiSeqNo;
	}

	public void setEaiSeqNo(long eaiSeqNo) {
		this.eaiSeqNo = eaiSeqNo;
	}

	@Id
	@Column(name = "BASE_DATE", nullable = false, length = 20)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Id
	@Column(name = "FIN_TX_NO", nullable = false, length = 20)
	public String getFinTxNo() {
		return this.finTxNo;
	}

	public void setFinTxNo(String finTxNo) {
		this.finTxNo = finTxNo;
	}

	@Column(name = "BIZ_DIV", length = 20)
	public String getBizDiv() {
		return this.bizDiv;
	}

	public void setBizDiv(String bizDiv) {
		this.bizDiv = bizDiv;

	}

	@Column(name = "BIZ_DIV_NM", length = 100)
	public String getBizDivNm() {
		return this.bizDivNm;
	}

	public void setBizDivNm(String bizDivNm) {
		this.bizDivNm = bizDivNm;

	}

	@Column(name = "CAPT_DIV", length = 20)
	public String getCaptDiv() {
		return this.captDiv;
	}

	public void setCaptDiv(String captDiv) {
		this.captDiv = captDiv;

	}

	@Column(name = "CAPT_DIV_NM", length = 100)
	public String getCaptDivNm() {
		return this.captDivNm;
	}

	public void setCaptDivNm(String captDivNm) {
		this.captDivNm = captDivNm;

	}

	@Column(name = "TX_TYPE", length = 20)
	public String getTxType() {
		return this.txType;
	}

	public void setTxType(String txType) {
		this.txType = txType;

	}

	@Column(name = "TX_TYPE_NM", length = 100)
	public String getTxTypeNm() {
		return this.txTypeNm;
	}

	public void setTxTypeNm(String txTypeNm) {
		this.txTypeNm = txTypeNm;

	}

	@Column(name = "PROD_NM", length = 100)
	public String getProdNm() {
		return this.prodNm;
	}

	public void setProdNm(String prodNm) {
		this.prodNm = prodNm;

	}

	@Column(name = "FST_FIN_TX_NO", length = 20)
	public String getFstFinTxNo() {
		return this.fstFinTxNo;
	}

	public void setFstFinTxNo(String fstFinTxNo) {
		this.fstFinTxNo = fstFinTxNo;

	}

	@Column(name = "CNT_PRTY", length = 20)
	public String getCntPrty() {
		return this.cntPrty;
	}

	public void setCntPrty(String cntPrty) {
		this.cntPrty = cntPrty;

	}

	@Column(name = "CNT_PRTY_NM", length = 100)
	public String getCntPrtyNm() {
		return this.cntPrtyNm;
	}

	public void setCntPrtyNm(String cntPrtyNm) {
		this.cntPrtyNm = cntPrtyNm;

	}

	@Column(name = "ACCT_NO", length = 25)
	public String getAcctNo() {
		return this.acctNo;
	}

	public void setAcctNo(String acctNo) {
		this.acctNo = acctNo;

	}

	@Column(name = "TERM_ST_DATE", length = 20)
	public String getTermStDate() {
		return this.termStDate;
	}

	public void setTermStDate(String termStDate) {
		this.termStDate = termStDate;

	}

	@Column(name = "TERM_ED_DATE", length = 20)
	public String getTermEdDate() {
		return this.termEdDate;
	}

	public void setTermEdDate(String termEdDate) {
		this.termEdDate = termEdDate;

	}

	@Column(name = "ORIG_AMT", precision = 20, scale = 0)
	public BigDecimal getOrigAmt() {
		return this.origAmt;
	}

	public void setOrigAmt(BigDecimal origAmt) {
		this.origAmt = origAmt;

	}

	@Column(name = "ACCT_CODE", length = 20)
	public String getAcctCode() {
		return this.acctCode;
	}

	public void setAcctCode(String acctCode) {
		this.acctCode = acctCode;

	}

	@Column(name = "ACCT_CODE_NM", length = 100)
	public String getAcctCodeNm() {
		return this.acctCodeNm;
	}

	public void setAcctCodeNm(String acctCodeNm) {
		this.acctCodeNm = acctCodeNm;

	}

	@Column(name = "PAY_AMT", precision = 20, scale = 0)
	public BigDecimal getPayAmt() {
		return this.payAmt;
	}

	public void setPayAmt(BigDecimal payAmt) {
		this.payAmt = payAmt;

	}

	@Column(name = "INT_AMT", precision = 20, scale = 0)
	public BigDecimal getIntAmt() {
		return this.intAmt;
	}

	public void setIntAmt(BigDecimal intAmt) {
		this.intAmt = intAmt;

	}

	@Column(name = "CORP_TAX_AMT", precision = 20, scale = 0)
	public BigDecimal getCorpTaxAmt() {
		return this.corpTaxAmt;
	}

	public void setCorpTaxAmt(BigDecimal corpTaxAmt) {
		this.corpTaxAmt = corpTaxAmt;

	}

	@Column(name = "MUNI_TAX_AMT", precision = 20, scale = 0)
	public BigDecimal getMuniTaxAmt() {
		return this.muniTaxAmt;
	}

	public void setMuniTaxAmt(BigDecimal muniTaxAmt) {
		this.muniTaxAmt = muniTaxAmt;

	}

	@Column(name = "RESIDUAL_AMT", precision = 20, scale = 0)
	public BigDecimal getResidualAmt() {
		return this.residualAmt;
	}

	public void setResidualAmt(BigDecimal residualAmt) {
		this.residualAmt = residualAmt;

	}

	@Column(name = "BOOKING_DATE", length = 20)
	public String getBookingDate() {
		return this.bookingDate;
	}

	public void setBookingDate(String bookingDate) {
		this.bookingDate = bookingDate;

	}

	@Column(name = "BOOKING_NO", length = 20)
	public String getBookingNo() {
		return this.bookingNo;
	}

	public void setBookingNo(String bookingNo) {
		this.bookingNo = bookingNo;

	}

	@Column(name = "CRE_DTTM", length = 20)
	public String getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(String creDttm) {
		this.creDttm = creDttm;

	}

	@Column(name = "CHG_DTTM", length = 20)
	public String getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(String chgDttm) {
		this.chgDttm = chgDttm;

	}

	@Column(name = "EAI_PTTN", length = 1)
	public String getEaiPttn() {
		return this.eaiPttn;
	}

	public void setEaiPttn(String eaiPttn) {
		this.eaiPttn = eaiPttn;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EAI_CRE_DTTM", length = 7)
	public Date getEaiCreDttm() {
		return this.eaiCreDttm;
	}

	public void setEaiCreDttm(Date eaiCreDttm) {
		this.eaiCreDttm = eaiCreDttm;

	}

	@Column(name = "EAI_TRST_TYPE", length = 1)
	public String getEaiTrstType() {
		return this.eaiTrstType;
	}

	public void setEaiTrstType(String eaiTrstType) {
		this.eaiTrstType = eaiTrstType;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EAI_TRST_DTTM", length = 7)
	public Date getEaiTrstDttm() {
		return this.eaiTrstDttm;
	}

	public void setEaiTrstDttm(Date eaiTrstDttm) {
		this.eaiTrstDttm = eaiTrstDttm;

	}

	@Column(name = "ERR_MSG", length = 200)
	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getEaiSeqNo());
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getFinTxNo());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmErpTxIfr))
			return false;
		NcmErpTxIfr castOther = (NcmErpTxIfr) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getEaiSeqNo();
		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getFinTxNo() == null ? 0 : this.getFinTxNo().hashCode());
		return result;
	}

}
