package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmErpAccountIfr generated by hbm2java
 */

@Entity(name = "NaviNcmErpAccountIfr")
@IdClass(value = NcmErpAccountIfrId.class)
@Table(name = "NCM_ERP_ACCOUNT_IFR", schema = "NCM")
public class NcmErpAccountIfr implements java.io.Serializable, Navigatable {

	private long eaiSeqNo;
	private String acctNo;
	private String txType;
	private String stateCode;
	private String txTypeNm;
	private String termType;
	private String prodType;
	private String prodTypeNm;
	private String cntPrty;
	private String cntPrtyNm;
	private String startDate;
	private String endDate;
	private String creDttm;
	private String chgDttm;
	private String eaiPttn;
	private Date eaiCreDttm;
	private String eaiTrstType;
	private Date eaiTrstDttm;
	private String errMsg;

	public NcmErpAccountIfr() {
	}

	@Id
	@Column(name = "EAI_SEQ_NO", nullable = false, precision = 15, scale = 0)
	public long getEaiSeqNo() {
		return this.eaiSeqNo;
	}

	public void setEaiSeqNo(long eaiSeqNo) {
		this.eaiSeqNo = eaiSeqNo;
	}

	@Id
	@Column(name = "ACCT_NO", nullable = false, length = 20)
	public String getAcctNo() {
		return this.acctNo;
	}

	public void setAcctNo(String acctNo) {
		this.acctNo = acctNo;
	}

	@Id
	@Column(name = "TX_TYPE", nullable = false, length = 20)
	public String getTxType() {
		return this.txType;
	}

	public void setTxType(String txType) {
		this.txType = txType;
	}

	@Column(name = "STATE_CODE", length = 20)
	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;

	}

	@Column(name = "TX_TYPE_NM", length = 100)
	public String getTxTypeNm() {
		return this.txTypeNm;
	}

	public void setTxTypeNm(String txTypeNm) {
		this.txTypeNm = txTypeNm;

	}

	@Column(name = "TERM_TYPE", length = 20)
	public String getTermType() {
		return this.termType;
	}

	public void setTermType(String termType) {
		this.termType = termType;

	}

	@Column(name = "PROD_TYPE", length = 20)
	public String getProdType() {
		return this.prodType;
	}

	public void setProdType(String prodType) {
		this.prodType = prodType;

	}

	@Column(name = "PROD_TYPE_NM", length = 100)
	public String getProdTypeNm() {
		return this.prodTypeNm;
	}

	public void setProdTypeNm(String prodTypeNm) {
		this.prodTypeNm = prodTypeNm;

	}

	@Column(name = "CNT_PRTY", length = 20)
	public String getCntPrty() {
		return this.cntPrty;
	}

	public void setCntPrty(String cntPrty) {
		this.cntPrty = cntPrty;

	}

	@Column(name = "CNT_PRTY_NM", length = 100)
	public String getCntPrtyNm() {
		return this.cntPrtyNm;
	}

	public void setCntPrtyNm(String cntPrtyNm) {
		this.cntPrtyNm = cntPrtyNm;

	}

	@Column(name = "START_DATE", length = 20)
	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;

	}

	@Column(name = "END_DATE", length = 20)
	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;

	}

	@Column(name = "CRE_DTTM", length = 20)
	public String getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(String creDttm) {
		this.creDttm = creDttm;

	}

	@Column(name = "CHG_DTTM", length = 20)
	public String getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(String chgDttm) {
		this.chgDttm = chgDttm;

	}

	@Column(name = "EAI_PTTN", length = 1)
	public String getEaiPttn() {
		return this.eaiPttn;
	}

	public void setEaiPttn(String eaiPttn) {
		this.eaiPttn = eaiPttn;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EAI_CRE_DTTM", length = 7)
	public Date getEaiCreDttm() {
		return this.eaiCreDttm;
	}

	public void setEaiCreDttm(Date eaiCreDttm) {
		this.eaiCreDttm = eaiCreDttm;

	}

	@Column(name = "EAI_TRST_TYPE", length = 1)
	public String getEaiTrstType() {
		return this.eaiTrstType;
	}

	public void setEaiTrstType(String eaiTrstType) {
		this.eaiTrstType = eaiTrstType;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EAI_TRST_DTTM", length = 7)
	public Date getEaiTrstDttm() {
		return this.eaiTrstDttm;
	}

	public void setEaiTrstDttm(Date eaiTrstDttm) {
		this.eaiTrstDttm = eaiTrstDttm;

	}

	@Column(name = "ERR_MSG", length = 200)
	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getEaiSeqNo());
		buffer.append("#").append(getAcctNo());
		buffer.append("#").append(getTxType());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmErpAccountIfr))
			return false;
		NcmErpAccountIfr castOther = (NcmErpAccountIfr) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getEaiSeqNo();
		result = 37 * result + (getAcctNo() == null ? 0 : this.getAcctNo().hashCode());
		result = 37 * result + (getTxType() == null ? 0 : this.getTxType().hashCode());
		return result;
	}

}
