package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmKfrHoldingYield generated by hbm2java
 */

@Entity(name = "NaviNcmKfrHoldingYield")
@IdClass(value = NcmKfrHoldingYieldId.class)
@Table(name = "NCM_KFR_HOLDING_YIELD", schema = "NCM")
public class NcmKfrHoldingYield implements java.io.Serializable, Navigatable {

	private String tradeday;
	private String mgrcode;
	private String fundmgrcode;
	private String assetbclasscode;
	private String assetsclasscode;
	private String itemcode;
	private String itemname;
	private Long amtcurr;
	private Long evalamt;
	private Long retvaltot;
	private Long wtvaltot;
	private BigDecimal rettot;
	private String evalcorpcode;
	private Date creDttm;
	private String creEmpNo;
	private Date chgDttm;
	private String chgEmpNo;
	private String workfilename;

	public NcmKfrHoldingYield() {
	}

	@Id
	@Column(name = "TRADEDAY", nullable = false, length = 8)
	public String getTradeday() {
		return this.tradeday;
	}

	public void setTradeday(String tradeday) {
		this.tradeday = tradeday;
	}

	@Id
	@Column(name = "MGRCODE", nullable = false, length = 3)
	public String getMgrcode() {
		return this.mgrcode;
	}

	public void setMgrcode(String mgrcode) {
		this.mgrcode = mgrcode;
	}

	@Id
	@Column(name = "FUNDMGRCODE", nullable = false, length = 30)
	public String getFundmgrcode() {
		return this.fundmgrcode;
	}

	public void setFundmgrcode(String fundmgrcode) {
		this.fundmgrcode = fundmgrcode;
	}

	@Id
	@Column(name = "ASSETBCLASSCODE", nullable = false, length = 2)
	public String getAssetbclasscode() {
		return this.assetbclasscode;
	}

	public void setAssetbclasscode(String assetbclasscode) {
		this.assetbclasscode = assetbclasscode;
	}

	@Id
	@Column(name = "ASSETSCLASSCODE", nullable = false, length = 2)
	public String getAssetsclasscode() {
		return this.assetsclasscode;
	}

	public void setAssetsclasscode(String assetsclasscode) {
		this.assetsclasscode = assetsclasscode;
	}

	@Id
	@Column(name = "ITEMCODE", nullable = false, length = 50)
	public String getItemcode() {
		return this.itemcode;
	}

	public void setItemcode(String itemcode) {
		this.itemcode = itemcode;
	}

	@Column(name = "ITEMNAME", length = 100)
	public String getItemname() {
		return this.itemname;
	}

	public void setItemname(String itemname) {
		this.itemname = itemname;

	}

	@Column(name = "AMTCURR", precision = 18, scale = 0)
	public Long getAmtcurr() {
		return this.amtcurr;
	}

	public void setAmtcurr(Long amtcurr) {
		this.amtcurr = amtcurr;

	}

	@Column(name = "EVALAMT", precision = 18, scale = 0)
	public Long getEvalamt() {
		return this.evalamt;
	}

	public void setEvalamt(Long evalamt) {
		this.evalamt = evalamt;

	}

	@Column(name = "RETVALTOT", precision = 18, scale = 0)
	public Long getRetvaltot() {
		return this.retvaltot;
	}

	public void setRetvaltot(Long retvaltot) {
		this.retvaltot = retvaltot;

	}

	@Column(name = "WTVALTOT", precision = 18, scale = 0)
	public Long getWtvaltot() {
		return this.wtvaltot;
	}

	public void setWtvaltot(Long wtvaltot) {
		this.wtvaltot = wtvaltot;

	}

	@Column(name = "RETTOT", precision = 20, scale = 12)
	public BigDecimal getRettot() {
		return this.rettot;
	}

	public void setRettot(BigDecimal rettot) {
		this.rettot = rettot;

	}

	@Column(name = "EVALCORPCODE", length = 4)
	public String getEvalcorpcode() {
		return this.evalcorpcode;
	}

	public void setEvalcorpcode(String evalcorpcode) {
		this.evalcorpcode = evalcorpcode;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRE_DTTM", length = 7)
	public Date getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm) {
		this.creDttm = creDttm;

	}

	@Column(name = "CRE_EMP_NO", length = 6)
	public String getCreEmpNo() {
		return this.creEmpNo;
	}

	public void setCreEmpNo(String creEmpNo) {
		this.creEmpNo = creEmpNo;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHG_DTTM", length = 7)
	public Date getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(Date chgDttm) {
		this.chgDttm = chgDttm;

	}

	@Column(name = "CHG_EMP_NO", length = 6)
	public String getChgEmpNo() {
		return this.chgEmpNo;
	}

	public void setChgEmpNo(String chgEmpNo) {
		this.chgEmpNo = chgEmpNo;

	}

	@Column(name = "WORKFILENAME", length = 30)
	public String getWorkfilename() {
		return this.workfilename;
	}

	public void setWorkfilename(String workfilename) {
		this.workfilename = workfilename;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getTradeday());
		buffer.append("#").append(getMgrcode());
		buffer.append("#").append(getFundmgrcode());
		buffer.append("#").append(getAssetbclasscode());
		buffer.append("#").append(getAssetsclasscode());
		buffer.append("#").append(getItemcode());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmKfrHoldingYield))
			return false;
		NcmKfrHoldingYield castOther = (NcmKfrHoldingYield) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTradeday() == null ? 0 : this.getTradeday().hashCode());
		result = 37 * result + (getMgrcode() == null ? 0 : this.getMgrcode().hashCode());
		result = 37 * result + (getFundmgrcode() == null ? 0 : this.getFundmgrcode().hashCode());
		result = 37 * result + (getAssetbclasscode() == null ? 0 : this.getAssetbclasscode().hashCode());
		result = 37 * result + (getAssetsclasscode() == null ? 0 : this.getAssetsclasscode().hashCode());
		result = 37 * result + (getItemcode() == null ? 0 : this.getItemcode().hashCode());
		return result;
	}

}
