package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmKfrMarketIndex generated by hbm2java
 */

@Entity(name = "NaviNcmKfrMarketIndex")
@IdClass(value = NcmKfrMarketIndexId.class)
@Table(name = "NCM_KFR_MARKET_INDEX", schema = "NCM")
public class NcmKfrMarketIndex implements java.io.Serializable, Navigatable {

	private String tradeday;
	private String mktcode;
	private String mktname;
	private String indextype;
	private BigDecimal idxval;
	private BigDecimal coupon;
	private String evalcorpcode;
	private Date creDttm;
	private String creEmpNo;
	private Date chgDttm;
	private String chgEmpNo;
	private String workfilename;

	public NcmKfrMarketIndex() {
	}

	@Id
	@Column(name = "TRADEDAY", nullable = false, length = 8)
	public String getTradeday() {
		return this.tradeday;
	}

	public void setTradeday(String tradeday) {
		this.tradeday = tradeday;
	}

	@Id
	@Column(name = "MKTCODE", nullable = false, length = 10)
	public String getMktcode() {
		return this.mktcode;
	}

	public void setMktcode(String mktcode) {
		this.mktcode = mktcode;
	}

	@Column(name = "MKTNAME", nullable = false, length = 50)
	public String getMktname() {
		return this.mktname;
	}

	public void setMktname(String mktname) {
		this.mktname = mktname;

	}

	@Column(name = "INDEXTYPE", length = 2)
	public String getIndextype() {
		return this.indextype;
	}

	public void setIndextype(String indextype) {
		this.indextype = indextype;

	}

	@Column(name = "IDXVAL", precision = 20, scale = 12)
	public BigDecimal getIdxval() {
		return this.idxval;
	}

	public void setIdxval(BigDecimal idxval) {
		this.idxval = idxval;

	}

	@Column(name = "COUPON", precision = 20, scale = 12)
	public BigDecimal getCoupon() {
		return this.coupon;
	}

	public void setCoupon(BigDecimal coupon) {
		this.coupon = coupon;

	}

	@Column(name = "EVALCORPCODE", nullable = false, length = 4)
	public String getEvalcorpcode() {
		return this.evalcorpcode;
	}

	public void setEvalcorpcode(String evalcorpcode) {
		this.evalcorpcode = evalcorpcode;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRE_DTTM", nullable = false, length = 7)
	public Date getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm) {
		this.creDttm = creDttm;

	}

	@Column(name = "CRE_EMP_NO", nullable = false, length = 6)
	public String getCreEmpNo() {
		return this.creEmpNo;
	}

	public void setCreEmpNo(String creEmpNo) {
		this.creEmpNo = creEmpNo;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHG_DTTM", nullable = false, length = 7)
	public Date getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(Date chgDttm) {
		this.chgDttm = chgDttm;

	}

	@Column(name = "CHG_EMP_NO", nullable = false, length = 6)
	public String getChgEmpNo() {
		return this.chgEmpNo;
	}

	public void setChgEmpNo(String chgEmpNo) {
		this.chgEmpNo = chgEmpNo;

	}

	@Column(name = "WORKFILENAME", length = 30)
	public String getWorkfilename() {
		return this.workfilename;
	}

	public void setWorkfilename(String workfilename) {
		this.workfilename = workfilename;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getTradeday());
		buffer.append("#").append(getMktcode());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmKfrMarketIndex))
			return false;
		NcmKfrMarketIndex castOther = (NcmKfrMarketIndex) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTradeday() == null ? 0 : this.getTradeday().hashCode());
		result = 37 * result + (getMktcode() == null ? 0 : this.getMktcode().hashCode());
		return result;
	}

}
