package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv2BmReturn generated by hbm2java
 */

@Entity(name = "NaviNcmLv2BmReturn")
@IdClass(value = NcmLv2BmReturnId.class)
@Table(name = "NCM_LV2_BM_RETURN", schema = "NCM")
public class NcmLv2BmReturn implements java.io.Serializable, Navigatable {

	private String baseDate;
	private String bmId;
	private BigDecimal m01BmYield;
	private BigDecimal m03BmYield;
	private BigDecimal m06BmYield;
	private BigDecimal m12BmYield;
	private BigDecimal m24BmYield;
	private BigDecimal m36BmYield;
	private BigDecimal ytdBmYield;
	private BigDecimal qtdBmYield;
	private BigDecimal mtdBmYield;
	private BigDecimal fy1BmYield;
	private BigDecimal fy2BmYield;
	private BigDecimal fy3BmYield;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv2BmReturn() {
	}

	@Id
	@Column(name = "BASE_DATE", nullable = false, length = 8)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Id
	@Column(name = "BM_ID", nullable = false, length = 20)
	public String getBmId() {
		return this.bmId;
	}

	public void setBmId(String bmId) {
		this.bmId = bmId;
	}

	@Column(name = "M01_BM_YIELD", precision = 12, scale = 8)
	public BigDecimal getM01BmYield() {
		return this.m01BmYield;
	}

	public void setM01BmYield(BigDecimal m01BmYield) {
		this.m01BmYield = m01BmYield;

	}

	@Column(name = "M03_BM_YIELD", precision = 12, scale = 8)
	public BigDecimal getM03BmYield() {
		return this.m03BmYield;
	}

	public void setM03BmYield(BigDecimal m03BmYield) {
		this.m03BmYield = m03BmYield;

	}

	@Column(name = "M06_BM_YIELD", precision = 12, scale = 8)
	public BigDecimal getM06BmYield() {
		return this.m06BmYield;
	}

	public void setM06BmYield(BigDecimal m06BmYield) {
		this.m06BmYield = m06BmYield;

	}

	@Column(name = "M12_BM_YIELD", precision = 12, scale = 8)
	public BigDecimal getM12BmYield() {
		return this.m12BmYield;
	}

	public void setM12BmYield(BigDecimal m12BmYield) {
		this.m12BmYield = m12BmYield;

	}

	@Column(name = "M24_BM_YIELD", precision = 12, scale = 8)
	public BigDecimal getM24BmYield() {
		return this.m24BmYield;
	}

	public void setM24BmYield(BigDecimal m24BmYield) {
		this.m24BmYield = m24BmYield;

	}

	@Column(name = "M36_BM_YIELD", precision = 12, scale = 8)
	public BigDecimal getM36BmYield() {
		return this.m36BmYield;
	}

	public void setM36BmYield(BigDecimal m36BmYield) {
		this.m36BmYield = m36BmYield;

	}

	@Column(name = "YTD_BM_YIELD", precision = 12, scale = 8)
	public BigDecimal getYtdBmYield() {
		return this.ytdBmYield;
	}

	public void setYtdBmYield(BigDecimal ytdBmYield) {
		this.ytdBmYield = ytdBmYield;

	}

	@Column(name = "QTD_BM_YIELD", precision = 12, scale = 8)
	public BigDecimal getQtdBmYield() {
		return this.qtdBmYield;
	}

	public void setQtdBmYield(BigDecimal qtdBmYield) {
		this.qtdBmYield = qtdBmYield;

	}

	@Column(name = "MTD_BM_YIELD", precision = 12, scale = 8)
	public BigDecimal getMtdBmYield() {
		return this.mtdBmYield;
	}

	public void setMtdBmYield(BigDecimal mtdBmYield) {
		this.mtdBmYield = mtdBmYield;

	}

	@Column(name = "FY1_BM_YIELD", precision = 12, scale = 8)
	public BigDecimal getFy1BmYield() {
		return this.fy1BmYield;
	}

	public void setFy1BmYield(BigDecimal fy1BmYield) {
		this.fy1BmYield = fy1BmYield;

	}

	@Column(name = "FY2_BM_YIELD", precision = 12, scale = 8)
	public BigDecimal getFy2BmYield() {
		return this.fy2BmYield;
	}

	public void setFy2BmYield(BigDecimal fy2BmYield) {
		this.fy2BmYield = fy2BmYield;

	}

	@Column(name = "FY3_BM_YIELD", precision = 12, scale = 8)
	public BigDecimal getFy3BmYield() {
		return this.fy3BmYield;
	}

	public void setFy3BmYield(BigDecimal fy3BmYield) {
		this.fy3BmYield = fy3BmYield;

	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getBmId());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmLv2BmReturn))
			return false;
		NcmLv2BmReturn castOther = (NcmLv2BmReturn) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getBmId() == null ? 0 : this.getBmId().hashCode());
		return result;
	}

}
