package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv2RiskAdj generated by hbm2java
 */

@Entity(name = "NaviNcmLv2RiskAdj")
@IdClass(value = NcmLv2RiskAdjId.class)
@Table(name = "NCM_LV2_RISK_ADJ", schema = "NCM")
public class NcmLv2RiskAdj implements java.io.Serializable, Navigatable {

	private String baseDate;
	private String cptlDivCd;
	private String yieldLclssCd;
	private String yieldDivCd;
	private String prodTypeCd;
	private String matCd;
	private BigDecimal avgYield;
	private BigDecimal bmAvgYield;
	private BigDecimal rfAvgYield;
	private BigDecimal stdev;
	private BigDecimal bmStdev;
	private BigDecimal sharpe;
	private BigDecimal bmSharpe;
	private BigDecimal semiStdev;
	private BigDecimal bmSemiStdev;
	private BigDecimal sortino;
	private BigDecimal bmSortino;
	private BigDecimal te;
	private BigDecimal ir;
	private Integer yieldCnt;
	private Integer bmCnt;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv2RiskAdj() {
	}

	@Id
	@Column(name = "BASE_DATE", nullable = false, length = 8)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Id
	@Column(name = "CPTL_DIV_CD", nullable = false, length = 10)
	public String getCptlDivCd() {
		return this.cptlDivCd;
	}

	public void setCptlDivCd(String cptlDivCd) {
		this.cptlDivCd = cptlDivCd;
	}

	@Id
	@Column(name = "YIELD_LCLSS_CD", nullable = false, length = 10)
	public String getYieldLclssCd() {
		return this.yieldLclssCd;
	}

	public void setYieldLclssCd(String yieldLclssCd) {
		this.yieldLclssCd = yieldLclssCd;
	}

	@Id
	@Column(name = "YIELD_DIV_CD", nullable = false, length = 20)
	public String getYieldDivCd() {
		return this.yieldDivCd;
	}

	public void setYieldDivCd(String yieldDivCd) {
		this.yieldDivCd = yieldDivCd;
	}

	@Id
	@Column(name = "PROD_TYPE_CD", nullable = false, length = 10)
	public String getProdTypeCd() {
		return this.prodTypeCd;
	}

	public void setProdTypeCd(String prodTypeCd) {
		this.prodTypeCd = prodTypeCd;
	}

	@Id
	@Column(name = "MAT_CD", nullable = false, length = 10)
	public String getMatCd() {
		return this.matCd;
	}

	public void setMatCd(String matCd) {
		this.matCd = matCd;
	}

	@Column(name = "AVG_YIELD", precision = 22, scale = 8)
	public BigDecimal getAvgYield() {
		return this.avgYield;
	}

	public void setAvgYield(BigDecimal avgYield) {
		this.avgYield = avgYield;

	}

	@Column(name = "BM_AVG_YIELD", precision = 22, scale = 8)
	public BigDecimal getBmAvgYield() {
		return this.bmAvgYield;
	}

	public void setBmAvgYield(BigDecimal bmAvgYield) {
		this.bmAvgYield = bmAvgYield;

	}

	@Column(name = "RF_AVG_YIELD", precision = 22, scale = 8)
	public BigDecimal getRfAvgYield() {
		return this.rfAvgYield;
	}

	public void setRfAvgYield(BigDecimal rfAvgYield) {
		this.rfAvgYield = rfAvgYield;

	}

	@Column(name = "STDEV", precision = 22, scale = 8)
	public BigDecimal getStdev() {
		return this.stdev;
	}

	public void setStdev(BigDecimal stdev) {
		this.stdev = stdev;

	}

	@Column(name = "BM_STDEV", precision = 22, scale = 8)
	public BigDecimal getBmStdev() {
		return this.bmStdev;
	}

	public void setBmStdev(BigDecimal bmStdev) {
		this.bmStdev = bmStdev;

	}

	@Column(name = "SHARPE", precision = 22, scale = 8)
	public BigDecimal getSharpe() {
		return this.sharpe;
	}

	public void setSharpe(BigDecimal sharpe) {
		this.sharpe = sharpe;

	}

	@Column(name = "BM_SHARPE", precision = 22, scale = 8)
	public BigDecimal getBmSharpe() {
		return this.bmSharpe;
	}

	public void setBmSharpe(BigDecimal bmSharpe) {
		this.bmSharpe = bmSharpe;

	}

	@Column(name = "SEMI_STDEV", precision = 22, scale = 8)
	public BigDecimal getSemiStdev() {
		return this.semiStdev;
	}

	public void setSemiStdev(BigDecimal semiStdev) {
		this.semiStdev = semiStdev;

	}

	@Column(name = "BM_SEMI_STDEV", precision = 22, scale = 8)
	public BigDecimal getBmSemiStdev() {
		return this.bmSemiStdev;
	}

	public void setBmSemiStdev(BigDecimal bmSemiStdev) {
		this.bmSemiStdev = bmSemiStdev;

	}

	@Column(name = "SORTINO", precision = 22, scale = 8)
	public BigDecimal getSortino() {
		return this.sortino;
	}

	public void setSortino(BigDecimal sortino) {
		this.sortino = sortino;

	}

	@Column(name = "BM_SORTINO", precision = 22, scale = 8)
	public BigDecimal getBmSortino() {
		return this.bmSortino;
	}

	public void setBmSortino(BigDecimal bmSortino) {
		this.bmSortino = bmSortino;

	}

	@Column(name = "TE", precision = 22, scale = 8)
	public BigDecimal getTe() {
		return this.te;
	}

	public void setTe(BigDecimal te) {
		this.te = te;

	}

	@Column(name = "IR", precision = 22, scale = 8)
	public BigDecimal getIr() {
		return this.ir;
	}

	public void setIr(BigDecimal ir) {
		this.ir = ir;

	}

	@Column(name = "YIELD_CNT", precision = 5, scale = 0)
	public Integer getYieldCnt() {
		return this.yieldCnt;
	}

	public void setYieldCnt(Integer yieldCnt) {
		this.yieldCnt = yieldCnt;

	}

	@Column(name = "BM_CNT", precision = 5, scale = 0)
	public Integer getBmCnt() {
		return this.bmCnt;
	}

	public void setBmCnt(Integer bmCnt) {
		this.bmCnt = bmCnt;

	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getCptlDivCd());
		buffer.append("#").append(getYieldLclssCd());
		buffer.append("#").append(getYieldDivCd());
		buffer.append("#").append(getProdTypeCd());
		buffer.append("#").append(getMatCd());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmLv2RiskAdj))
			return false;
		NcmLv2RiskAdj castOther = (NcmLv2RiskAdj) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getCptlDivCd() == null ? 0 : this.getCptlDivCd().hashCode());
		result = 37 * result + (getYieldLclssCd() == null ? 0 : this.getYieldLclssCd().hashCode());
		result = 37 * result + (getYieldDivCd() == null ? 0 : this.getYieldDivCd().hashCode());
		result = 37 * result + (getProdTypeCd() == null ? 0 : this.getProdTypeCd().hashCode());
		result = 37 * result + (getMatCd() == null ? 0 : this.getMatCd().hashCode());
		return result;
	}

}
