package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

/**
 * NcmLv2ComplRstId generated by hbm2java
 */

public class NcmLv2ComplRstId implements java.io.Serializable, Navigatable {

	private String baseDate;
	private String applyDivCd;
	private String applyCd;
	private String complTypeCd;
	private short seq;

	public NcmLv2ComplRstId() {
	}

	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;

	}

	public String getApplyDivCd() {
		return this.applyDivCd;
	}

	public void setApplyDivCd(String applyDivCd) {
		this.applyDivCd = applyDivCd;

	}

	public String getApplyCd() {
		return this.applyCd;
	}

	public void setApplyCd(String applyCd) {
		this.applyCd = applyCd;

	}

	public String getComplTypeCd() {
		return this.complTypeCd;
	}

	public void setComplTypeCd(String complTypeCd) {
		this.complTypeCd = complTypeCd;

	}

	public short getSeq() {
		return this.seq;
	}

	public void setSeq(short seq) {
		this.seq = seq;

	}

	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getApplyDivCd());
		buffer.append("#").append(getApplyCd());
		buffer.append("#").append(getComplTypeCd());
		buffer.append("#").append(getSeq());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmLv2ComplRstId))
			return false;
		NcmLv2ComplRstId castOther = (NcmLv2ComplRstId) other;

		return ((this.getBaseDate() == castOther.getBaseDate())
				|| (this.getBaseDate() != null && castOther.getBaseDate() != null && this.getBaseDate().equals(castOther.getBaseDate())))
				&& ((this.getApplyDivCd() == castOther.getApplyDivCd())
						|| (this.getApplyDivCd() != null && castOther.getApplyDivCd() != null && this.getApplyDivCd().equals(castOther.getApplyDivCd())))
				&& ((this.getApplyCd() == castOther.getApplyCd())
						|| (this.getApplyCd() != null && castOther.getApplyCd() != null && this.getApplyCd().equals(castOther.getApplyCd())))
				&& ((this.getComplTypeCd() == castOther.getComplTypeCd())
						|| (this.getComplTypeCd() != null && castOther.getComplTypeCd() != null && this.getComplTypeCd().equals(castOther.getComplTypeCd())))
				&& (this.getSeq() == castOther.getSeq());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getApplyDivCd() == null ? 0 : this.getApplyDivCd().hashCode());
		result = 37 * result + (getApplyCd() == null ? 0 : this.getApplyCd().hashCode());
		result = 37 * result + (getComplTypeCd() == null ? 0 : this.getComplTypeCd().hashCode());
		result = 37 * result + this.getSeq();
		return result;
	}

}
