package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmLv2PortAmtRisk generated by hbm2java
 */

@Entity(name = "NaviNcmLv2PortAmtRisk")
@IdClass(value = NcmLv2PortAmtRiskId.class)
@Table(name = "NCM_LV2_PORT_AMT_RISK", schema = "NCM")
public class NcmLv2PortAmtRisk implements java.io.Serializable, Navigatable {

	private String baseDate;
	private String cptlDivCd;
	private String yieldLclssCd;
	private String yieldDivCd;
	private String prodTypeCd;
	private BigDecimal hldAmt;
	private BigDecimal bookAmt;
	private BigDecimal mktEvalAmt;
	private BigDecimal bdayEvalAmt;
	private BigDecimal intInflowAmt;
	private BigDecimal accumRealPl;
	private BigDecimal evalPl;
	private BigDecimal evalPlInc;
	private BigDecimal todayBuyAmt;
	private BigDecimal todaySellAmt;
	private BigDecimal dbaseEvalAmt;
	private BigDecimal nbaseEvalAmt;
	private BigDecimal hldAmtWght;
	private BigDecimal mktEvalWght;
	private BigDecimal todayAwghtYield;
	private BigDecimal todayTwghtYield;
	private BigDecimal accumTwghtYield;
	private BigDecimal accumEvalAmt;
	private BigDecimal accumHldWght;
	private BigDecimal accumEvalWght;
	private BigDecimal hldCnt;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmLv2PortAmtRisk() {
	}

	@Id
	@Column(name = "BASE_DATE", nullable = false, length = 8)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Id
	@Column(name = "CPTL_DIV_CD", nullable = false, length = 10)
	public String getCptlDivCd() {
		return this.cptlDivCd;
	}

	public void setCptlDivCd(String cptlDivCd) {
		this.cptlDivCd = cptlDivCd;
	}

	@Id
	@Column(name = "YIELD_LCLSS_CD", nullable = false, length = 10)
	public String getYieldLclssCd() {
		return this.yieldLclssCd;
	}

	public void setYieldLclssCd(String yieldLclssCd) {
		this.yieldLclssCd = yieldLclssCd;
	}

	@Id
	@Column(name = "YIELD_DIV_CD", nullable = false, length = 20)
	public String getYieldDivCd() {
		return this.yieldDivCd;
	}

	public void setYieldDivCd(String yieldDivCd) {
		this.yieldDivCd = yieldDivCd;
	}

	@Id
	@Column(name = "PROD_TYPE_CD", nullable = false, length = 10)
	public String getProdTypeCd() {
		return this.prodTypeCd;
	}

	public void setProdTypeCd(String prodTypeCd) {
		this.prodTypeCd = prodTypeCd;
	}

	@Column(name = "HLD_AMT", precision = 22, scale = 0)
	public BigDecimal getHldAmt() {
		return this.hldAmt;
	}

	public void setHldAmt(BigDecimal hldAmt) {
		this.hldAmt = hldAmt;

	}

	@Column(name = "BOOK_AMT", precision = 22, scale = 0)
	public BigDecimal getBookAmt() {
		return this.bookAmt;
	}

	public void setBookAmt(BigDecimal bookAmt) {
		this.bookAmt = bookAmt;

	}

	@Column(name = "MKT_EVAL_AMT", precision = 22, scale = 0)
	public BigDecimal getMktEvalAmt() {
		return this.mktEvalAmt;
	}

	public void setMktEvalAmt(BigDecimal mktEvalAmt) {
		this.mktEvalAmt = mktEvalAmt;

	}

	@Column(name = "BDAY_EVAL_AMT", precision = 22, scale = 0)
	public BigDecimal getBdayEvalAmt() {
		return this.bdayEvalAmt;
	}

	public void setBdayEvalAmt(BigDecimal bdayEvalAmt) {
		this.bdayEvalAmt = bdayEvalAmt;

	}

	@Column(name = "INT_INFLOW_AMT", precision = 22, scale = 0)
	public BigDecimal getIntInflowAmt() {
		return this.intInflowAmt;
	}

	public void setIntInflowAmt(BigDecimal intInflowAmt) {
		this.intInflowAmt = intInflowAmt;

	}

	@Column(name = "ACCUM_REAL_PL", precision = 22, scale = 0)
	public BigDecimal getAccumRealPl() {
		return this.accumRealPl;
	}

	public void setAccumRealPl(BigDecimal accumRealPl) {
		this.accumRealPl = accumRealPl;

	}

	@Column(name = "EVAL_PL", precision = 22, scale = 0)
	public BigDecimal getEvalPl() {
		return this.evalPl;
	}

	public void setEvalPl(BigDecimal evalPl) {
		this.evalPl = evalPl;

	}

	@Column(name = "EVAL_PL_INC", precision = 22, scale = 0)
	public BigDecimal getEvalPlInc() {
		return this.evalPlInc;
	}

	public void setEvalPlInc(BigDecimal evalPlInc) {
		this.evalPlInc = evalPlInc;

	}

	@Column(name = "TODAY_BUY_AMT", precision = 22, scale = 0)
	public BigDecimal getTodayBuyAmt() {
		return this.todayBuyAmt;
	}

	public void setTodayBuyAmt(BigDecimal todayBuyAmt) {
		this.todayBuyAmt = todayBuyAmt;

	}

	@Column(name = "TODAY_SELL_AMT", precision = 22, scale = 0)
	public BigDecimal getTodaySellAmt() {
		return this.todaySellAmt;
	}

	public void setTodaySellAmt(BigDecimal todaySellAmt) {
		this.todaySellAmt = todaySellAmt;

	}

	@Column(name = "DBASE_EVAL_AMT", precision = 22, scale = 0)
	public BigDecimal getDbaseEvalAmt() {
		return this.dbaseEvalAmt;
	}

	public void setDbaseEvalAmt(BigDecimal dbaseEvalAmt) {
		this.dbaseEvalAmt = dbaseEvalAmt;

	}

	@Column(name = "NBASE_EVAL_AMT", precision = 22, scale = 0)
	public BigDecimal getNbaseEvalAmt() {
		return this.nbaseEvalAmt;
	}

	public void setNbaseEvalAmt(BigDecimal nbaseEvalAmt) {
		this.nbaseEvalAmt = nbaseEvalAmt;

	}

	@Column(name = "HLD_AMT_WGHT", precision = 12, scale = 8)
	public BigDecimal getHldAmtWght() {
		return this.hldAmtWght;
	}

	public void setHldAmtWght(BigDecimal hldAmtWght) {
		this.hldAmtWght = hldAmtWght;

	}

	@Column(name = "MKT_EVAL_WGHT", precision = 12, scale = 8)
	public BigDecimal getMktEvalWght() {
		return this.mktEvalWght;
	}

	public void setMktEvalWght(BigDecimal mktEvalWght) {
		this.mktEvalWght = mktEvalWght;

	}

	@Column(name = "TODAY_AWGHT_YIELD", precision = 12, scale = 8)
	public BigDecimal getTodayAwghtYield() {
		return this.todayAwghtYield;
	}

	public void setTodayAwghtYield(BigDecimal todayAwghtYield) {
		this.todayAwghtYield = todayAwghtYield;

	}

	@Column(name = "TODAY_TWGHT_YIELD", precision = 12, scale = 8)
	public BigDecimal getTodayTwghtYield() {
		return this.todayTwghtYield;
	}

	public void setTodayTwghtYield(BigDecimal todayTwghtYield) {
		this.todayTwghtYield = todayTwghtYield;

	}

	@Column(name = "ACCUM_TWGHT_YIELD", precision = 12, scale = 8)
	public BigDecimal getAccumTwghtYield() {
		return this.accumTwghtYield;
	}

	public void setAccumTwghtYield(BigDecimal accumTwghtYield) {
		this.accumTwghtYield = accumTwghtYield;

	}

	@Column(name = "ACCUM_EVAL_AMT", precision = 22, scale = 0)
	public BigDecimal getAccumEvalAmt() {
		return this.accumEvalAmt;
	}

	public void setAccumEvalAmt(BigDecimal accumEvalAmt) {
		this.accumEvalAmt = accumEvalAmt;

	}

	@Column(name = "ACCUM_HLD_WGHT", precision = 12, scale = 8)
	public BigDecimal getAccumHldWght() {
		return this.accumHldWght;
	}

	public void setAccumHldWght(BigDecimal accumHldWght) {
		this.accumHldWght = accumHldWght;

	}

	@Column(name = "ACCUM_EVAL_WGHT", precision = 12, scale = 8)
	public BigDecimal getAccumEvalWght() {
		return this.accumEvalWght;
	}

	public void setAccumEvalWght(BigDecimal accumEvalWght) {
		this.accumEvalWght = accumEvalWght;

	}

	@Column(name = "HLD_CNT", precision = 22, scale = 0)
	public BigDecimal getHldCnt() {
		return this.hldCnt;
	}

	public void setHldCnt(BigDecimal hldCnt) {
		this.hldCnt = hldCnt;

	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getCptlDivCd());
		buffer.append("#").append(getYieldLclssCd());
		buffer.append("#").append(getYieldDivCd());
		buffer.append("#").append(getProdTypeCd());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmLv2PortAmtRisk))
			return false;
		NcmLv2PortAmtRisk castOther = (NcmLv2PortAmtRisk) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getCptlDivCd() == null ? 0 : this.getCptlDivCd().hashCode());
		result = 37 * result + (getYieldLclssCd() == null ? 0 : this.getYieldLclssCd().hashCode());
		result = 37 * result + (getYieldDivCd() == null ? 0 : this.getYieldDivCd().hashCode());
		result = 37 * result + (getProdTypeCd() == null ? 0 : this.getProdTypeCd().hashCode());
		return result;
	}

}
