package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMmtPosition generated by hbm2java
 */

@Entity(name = "NaviNcmMmtPosition")
@IdClass(value = NcmMmtPositionId.class)
@Table(name = "NCM_MMT_POSITION", schema = "NCM")
public class NcmMmtPosition implements java.io.Serializable, Navigatable {

	private String seqNo;
	private String bizDt;
	private String stockCd;
	private String acctCd;
	private String cptlGb;
	private String termGb;
	private String bankNm;
	private String acctNm;
	private String estbDt;
	private long faceAmt;
	private BigDecimal prRet;
	private String exprDt;
	private BigDecimal clsRet;
	private Long exprAmt;
	private boolean acctGb;
	private Date creDttm;
	private String creEmpNo;
	private Date chgDttm;
	private String chgEmpNo;
	private String workfilename;

	public NcmMmtPosition() {
	}

	@Id
	@Column(name = "SEQ_NO", nullable = false, length = 7)
	public String getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(String seqNo) {
		this.seqNo = seqNo;
	}

	@Id
	@Column(name = "BIZ_DT", nullable = false, length = 8)
	public String getBizDt() {
		return this.bizDt;
	}

	public void setBizDt(String bizDt) {
		this.bizDt = bizDt;
	}

	@Id
	@Column(name = "STOCK_CD", nullable = false, length = 13)
	public String getStockCd() {
		return this.stockCd;
	}

	public void setStockCd(String stockCd) {
		this.stockCd = stockCd;
	}

	@Id
	@Column(name = "ACCT_CD", nullable = false, length = 30)
	public String getAcctCd() {
		return this.acctCd;
	}

	public void setAcctCd(String acctCd) {
		this.acctCd = acctCd;
	}

	@Id
	@Column(name = "CPTL_GB", nullable = false, length = 2)
	public String getCptlGb() {
		return this.cptlGb;
	}

	public void setCptlGb(String cptlGb) {
		this.cptlGb = cptlGb;
	}

	@Id
	@Column(name = "TERM_GB", nullable = false, length = 2)
	public String getTermGb() {
		return this.termGb;
	}

	public void setTermGb(String termGb) {
		this.termGb = termGb;
	}

	@Column(name = "BANK_NM", nullable = false, length = 30)
	public String getBankNm() {
		return this.bankNm;
	}

	public void setBankNm(String bankNm) {
		this.bankNm = bankNm;

	}

	@Column(name = "ACCT_NM", nullable = false, length = 100)
	public String getAcctNm() {
		return this.acctNm;
	}

	public void setAcctNm(String acctNm) {
		this.acctNm = acctNm;

	}

	@Column(name = "ESTB_DT", nullable = false, length = 8)
	public String getEstbDt() {
		return this.estbDt;
	}

	public void setEstbDt(String estbDt) {
		this.estbDt = estbDt;

	}

	@Column(name = "FACE_AMT", nullable = false, precision = 15, scale = 0)
	public long getFaceAmt() {
		return this.faceAmt;
	}

	public void setFaceAmt(long faceAmt) {
		this.faceAmt = faceAmt;

	}

	@Column(name = "PR_RET", nullable = false, precision = 7, scale = 3)
	public BigDecimal getPrRet() {
		return this.prRet;
	}

	public void setPrRet(BigDecimal prRet) {
		this.prRet = prRet;

	}

	@Column(name = "EXPR_DT", nullable = false, length = 8)
	public String getExprDt() {
		return this.exprDt;
	}

	public void setExprDt(String exprDt) {
		this.exprDt = exprDt;

	}

	@Column(name = "CLS_RET", precision = 7, scale = 3)
	public BigDecimal getClsRet() {
		return this.clsRet;
	}

	public void setClsRet(BigDecimal clsRet) {
		this.clsRet = clsRet;

	}

	@Column(name = "EXPR_AMT", precision = 15, scale = 0)
	public Long getExprAmt() {
		return this.exprAmt;
	}

	public void setExprAmt(Long exprAmt) {
		this.exprAmt = exprAmt;

	}

	@Column(name = "ACCT_GB", nullable = false, precision = 1, scale = 0)
	public boolean isAcctGb() {
		return this.acctGb;
	}

	public void setAcctGb(boolean acctGb) {
		this.acctGb = acctGb;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRE_DTTM", length = 7)
	public Date getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm) {
		this.creDttm = creDttm;

	}

	@Column(name = "CRE_EMP_NO", length = 6)
	public String getCreEmpNo() {
		return this.creEmpNo;
	}

	public void setCreEmpNo(String creEmpNo) {
		this.creEmpNo = creEmpNo;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHG_DTTM", length = 7)
	public Date getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(Date chgDttm) {
		this.chgDttm = chgDttm;

	}

	@Column(name = "CHG_EMP_NO", length = 6)
	public String getChgEmpNo() {
		return this.chgEmpNo;
	}

	public void setChgEmpNo(String chgEmpNo) {
		this.chgEmpNo = chgEmpNo;

	}

	@Column(name = "WORKFILENAME", length = 30)
	public String getWorkfilename() {
		return this.workfilename;
	}

	public void setWorkfilename(String workfilename) {
		this.workfilename = workfilename;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getSeqNo());
		buffer.append("#").append(getBizDt());
		buffer.append("#").append(getStockCd());
		buffer.append("#").append(getAcctCd());
		buffer.append("#").append(getCptlGb());
		buffer.append("#").append(getTermGb());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMmtPosition))
			return false;
		NcmMmtPosition castOther = (NcmMmtPosition) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSeqNo() == null ? 0 : this.getSeqNo().hashCode());
		result = 37 * result + (getBizDt() == null ? 0 : this.getBizDt().hashCode());
		result = 37 * result + (getStockCd() == null ? 0 : this.getStockCd().hashCode());
		result = 37 * result + (getAcctCd() == null ? 0 : this.getAcctCd().hashCode());
		result = 37 * result + (getCptlGb() == null ? 0 : this.getCptlGb().hashCode());
		result = 37 * result + (getTermGb() == null ? 0 : this.getTermGb().hashCode());
		return result;
	}

}
