package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import java.util.Date;

/**
 * NcmMstCodeTmpId generated by hbm2java
 */

public class NcmMstCodeTmpId implements java.io.Serializable, Navigatable {

	private String codeGroup;
	private String codeId;
	private String codeNm;
	private String codeRemark;
	private String codeGroupNm;
	private BigDecimal codeOrder;
	private String updateId;
	private Date lastUpdate;

	public NcmMstCodeTmpId() {
	}

	public String getCodeGroup() {
		return this.codeGroup;
	}

	public void setCodeGroup(String codeGroup) {
		this.codeGroup = codeGroup;

	}

	public String getCodeId() {
		return this.codeId;
	}

	public void setCodeId(String codeId) {
		this.codeId = codeId;

	}

	public String getCodeNm() {
		return this.codeNm;
	}

	public void setCodeNm(String codeNm) {
		this.codeNm = codeNm;

	}

	public String getCodeRemark() {
		return this.codeRemark;
	}

	public void setCodeRemark(String codeRemark) {
		this.codeRemark = codeRemark;

	}

	public String getCodeGroupNm() {
		return this.codeGroupNm;
	}

	public void setCodeGroupNm(String codeGroupNm) {
		this.codeGroupNm = codeGroupNm;

	}

	public BigDecimal getCodeOrder() {
		return this.codeOrder;
	}

	public void setCodeOrder(BigDecimal codeOrder) {
		this.codeOrder = codeOrder;

	}

	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getCodeGroup());
		buffer.append("#").append(getCodeId());
		buffer.append("#").append(getCodeNm());
		buffer.append("#").append(getCodeRemark());
		buffer.append("#").append(getCodeGroupNm());
		buffer.append("#").append(getCodeOrder());
		buffer.append("#").append(getUpdateId());
		buffer.append("#").append(getLastUpdate());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstCodeTmpId))
			return false;
		NcmMstCodeTmpId castOther = (NcmMstCodeTmpId) other;

		return ((this.getCodeGroup() == castOther.getCodeGroup())
				|| (this.getCodeGroup() != null && castOther.getCodeGroup() != null && this.getCodeGroup().equals(castOther.getCodeGroup())))
				&& ((this.getCodeId() == castOther.getCodeId()) || (this.getCodeId() != null && castOther.getCodeId() != null && this.getCodeId().equals(castOther.getCodeId())))
				&& ((this.getCodeNm() == castOther.getCodeNm()) || (this.getCodeNm() != null && castOther.getCodeNm() != null && this.getCodeNm().equals(castOther.getCodeNm())))
				&& ((this.getCodeRemark() == castOther.getCodeRemark())
						|| (this.getCodeRemark() != null && castOther.getCodeRemark() != null && this.getCodeRemark().equals(castOther.getCodeRemark())))
				&& ((this.getCodeGroupNm() == castOther.getCodeGroupNm())
						|| (this.getCodeGroupNm() != null && castOther.getCodeGroupNm() != null && this.getCodeGroupNm().equals(castOther.getCodeGroupNm())))
				&& ((this.getCodeOrder() == castOther.getCodeOrder())
						|| (this.getCodeOrder() != null && castOther.getCodeOrder() != null && this.getCodeOrder().equals(castOther.getCodeOrder())))
				&& ((this.getUpdateId() == castOther.getUpdateId())
						|| (this.getUpdateId() != null && castOther.getUpdateId() != null && this.getUpdateId().equals(castOther.getUpdateId())))
				&& ((this.getLastUpdate() == castOther.getLastUpdate())
						|| (this.getLastUpdate() != null && castOther.getLastUpdate() != null && this.getLastUpdate().equals(castOther.getLastUpdate())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodeGroup() == null ? 0 : this.getCodeGroup().hashCode());
		result = 37 * result + (getCodeId() == null ? 0 : this.getCodeId().hashCode());
		result = 37 * result + (getCodeNm() == null ? 0 : this.getCodeNm().hashCode());
		result = 37 * result + (getCodeRemark() == null ? 0 : this.getCodeRemark().hashCode());
		result = 37 * result + (getCodeGroupNm() == null ? 0 : this.getCodeGroupNm().hashCode());
		result = 37 * result + (getCodeOrder() == null ? 0 : this.getCodeOrder().hashCode());
		result = 37 * result + (getUpdateId() == null ? 0 : this.getUpdateId().hashCode());
		result = 37 * result + (getLastUpdate() == null ? 0 : this.getLastUpdate().hashCode());
		return result;
	}

}
