package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * NcmMstBmcompositeTmp generated by hbm2java
 */

@Entity(name = "NaviNcmMstBmcompositeTmp")
@IdClass(value = NcmMstBmcompositeTmpId.class)
@Table(name = "NCM_MST_BMCOMPOSITE_TMP", schema = "NCM")
public class NcmMstBmcompositeTmp implements java.io.Serializable, Navigatable {

	private String bmId;
	private String bmAppoint;
	private String subBmId;
	private BigDecimal compRatio;
	private String applyStDate;
	private String applyEndDate;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMstBmcompositeTmp() {
	}

	@Id
	@Column(name = "BM_ID", nullable = false, length = 20)
	public String getBmId() {
		return this.bmId;
	}

	public void setBmId(String bmId) {
		this.bmId = bmId;
	}

	@Id
	@Column(name = "BM_APPOINT", length = 2)
	public String getBmAppoint() {
		return this.bmAppoint;
	}

	public void setBmAppoint(String bmAppoint) {
		this.bmAppoint = bmAppoint;
	}

	@Id
	@Column(name = "SUB_BM_ID", nullable = false, length = 20)
	public String getSubBmId() {
		return this.subBmId;
	}

	public void setSubBmId(String subBmId) {
		this.subBmId = subBmId;
	}

	@Id
	@Column(name = "COMP_RATIO", precision = 10, scale = 5)
	public BigDecimal getCompRatio() {
		return this.compRatio;
	}

	public void setCompRatio(BigDecimal compRatio) {
		this.compRatio = compRatio;
	}

	@Id
	@Column(name = "APPLY_ST_DATE", length = 8)
	public String getApplyStDate() {
		return this.applyStDate;
	}

	public void setApplyStDate(String applyStDate) {
		this.applyStDate = applyStDate;
	}

	@Id
	@Column(name = "APPLY_END_DATE", nullable = false, length = 8)
	public String getApplyEndDate() {
		return this.applyEndDate;
	}

	public void setApplyEndDate(String applyEndDate) {
		this.applyEndDate = applyEndDate;
	}

	@Id
	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}

	@Id
	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	@Id
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBmId());
		buffer.append("#").append(getBmAppoint());
		buffer.append("#").append(getSubBmId());
		buffer.append("#").append(getCompRatio());
		buffer.append("#").append(getApplyStDate());
		buffer.append("#").append(getApplyEndDate());
		buffer.append("#").append(getSrcTable());
		buffer.append("#").append(getUpdateId());
		buffer.append("#").append(getLastUpdate());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstBmcompositeTmp))
			return false;
		NcmMstBmcompositeTmp castOther = (NcmMstBmcompositeTmp) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBmId() == null ? 0 : this.getBmId().hashCode());
		result = 37 * result + (getBmAppoint() == null ? 0 : this.getBmAppoint().hashCode());
		result = 37 * result + (getSubBmId() == null ? 0 : this.getSubBmId().hashCode());
		result = 37 * result + (getCompRatio() == null ? 0 : this.getCompRatio().hashCode());
		result = 37 * result + (getApplyStDate() == null ? 0 : this.getApplyStDate().hashCode());
		result = 37 * result + (getApplyEndDate() == null ? 0 : this.getApplyEndDate().hashCode());
		result = 37 * result + (getSrcTable() == null ? 0 : this.getSrcTable().hashCode());
		result = 37 * result + (getUpdateId() == null ? 0 : this.getUpdateId().hashCode());
		result = 37 * result + (getLastUpdate() == null ? 0 : this.getLastUpdate().hashCode());
		return result;
	}

}
