package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMktYieldCurve generated by hbm2java
 */

@Entity(name = "NaviNcmMktYieldCurve")
@IdClass(value = NcmMktYieldCurveId.class)
@Table(name = "NCM_MKT_YIELD_CURVE", schema = "NCM")
public class NcmMktYieldCurve implements java.io.Serializable, Navigatable {

	private String baseDate;
	private String mvId;
	private BigDecimal d001Int;
	private BigDecimal m001Int;
	private BigDecimal m003Int;
	private BigDecimal m006Int;
	private BigDecimal m009Int;
	private BigDecimal m012Int;
	private BigDecimal m018Int;
	private BigDecimal m024Int;
	private BigDecimal m030Int;
	private BigDecimal m036Int;
	private BigDecimal m048Int;
	private BigDecimal m060Int;
	private BigDecimal m084Int;
	private BigDecimal m120Int;
	private BigDecimal m180Int;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMktYieldCurve() {
	}

	@Id
	@Column(name = "BASE_DATE", nullable = false, length = 8)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Id
	@Column(name = "MV_ID", nullable = false, length = 20)
	public String getMvId() {
		return this.mvId;
	}

	public void setMvId(String mvId) {
		this.mvId = mvId;
	}

	@Column(name = "D001_INT", nullable = false, precision = 12, scale = 8)
	public BigDecimal getD001Int() {
		return this.d001Int;
	}

	public void setD001Int(BigDecimal d001Int) {
		this.d001Int = d001Int;

	}

	@Column(name = "M001_INT", nullable = false, precision = 12, scale = 8)
	public BigDecimal getM001Int() {
		return this.m001Int;
	}

	public void setM001Int(BigDecimal m001Int) {
		this.m001Int = m001Int;

	}

	@Column(name = "M003_INT", nullable = false, precision = 12, scale = 8)
	public BigDecimal getM003Int() {
		return this.m003Int;
	}

	public void setM003Int(BigDecimal m003Int) {
		this.m003Int = m003Int;

	}

	@Column(name = "M006_INT", nullable = false, precision = 12, scale = 8)
	public BigDecimal getM006Int() {
		return this.m006Int;
	}

	public void setM006Int(BigDecimal m006Int) {
		this.m006Int = m006Int;

	}

	@Column(name = "M009_INT", nullable = false, precision = 12, scale = 8)
	public BigDecimal getM009Int() {
		return this.m009Int;
	}

	public void setM009Int(BigDecimal m009Int) {
		this.m009Int = m009Int;

	}

	@Column(name = "M012_INT", nullable = false, precision = 12, scale = 8)
	public BigDecimal getM012Int() {
		return this.m012Int;
	}

	public void setM012Int(BigDecimal m012Int) {
		this.m012Int = m012Int;

	}

	@Column(name = "M018_INT", nullable = false, precision = 12, scale = 8)
	public BigDecimal getM018Int() {
		return this.m018Int;
	}

	public void setM018Int(BigDecimal m018Int) {
		this.m018Int = m018Int;

	}

	@Column(name = "M024_INT", nullable = false, precision = 12, scale = 8)
	public BigDecimal getM024Int() {
		return this.m024Int;
	}

	public void setM024Int(BigDecimal m024Int) {
		this.m024Int = m024Int;

	}

	@Column(name = "M030_INT", nullable = false, precision = 12, scale = 8)
	public BigDecimal getM030Int() {
		return this.m030Int;
	}

	public void setM030Int(BigDecimal m030Int) {
		this.m030Int = m030Int;

	}

	@Column(name = "M036_INT", nullable = false, precision = 12, scale = 8)
	public BigDecimal getM036Int() {
		return this.m036Int;
	}

	public void setM036Int(BigDecimal m036Int) {
		this.m036Int = m036Int;

	}

	@Column(name = "M048_INT", nullable = false, precision = 12, scale = 8)
	public BigDecimal getM048Int() {
		return this.m048Int;
	}

	public void setM048Int(BigDecimal m048Int) {
		this.m048Int = m048Int;

	}

	@Column(name = "M060_INT", nullable = false, precision = 12, scale = 8)
	public BigDecimal getM060Int() {
		return this.m060Int;
	}

	public void setM060Int(BigDecimal m060Int) {
		this.m060Int = m060Int;

	}

	@Column(name = "M084_INT", nullable = false, precision = 12, scale = 8)
	public BigDecimal getM084Int() {
		return this.m084Int;
	}

	public void setM084Int(BigDecimal m084Int) {
		this.m084Int = m084Int;

	}

	@Column(name = "M120_INT", nullable = false, precision = 12, scale = 8)
	public BigDecimal getM120Int() {
		return this.m120Int;
	}

	public void setM120Int(BigDecimal m120Int) {
		this.m120Int = m120Int;

	}

	@Column(name = "M180_INT", nullable = false, precision = 12, scale = 8)
	public BigDecimal getM180Int() {
		return this.m180Int;
	}

	public void setM180Int(BigDecimal m180Int) {
		this.m180Int = m180Int;

	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getMvId());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMktYieldCurve))
			return false;
		NcmMktYieldCurve castOther = (NcmMktYieldCurve) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getMvId() == null ? 0 : this.getMvId().hashCode());
		return result;
	}

}
