package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMstPrgm generated by hbm2java
 */

@Entity(name = "NaviNcmMstPrgm")
@Table(name = "NCM_MST_PRGM", schema = "NCM")
public class NcmMstPrgm implements java.io.Serializable, Navigatable {

	private String prgmId;
	private String menuId;
	private BigDecimal seqNo;
	private String menuNm;
	private String updateId;
	private Date lastUpdate;
	private String completeYn;

	public NcmMstPrgm() {
	}

	@Id
	@Column(name = "PRGM_ID", unique = true, nullable = false, length = 100)
	public String getPrgmId() {
		return this.prgmId;
	}

	public void setPrgmId(String prgmId) {
		this.prgmId = prgmId;

	}

	@Column(name = "MENU_ID", length = 20)
	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;

	}

	@Column(name = "SEQ_NO", precision = 22, scale = 0)
	public BigDecimal getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(BigDecimal seqNo) {
		this.seqNo = seqNo;

	}

	@Column(name = "MENU_NM", length = 100)
	public String getMenuNm() {
		return this.menuNm;
	}

	public void setMenuNm(String menuNm) {
		this.menuNm = menuNm;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	@Column(name = "COMPLETE_YN", length = 1)
	public String getCompleteYn() {
		return this.completeYn;
	}

	public void setCompleteYn(String completeYn) {
		this.completeYn = completeYn;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getPrgmId());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstPrgm))
			return false;
		NcmMstPrgm castOther = (NcmMstPrgm) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (idString() == null ? 0 : this.idString().hashCode());
		return result;
	}

}
