package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMktMarketVariable generated by hbm2java
 */

@Entity(name = "NaviNcmMktMarketVariable")
@Table(name = "NCM_MKT_MARKET_VARIABLE", schema = "NCM")
public class NcmMktMarketVariable implements java.io.Serializable, Navigatable {

	private String mvId;
	private String mvNm;
	private String mvTypeCd;
	private String creaOrgId;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMktMarketVariable() {
	}

	@Id
	@Column(name = "MV_ID", unique = true, nullable = false, length = 20)
	public String getMvId() {
		return this.mvId;
	}

	public void setMvId(String mvId) {
		this.mvId = mvId;

	}

	@Column(name = "MV_NM", length = 100)
	public String getMvNm() {
		return this.mvNm;
	}

	public void setMvNm(String mvNm) {
		this.mvNm = mvNm;

	}

	@Column(name = "MV_TYPE_CD", length = 10)
	public String getMvTypeCd() {
		return this.mvTypeCd;
	}

	public void setMvTypeCd(String mvTypeCd) {
		this.mvTypeCd = mvTypeCd;

	}

	@Column(name = "CREA_ORG_ID", length = 20)
	public String getCreaOrgId() {
		return this.creaOrgId;
	}

	public void setCreaOrgId(String creaOrgId) {
		this.creaOrgId = creaOrgId;

	}

	@Column(name = "SRC_TABLE", length = 20)
	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getMvId());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMktMarketVariable))
			return false;
		NcmMktMarketVariable castOther = (NcmMktMarketVariable) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (idString() == null ? 0 : this.idString().hashCode());
		return result;
	}

}
