package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import java.util.Date;

/**
 * NcmMstBmcompositeTmpId generated by hbm2java
 */

public class NcmMstBmcompositeTmpId implements java.io.Serializable, Navigatable {

	private String bmId;
	private String bmAppoint;
	private String subBmId;
	private BigDecimal compRatio;
	private String applyStDate;
	private String applyEndDate;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMstBmcompositeTmpId() {
	}

	public String getBmId() {
		return this.bmId;
	}

	public void setBmId(String bmId) {
		this.bmId = bmId;

	}

	public String getBmAppoint() {
		return this.bmAppoint;
	}

	public void setBmAppoint(String bmAppoint) {
		this.bmAppoint = bmAppoint;

	}

	public String getSubBmId() {
		return this.subBmId;
	}

	public void setSubBmId(String subBmId) {
		this.subBmId = subBmId;

	}

	public BigDecimal getCompRatio() {
		return this.compRatio;
	}

	public void setCompRatio(BigDecimal compRatio) {
		this.compRatio = compRatio;

	}

	public String getApplyStDate() {
		return this.applyStDate;
	}

	public void setApplyStDate(String applyStDate) {
		this.applyStDate = applyStDate;

	}

	public String getApplyEndDate() {
		return this.applyEndDate;
	}

	public void setApplyEndDate(String applyEndDate) {
		this.applyEndDate = applyEndDate;

	}

	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBmId());
		buffer.append("#").append(getBmAppoint());
		buffer.append("#").append(getSubBmId());
		buffer.append("#").append(getCompRatio());
		buffer.append("#").append(getApplyStDate());
		buffer.append("#").append(getApplyEndDate());
		buffer.append("#").append(getSrcTable());
		buffer.append("#").append(getUpdateId());
		buffer.append("#").append(getLastUpdate());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstBmcompositeTmpId))
			return false;
		NcmMstBmcompositeTmpId castOther = (NcmMstBmcompositeTmpId) other;

		return ((this.getBmId() == castOther.getBmId()) || (this.getBmId() != null && castOther.getBmId() != null && this.getBmId().equals(castOther.getBmId())))
				&& ((this.getBmAppoint() == castOther.getBmAppoint())
						|| (this.getBmAppoint() != null && castOther.getBmAppoint() != null && this.getBmAppoint().equals(castOther.getBmAppoint())))
				&& ((this.getSubBmId() == castOther.getSubBmId())
						|| (this.getSubBmId() != null && castOther.getSubBmId() != null && this.getSubBmId().equals(castOther.getSubBmId())))
				&& ((this.getCompRatio() == castOther.getCompRatio())
						|| (this.getCompRatio() != null && castOther.getCompRatio() != null && this.getCompRatio().equals(castOther.getCompRatio())))
				&& ((this.getApplyStDate() == castOther.getApplyStDate())
						|| (this.getApplyStDate() != null && castOther.getApplyStDate() != null && this.getApplyStDate().equals(castOther.getApplyStDate())))
				&& ((this.getApplyEndDate() == castOther.getApplyEndDate())
						|| (this.getApplyEndDate() != null && castOther.getApplyEndDate() != null && this.getApplyEndDate().equals(castOther.getApplyEndDate())))
				&& ((this.getSrcTable() == castOther.getSrcTable())
						|| (this.getSrcTable() != null && castOther.getSrcTable() != null && this.getSrcTable().equals(castOther.getSrcTable())))
				&& ((this.getUpdateId() == castOther.getUpdateId())
						|| (this.getUpdateId() != null && castOther.getUpdateId() != null && this.getUpdateId().equals(castOther.getUpdateId())))
				&& ((this.getLastUpdate() == castOther.getLastUpdate())
						|| (this.getLastUpdate() != null && castOther.getLastUpdate() != null && this.getLastUpdate().equals(castOther.getLastUpdate())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBmId() == null ? 0 : this.getBmId().hashCode());
		result = 37 * result + (getBmAppoint() == null ? 0 : this.getBmAppoint().hashCode());
		result = 37 * result + (getSubBmId() == null ? 0 : this.getSubBmId().hashCode());
		result = 37 * result + (getCompRatio() == null ? 0 : this.getCompRatio().hashCode());
		result = 37 * result + (getApplyStDate() == null ? 0 : this.getApplyStDate().hashCode());
		result = 37 * result + (getApplyEndDate() == null ? 0 : this.getApplyEndDate().hashCode());
		result = 37 * result + (getSrcTable() == null ? 0 : this.getSrcTable().hashCode());
		result = 37 * result + (getUpdateId() == null ? 0 : this.getUpdateId().hashCode());
		result = 37 * result + (getLastUpdate() == null ? 0 : this.getLastUpdate().hashCode());
		return result;
	}

}
