package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * NcmMstDate generated by hbm2java
 */

@Entity(name = "NaviNcmMstDate")
@IdClass(value = NcmMstDateId.class)
@Table(name = "NCM_MST_DATE", schema = "NCM")
public class NcmMstDate implements java.io.Serializable, Navigatable {

	private String calDate;
	private String calDivCd;
	private BigDecimal seqNo;
	private BigDecimal daySeq;
	private BigDecimal weekSeq;
	private String trdYn;
	private String wsYn;
	private String weYn;
	private String msYn;
	private String meYn;
	private String qsYn;
	private String qeYn;
	private String ysYn;
	private String yeYn;
	private String bfD1;
	private String bfD2;
	private String bfW1;
	private String bfW2;
	private String bfM1;
	private String bfM2;
	private String bfM3;
	private String bfM4;
	private String bfM5;
	private String bfM6;
	private String bfM7;
	private String bfM8;
	private String bfM9;
	private String bfM10;
	private String bfM11;
	private String bfM12;
	private String bfM18;
	private String bfM24;
	private String bfM30;
	private String bfM36;
	private String bfM42;
	private String bfM48;
	private String bfM54;
	private String bfM60;
	private String afD1;
	private String bfQ1;

	public NcmMstDate() {
	}

	@Id
	@Column(name = "CAL_DATE", nullable = false, length = 8)
	public String getCalDate() {
		return this.calDate;
	}

	public void setCalDate(String calDate) {
		this.calDate = calDate;
	}

	@Id
	@Column(name = "CAL_DIV_CD", nullable = false, length = 2)
	public String getCalDivCd() {
		return this.calDivCd;
	}

	public void setCalDivCd(String calDivCd) {
		this.calDivCd = calDivCd;
	}

	@Column(name = "SEQ_NO", precision = 22, scale = 0)
	public BigDecimal getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(BigDecimal seqNo) {
		this.seqNo = seqNo;

	}

	@Column(name = "DAY_SEQ", precision = 22, scale = 0)
	public BigDecimal getDaySeq() {
		return this.daySeq;
	}

	public void setDaySeq(BigDecimal daySeq) {
		this.daySeq = daySeq;

	}

	@Column(name = "WEEK_SEQ", precision = 22, scale = 0)
	public BigDecimal getWeekSeq() {
		return this.weekSeq;
	}

	public void setWeekSeq(BigDecimal weekSeq) {
		this.weekSeq = weekSeq;

	}

	@Column(name = "TRD_YN", length = 1)
	public String getTrdYn() {
		return this.trdYn;
	}

	public void setTrdYn(String trdYn) {
		this.trdYn = trdYn;

	}

	@Column(name = "WS_YN", length = 1)
	public String getWsYn() {
		return this.wsYn;
	}

	public void setWsYn(String wsYn) {
		this.wsYn = wsYn;

	}

	@Column(name = "WE_YN", length = 1)
	public String getWeYn() {
		return this.weYn;
	}

	public void setWeYn(String weYn) {
		this.weYn = weYn;

	}

	@Column(name = "MS_YN", length = 1)
	public String getMsYn() {
		return this.msYn;
	}

	public void setMsYn(String msYn) {
		this.msYn = msYn;

	}

	@Column(name = "ME_YN", length = 1)
	public String getMeYn() {
		return this.meYn;
	}

	public void setMeYn(String meYn) {
		this.meYn = meYn;

	}

	@Column(name = "QS_YN", length = 1)
	public String getQsYn() {
		return this.qsYn;
	}

	public void setQsYn(String qsYn) {
		this.qsYn = qsYn;

	}

	@Column(name = "QE_YN", length = 1)
	public String getQeYn() {
		return this.qeYn;
	}

	public void setQeYn(String qeYn) {
		this.qeYn = qeYn;

	}

	@Column(name = "YS_YN", length = 1)
	public String getYsYn() {
		return this.ysYn;
	}

	public void setYsYn(String ysYn) {
		this.ysYn = ysYn;

	}

	@Column(name = "YE_YN", length = 1)
	public String getYeYn() {
		return this.yeYn;
	}

	public void setYeYn(String yeYn) {
		this.yeYn = yeYn;

	}

	@Column(name = "BF_D1", length = 8)
	public String getBfD1() {
		return this.bfD1;
	}

	public void setBfD1(String bfD1) {
		this.bfD1 = bfD1;

	}

	@Column(name = "BF_D2", length = 8)
	public String getBfD2() {
		return this.bfD2;
	}

	public void setBfD2(String bfD2) {
		this.bfD2 = bfD2;

	}

	@Column(name = "BF_W1", length = 8)
	public String getBfW1() {
		return this.bfW1;
	}

	public void setBfW1(String bfW1) {
		this.bfW1 = bfW1;

	}

	@Column(name = "BF_W2", length = 8)
	public String getBfW2() {
		return this.bfW2;
	}

	public void setBfW2(String bfW2) {
		this.bfW2 = bfW2;

	}

	@Column(name = "BF_M1", length = 8)
	public String getBfM1() {
		return this.bfM1;
	}

	public void setBfM1(String bfM1) {
		this.bfM1 = bfM1;

	}

	@Column(name = "BF_M2", length = 8)
	public String getBfM2() {
		return this.bfM2;
	}

	public void setBfM2(String bfM2) {
		this.bfM2 = bfM2;

	}

	@Column(name = "BF_M3", length = 8)
	public String getBfM3() {
		return this.bfM3;
	}

	public void setBfM3(String bfM3) {
		this.bfM3 = bfM3;

	}

	@Column(name = "BF_M4", length = 8)
	public String getBfM4() {
		return this.bfM4;
	}

	public void setBfM4(String bfM4) {
		this.bfM4 = bfM4;

	}

	@Column(name = "BF_M5", length = 8)
	public String getBfM5() {
		return this.bfM5;
	}

	public void setBfM5(String bfM5) {
		this.bfM5 = bfM5;

	}

	@Column(name = "BF_M6", length = 8)
	public String getBfM6() {
		return this.bfM6;
	}

	public void setBfM6(String bfM6) {
		this.bfM6 = bfM6;

	}

	@Column(name = "BF_M7", length = 8)
	public String getBfM7() {
		return this.bfM7;
	}

	public void setBfM7(String bfM7) {
		this.bfM7 = bfM7;

	}

	@Column(name = "BF_M8", length = 8)
	public String getBfM8() {
		return this.bfM8;
	}

	public void setBfM8(String bfM8) {
		this.bfM8 = bfM8;

	}

	@Column(name = "BF_M9", length = 8)
	public String getBfM9() {
		return this.bfM9;
	}

	public void setBfM9(String bfM9) {
		this.bfM9 = bfM9;

	}

	@Column(name = "BF_M10", length = 8)
	public String getBfM10() {
		return this.bfM10;
	}

	public void setBfM10(String bfM10) {
		this.bfM10 = bfM10;

	}

	@Column(name = "BF_M11", length = 8)
	public String getBfM11() {
		return this.bfM11;
	}

	public void setBfM11(String bfM11) {
		this.bfM11 = bfM11;

	}

	@Column(name = "BF_M12", length = 8)
	public String getBfM12() {
		return this.bfM12;
	}

	public void setBfM12(String bfM12) {
		this.bfM12 = bfM12;

	}

	@Column(name = "BF_M18", length = 8)
	public String getBfM18() {
		return this.bfM18;
	}

	public void setBfM18(String bfM18) {
		this.bfM18 = bfM18;

	}

	@Column(name = "BF_M24", length = 8)
	public String getBfM24() {
		return this.bfM24;
	}

	public void setBfM24(String bfM24) {
		this.bfM24 = bfM24;

	}

	@Column(name = "BF_M30", length = 8)
	public String getBfM30() {
		return this.bfM30;
	}

	public void setBfM30(String bfM30) {
		this.bfM30 = bfM30;

	}

	@Column(name = "BF_M36", length = 8)
	public String getBfM36() {
		return this.bfM36;
	}

	public void setBfM36(String bfM36) {
		this.bfM36 = bfM36;

	}

	@Column(name = "BF_M42", length = 8)
	public String getBfM42() {
		return this.bfM42;
	}

	public void setBfM42(String bfM42) {
		this.bfM42 = bfM42;

	}

	@Column(name = "BF_M48", length = 8)
	public String getBfM48() {
		return this.bfM48;
	}

	public void setBfM48(String bfM48) {
		this.bfM48 = bfM48;

	}

	@Column(name = "BF_M54", length = 8)
	public String getBfM54() {
		return this.bfM54;
	}

	public void setBfM54(String bfM54) {
		this.bfM54 = bfM54;

	}

	@Column(name = "BF_M60", length = 8)
	public String getBfM60() {
		return this.bfM60;
	}

	public void setBfM60(String bfM60) {
		this.bfM60 = bfM60;

	}

	@Column(name = "AF_D1", length = 8)
	public String getAfD1() {
		return this.afD1;
	}

	public void setAfD1(String afD1) {
		this.afD1 = afD1;

	}

	@Column(name = "BF_Q1", length = 8)
	public String getBfQ1() {
		return this.bfQ1;
	}

	public void setBfQ1(String bfQ1) {
		this.bfQ1 = bfQ1;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getCalDate());
		buffer.append("#").append(getCalDivCd());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstDate))
			return false;
		NcmMstDate castOther = (NcmMstDate) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCalDate() == null ? 0 : this.getCalDate().hashCode());
		result = 37 * result + (getCalDivCd() == null ? 0 : this.getCalDivCd().hashCode());
		return result;
	}

}
