package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.util.Date;

/**
 * NcmMstProdTypeTmpId generated by hbm2java
 */

public class NcmMstProdTypeTmpId implements java.io.Serializable, Navigatable {

	private String prodTypeCd;
	private String prodTypeNm;
	private String prodLclssCd;
	private String fixIntYn;
	private String guarYn;
	private String dmstDivCd;
	private String prodHldYn;
	private String hedgeDivCd;
	private String srcTable;
	private String updateId;
	private Date lastUpdate;

	public NcmMstProdTypeTmpId() {
	}

	public String getProdTypeCd() {
		return this.prodTypeCd;
	}

	public void setProdTypeCd(String prodTypeCd) {
		this.prodTypeCd = prodTypeCd;

	}

	public String getProdTypeNm() {
		return this.prodTypeNm;
	}

	public void setProdTypeNm(String prodTypeNm) {
		this.prodTypeNm = prodTypeNm;

	}

	public String getProdLclssCd() {
		return this.prodLclssCd;
	}

	public void setProdLclssCd(String prodLclssCd) {
		this.prodLclssCd = prodLclssCd;

	}

	public String getFixIntYn() {
		return this.fixIntYn;
	}

	public void setFixIntYn(String fixIntYn) {
		this.fixIntYn = fixIntYn;

	}

	public String getGuarYn() {
		return this.guarYn;
	}

	public void setGuarYn(String guarYn) {
		this.guarYn = guarYn;

	}

	public String getDmstDivCd() {
		return this.dmstDivCd;
	}

	public void setDmstDivCd(String dmstDivCd) {
		this.dmstDivCd = dmstDivCd;

	}

	public String getProdHldYn() {
		return this.prodHldYn;
	}

	public void setProdHldYn(String prodHldYn) {
		this.prodHldYn = prodHldYn;

	}

	public String getHedgeDivCd() {
		return this.hedgeDivCd;
	}

	public void setHedgeDivCd(String hedgeDivCd) {
		this.hedgeDivCd = hedgeDivCd;

	}

	public String getSrcTable() {
		return this.srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;

	}

	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getProdTypeCd());
		buffer.append("#").append(getProdTypeNm());
		buffer.append("#").append(getProdLclssCd());
		buffer.append("#").append(getFixIntYn());
		buffer.append("#").append(getGuarYn());
		buffer.append("#").append(getDmstDivCd());
		buffer.append("#").append(getProdHldYn());
		buffer.append("#").append(getHedgeDivCd());
		buffer.append("#").append(getSrcTable());
		buffer.append("#").append(getUpdateId());
		buffer.append("#").append(getLastUpdate());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMstProdTypeTmpId))
			return false;
		NcmMstProdTypeTmpId castOther = (NcmMstProdTypeTmpId) other;

		return ((this.getProdTypeCd() == castOther.getProdTypeCd())
				|| (this.getProdTypeCd() != null && castOther.getProdTypeCd() != null && this.getProdTypeCd().equals(castOther.getProdTypeCd())))
				&& ((this.getProdTypeNm() == castOther.getProdTypeNm())
						|| (this.getProdTypeNm() != null && castOther.getProdTypeNm() != null && this.getProdTypeNm().equals(castOther.getProdTypeNm())))
				&& ((this.getProdLclssCd() == castOther.getProdLclssCd())
						|| (this.getProdLclssCd() != null && castOther.getProdLclssCd() != null && this.getProdLclssCd().equals(castOther.getProdLclssCd())))
				&& ((this.getFixIntYn() == castOther.getFixIntYn())
						|| (this.getFixIntYn() != null && castOther.getFixIntYn() != null && this.getFixIntYn().equals(castOther.getFixIntYn())))
				&& ((this.getGuarYn() == castOther.getGuarYn()) || (this.getGuarYn() != null && castOther.getGuarYn() != null && this.getGuarYn().equals(castOther.getGuarYn())))
				&& ((this.getDmstDivCd() == castOther.getDmstDivCd())
						|| (this.getDmstDivCd() != null && castOther.getDmstDivCd() != null && this.getDmstDivCd().equals(castOther.getDmstDivCd())))
				&& ((this.getProdHldYn() == castOther.getProdHldYn())
						|| (this.getProdHldYn() != null && castOther.getProdHldYn() != null && this.getProdHldYn().equals(castOther.getProdHldYn())))
				&& ((this.getHedgeDivCd() == castOther.getHedgeDivCd())
						|| (this.getHedgeDivCd() != null && castOther.getHedgeDivCd() != null && this.getHedgeDivCd().equals(castOther.getHedgeDivCd())))
				&& ((this.getSrcTable() == castOther.getSrcTable())
						|| (this.getSrcTable() != null && castOther.getSrcTable() != null && this.getSrcTable().equals(castOther.getSrcTable())))
				&& ((this.getUpdateId() == castOther.getUpdateId())
						|| (this.getUpdateId() != null && castOther.getUpdateId() != null && this.getUpdateId().equals(castOther.getUpdateId())))
				&& ((this.getLastUpdate() == castOther.getLastUpdate())
						|| (this.getLastUpdate() != null && castOther.getLastUpdate() != null && this.getLastUpdate().equals(castOther.getLastUpdate())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProdTypeCd() == null ? 0 : this.getProdTypeCd().hashCode());
		result = 37 * result + (getProdTypeNm() == null ? 0 : this.getProdTypeNm().hashCode());
		result = 37 * result + (getProdLclssCd() == null ? 0 : this.getProdLclssCd().hashCode());
		result = 37 * result + (getFixIntYn() == null ? 0 : this.getFixIntYn().hashCode());
		result = 37 * result + (getGuarYn() == null ? 0 : this.getGuarYn().hashCode());
		result = 37 * result + (getDmstDivCd() == null ? 0 : this.getDmstDivCd().hashCode());
		result = 37 * result + (getProdHldYn() == null ? 0 : this.getProdHldYn().hashCode());
		result = 37 * result + (getHedgeDivCd() == null ? 0 : this.getHedgeDivCd().hashCode());
		result = 37 * result + (getSrcTable() == null ? 0 : this.getSrcTable().hashCode());
		result = 37 * result + (getUpdateId() == null ? 0 : this.getUpdateId().hashCode());
		result = 37 * result + (getLastUpdate() == null ? 0 : this.getLastUpdate().hashCode());
		return result;
	}

}
