package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmMmtUnderAbcp generated by hbm2java
 */

@Entity(name = "NaviNcmMmtUnderAbcp")
@IdClass(value = NcmMmtUnderAbcpId.class)
@Table(name = "NCM_MMT_UNDER_ABCP", schema = "NCM")
public class NcmMmtUnderAbcp implements java.io.Serializable, Navigatable {

	private String seqNo;
	private String bizDt;
	private String stockCd;
	private String acctCd;
	private String assetCd;
	private String unastCd;
	private String unastNm;
	private String unastGb;
	private String unastPubNo;
	private String unastPubNm;
	private String unastCrdtGd;
	private String crdtEvalAg;
	private String crdtTypeCd;
	private String cdsGbCd;
	private String bnkrpt;
	private String bkSecuTyp;
	private String devNm;
	private String bldNm;
	private String bldNo;
	private String bldCrdtGd;
	private String bldCrdtEval;
	private String bldCrdtCd;
	private Date creDttm;
	private String creEmpNo;
	private Date chgDttm;
	private String chgEmpNo;
	private String workfilename;

	public NcmMmtUnderAbcp() {
	}

	@Id
	@Column(name = "SEQ_NO", nullable = false, length = 7)
	public String getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(String seqNo) {
		this.seqNo = seqNo;
	}

	@Id
	@Column(name = "BIZ_DT", nullable = false, length = 8)
	public String getBizDt() {
		return this.bizDt;
	}

	public void setBizDt(String bizDt) {
		this.bizDt = bizDt;
	}

	@Id
	@Column(name = "STOCK_CD", nullable = false, length = 13)
	public String getStockCd() {
		return this.stockCd;
	}

	public void setStockCd(String stockCd) {
		this.stockCd = stockCd;
	}

	@Id
	@Column(name = "ACCT_CD", nullable = false, length = 30)
	public String getAcctCd() {
		return this.acctCd;
	}

	public void setAcctCd(String acctCd) {
		this.acctCd = acctCd;
	}

	@Id
	@Column(name = "ASSET_CD", nullable = false, length = 12)
	public String getAssetCd() {
		return this.assetCd;
	}

	public void setAssetCd(String assetCd) {
		this.assetCd = assetCd;
	}

	@Id
	@Column(name = "UNAST_CD", nullable = false, length = 14)
	public String getUnastCd() {
		return this.unastCd;
	}

	public void setUnastCd(String unastCd) {
		this.unastCd = unastCd;
	}

	@Column(name = "UNAST_NM", nullable = false, length = 100)
	public String getUnastNm() {
		return this.unastNm;
	}

	public void setUnastNm(String unastNm) {
		this.unastNm = unastNm;

	}

	@Column(name = "UNAST_GB", nullable = false, length = 2)
	public String getUnastGb() {
		return this.unastGb;
	}

	public void setUnastGb(String unastGb) {
		this.unastGb = unastGb;

	}

	@Column(name = "UNAST_PUB_NO", length = 13)
	public String getUnastPubNo() {
		return this.unastPubNo;
	}

	public void setUnastPubNo(String unastPubNo) {
		this.unastPubNo = unastPubNo;

	}

	@Column(name = "UNAST_PUB_NM", length = 30)
	public String getUnastPubNm() {
		return this.unastPubNm;
	}

	public void setUnastPubNm(String unastPubNm) {
		this.unastPubNm = unastPubNm;

	}

	@Column(name = "UNAST_CRDT_GD", nullable = false, length = 4)
	public String getUnastCrdtGd() {
		return this.unastCrdtGd;
	}

	public void setUnastCrdtGd(String unastCrdtGd) {
		this.unastCrdtGd = unastCrdtGd;

	}

	@Column(name = "CRDT_EVAL_AG", length = 2)
	public String getCrdtEvalAg() {
		return this.crdtEvalAg;
	}

	public void setCrdtEvalAg(String crdtEvalAg) {
		this.crdtEvalAg = crdtEvalAg;

	}

	@Column(name = "CRDT_TYPE_CD", length = 2)
	public String getCrdtTypeCd() {
		return this.crdtTypeCd;
	}

	public void setCrdtTypeCd(String crdtTypeCd) {
		this.crdtTypeCd = crdtTypeCd;

	}

	@Column(name = "CDS_GB_CD", length = 2)
	public String getCdsGbCd() {
		return this.cdsGbCd;
	}

	public void setCdsGbCd(String cdsGbCd) {
		this.cdsGbCd = cdsGbCd;

	}

	@Column(name = "BNKRPT", length = 2)
	public String getBnkrpt() {
		return this.bnkrpt;
	}

	public void setBnkrpt(String bnkrpt) {
		this.bnkrpt = bnkrpt;

	}

	@Column(name = "BK_SECU_TYP", length = 2)
	public String getBkSecuTyp() {
		return this.bkSecuTyp;
	}

	public void setBkSecuTyp(String bkSecuTyp) {
		this.bkSecuTyp = bkSecuTyp;

	}

	@Column(name = "DEV_NM", length = 30)
	public String getDevNm() {
		return this.devNm;
	}

	public void setDevNm(String devNm) {
		this.devNm = devNm;

	}

	@Column(name = "BLD_NM", length = 30)
	public String getBldNm() {
		return this.bldNm;
	}

	public void setBldNm(String bldNm) {
		this.bldNm = bldNm;

	}

	@Column(name = "BLD_NO", length = 13)
	public String getBldNo() {
		return this.bldNo;
	}

	public void setBldNo(String bldNo) {
		this.bldNo = bldNo;

	}

	@Column(name = "BLD_CRDT_GD", length = 4)
	public String getBldCrdtGd() {
		return this.bldCrdtGd;
	}

	public void setBldCrdtGd(String bldCrdtGd) {
		this.bldCrdtGd = bldCrdtGd;

	}

	@Column(name = "BLD_CRDT_EVAL", length = 2)
	public String getBldCrdtEval() {
		return this.bldCrdtEval;
	}

	public void setBldCrdtEval(String bldCrdtEval) {
		this.bldCrdtEval = bldCrdtEval;

	}

	@Column(name = "BLD_CRDT_CD", length = 2)
	public String getBldCrdtCd() {
		return this.bldCrdtCd;
	}

	public void setBldCrdtCd(String bldCrdtCd) {
		this.bldCrdtCd = bldCrdtCd;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRE_DTTM", length = 7)
	public Date getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm) {
		this.creDttm = creDttm;

	}

	@Column(name = "CRE_EMP_NO", length = 6)
	public String getCreEmpNo() {
		return this.creEmpNo;
	}

	public void setCreEmpNo(String creEmpNo) {
		this.creEmpNo = creEmpNo;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHG_DTTM", length = 7)
	public Date getChgDttm() {
		return this.chgDttm;
	}

	public void setChgDttm(Date chgDttm) {
		this.chgDttm = chgDttm;

	}

	@Column(name = "CHG_EMP_NO", length = 6)
	public String getChgEmpNo() {
		return this.chgEmpNo;
	}

	public void setChgEmpNo(String chgEmpNo) {
		this.chgEmpNo = chgEmpNo;

	}

	@Column(name = "WORKFILENAME", length = 30)
	public String getWorkfilename() {
		return this.workfilename;
	}

	public void setWorkfilename(String workfilename) {
		this.workfilename = workfilename;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getSeqNo());
		buffer.append("#").append(getBizDt());
		buffer.append("#").append(getStockCd());
		buffer.append("#").append(getAcctCd());
		buffer.append("#").append(getAssetCd());
		buffer.append("#").append(getUnastCd());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmMmtUnderAbcp))
			return false;
		NcmMmtUnderAbcp castOther = (NcmMmtUnderAbcp) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSeqNo() == null ? 0 : this.getSeqNo().hashCode());
		result = 37 * result + (getBizDt() == null ? 0 : this.getBizDt().hashCode());
		result = 37 * result + (getStockCd() == null ? 0 : this.getStockCd().hashCode());
		result = 37 * result + (getAcctCd() == null ? 0 : this.getAcctCd().hashCode());
		result = 37 * result + (getAssetCd() == null ? 0 : this.getAssetCd().hashCode());
		result = 37 * result + (getUnastCd() == null ? 0 : this.getUnastCd().hashCode());
		return result;
	}

}
