package com.eugenefe.entity.ncm;
// Generated Dec 21, 2016 2:18:11 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugenefe.util.Navigatable;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NcmVldRst generated by hbm2java
 */

@Entity(name = "NaviNcmVldRst")
@IdClass(value = NcmVldRstId.class)
@Table(name = "NCM_VLD_RST", schema = "NCM")
public class NcmVldRst implements java.io.Serializable, Navigatable {

	private String baseDate;
	private String vldTypeCd;
	private short seq;
	private String keyCol1;
	private String keyCol1Nm;
	private String keyCol2;
	private String keyCol2Nm;
	private String keyCol3;
	private String keyCol3Nm;
	private String updateId;
	private Date lastUpdate;

	public NcmVldRst() {
	}

	@Id
	@Column(name = "BASE_DATE", nullable = false, length = 8)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Id
	@Column(name = "VLD_TYPE_CD", nullable = false, length = 100)
	public String getVldTypeCd() {
		return this.vldTypeCd;
	}

	public void setVldTypeCd(String vldTypeCd) {
		this.vldTypeCd = vldTypeCd;
	}

	@Id
	@Column(name = "SEQ", nullable = false, precision = 4, scale = 0)
	public short getSeq() {
		return this.seq;
	}

	public void setSeq(short seq) {
		this.seq = seq;
	}

	@Column(name = "KEY_COL1", length = 100)
	public String getKeyCol1() {
		return this.keyCol1;
	}

	public void setKeyCol1(String keyCol1) {
		this.keyCol1 = keyCol1;

	}

	@Column(name = "KEY_COL1_NM", length = 100)
	public String getKeyCol1Nm() {
		return this.keyCol1Nm;
	}

	public void setKeyCol1Nm(String keyCol1Nm) {
		this.keyCol1Nm = keyCol1Nm;

	}

	@Column(name = "KEY_COL2", length = 100)
	public String getKeyCol2() {
		return this.keyCol2;
	}

	public void setKeyCol2(String keyCol2) {
		this.keyCol2 = keyCol2;

	}

	@Column(name = "KEY_COL2_NM", length = 100)
	public String getKeyCol2Nm() {
		return this.keyCol2Nm;
	}

	public void setKeyCol2Nm(String keyCol2Nm) {
		this.keyCol2Nm = keyCol2Nm;

	}

	@Column(name = "KEY_COL3", length = 100)
	public String getKeyCol3() {
		return this.keyCol3;
	}

	public void setKeyCol3(String keyCol3) {
		this.keyCol3 = keyCol3;

	}

	@Column(name = "KEY_COL3_NM", length = 100)
	public String getKeyCol3Nm() {
		return this.keyCol3Nm;
	}

	public void setKeyCol3Nm(String keyCol3Nm) {
		this.keyCol3Nm = keyCol3Nm;

	}

	@Column(name = "UPDATE_ID", length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;

	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getVldTypeCd());
		buffer.append("#").append(getSeq());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcmVldRst))
			return false;
		NcmVldRst castOther = (NcmVldRst) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getVldTypeCd() == null ? 0 : this.getVldTypeCd().hashCode());
		result = 37 * result + this.getSeq();
		return result;
	}

}
