package com.eugenefe.entities;
// Generated May 29, 2016 10:08:33 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OdsKrxMetaDetail generated by hbm2java
 */
@Entity
@Table(name = "ods_krx_meta_detail", catalog = "eugenefe")
public class OdsKrxMetaDetail implements java.io.Serializable {

	private OdsKrxMetaDetailId id;
	private String mapValue;

	public OdsKrxMetaDetail() {
	}

	public OdsKrxMetaDetail(OdsKrxMetaDetailId id) {
		this.id = id;
	}

	public OdsKrxMetaDetail(OdsKrxMetaDetailId id, String mapValue) {
		this.id = id;
		this.mapValue = mapValue;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "metaId", column = @Column(name = "META_ID", nullable = false, length = 20) ),
			@AttributeOverride(name = "mapKey", column = @Column(name = "MAP_KEY", nullable = false, length = 50) ) })
	public OdsKrxMetaDetailId getId() {
		return this.id;
	}

	public void setId(OdsKrxMetaDetailId id) {
		this.id = id;
	}

	@Column(name = "MAP_VALUE", length = 200)
	public String getMapValue() {
		return this.mapValue;
	}

	public void setMapValue(String mapValue) {
		this.mapValue = mapValue;
	}

}
