package com.eugenefe.entities;
// Generated May 26, 2016 11:57:16 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OdsKrxMeta generated by hbm2java
 */
@Entity
@Table(name = "ods_krx_meta", catalog = "eugenefe")
public class OdsKrxMeta implements java.io.Serializable {

	private String metaId;
	private String viewNo;
	private String viewName;
	private String viewType;
	private String requestType;
	private String url;
	private String optUrl;
	private String filePath;

	public OdsKrxMeta() {
	}

	public OdsKrxMeta(String metaId, String viewNo) {
		this.metaId = metaId;
		this.viewNo = viewNo;
	}

	public OdsKrxMeta(String metaId, String viewNo, String viewName, String viewType, String requestType, String url,
			String optUrl, String filePath) {
		this.metaId = metaId;
		this.viewNo = viewNo;
		this.viewName = viewName;
		this.viewType = viewType;
		this.requestType = requestType;
		this.url = url;
		this.optUrl = optUrl;
		this.filePath = filePath;
	}

	@Id

	@Column(name = "META_ID", unique = true, nullable = false, length = 20)
	public String getMetaId() {
		return this.metaId;
	}

	public void setMetaId(String metaId) {
		this.metaId = metaId;
	}

	@Column(name = "VIEW_NO", nullable = false, length = 20)
	public String getViewNo() {
		return this.viewNo;
	}

	public void setViewNo(String viewNo) {
		this.viewNo = viewNo;
	}

	@Column(name = "VIEW_NAME", length = 50)
	public String getViewName() {
		return this.viewName;
	}

	public void setViewName(String viewName) {
		this.viewName = viewName;
	}

	@Column(name = "VIEW_TYPE", length = 10)
	public String getViewType() {
		return this.viewType;
	}

	public void setViewType(String viewType) {
		this.viewType = viewType;
	}

	@Column(name = "REQUEST_TYPE", length = 10)
	public String getRequestType() {
		return this.requestType;
	}

	public void setRequestType(String requestType) {
		this.requestType = requestType;
	}

	@Column(name = "URL", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "OPT_URL", length = 200)
	public String getOptUrl() {
		return this.optUrl;
	}

	public void setOptUrl(String optUrl) {
		this.optUrl = optUrl;
	}

	@Column(name = "FILE_PATH", length = 50)
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

}
