package com.eugenefe.entities;
// Generated May 26, 2016 11:57:16 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OdsYahooPrice generated by hbm2java
 */
@Entity
@Table(name = "ods_yahoo_price", catalog = "eugenefe")
public class OdsYahooPrice implements java.io.Serializable {

	private OdsYahooPriceId id;
	private BigDecimal openPrice;
	private BigDecimal lowPrice;
	private BigDecimal highPrice;
	private BigDecimal closePrice;
	private BigDecimal volume;
	private BigDecimal adjClose;

	public OdsYahooPrice() {
	}

	public OdsYahooPrice(OdsYahooPriceId id) {
		this.id = id;
	}

	public OdsYahooPrice(OdsYahooPriceId id, BigDecimal openPrice, BigDecimal lowPrice, BigDecimal highPrice,
			BigDecimal closePrice, BigDecimal volume, BigDecimal adjClose) {
		this.id = id;
		this.openPrice = openPrice;
		this.lowPrice = lowPrice;
		this.highPrice = highPrice;
		this.closePrice = closePrice;
		this.volume = volume;
		this.adjClose = adjClose;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "yahooId", column = @Column(name = "YAHOO_ID", nullable = false, length = 20) ),
			@AttributeOverride(name = "baseDate", column = @Column(name = "BASE_DATE", nullable = false, length = 20) ) })
	public OdsYahooPriceId getId() {
		return this.id;
	}

	public void setId(OdsYahooPriceId id) {
		this.id = id;
	}

	@Column(name = "OPEN_PRICE", precision = 20, scale = 4)
	public BigDecimal getOpenPrice() {
		return this.openPrice;
	}

	public void setOpenPrice(BigDecimal openPrice) {
		this.openPrice = openPrice;
	}

	@Column(name = "LOW_PRICE", precision = 20, scale = 4)
	public BigDecimal getLowPrice() {
		return this.lowPrice;
	}

	public void setLowPrice(BigDecimal lowPrice) {
		this.lowPrice = lowPrice;
	}

	@Column(name = "HIGH_PRICE", precision = 20, scale = 4)
	public BigDecimal getHighPrice() {
		return this.highPrice;
	}

	public void setHighPrice(BigDecimal highPrice) {
		this.highPrice = highPrice;
	}

	@Column(name = "CLOSE_PRICE", precision = 20, scale = 4)
	public BigDecimal getClosePrice() {
		return this.closePrice;
	}

	public void setClosePrice(BigDecimal closePrice) {
		this.closePrice = closePrice;
	}

	@Column(name = "VOLUME", precision = 20, scale = 4)
	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	@Column(name = "ADJ_CLOSE", precision = 20, scale = 4)
	public BigDecimal getAdjClose() {
		return this.adjClose;
	}

	public void setAdjClose(BigDecimal adjClose) {
		this.adjClose = adjClose;
	}

}
