package com.eugenefe.entity.temp;
// Generated Dec 19, 2016 6:36:07 PM by Hibernate Tools 5.2.0.Beta1 with Custom Template_takion!!!!!! 

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.MapKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.eugenefe.embeddable.StrikePrice;
import com.eugenefe.util.Navigatable;

/**
 * Hifive generated by hbm2java
 */

@Entity
@Table(name = "HIFIVE", schema = "TAKION79")
public class Hifive implements java.io.Serializable, Navigatable {

	private String prodId;
//	private String counterparty;
	private String prodName;
	private String hifiveType;
	private String issueDate;
	private String maturityDate;
	private Long faceAmt;
	private Long notionalAmt;
	private BigDecimal downBarrier;
	private BigDecimal maxLoss;
	private BigDecimal couponRateLast;
	private String hittingType;
	private Character virturalYn;

	public Hifive() {
	}

	@Id
	@Column(name = "PROD_ID", unique = true, nullable = false, length = 20)
	public String getProdId() {
		return this.prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;

	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "COUNTERPARTY_ID", nullable = false)
//	public Counterparty getCounterparty() {
//		return this.counterparty;
//	}
//
//	public void setCounterparty(Counterparty counterparty) {
//		this.counterparty = counterparty;
//
//	}

	@Column(name = "PROD_NAME", length = 50)
	public String getProdName() {
		return this.prodName;
	}

	public void setProdName(String prodName) {
		this.prodName = prodName;

	}

	@Column(name = "HIFIVE_TYPE", length = 10)
	public String getHifiveType() {
		return this.hifiveType;
	}

	public void setHifiveType(String hifiveType) {
		this.hifiveType = hifiveType;

	}

	@Column(name = "ISSUE_DATE", length = 8)
	public String getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(String issueDate) {
		this.issueDate = issueDate;

	}

	@Column(name = "MATURITY_DATE", length = 8)
	public String getMaturityDate() {
		return this.maturityDate;
	}

	public void setMaturityDate(String maturityDate) {
		this.maturityDate = maturityDate;

	}

	@Column(name = "FACE_AMT", precision = 10, scale = 0)
	public Long getFaceAmt() {
		return this.faceAmt;
	}

	public void setFaceAmt(Long faceAmt) {
		this.faceAmt = faceAmt;

	}

	@Column(name = "NOTIONAL_AMT", precision = 10, scale = 0)
	public Long getNotionalAmt() {
		return this.notionalAmt;
	}

	public void setNotionalAmt(Long notionalAmt) {
		this.notionalAmt = notionalAmt;

	}

	@Column(name = "DOWN_BARRIER", precision = 10, scale = 4)
	public BigDecimal getDownBarrier() {
		return this.downBarrier;
	}

	public void setDownBarrier(BigDecimal downBarrier) {
		this.downBarrier = downBarrier;

	}

	@Column(name = "MAX_LOSS", precision = 10, scale = 4)
	public BigDecimal getMaxLoss() {
		return this.maxLoss;
	}

	public void setMaxLoss(BigDecimal maxLoss) {
		this.maxLoss = maxLoss;

	}

	@Column(name = "COUPON_RATE_LAST", precision = 10, scale = 4)
	public BigDecimal getCouponRateLast() {
		return this.couponRateLast;
	}

	public void setCouponRateLast(BigDecimal couponRateLast) {
		this.couponRateLast = couponRateLast;

	}

	@Column(name = "HITTING_TYPE", length = 10)
	public String getHittingType() {
		return this.hittingType;
	}

	public void setHittingType(String hittingType) {
		this.hittingType = hittingType;

	}

	@Column(name = "VIRTURAL_YN", length = 1)
	public Character getVirturalYn() {
		return this.virturalYn;
	}

	public void setVirturalYn(Character virturalYn) {
		this.virturalYn = virturalYn;

	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unresolved")
//	public Set<HifiveUnderlying> getHifiveUnderlyings() {
//		return this.hifiveUnderlyings;
//	}
//
//	public void setHifiveUnderlyings(Set<HifiveUnderlying> hifiveUnderlyings) {
//		this.hifiveUnderlyings = hifiveUnderlyings;
//
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unresolved")
//	public Set<Pricing> getPricings() {
//		return this.pricings;
//	}
//
//	public void setPricings(Set<Pricing> pricings) {
//		this.pricings = pricings;
//
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unresolved")
//	public Set<HifiveStrike> getHifiveStrikes() {
//		return this.hifiveStrikes;
//	}
//
//	public void setHifiveStrikes(Set<HifiveStrike> hifiveStrikes) {
//		this.hifiveStrikes = hifiveStrikes;
//
//	}
//
//	@OneToOne(fetch = FetchType.LAZY, mappedBy = "unresolved")
//	public HifiveSwapIr getHifiveSwapIr() {
//		return this.hifiveSwapIr;
//	}
//
//	public void setHifiveSwapIr(HifiveSwapIr hifiveSwapIr) {
//		this.hifiveSwapIr = hifiveSwapIr;
//
//	}
	
	private Map<TempMarketVariable, StrikePrice> underlyingMap = new HashMap<TempMarketVariable, StrikePrice>();
	
//	@ManyToMany
//	@JoinTable(name="HIFIVE_UNDERLYING", joinColumns = @JoinColumn(name ="PROD_ID"))
	@ElementCollection(fetch= FetchType.LAZY)
	@CollectionTable(name="HIFIVE_UNDERLYING", joinColumns = @JoinColumn(name ="PROD_ID"))
	@MapKeyJoinColumn(name = "STOCK_ID")
//	@AttributeOverrides({
//      @AttributeOverride(name="strikePrice",),
//      @AttributeOverride(name="shockValue", column=@Column(name="SHOCK_VALUE")),
//    })
	public Map<TempMarketVariable, StrikePrice> getUnderlyingMap() {
		return underlyingMap;
	}

	public void setUnderlyingMap(Map<TempMarketVariable, StrikePrice> underlyingMap) {
		this.underlyingMap = underlyingMap;
	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getProdId());

		String rst = buffer.toString();

		return rst;
	}

	

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Hifive))
			return false;
		Hifive castOther = (Hifive) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (idString() == null ? 0 : this.idString().hashCode());
		return result;
	}

}
